### ISSUE TITLE
Check Doctrine JSON type with MySQL and SQLite

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#10]
Currently, `face_recognition_faces` DB table has `descriptor` column of JSON type, which have `json_array` type. Double check that this can be used for MySQL and SQLite too. See also related issue #11 (if #11 is done, maybe this becomes non-issue)

**Comment by stalker314314** [comment]
No issues so far in CI testing. I will close this once we have better coverage on *Mapper classes (I guess once we can test actual face detection in tests)

**Comment by matiasdelellis** [comment]
In all the tests we do when moving the file to anothe route, the fileId is maintained. I do not see problems with this.
