### ISSUE TITLE
HTTP 404 for face thumbnails

### ISSUE THREAD

**Issue by SlavikCA** [matiasdelellis/facerecognition#102]
After face recognition, I went to Settings => Face Recognition.

That page has few persons, but all faces are just gray boxes - no faces are shown.

Browser console has many HTTP 404 errors, such as:
```
GET https://cloud.aidcim.org/apps/facerecognition/face/9/thumb/50  HTTP 404
 /apps/facerecognition/face/9/thumb/50:1 
```

![face](https://user-images.githubusercontent.com/6293679/50936570-13cc1c80-1425-11e9-9d47-426c5fd5577a.png)

**Comment by nervnet65** [comment]
I had the same thing. I had to add the following line in "config.php" to remove the "index.php" from the nextcloud address.
**'htaccess.RewriteBase' => '/'**
and then update htaccess with the occ command
**sudo -u apache php occ maintenance:update:htaccess**
I found this on https://help.nextcloud.com/t/removing-index-php-from-the-nextcloud-uri/13055

**Comment by SlavikCA** [comment]
Yes, it's the same as 92.

Yes, following @nervnet65 advice fixes the issue.

Thank you!
