### ISSUE TITLE
Do not show clusters with 1 face in it

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#113]
Not sure if this is a bug or a feature:), but I don't see anything good that can came out of this:) 40% of my clusters are clusters with 1 face and that can save some scrolling on page, thumbnail generation and user intimidation with lot of results thrown at him/her.

![slika](https://user-images.githubusercontent.com/188751/51941132-bd427480-240b-11e9-8ad4-78ff832ce7e5.png)

**Comment by james-cook** [comment]
Just getting to know the system but I quite like to have even these clusters just to get a feeling of what's going on - especially when adjusting sensitivity. 
Maybe a filter to reveal/hide single member clusters and default set at hidden...
