### ISSUE TITLE
TypeError: Handlebars.templates is undefined

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#119]
This might be continuation of #95.
After I merged https://github.com/matiasdelellis/facerecognition/commit/cb50dfd49d95e0ef83487e579c15614ce4327fc3, facerecognition page is blank. Here is output from firefox (I can translate if needed):
![slika](https://user-images.githubusercontent.com/188751/52911439-aae58900-329b-11e9-8a31-feaa68e05d9c.png)
and from edge:
![slika](https://user-images.githubusercontent.com/188751/52911418-75d93680-329b-11e9-819f-c340186648f0.png)

I did `make` before copying to my server, but [`js-templates` rule](https://github.com/matiasdelellis/facerecognition/commit/cb50dfd49d95e0ef83487e579c15614ce4327fc3#diff-b67911656ef5d18c4ae36cb6741b7965R54) was not part of default `make`? Also, if I run `make js-templates` rule manually, it is broken as I don't have `handlebars` executable.

This also doesn't work on my dev machine. Seems more likely that I am missing some dependency than coding issue? Looking at [this .gitignore](https://github.com/matiasdelellis/facerecognition/commit/cb50dfd49d95e0ef83487e579c15614ce4327fc3#diff-a084b794bc0759e7a6b77810e01874f2R3), I am missing `js/templates.js`?:
```
$:~/server/apps/facerecognition$ ls js -R
js:
admin.js  files-plugin.js  files-tabview.js  handlebars.js  lozad.js  personal.js  templates

js/templates:
personal.handlebars
```

**Comment by matiasdelellis** [comment]
Hi branko,
https://github.com/matiasdelellis/facerecognition/pull/118#issuecomment-462787351

I did not do it as dependence, because it's more like a build.. but the executable, I do not want to install it from there, but at least we should warn of that dependence, and that we must execute it

**Comment by matiasdelellis** [comment]
Hi again @stalker314314 ,

Check last PR.. :wink: 

p.s: By the way, a pleasure to know about you again!

**Comment by stalker314314** [comment]
I agree "handlebars" must be present and we should only warn (same as with `wget`, `bzip2`...) and not install it. But it should be automatic, I think - I run `make` and I get `js/templates.js`, right?

**Comment by stalker314314** [comment]
this is fixed:)
