### ISSUE TITLE
Thumbs cannot be displayed

### ISSUE THREAD

**Issue by emresaracoglu** [matiasdelellis/facerecognition#128]
Unfortunately, Showing in the admin panel but can not be displayed in the file list panel.

![screencapture-192-168-1-10-apps-files-2019-03-11-15_38_42](https://user-images.githubusercontent.com/297968/54128202-3a520800-4414-11e9-9773-22a419b02029.jpg)

**Comment by stalker314314** [comment]
I am not JS expert, but do you see any errors in log (dev tools). What is image location that those thumbnails are pointing to (I mean, their `<img>` elements)? If they are failing to load, what is HTTP error code?

P.S. We had something similar before (https://github.com/matiasdelellis/facerecognition/issues/92), but it is fixed more than month ago, so I would rule that out.

**Comment by matiasdelellis** [comment]
Maybe the template went wrong since https://github.com/matiasdelellis/facerecognition/pull/118

Now see that..

**Comment by matiasdelellis** [comment]
ReferenceError: lozad is not defined[Conocer más]

**Comment by matiasdelellis** [comment]
D'Oh!. Fixed in the last commit.. Please.. test it.. :smile: 

@stalker314314 Sorry to commit directly to master .. I have many experimental changes here.. but for now none of them interesting.. :sweat_smile:

**Comment by emresaracoglu** [comment]
The operation is successful 👍 

_Evidence:_ 😄 
![1Untitled](https://user-images.githubusercontent.com/297968/54163980-909a6780-4463-11e9-8ef2-ace39e71a4d3.png)

**Comment by matiasdelellis** [comment]
Ohh ... We still did not want to analyze the pets ...  :smile_cat:
