### ISSUE TITLE
Clusters on personal view should be sorted by their sizes

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#143]
@matiasdelellis - Yes, I know this is temporary view and I am aware this is not something we should invest a lot into:) That being said...I am very annoyed that people I care most (people having most faces in my collection) are not at the top. So, I propose this issue - sort persons by sizes of their respective clusters.
Now, I am completely fine that I do this, just wants an "ack" from you that you are OK with this work at all.

I was thinking to either:
1) add a new field `$cluster['faces_count']` in `PersonController::index` and let JS do the sorting, or
2) actually pre-sort clusters (server-side) during PersonMapper call

I would do 2) and maybe _even_ try to merge whole of `PersonController::index` into only one SQL call (so we don't do N lookup for faces in cluster). Thoughts?

**Comment by matiasdelellis** [comment]
@stalker314314 

> Yes, I know this is temporary view and I am aware this is not something we should invest a lot into:)

Something that works a lot, but unfortunately with few results, is to make a virtual view in the file manager -simil Trash, o Share with... view-, that would be a good replacement for this view.. So after we publish I'll ask the Nextcloud guys for help..

Regarding this report:

> ...sort persons by sizes of their respective clusters.
>
> Now, I am completely fine that I do this, just wants an "ack" from you that you are OK with this work at all.

I agree with that.

> I was thinking to either:
>    add a new field $cluster['faces_count'] in PersonController::index and let JS do the sorting, or
>    actually pre-sort clusters (server-side) during PersonMapper call
>
>I would do 2) and maybe even try to merge whole of PersonController::index into only one SQL call (so we don't do N lookup for faces in cluster). Thoughts?

I guess the best would be a combination of both, to be able to add a simple button to select the ordering.
