### ISSUE TITLE
Current status Stopped - 11 images in queue

### ISSUE THREAD

**Issue by santacl4ws** [matiasdelellis/facerecognition#147]
Hello,
currectly the app is stuck on "Current status Stopped - 11 images in queue".
The config is green and correct.
I am also unable to the the following "occ face:background_job [-u user-id] [-t timeout]" as i get the error "Command 'occ' not found, but there are 21 similar ones."

**Comment by santacl4ws** [comment]
I can run the command manually now by sudo -u www-data php occ face:background_job.
although this now crashed the entire server and just exits.

**Comment by santacl4ws** [comment]
I have increased my servers RAM to 12 GB.
This has seemed to resolve all my issues.

**Comment by maxi1134** [comment]
I also entounter this issue, but issuing more ram is not working:

![image](https://github.com/matiasdelellis/facerecognition/assets/1342643/006caf77-3b0a-403b-8a39-e883ac0f44ab)
