### ISSUE TITLE
Scanning photos stuck on 1 of 100

### ISSUE THREAD

**Issue by santacl4ws** [matiasdelellis/facerecognition#148]
I now have everything setup and complied to use my GPU.
When i run sudo -u www-data php occ face:background_job i get an error "illegal instruction".

root@larsh:/var/www/nextcloud# sudo -u www-data php occ face:background_job -u lewis -t 0 -vv
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Found 5998 MB available to PHP.
        Capping used memory to maximum of 4GB
        Applying the memory limit to 1024MB configured in settings.
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysi                                 s.)
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under                                  .nomedia) and remove them from DB)
        Skipping stale images removal for user lewis as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        0 faces found for clustering
        0 persons found after clustering
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Skipping full image scan for user lewis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for                                  them)
yielding
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ                                  at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
yielding
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184555(1).jpg
        Image scaled from 1944x2592 to 768x1024 (since max image area is 786432 pixels^2)
**Illegal instruction**
Looking on the web ui the scan is stuck on 1 of 100.

Analyzing images - 1 of 88 - Ends approximately in a few seconds

**Comment by matiasdelellis** [comment]
Hi, @santacl4ws 
Please tell me a couple of things ..

 * Dlib compiled by you? Version?
 * What hardware are you using?

..and make a couple of tests to check your installation:
 * https://github.com/davisking/dlib/blob/master/python_examples/face_recognition.py
 * https://github.com/matiasdelellis/facerecognition/issues/140#issuecomment-485821284

Thank you..

**Comment by santacl4ws** [comment]
@matiasdelellis 
Hello.
I now have it working now, kinda...
The issue was caused by me using "-DUSE_AVX_INSTRUCTIONS=1" but my Xeon does not support this.
It all seems to be working now, except it doesn't seem to update the "/settings/user/facerecognition" page.
I know it is using my GPU because:
1. the scan is MUCH faster
2. Running nvidia-smi -l 1 shows it in use.
I have it scanning 88 photos, how can i see if it is actually picking up faces?

**Comment by matiasdelellis** [comment]
> The issue was caused by me using "-DUSE_AVX_INSTRUCTIONS=1" but my Xeon does not support this.

Ohh.. Great.

> I know it is using my GPU because:
>
>    the scan is MUCH faster
>    Running nvidia-smi -l 1 shows it in use.

Ok ok, I was saying that we can not force its use, and it does not depend on this application. On the other hand, since I do not use GPU, I did not know this command but I will keep it in mind for future reports. :smiley:

Well,
We will have to document these details better.

> except it doesn't seem to update the "/settings/user/facerecognition" page.
I know it is using my GPU because:
> I have it scanning 88 photos, how can i see if it is actually picking up faces?

To ensure certain stability of the groups, and that the user does not rename some people, and then lose its we apply certain limits. So you need at least 100 faces to start to clustering.

If you are in testing stages you can modify it by hand.. :wink: 

https://github.com/matiasdelellis/facerecognition/blob/master/lib/BackgroundJob/Tasks/CreateClustersTask.php#L178

Regards.

**Comment by santacl4ws** [comment]
@matiasdelellis Do you have a rough estimate on how long it takes for the "/settings/user/facerecognition" page to populate?
I have added more pictures now so i have over 100 and re-scanned them.

**Comment by matiasdelellis** [comment]
Until some conditions are met, the clustering of faces is not done, so do not get any 'Persons' to show there.

MM.. Please attach the complete log of your last execution,  and the message should be clear enough.

> sudo -u www-data php occ face:background_job -vvv

NOTE:  '-vvv' to print more debug.. but it should not be necessary.

**Comment by matiasdelellis** [comment]
Ohh...

> 6/10 - Executing task CreateClustersTask (Create new persons or update existing persons) Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following: * have 1000 faces already processed (you have 0), * have 100 images (you have 0), * or you need to have 95% of you images processed (you have 0.00%)

I was referring to this., :disappointed:

**Comment by matiasdelellis** [comment]
Try resetting your database (Look at the readme), and try again. and it pays attention to what it returns when it analyzes each image.

**Comment by santacl4ws** [comment]
Reset database correctly... (I think)

```
sudo -u www-data php occ face:reset_all
Reset successfully done
```

output from scan after:

`root@larsh:/var/www/nextcloud# sudo -u www-data php occ face:background_job
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Applying the memory limit to 4096MB configured in settings.
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Skipping image scan for user Test that has disabled the analysis
        Finding missing images for user lewis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161011_222939064.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/received_10211066879175955.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161218_001750.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161118_115558.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/received_10211066712771795.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184129.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1474908613654.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-154402_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190607-194011_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_200323.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170707_230321.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1479586867239.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170707_230328.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184559.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160905_132509.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1470425902587.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161119_204930.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160919_085713.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161118_115559.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-154356_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161218_000415.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190608-083550_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184553.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_214625.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161119_160257.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/38223072_1903865716303188_3301373865300590592_o.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160818_133221.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_214622.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-014729_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161119_204634.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170708_000649.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161009_192509692.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_183440.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1476979432418.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161217_234604.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190611-170739_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1471366182992.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1469641015576.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161011_222941546.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Nextcloud.png
        Faces found: 0 (image will be skipped because it is too small)
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170325_231618.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184148.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1475160919533.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161106_184850107.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170707_230317.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/received_10211066837854922.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170318_222832_524.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/received_10154110844283525.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/received_10210925513441900.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190608-200625_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_214606.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170127_152515.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161118_115550.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160905_132504.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184601.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_214608.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170320_112018.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190608-200621_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160818_133227.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_214618.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161118_115553.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170707_230324.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170707_230326.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161009_192513955.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_200319.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_183444.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161217_230554.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160904_184118.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170320_112022.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1479721758537.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161218_000423.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1480438610344.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170325_231623.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161128_105339.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190607-235233_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_183458.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161023_162610945.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-154351_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-014801_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190608-084151_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190607-235253_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1475139237913.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_200317.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170320_112027.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170320_112015.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/FB_IMG_1490085625115.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-190547_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170320_112029.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160919_085710.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_184838.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/1480411166999.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161106_184855089.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161209_165906.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-113416_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-014818_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/Screenshot_20190609-154348_Instagram.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_184549.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161023_162605668.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170310_183508.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161106_184848314.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20170307_214555.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/IMG_20161119_160254.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20170707_225540.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/20160817_124835.jpg
        Processing image /mnt/ncdata/lewis/files/Photos/FB_IMG_1473921614441.jpg
10/10 - Executing task UnlockTask (Release obtained lock)
`

**Comment by santacl4ws** [comment]
Its odd that when it skips an image because its too small i get a response 
> Faces found: 0 (image will be skipped because it is too small)

But I dont get any after successfully scanning images.

**Comment by matiasdelellis** [comment]
Ok.. It is strange... :confused: 
it tells you that it is analyzing images, but it does not show you the result of each image.. 

The report should be like this:
```
[matias@nube nextcloud]$ sudo -u apache php occ face:background_job -u matias
[sudo] password for matias: 
1/10 - Executing task CheckRequirementsTask (Check all requirements)
	Applying the memory limit to 1024MB configured in settings.
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Clusters already exist, estimated there is no need to recreate them
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
	Finding missing images for user matias
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
	NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
	Processing image /media/datos/Services/nextcloud/data/matias/files/Imágenes/Android/Camara/IMG_20190606_175815487.jpg
	Faces found: 0
	Processing image /media/datos/Services/nextcloud/data/matias/files/Imágenes/Android/Camara/IMG_20190606_175809304.jpg
	Faces found: 0
	Processing image /media/datos/Services/nextcloud/data/matias/files/Imágenes/Android/Camara/IMG_20190606_175816735.jpg
	Faces found: 0
	Processing image /media/datos/Services/nextcloud/data/matias/files/Imágenes/Android/Camara/IMG_20190606_064623154.jpg
	Faces found: 1
	Processing image /media/datos/Services/nextcloud/data/matias/files/Imágenes/Android/Camara/IMG_20190608_112852791.jpg
	Faces found: 0
	Processing image /media/datos/Services/nextcloud/data/matias/files/Imágenes/Android/Camara/IMG_20190606_064616320.jpg
	Faces found: 1
10/10 - Executing task UnlockTask (Release obtained lock)
```

..indicating how many faces he found in each image.

@stalker314314  Any ideas?

**Comment by santacl4ws** [comment]
If it helps at all my dlib versions are:
libdlib-data/bionic,bionic 18.18-2build1 all
libdlib-dev/bionic 18.18-2build1 amd64
libdlib18/bionic 18.18-2build1 amd64

To compile dlib I do:
sudo cmake -DDLIB_USE_CUDA=1 -DBUILD_SHARED_LIBS=ON -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 ..

**Comment by stalker314314** [comment]
It looks like it never finishes detection:( But, this time, pdlib is not crashing, just returning some error and exception. Can you take a look at `oc_face_recognition_images` table (in SQL database where your Nextcloud is configured to) and see if there is anything in `isProcessed` and `error` column. Ideally, there should be stack trace and exception in `error` column!

@matiasdelellis This is one place where we can improve logging (when there is exception). Consider it on me soon.

**Comment by santacl4ws** [comment]
@stalker314314 
I can see the follwoing:
`
Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in file /home/ncadmin/dlib/dlib/cuda/cuda_utils.h:164. code: 8, reason: invalid device function | 2019-06-12 16:19:23 | 0
-- | -- | --
  | 1012 | lewis | 1728 | 1 | t | Error while calling cudaGetLastError() in file /home/ncadmin/dlib/dlib/cuda/gpu_data.cpp:114. code: 8, reason: invalid device function

`

**Comment by stalker314314** [comment]
Great it helped. Saga continues:) Keep us updated! I will fix logging, so you can debug this *without* fiddling with DB:)

**Comment by matiasdelellis** [comment]
> To fix it, try updating your Nvidia drivers to the latest version manually.

Ohh.. Ok..
We keep collecting information that should go to the FAQ. :sweat_smile: 

On the other hand..

> libdlib-data/bionic,bionic 18.18-2build1 all
> libdlib-dev/bionic 18.18-2build1 amd64
> libdlib18/bionic 18.18-2build1 amd64

It is too old and pdlib supposedly needs [19.13+](https://github.com/goodspb/pdlib#requirements)
I'm not sure how important this is since I'm not the author ... but then try to recompile it by hand.

**Comment by santacl4ws** [comment]
Okay, 
So ive had no luck so far.....
It seems to be nearly impossible to downgrade my cuda version and install cuda 7.5 with toolkit....
Someone sugested downloading the latest python3-dev files which hasnt seemed to help either...

**Comment by matiasdelellis** [comment]
Hi @santacl4ws 

> It seems to be nearly impossible to downgrade my cuda version and install cuda 7.5 with toolkit

You did not say you should upgrade?

> > To fix it, try updating your Nvidia drivers to the latest version manually.

**Comment by santacl4ws** [comment]
Hi @matiasdelellis That was my mistake, I did mean downgrade.
The gpu im trying to use is not supported by the new versions of CUDA.
One thing i am thinking about trying is replacing my quadro 4000 with a cheap but newer GPU such as a 960 as this will allow me to use much newer CUDA versions.

**Comment by matiasdelellis** [comment]
Hi @santacl4ws 
You could make some progress?

Ultimately, I can suggest you give it a chance to your CPU.. :sweat_smile: It will work much slower, but the command is designed to be executed progressively, and with patience, you will get the same results. :smile: 

On the other hand, assuming you got the GPU running, I invite you to write your conclusions, and any command necessary to verify its use, to be able to help other people. :smile: 

Thanks, :wink:

**Comment by santacl4ws** [comment]
@matiasdelellis
I should be getting a much newer gpu this week (GTX 970) I will update if you if I have any luck! :)

**Comment by matiasdelellis** [comment]
Hi,
I understand that this report was resolved, and I close it. Please, if necessary, open it again. :smile: 

p.s: I also await your conclusions about Cuda :wink:
