### ISSUE TITLE
Central place for loading DNN models

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#15]
In `ImageProcessingTask` class, there are loading of models, which should be better if they are in `Requirements` class, or somewhere else, central to where we can find it (with more complex lookup logic to find models). This task also depends on how we load and keep models (apt-get/manually, or automaticall in future)

**Comment by stalker314314** [comment]
@matiasdelellis Here is interesting idea that came to my mind:) Why don't we simply distribute models with our app? I mean, we _literally_ commit them to code (in some `data/models/1/` folder), and ship them with us. Benefits are:
* No need for complex lookup algorithms to find where models are
* No need to tell user to download them, we skip one step in setup (and no need to have some special code that will downlod them, from `admin/` somewhere)
* So, user experience is far, far better
* Ability to change/add models with new app versions (simply cxhange existing models, or add `data/models/2/` for new ones)
* Ability to survive app upgrades (I don't know what is the best place to put them in `facerecognition/` folder such they are preserved across app upgrades, I think they would need to be outside of `facerecognition/` folder)
* (when we have) easier testing in continous integration, as models will be there, downloaded along with the app

I was thinking of any downsides:
* **legal** - I looked and looked around dlib.net site, and I am not a lawyer, but I didn't saw anything that says "hey, you need to download models from our site in runtime, so I can see usage...". I hope we can try and if there is any problems, we can always remove them and change logic? I mean, we are doing this in good faith
* **size** - OK, all 3 of them are in total 30MB. They are surely not as small as distributing .php files, and bundling them will make us probably one of larger Nextcloud app, but I think it is not *that* big they cannot fit to any infrastructure (continous integration, upload to nextcloud app store, user internet connection bandwidth...)

So, do you agree to try this approach? It would make things sooo much easier for this task:)

**Comment by stalker314314** [comment]
Heya, @matiasdelellis , I guess you missed above comment (in between various PRs), so let me try with this ping😛 I need you opinion on this

**Comment by matiasdelellis** [comment]
Wow..
You're right, I read it very early on the phone and then forget it. :sweat_smile: 

> Ability to survive app upgrades (I don't know what is the best place to put them in facerecognition/ folder such they are preserved across app upgrades, I think they would need to be outside of facerecognition/ folder)

With this you convinced me.. :smiley: 

These can be shared within the application. At the most we must clarify the license and hopefully there are no size limitations to upload applications in Nextcloud.

But PLEASEEEEE, do not commit it to the git repository!.. Add a rule in the makefile (Even if it's horrible with wget), :wink: 

p.s: appeared some projects at work, plus exams of end of the year that have occupied me, but we continue with the same plan !.

**Comment by stalker314314** [comment]
For plan B, whenever you find time, I am occupied with those bugs, and next plan is to:
* close all bugs
* add support to fire exceptions from tasks
* setup some/any kind of CI, just a basic one, nothing fancy
* "_stress test_" backend on my own photo collection and see if it holds:D and fix those issue as I find them

After this, I hope that backend could be rock solid:)

**Comment by matiasdelellis** [comment]
> For plan B, whenever you find time

Tomorrow maybe I can do something... :grimacing: 

The rest ok.. great... :wink:
