### ISSUE TITLE
Bug report template..

### ISSUE THREAD

**Issue by matiasdelellis** [matiasdelellis/facerecognition#150]
Hi @stalker314314 
This issue is to discuss a bug reporting template to be used by users.
Basically it is to suggest a basic information that they must provide so that we can help them more efficiently.

See:
https://github.blog/2016-02-17-issue-and-pull-request-templates/

That's the Nextcloud server template.. Modify it here to fit our needs.

Template:
========

Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Try filling this report with the greatest care so that we can help you. :smile: 

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink: 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Server configuration

**Operating system**:

**Pdlib version:**

**How build dlib:**

**How build pdlib:**

**PHP version:**

**Web server:**

**Database:**

**Nextcloud version:**

### Client configuration
**Browser:**

**Operating system:**

#### Background task log
<details>
<summary>sudo -u apache php occ face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by stalker314314** [comment]
Looks fine to me:)
