### ISSUE TITLE
Can't increase memory assigned to face recognition app

### ISSUE THREAD

**Issue by jbruce716** [matiasdelellis/facerecognition#153]
Hello! I've increased the memory limit in both of my php.ini files, but the app won't let me go above 512M. I've 24GB of RAM total, so assigning 4GB shouldn't be an issue, should it? 

![image](https://user-images.githubusercontent.com/41759938/59930688-5ac92f80-9411-11e9-805f-48698531f7d6.png)

**Comment by stalker314314** [comment]
Yes, 4GB should be OK. It is also upper bound, our app is not allowing more than that, as there is no sense. But, what error do you get, if I may ask? When you run `occ face:background_job -vvv`, can you paste output? Just to see if it already set internally, or this is UI problem...

**Comment by jbruce716** [comment]
I believe it's simply a UI problem - that verbose setting was nice! :) See below:

![image](https://user-images.githubusercontent.com/41759938/59934903-9f0cfd80-941a-11e9-9e41-6bbe004adbb6.png)

**Comment by matiasdelellis** [comment]
Hi both,
Now see a bug, but no related with it.
https://github.com/matiasdelellis/facerecognition/blob/master/lib/Controller/SettingController.php#L147

@jbruce716 
Please, do a test:
Open the inspector and check the setappvalue query and its response when set value to 4GB:

Query:
![imagen](https://user-images.githubusercontent.com/733715/60016419-84c26200-965c-11e9-86d2-3bd2ac1f2a95.png)

Response:
![imagen](https://user-images.githubusercontent.com/733715/60016388-6fe5ce80-965c-11e9-851a-23a67f9de94c.png)

**Comment by matiasdelellis** [comment]
@stalker314314  sorry to push last commit to master.

@jbruce716 Although it is related, I do not think that it is the bug, since I should never have entered that if. But test it.. :confused:

**Comment by matiasdelellis** [comment]
Hi,
I understand that this report was resolved, and I close it. Please, if necessary, open it again. :smile:
