### ISSUE TITLE
Error: Call to a member function getParent() on bool (When viewing clusters)

### ISSUE THREAD

**Issue by qosmio** [matiasdelellis/facerecognition#154]
## Configuration information

**Pdlib Version: 0.1.0
Models Version: 1
Nextcloud: 16.0.1
OS: Ubuntu 18.04
DB: Postgres 11.4
Browser: Firefox Quantum 64
PHP: 7.3.4
Web Server: NGINX 1.16
Facerecognition Commit: cc43fa5c62f08ae170d13fba867c7b76cccdaddc
Dlib: 19.17**

I'm having an issue viewing the clusters page, even though I've run a full scan for my own username. I've actually never been able to view the clusters page, even on version 15.

![Annotation](https://user-images.githubusercontent.com/8892380/60623405-2e65c980-9da8-11e9-9f5c-14c3d5e235ec.png)

Below is the error 
### PHP Error
```php

[index] Error: Error: Call to a member function getParent() on bool at <<closure>>

0. /data/code/nextcloud/apps/facerecognition/lib/Controller/PersonController.php line 80
   OCA\FaceRecognition\Controller\PersonController->getRedirectToFileUrl(45166)
1. /data/code/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\FaceRecognition\Controller\PersonController->index()
2. /data/code/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\FaceRecognit ... {}, "index")
3. /data/code/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\FaceRecognit ... {}, "index")
4. /data/code/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\FaceRecogn ... r", "index", OC\AppFramework\ ... {}, {_route: "facerecognition.person.index"})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "facerecognition.person.index"})
6. /data/code/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "facerecognition.person.index"})
7. /data/code/nextcloud/lib/base.php line 975
   OC\Route\Router->match("/apps/facerecognition/persons")
8. /data/code/nextcloud/index.php line 42
   OC::handleRequest()
```

GET /apps/facerecognition/persons

### Config
```sql
SELECT appid,
       configkey,
       configvalue
  FROM public.oc_preferences
 WHERE appid='facerecognition'
   AND userid='qosmio'
```
appid|configkey|configvalue
---|---|---|
facerecognition|enabled|true
facerecognition|full_image_scan_done|true
facerecognition|force-create-clusters|false
facerecognition|recreate-clusters|false

**Comment by matiasdelellis** [comment]
Hi @qosmio 
It seems that this file (FileId 45166) is invalid, or does not exist. :disappointed: 
Is it always the same file? Any special storage configuration?

**Comment by qosmio** [comment]
It seems to be a different one every time. Now that you mention it, I see a lot of 

"File with ID XXXXX doesn't exist anymore, skipping it"

errors when I run the background task. Does the app not remove missing images if they've been deleted? Should I clean them manually from the table?

Thanks again!

**Comment by matiasdelellis** [comment]
Ohh.. Ok..
You can force delete non-existing entries by adding a 'stale_images_removal_needed' setting: 

```
INSERT INTO `oc_preferences` (`userid`, `appid`, `configkey`, `configvalue`)
VALUES ('qosmio', 'facerecognition', 'stale_images_removal_needed', 'true');
```

..and then excecute the background task again..

Please, try it..

However, I am interested in knowing if you did any particular task with the files. I will apply a patch to ignore these files in the controller, but I am interested to know what happened.

**Comment by qosmio** [comment]
I tried that now and it fixed the issue! I'm starting to see clusters popping up now. Thanks! 

I mostly moved images around into different folders to organize them a little more, and for some of them I had deleted duplicates. Would that potentially cause problems?

**Comment by matiasdelellis** [comment]
> I tried that now and it fixed the issue! I'm starting to see clusters popping up now. Thanks!

Geat. :smile:
However, I must make a patch to ignore these files in the fronted. :wink: 

> I mostly moved images around into different folders to organize them a little more, and for some of them I had deleted duplicates.

You did it on nextcloud fronted or directly on the disk and then updated?

> Would that potentially cause problems?

It should not cause problems.. in our tests, when moving files the fileId are conserved, and when we delete them we have hooks that should eliminate the entry, but I will do tests. :con

**Comment by matiasdelellis** [comment]
Hi,
I understand that this report was resolved, and I close it. Please, if necessary, open it again. :smile:
