### ISSUE TITLE
"There was an error trying to show your friends" message - was working before

### ISSUE THREAD

**Issue by james-cook** [matiasdelellis/facerecognition#156]
This was working up to a few days ago - now when I go to
`/index.php/settings/user/facerecognition` I get the above message.
I did update a few apps as indicated on the "apps" page recently... could be a consequence(?)
Using Nextcloud 15 - latest

No errors in mysql/error.log or apache2/error.log...

**Comment by james-cook** [comment]
Thinking about this - what I did do some weeks ago is delete some images on the file system (duplicates etc.). 
I do run `occ files:scan --all` in cron... which should make things ok... or can this lead to errors with facerecognition?

**Comment by matiasdelellis** [comment]
Hi @james-cook 
Seems relates to https://github.com/matiasdelellis/facerecognition/issues/154 issue.

Try force remove old entries as described here  https://github.com/matiasdelellis/facerecognition/issues/154#issuecomment-508276648

However, with the last commit it should work correctly..

**Comment by matiasdelellis** [comment]
Hi,
I understand that this report was resolved, and I close it. Please, if necessary, open it again. :smile:
