### ISSUE TITLE
Feature: Able to auto tag

### ISSUE THREAD

**Issue by aleksandrmetik** [matiasdelellis/facerecognition#157]
Hello
Could you please implement a feature to add/remove/change tags to recognized photos. It will be a very helpful feature. Thanks

**Comment by stalker314314** [comment]
I think, in @matiasdelellis design, this would be separate app, one that deals with data produced from facerecognition app. But, yes, I see that we can connect "person" to "tag" and add/remove/change tags to persons after clustering is done. Let's see what @matiasdelellis think, should we do it in this app, or create separate app?

**Comment by matiasdelellis** [comment]
Hi @aleksandrmetik

You mean add tags like Family? High school friends? Etc?

I have some intentions to add some option to assign tags automatically, but it will be simpler than you intend. Just say: "This person is part of my Family", and automatically add the tag "Family". But we should not add labels such as landscape, vacations, friends, food or New York.

What actions do you expect with tags? How do you imagine the workflow?

Of course, thank you very much for participating here. smile
