### ISSUE TITLE
Cant run Analysis

### ISSUE THREAD

**Issue by tilight** [matiasdelellis/facerecognition#190]
```
        Processing image /media/extern-1tb/talha/files/Google Fotos Export/2019/2019-08-11/20190811_143730_019.jpg
        Faces found: 0. Image will be skipped because of the following error: std::bad_array_new_length
        Processing image /media/extern-1tb/talha/files/Google Fotos Export/2019/2019-07-23 #2/20190723_185811(1).jpg
```

An unhandled exception has been thrown:

```
Error: Call to a member function file_get_contents() on null in /var/www/html/cloud/lib/private/Files/Filesystem.php:711
Stack trace:
#0 /var/www/html/cloud/lib/private/legacy/image.php(622): OC\Files\Filesystem::file_get_contents('/media/extern-1...')
#1 /var/www/html/cloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(249): OC_Image->loadFromFile('/media/extern-1...')
#2 /var/www/html/cloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(217): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->prepareImage('/media/extern-1...')
#3 /var/www/html/cloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(167): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->findFaces(Object(CnnFaceDetection), '/media/extern-1...', Object(OCA\FaceRecognition\Db\Image))
#4 /var/www/html/cloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#5 /var/www/html/cloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, false, NULL, NULL)
#6 /var/www/html/cloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/cloud/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/cloud/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/cloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/cloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/cloud/console.php(97): OC\Console\Application->run()
#12 /var/www/html/cloud/occ(11): require_once('/var/www/html/c...')
```

**Comment by stalker314314** [comment]
Do you maybe use server side encryption? I am seeing that `file_get_contents` is used only in that case.

**Comment by tilight** [comment]
hi,
i dont use server side encryption

**Comment by stalker314314** [comment]
Huh. I am out of good ideas:) Can you provide NC version you use, and how you compiled/installed dlib and pdlib. `std::bad_array_new_length` usually points to different libraries being used in compile and in runtime.

Regarding this null on `file_get_contents`, it seems that [exif_imagetype](https://www.php.net/manual/en/function.exif-imagetype.php) is returning some weird value, but only way to check that is to send @matiasdelellis or me that file (not resized/cropped). If this is acceptable for you, my mail is branko [at] kokanovic dot org.

**Comment by matiasdelellis** [comment]
Hi, From what I see you are using an external storage, which is the only thing strange (in the sense that I don't try it), but I guess it shouldn't cause a problem.

**Comment by tilight** [comment]
> Huh. I am out of good ideas:) Can you provide NC version you use, and how you compiled/installed dlib and pdlib. `std::bad_array_new_length` usually points to different libraries being used in compile and in runtime.
> 
> Regarding this null on `file_get_contents`, it seems that [exif_imagetype](https://www.php.net/manual/en/function.exif-imagetype.php) is returning some weird value, but only way to check that is to send @matiasdelellis or me that file (not resized/cropped). If this is acceptable for you, my mail is branko [at] kokanovic dot org.

Hi,
my NC version is 17.0.1 and i've installed all libraries as shown in the installation guide :)
Sorry, clould you name the file you want to have sent? Then i will provide it to you.

**Comment by matiasdelellis** [comment]
> Hi,
> my NC version is 17.0.1 and i've installed all libraries as shown in the installation guide :)
Sorry, clould you name the file you want to have sent? Then i will provide it to you.

> Processing image /media/extern-1tb/talha/files/Google Fotos Export/2019/2019-07-23 #2/20190723_185811(1).jpg

If the exception occurs in this file for example, it is a good file to try. :wink: 

p.s.: Can you confirm how your storage `/media/extern-1tb/` is mounted to NC?

**Comment by stalker314314** [comment]
@tilight Sorry for not telling. I was referring to file: `/media/extern-1tb/talha/files/Google Fotos Export/2019/2019-08-11/20190811_143730_019.jpg` (but please, do not send it as image, send it as file)

@matiasdelellis I think this is not external storage (except in name), as there are parts of path that looks like regular internal storage ("talha/files" part):

/media/extern-1tb/**talha/files**/Google Fotos Export/2019/2019-08-11/20190811_143730_019.jpg`

**Comment by tilight** [comment]
> @tilight Sorry for not telling. I was referring to file: `/media/extern-1tb/talha/files/Google Fotos Export/2019/2019-08-11/20190811_143730_019.jpg` (but please, do not send it as image, send it as file)
> 
> @matiasdelellis I think this is not external storage (except in name), as there are parts of path that looks like regular internal storage ("talha/files" part):
> 
> /media/extern-1tb/**talha/files**/Google Fotos Export/2019/2019-08-11/20190811_143730_019.jpg`

Hi,
uploaded on wetransfer:
https://we.tl/t-FANNTHHt7K

**Comment by matiasdelellis** [comment]
The file seems valid .. You can activate the debug and see the nextcloud.log reports ?
Thanks

**Comment by matiasdelellis** [comment]
HI @tilight 
There was an important rewrite in the management of the files. Can you try again?

**Comment by tilight** [comment]
Do i need to git pull again?

Mit freundlichen Grüßen
Talha Sariyürek


Am Do., 6. Feb. 2020 um 16:03 Uhr schrieb matiasdelellis <
notifications@github.com>:

**Comment by matiasdelellis** [comment]
```
[matias@nube facerecognition]$ git pull
[matias@nube facerecognition]$ make clean & make
[matias@nube facerecognition]$ sudo -u apache php ../../occ face:setup
[matias@nube facerecognition]$ sudo -u apache php ../../occ face:background_job -vvv
```

**Comment by tilight** [comment]
Did it all. Now it tells me:
Your system does not meet the minimum of memory requirements.
Face recognition application requires at least 2 GB of system memory.

But i have 4G system memory.

Greetings
Talha

Am Do., 6. Feb. 2020 um 18:33 Uhr schrieb matiasdelellis <
notifications@github.com>:

**Comment by matiasdelellis** [comment]
mM,, This is strange.. 😕 

Please share your content of you `/proc/meminfo` file (`cat /proc/meminfo` ), and and the result of this in bash: `php -r 'print php_uname("s");'`

**Comment by matiasdelellis** [comment]
@tilight 
What is the status of this? Thanks.
