### ISSUE TITLE
[Feature Request] Less memory

### ISSUE THREAD

**Issue by brOOper** [matiasdelellis/facerecognition#200]
My nextcloud instance is running on a Raspberry Pi 3 Model B+ (only 1 GB RAM). Would be great if the app would work with less memory.

**Comment by stalker314314** [comment]
This basically boils down to issue #93 . HOG detector will give worse results (in detection), but can be run wilth far less memory. Whether it can be run in Raspberry.... remains to be seen. @matiasdelellis I will close this issue as #93 is same, please reopen if you think otherwise.

**Comment by matiasdelellis** [comment]
@brOOper I agree with @stalker314314 
Our official answer is that. :sweat_smile: 

However I clarify that there are ways to 'skip' this problem...
* Swap: It is not obvious? It is also obvious that it will be slower, :sweat_smile: but it works perfectly. :wink: 
* Force an small  size of image for analysis. 
  - https://github.com/matiasdelellis/facerecognition/blob/master/lib/Command/BackgroundCommand.php#L71
  - This also means that you will find reducing photos by narrowing the images a lot.
  - MM.. Try small values... MaxImageArea = 1024x768 = 1786432

This last option will never be official, but I want someone to experience it. :sweat_smile: :wink: 

@stalker314314 This option is not documented.
