### ISSUE TITLE
dlib on Nextcloudpi Raspbian 10 on NC 16.0.3 --> "no module named 'dlib' "

### ISSUE THREAD

**Issue by majordomus0** [matiasdelellis/facerecognition#207]
Hi, 

I have a raspberry pi 4 with 4GB of ram and Raspbian 10 / buster installed with Nextcloud 16.0.3 and would like to install facerecognition.

To have the prerequisites like C++11 support, openblas and libx-dev, I first executed the following commands with no errors

sudo apt update && sudo apt upgrade -y
sudo apt-get install build-essential
sudo apt-get install libopenblas-dev liblapack-dev
sudo apt-get install cmake

After that, I exactly executed all the commands from your installation manual, also with no errors, as I could see

To check if everything was properly installed, I installed pdlib-min-test-suite.

after executing "make php-test" I got the following error:

> bzip2 -d vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2
> php scripts/face_detect.php
> Cannot load Zend OPcache - it was already loaded
> Welcome to pdlib min test suite for Facerecognition app...
> 
> First we try to open the models... Done

> Processing file: input/Big Bang Theory.jpg
> PHP Fatal error:  Uncaught Exception: std::bad_array_new_length in /home/pi/pdlib-min-test-suite/scripts/face_detect.php:35
> Stack trace:
> #0 /home/pi/pdlib-min-test-suite/scripts/face_detect.php(35): CnnFaceDetection->detect('input/Big Bang ...')
> #1 /home/pi/pdlib-min-test-suite/scripts/face_detect.php(53): findFaces('input/Big Bang ...')
> #2 {main}
>   thrown in /home/pi/pdlib-min-test-suite/scripts/face_detect.php on line 35
> make: *** **[Makefile:27: php-test] Error 255**
> 
> 

Because the test suite manual told me so, I executed "make python-test" , which got me the following error:

> python3 scripts/face_detect.py
> Traceback (most recent call last):
>   File "scripts/face_detect.py", line 6, in <module>
>     import dlib
> ModuleNotFoundError: **No module named 'dlib'**
> make: *** [Makefile:30: python-test] Error 1

All this seems pretty strange to me, because after exactly following your installation manual, 
I typed "php -m | grep pdlib" with the expected output "pdlib":

> pi@nextcloudpi:/etc/php/7.3/fpm $ php -m | grep pdlib
> Cannot load Zend OPcache - it was already loaded
> pdlib

Maybe you could help me with this problem as I am really keen to try out the face reognition, but I am no Linux pro , although I try my best. :(

Wish you have a happy new year, greetings, Majordomus

**Comment by matiasdelellis** [comment]
Hi @majordomus0 

> Because the test suite manual told me so, I executed "make python-test" , which got me the following error:
>
>    python3 scripts/face_detect.py
>    Traceback (most recent call last):
>    File "scripts/face_detect.py", line 6, in
>    import dlib
>    ModuleNotFoundError: No module named 'dlib'
>    make: *** [Makefile:30: python-test] Error 1

In this case, it's because you literally didn't compile python bindings.. You have to install other dependencies before build. Don't worry about it. :wink: 

> pi@nextcloudpi:/etc/php/7.3/fpm $ php -m | grep pdlib
> Cannot load Zend OPcache - it was already loaded
> pdlib

According to this, you compiled it correctly.. So it sounds more like a memory problem .. This test uses a large image ... which implies a lot of memory. and I guess the kernel is killing the process .. :disappointed: 

First of all, you can try adding swap memory. A 2Gb Swap file I guess it would be fine. 

https://wiki.archlinux.org/index.php/Swap

**Comment by majordomus0** [comment]
Hi Matias, 

first let me say thank you 1000 times for your help, your software could now be installed! :-)

As my Nextcloud updated itself to 17.0.2.1, facerecognition somehow wasn't available to be installed in the official app store, so I followed the instructions for manual install.

There are only 2 more errors / questions with it with it, maybe you can tell me if these errors are a problem?

First, after executing

**sudo -u www-data php ./occ face:setup**   (as I read I think www-data is the "httpd" user on raspbian)

I get the message:  **There are no commands defined in the "face" namespace.**  
Does this message show me that something has not been installed properly?

The other thing is, in "configuration information" under NC settings, I get the message

> Pdlib Version: 0.1.0
> 
> Models Version: 1
> 
> **The files of the models version 1 were not found.** 

Again, is this error message bad?


Anyway, thank you again for your great help, thank you for programming this software and contributing to a great project.

I wish you a happy new year and greetings from Germany to Italy (if that's where you are from, by your name :-) !

**Comment by majordomus0** [comment]
Hey, sorry for bothering you. After restarting, the models could be installed properly with 

> sudo -u www-data php ./occ face:setup

 without the error message.

So I think, after restart, I think the program will tell me that it found the models :-)

**Comment by matiasdelellis** [comment]
Wow. I'm glad it works! :grimacing: 

> I wish you a happy new year and greetings from Germany to Italy (if that's where you are from, by your name :-) !

I have Italian ancestry, but I am Argentine. :sweat_smile: 
Thank you very much for the greeting! Best wishes to you too. :smile:

**Comment by mohamnag** [comment]
just ended up here as the guides still have no way of proper installation on a raspberry pi and there are no precompiled binary for 'armhf' architecture in your repositories. could you please add some tutorial on how to proceed installing on a raspberry pi? 

now that goolge is going to charge for its photo storage, is the best chance for raspberry pi based image services like this to take off!

**Comment by matiasdelellis** [comment]
> just ended up here as the guides still have no way of proper installation on a raspberry pi and there are no precompiled binary for 'armhf' architecture in your repositories. could you please add some tutorial on how to proceed installing on a raspberry pi?

Hi @mohamnag  
You have to compile pdlib by hand... Raspberry has nothing in particular to consider..

Just follow this guide.. https://github.com/goodspb/pdlib#dlib 

> now that goolge is going to charge for its photo storage, is the best chance for raspberry pi based image services like this to take off!

Ohh.. Poor us!. hahaha.  :see_no_evil:
