### ISSUE TITLE
Support for external storage

### ISSUE THREAD

**Issue by Ang3er** [matiasdelellis/facerecognition#212]
As already discussed in issue #26 a beta version was released for support of shared storage. In my case my nextcloud instance is running in a vm on my QNAP Nas. Thereby I mounted the storage as external storage with type local via an nfs mount. As nextcloud now thinks it is an external storage, the facerecognition is not analyzing any pictures in the external storages.

A screenshot to explan my mount option.
CUrrently it is not an option to change the mount option, as I need to access the storages via QNAP directly with afp. Therefore it is not an option to hold all data as a user local data and share it with the others, because than the data will be stored in nextcloud/data/user/files/...
Currently I can access the data directly via afp and the folder Bilder ;)

![image](https://user-images.githubusercontent.com/12126245/71893669-9bd62680-314c-11ea-92a2-51f7d95d5044.png)

Thanks in advance

**Comment by matiasdelellis** [comment]
Hi @Ang3er 
The same logic used in #26 can be used for external storages.

https://github.com/matiasdelellis/facerecognition/blob/4a2683fab8a0da8d0bdfa1600a1fc29d5c7537f1/lib/Service/FileService.php#L192-L203

This is pending because I can't find a consistent way to detect them. We need something as simple as this.

https://github.com/matiasdelellis/facerecognition/blob/4a2683fab8a0da8d0bdfa1600a1fc29d5c7537f1/lib/Service/FileService.php#L178-L183

But I still don't see how to do it cleanly. And note that I cannot consider all cases individually. It should be something more or less generic.

**Comment by Ang3er** [comment]
@matiasdelellis Perferct, didnt know that this request is still pending. Thanks for the nice development. Therefore I think we can close this issue

**Comment by matiasdelellis** [comment]
Reopen this as reference.. :wink:

**Comment by hairlesshobo** [comment]
Hey, great work on this app so far. Believe it or not, the ability to do in-house facial recognition is what encouraged me to setup my own NextCloud instance. With that said.. what is the latest news (if any) on support for external storage? All of my data is stored on external storage and without the ability to scan for faces there, it makes me sad ;).

**Comment by Ang3er** [comment]
@matiasdelellis: May this be a reference point as the occ files:scan --all is enabled to check on external data storages 
https://help.nextcloud.com/t/automate-occ-filescan/35282/7

thanks in advance

**Comment by matiasdelellis** [comment]
Hi @Ang3er @hairlesshobo @stalker314314 

Sorry I tagged all of you, but I guess you are the most interested in this :sweat_smile: 

On https://github.com/matiasdelellis/facerecognition/pull/246 add experimental support for external storage. :wink: 

As with shared files, it will remain experimental in the sense that it will not be enabled by default, and there will be no and option in the fronted to enable it until it is well tested, but I think it's functional enough.. :wink:

**Comment by matiasdelellis** [comment]
p.s:

`sudo -u apache php occ config:app:set facerecognition handle-external-files --value true`

:wink:

**Comment by hairlesshobo** [comment]
@matiasdelellis awesome! I will check it out asap and report back. Thanks!

**Comment by Ang3er** [comment]
waiting for the merge ;)

**Comment by matiasdelellis** [comment]
Done..
If anyone can do a real test welcome... :wink:

**Comment by Ang3er** [comment]
Seems to work pretty good, now I am just trying to seperate wrong persons from groups. Looking for a solution in the current open threads, maybe somebody can give me a hint?

**Comment by matiasdelellis** [comment]
> Seems to work pretty good.

Geat. :smile:
I will leave it open until the next version is published to discuss any inconvenience. :wink: 

> now,  am just trying to seperate wrong persons from groups. Looking for a solution in the current open threads, maybe somebody can give me a hint?

There is still no way to separate groups. It is fairly discussed, but we are still focused on fully automatic grouping. The fundamental difference in clustering quality is defined by minimal confidence and sensitivity..
See: https://github.com/matiasdelellis/facerecognition/wiki/Confidence and https://github.com/matiasdelellis/facerecognition/wiki/Sensitivity

What values do you have configured? and which model are you using?

**Comment by Ang3er** [comment]
Currently running with your recommondations --> Model 2 Confidence 0,9 Sensitivity 0,4.
Will play with those parameters, but once again --> BIG THANKYOU! for such a nice app. Would like to help you implement more although iam better on the side of ideas and testing ;P

**Comment by matiasdelellis** [comment]
> Model 2 Confidence 0,9 Sensitivity 0,4.

You can increase confidence to 1.0, but these are practically the best values and in this point you should have good results. How many errors do you see? 

You can try to force a little more the sensitivity: Changing this value https://github.com/matiasdelellis/facerecognition/blob/master/lib/Service/SettingsService.php#L56 to 0.3, but for now, I will not change this default value.

**Comment by hairlesshobo** [comment]
@matiasdelellis i was able to test it out and can also confirm that it works!

I do have one question, and this may be wayyy outside of the scope of your app, but I must admit.. I didn't get quite the results I expected. What I mean is that, based on my current system configuration, it did not scan what I thought it would. So here is a quick layout of how I have things configured.. the "admin" account has all of the SMB shares that I need attached to it. Then, sub folders from that are shared from admin to other users. For example, I have the "Phones" share which contains a sub folder for both my wife and I. Our phones automatically upload all of our pictures/videos. Well, for my user account, the folder called "Camera", which is actually shared from "admin" to my account shows up in the file view...

![image](https://user-images.githubusercontent.com/3877800/79779094-c61cb000-8307-11ea-9b79-bfaafb8cc7fc.png)

I have enabled both of the following settings:
`occ config:app:set facerecognition handle_external_files --value true`
`occ config:app:set facerecognition handle_shared_files --value true`

So, with all of that said.. is there a better way to set things up on my side so that this all works as expected? Should I instead mount the share per-user? The reason I set things up like this is so that we can easily share things between us, such as when I take a photo, my wife can easily view it and vice-versa. I am also concerned that if I setup shares per-user, it will double the work to do facial recognition. Is there any way to share this facial recognition stats between the two of us?

OK, so sorry if I got way off topic or if you couldn't follow what I was saying, but any advice would be suggested.

Thanks!

**Comment by matiasdelellis** [comment]
Wow, this is quite a complex setup .. :sweat_smile: 

> @matiasdelellis i was able to test it out and can also confirm that it works!

Ok. Thanks.. :smile: 

> So, with all of that said.. is there a better way to set things up on my side so that this all works as expected? 

MM.. It is not clear what you expect. Beyond the other questions that I now answer.

>  Should I instead mount the share per-user?

For a setup like you have, I would suggest using group folders. But since no one required it, I had not implemented it. Maybe soon I can do it.

>  Is there any way to share this facial recognition stats between the two of us?

No.. Not yet, and it is unlikely to change soon. Duplicate analisys on same images is something I would like to avoid, but it adds a lot of complexity.

In fact, there are questions about whether it is correct analyze shared photos, and partly because of this it is disabled by default, but let's ignore this discussion. :sweat_smile: 

On the other hand, assigning names to people is something very personal. For example, in the photos that you appear you will probably assign only your name, but your wife, in the same photos, assigned you with some loving nickname. You would call your brother by name, and your wife would only call him brother-in-law.

Well, in resume we intend to avoid double work at some point, but the naming is independent.. sorry.

**Comment by hairlesshobo** [comment]
Oh absolutely, I completely understand the naming being per-user, but i really meant the face statistics and grouping being shared. I realize my setup is very complicated and the more I think about it, the more I realize I am trying to use NextCloud in a way that it really isn't designed. But in short, thank you for all the hard work you have put into this!! I will continue playing around and see what I can come up with.

**Comment by matiasdelellis** [comment]
If you need this application with external storage, **DO NOT UPDATE NEXTCLOUD 19 YET**.

Well .. Don't be scared by the capital letters .. I'm not yelling at you .. haha.
The rest of nextcloud, and this application works correctly.. 

For my part, I only have it tested with SFTP. Most likely, it is a problem with this storage. If someone test it with other storage, please comment.

```
	Processing image /tmp/oc_tmp_WgvgVc
	Faces found: 0. Image will be skipped because of the following error: Image is not valid, probably cannot be loaded
	RuntimeException: Image is not valid, probably cannot be loaded in /var/www/html/nextcloud/apps/facerecognition/lib/Helper/TempImage.php:116
Stack trace:
#0 /var/www/html/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#1 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(210): OCA\FaceRecognition\Helper\TempImage->__construct('/tmp/oc_tmp_Wgv...', 'image/png', 4194300, 512)
#2 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage(Object(OCA\FaceRecognition\Db\Image))
#3 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#4 /var/www/html/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(25200, true, Object(OC\User\User), NULL)
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#12 {main}
```	Processing image /tmp/oc_tmp_WgvgVc
	Faces found: 0. Image will be skipped because of the following error: Image is not valid, probably cannot be loaded
	RuntimeException: Image is not valid, probably cannot be loaded in /var/www/html/nextcloud/apps/facerecognition/lib/Helper/TempImage.php:116
Stack trace:
#0 /var/www/html/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#1 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(210): OCA\FaceRecognition\Helper\TempImage->__construct('/tmp/oc_tmp_Wgv...', 'image/png', 4194300, 512)
#2 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage(Object(OCA\FaceRecognition\Db\Image))
#3 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#4 /var/www/html/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(25200, true, Object(OC\User\User), NULL)
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#12 {main}


```
[PHP] Error: fopen(sftpread://home/matias/Imágenes/The Big Bang Theory//111951_0234b.jpg): failed to open stream: &quot;OCA\Files_External\Lib\Storage\SFTPReadStream::stream_open&quot; call failed at /var/www/html/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php#378

GET /apps/facerecognition/face/81753/thumb/32
from 192.168.1.155 by matias at 2020-05-07T12:59:52+00:00
```

**Comment by matiasdelellis** [comment]
It seems the SFTP is broken in Nextcloud. I still haven't test the rest, but I think it is exclusively SFTP

**Comment by szaimen** [comment]
Maybe you could test a local external storage for testing?
That is relatively fail-proof in my experience...

**Comment by matiasdelellis** [comment]
> Maybe you could take a local external storage for testing?
> That is relatively fail-proof in my experience...

Local storage works..

**Comment by hanmey97** [comment]
Hey
I'm trying to use the app with an external SMB server.
I executed the occ commands for the external memory. However, he cannot find any photos from the external memory.

**Comment by matiasdelellis** [comment]
Hi @hanmey97 

First of all . You enable it?

> occ config:app:set facerecognition handle_external_files --value true

... then you can force the search for new photos:

> occ user:setting USER_ID facerecognition full_image_scan_done false

**Comment by hanmey97** [comment]
Yes, I have also activated shared files as a test. Files that are normally stored in the cloud are also processed.

**Comment by matiasdelellis** [comment]
@hanmey97 

Please, execute that and share the log:

```
[matias@nube nextcloud]$ sudo -u apache php occ user:setting matias facerecognition full_image_scan_done false
[sudo] password for matias: 
[matias@nube nextcloud]$ sudo -u apache php occ user:setting matias facerecognition full_image_scan_done 
false
[matias@nube nextcloud]$ time sudo -u apache php occ face:background_job -u matias -vvv
1/10 - Executing task CheckRequirementsTask (Check all requirements)
	System: Linux
	System memory: 7808102400
	PHP Memory Limit: 6442450944
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
	Skipping stale images removal for user matias as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Found 0 faces without associated persons for user matias and model 4
	Clusters already exist, estimated there is no need to recreate them
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
	Finding missing images for user matias
	Found /matias/files/1365-1024.jpg
	Found /matias/files/Adjuntos/Birdie.jpg
	Found /matias/files/Adjuntos/Toucan.jpg
	Found /matias/files/IMG-20160217-WA0000.jpg
	Found /matias/files/Imágenes/Android/1*cynXSoakjksBCXgsaHUjPA.jpeg
	Found /matias/files/Imágenes/Android/Camara/IMG-20151008-WA0006.jpg
	Found /matias/files/Imágenes/Android/Camara/IMG-20160410-WA0006.jpg
	Found /matias/files/Imágenes/Android/Camara/IMG-20161118-WA0004 (2).jpg
....
```

**Comment by hanmey97** [comment]
I'm sorry for replying so late.
After doing a file scan it worked all of a sudden. Thanks for the quick help.

**Comment by Derkades** [comment]
Worked for me as well in NC 19.0.3 using Samba shares (after setting full_image_scan_done false)

**Comment by Derkades** [comment]
When sharing one external storage with multiple users, the application seems to scan for faces for each user. This is a bit problematic when using a network share with 20k+ images.

Would it be possible to ignore already scanned files? From my testing it looks like the nextcloud preview app does handle this correctly, when generating thumbnails as one user and switching to another it uses thumbnails from disk instead of re-generating thumbnails.

At least currently users are not able to modify face groups so to me it seems that they could be shared among users.

**Comment by matiasdelellis** [comment]
Hi @Derkades 

> Would it be possible to ignore already scanned files? 

It is possible of course, but it can complicates the logic of the application a lot. It is in constant consideration, but it is not yet among the priorities. Keep in mind that although it works, it is still a hidden feature, and for testing.. Sorry..

Is it very inefficient? Yes.. Sorry.. :disappointed: 
But it works, and there are other problems with higher priority.. :sweat_smile:

**Comment by matiasdelellis** [comment]
Well, With the latest update I added support for group folders, which I think is the last relevant one to add. 😬

**Comment by Derkades** [comment]
@szaimen I've created an issue here: #397

**Comment by janneskretschmer** [comment]
Hello, thanks for the great effort.
I tried to enable the image recognition for external storage (and to be sure for shared files):
`pi@nextcloudpi:~ $ sudo -u www-data php /var/www/nextcloud/occ config:app:set facerecognition handle-external-files --value true`
`Config value handle-external-files for app facerecognition set to true`
`pi@nextcloudpi:~ $ sudo -u www-data php /var/www/nextcloud/occ config:app:set facerecognition handle_shared_files --value true`
`Config value handle_shared_files for app facerecognition set to true`

The folder is mounted with samba and contains almost 500GB of images:
![grafik](https://user-images.githubusercontent.com/14330904/107293244-904de100-6a6b-11eb-9357-3ea1be079553.png)

The background_job works for the local images like a charm, but it doesn't detect any external files. There is no .nomedia/.noimage file or similar in the path.
> 9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
10/10 - Executing task UnlockTask (Release obtained lock)

Do you have any idea, what I'm doing wrong?

**Comment by Derkades** [comment]
@janneskretschmer make sure to also run `occ user:setting YourUsernameHere facerecognition full_image_scan_done false`
