### ISSUE TITLE
Images handled differently in "standard" nextcloud after adding facerecognition

### ISSUE THREAD

**Issue by james-cook** [matiasdelellis/facerecognition#216]
I have been progressively installing nextcloud, and then facerecognition on a new ubuntu droplet.
When moving from a full_fpm_alpine (includes imagemagick - I saved this droplet image so I can go back to check) by adding ONLY facerecognition dependencies  (compiling in dlib/pdlib etc.) and then the app itself I noticed that the behaviour of Nextcloud itself before and afterwards is different.

Has anyone else noticed this?

### Expected behaviour

The original image handling behaviour should not be affected (see the actual behaviour below)

### Actual behaviour
This is just what I've noticed so far:

- Drag and drop of a PDF file into a folder no longer generates a thumbnail for the pdf - just the red pdf icon appears
- Clicking on a TIFF file (thumbnail/name) no longer leads to a "view" of the TIFF file in the gallery (in fact a larger JPG is shown), instead you get a "What do you want to do with this file" download kind of dialog in the browser
- <other things perhaps>

### Steps to reproduce
1. install https://github.com/ReinerNippes/nextcloud to a new droplet
2. change the build to use full_fpm_alpine instead of just fpm-alpine for the nextcloud container (full_fpm_alpine contains imagemagick with a wide range of image handling delegate (though SVG is missing I seem to remember))
3. fire up the NC instance - all works as it "should" including the handling of "exotic" file types - e.g.:pdf and tiff
4. Now compile dlib/pdlib into the container (in the dockerfile) - I'm using this code pretty much 1 to 1:https://github.com/matiasdelellis/facerecognition/issues/175#issuecomment-554747326
5. and install the facerecognition app (this I did by hand so far - not in the dockerfile yet)
6. File handling of pdf and tiff files has changed

### Server configuration

* **Operating system:**
Host -  is ubuntu 16.04 - upgraded to be docker ready by https://github.com/ReinerNippes/nextcloud

Guest - is full_fpm_alpine modified by https://github.com/ReinerNippes/nextcloud 

* **Pdlib version:**
How can I check this? - I used `git clone https://github.com/goodspb/pdlib.git 
`
* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
Dlib works file as shown by test

```
 make php-test
mkdir -p vendor/models/1
wget https://github.com/davisking/dlib-models/raw/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2 -O vendor/models/1/mmod_human_face_detector.dat.bz2
--2020-01-18 02:19:53--  https://github.com/davisking/dlib-models/raw/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/davisking/dlib-models/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2 [following]
--2020-01-18 02:19:54--  https://raw.githubusercontent.com/davisking/dlib-models/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2
Resolving raw.githubusercontent.com... 151.101.112.133
Connecting to raw.githubusercontent.com|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 694687 (678K) [application/octet-stream]
Saving to: 'vendor/models/1/mmod_human_face_detector.dat.bz2'

vendor/models/1/mmod_human_face_detector.d 100%[========================================================================================>] 678.41K  --.-KB/s    in 0.003s

2020-01-18 02:19:54 (225 MB/s) - 'vendor/models/1/mmod_human_face_detector.dat.bz2' saved [694687/694687]

bzip2 -d vendor/models/1/mmod_human_face_detector.dat.bz2
mkdir -p vendor/models/1
wget https://github.com/davisking/dlib-models/raw/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2 -O vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2
--2020-01-18 02:19:54--  https://github.com/davisking/dlib-models/raw/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/davisking/dlib-models/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2 [following]
--2020-01-18 02:19:55--  https://raw.githubusercontent.com/davisking/dlib-models/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2
Resolving raw.githubusercontent.com... 151.101.112.133
Connecting to raw.githubusercontent.com|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21428389 (20M) [application/octet-stream]
Saving to: 'vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2'

vendor/models/1/dlib_face_recognition_resn 100%[========================================================================================>]  20.44M  80.8MB/s    in 0.3s

2020-01-18 02:19:56 (80.8 MB/s) - 'vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2' saved [21428389/21428389]

bzip2 -d vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2
mkdir -p vendor/models/1
wget https://github.com/davisking/dlib-models/raw/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2 -O vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2
--2020-01-18 02:20:12--  https://github.com/davisking/dlib-models/raw/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/davisking/dlib-models/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2 [following]
--2020-01-18 02:20:12--  https://raw.githubusercontent.com/davisking/dlib-models/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2
Resolving raw.githubusercontent.com... 151.101.112.133
Connecting to raw.githubusercontent.com|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5706710 (5.4M) [application/octet-stream]
Saving to: 'vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2'

vendor/models/1/shape_predictor_5_face_lan 100%[========================================================================================>]   5.44M  --.-KB/s    in 0.06s

2020-01-18 02:20:13 (96.4 MB/s) - 'vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2' saved [5706710/5706710]

bzip2 -d vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2
php scripts/face_detect.php
Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg
Number of faces detected: 7
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Processing file: input/Big Bang Theory.png
Number of faces detected: 7
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done

```

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
This is NOT working - but as I understand it this is not critical:
```
/tmp/d1/pdlib-min-test-suite # make python-test
python3 scripts/face_detect.py
Traceback (most recent call last):
  File "scripts/face_detect.py", line 6, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'
```

* **PHP version:**
On guest: PHP Version => 7.3.13

* **Web server:**
nginx

* **Database:**
mysql

* **Nextcloud version:**
latest stable - 17.02

### Client configuration

* **Browser:**
Chrome

* **Operating system:**
W10

**Comment by matiasdelellis** [comment]
Hi @james-cook 
This looks like a bug, I will try to reproduce it. :wink: 

Thanks.

**Comment by james-cook** [comment]
Yes, I will also check the  complete procedure once again.

**Comment by james-cook** [comment]
PDF: 
I re-ran the whole install. The problem is definitely reproducible. 
In **my setup** It happens BEFORE you enable the facerecognition app. 
It seems adding the lines;

> [pdlib]
> extension="pdlib.so"

to the files: `/usr/local/etc/php/php.ini` and `/var/www/html/config/php.ini` "cause" the PDF error. 
(I did not even get around to enabling the facerecognition app)
Simply by removing those lines from `/var/www/html/config/php.ini` allows the PDF files to be converted again.

For the TIFF handling I missed the point at which it happens (but it DOES happen!) so I'll re-check.
AFAICT it's not affected by the installation/settings for pdlib.so.

**Comment by james-cook** [comment]
I checked "everything" again.
The upshot is that the handling for TIFF and PDF remain "OK" right until I enable the  pdlib.so library.
Even after I add the line

> [pdlib]
> extension="pdlib.so"

to `/var/www/html/config/php.ini`
the handling is "OK".

But after restarting nginx and nextcloud the problem appears for both TIFF and PDF files.

There is also some "entanglement" with CameraRawPreviews app. 
In the previous run I noticed this was originally ENABLED, so I disabled it early in the procedure.
This time I kept the app enabled throughout:

- In the previous run, the thumbnail for the TIFF was always generated but clicking the file name or thumbnail after enabling pdlib.so led to the download dialog being displayed.
- In this run, with CameraRawPreviews enabled in every step, in the last step after enabling pdlib.so, the TIFF thumbnail is no longer generated. And clicking on the filename leads to the preview page but the dialog says "Error loading XXX.TIFF"

**Comment by matiasdelellis** [comment]
Wow. Thanks for the research. :grimacing: 

Honestly, at first glance I don't understand where this can happen. It's strange.. :disappointed: 

Today I will try to finish the PR #213 and then investigated this better .. :wink:

**Comment by james-cook** [comment]
No worries :) This has been itching me for some time.
I checked the error log for nextcloud and see:
This is the pdf error:


```
{"reqId":"LxPixtau2kuPktCxyz4R","level":3,"time":"2020-01-22T10:39:27+00:00","remoteAddr":"37.228.255.207","user":"admin","app":"core","metho     d":"GET","url":"/core/preview?fileId=907&c=aa913088d6982bde41c6f994f12a0d21&x=250&y=250&forceIcon=0","message":
  {"Exception":"ImagickException     ","Message":"Postscript delegate failed `[ghostscript library 9.50] -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap     =500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dFirstPage=1 -dLastPage=1 '     -sOutputFile=/tmp/magick-44TLy44WgbMICl%d' '-f/tmp/magick-44EzGbTNOKoBJg' '-f/tmp/magick-44WHNOEQJJOlHF'': Unrecoverable error: ioerror in se     tdistillerparams
Operand stack:
    --nostringval--
 @ error/ghostscript-private.h/InvokeGhostscriptDelegate/171","Code":415,"Trace":[
  {"file":"/var/www/html/lib/private/Preview/Bitmap.php","line":88,"function":"readimage","class":"Imagick","type":"->","args":["/var/nc-data/admin/files/ddG/test.pdf[0]"]},
  {"file":"/var/www/html/lib/private/Preview/Bitmap.php","line":51,"function":"getResizedPreview","class":"OC\\Preview\\Bitmap","type":"->","args":
    ["/var/nc-data/admin/files/ddG/test.pdf",1024,768]},
  {"file":"/var/www/html/lib/private/Preview/GeneratorHelper.php","line":62,"function":"getThumbnail","class":"OC\\Preview\\Bitmap","type":"->","args":[
    {"__class__":"OC\\Files\   ode\\File"},1024,768]},
```

AFAICT this error only occurs when pdlib.so is enabled.

**Comment by james-cook** [comment]
It looks like this may be solved. 

I re-ran everything this time using your Dockerfile elements from: https://github.com/matiasdelellis/facerecognition/issues/175#issuecomment-554747326
Initial tests seem to show that with pdlib.so compiled in this way TIFFs and PDFs are being handled correctly.

I'll run the whole thing again just to make and document the differences in the Dockerfiles used.

**Comment by matiasdelellis** [comment]
Hi @james-cook 
I still don't fully understand problem. :sweat_smile: but then can we consider it fixed?

Thanks.

**Comment by matiasdelellis** [comment]
Well... I guess it's fixed .. :sweat_smile: 

Thanks you so much!.
