### ISSUE TITLE
Error: Call to undefined function OCA\FaceRecognition\Command\bzopen()

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#218]
**Steps to Reproduce**
sudo -u www-data php /var/www/nextcloud/occ face:setup

**Error Message**
An unhandled exception has been thrown:
Error: Call to undefined function OCA\FaceRecognition\Command\bzopen() in /var/www/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php:191

Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(102): OCA\FaceRecognition\Command\SetupCommand->bunzip2('/tmp/oc_tmp_mTp...', '/var/www/nextcl...')
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/console.php(97): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**PHP version:**
PHP 7.3

**Nextcloud version:**
v17

**Comment by matiasdelellis** [comment]
Install php-bz2 (Or the equivalent name in your distribution)

**Comment by snakyjake1** [comment]
I had tried this with the same problem:
> $ apt install php-bz2
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> php-bz2 is already the newest version (2:7.4+71+ubuntu16.04.1+deb.sury.org+1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

However, this worked instead:

> $ apt install php7.3-bz2 

Thank you!

**Comment by matiasdelellis** [comment]
Ok. Another piece of information to add to the wiki, but we can close it .. 
Thank for participate here.. :smile:
