### ISSUE TITLE
Empty page/frame under the User Face Recognition settings.

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#219]
I see an empty page/frame under the User Face Recognition settings.
https://[ip]/nextcloud/index.php/settings/user/facerecognition

No problems seeing the Administration Face Recognition page.
https://[ip]/nextcloud/index.php/settings/admin/facerecognition

Log:
"Could not find resource file \"\/nextcloud\/apps\/facerecognition\/js\/templates.js\""

**[SOLUTION]**
I manually extracted the missing file **template.js** from github, and moved it to the folder "**nextcloud/apps/facerecognition/js**"

**Comment by matiasdelellis** [comment]
HI @snakyjake1 
The `/nextcloud/apps/facerecognition/js/templates.js` goes not exist on github.. :sweat_smile: 

I don't know where you extracted it, but I tell you that it is created automatically when you run `make` or `make js-templates`.
Please run this last command (`make js-templates`) and share the result. :wink:

**Comment by snakyjake1** [comment]
> $ make js-templates
> node_modules/handlebars/bin/handlebars js/templates -f js/templates.js
> make: node_modules/handlebars/bin/handlebars: Command not found
> Makefile:106: recipe for target 'js-templates' failed
> make: *** [js-templates] Error 127

**Comment by snakyjake1** [comment]
> I don't know where you extracted it

I got templates.js from the release asset facerecognition.tar.gz.

**Comment by matiasdelellis** [comment]
> make: node_modules/handlebars/bin/handlebars: Command not found

Ok.. Composer install handlebars when execute `make`, an you had problems with 'composer' on other report.. If you solved composer, run a `make clean` and then `make` again. 

Please share the result of both commands.. :wink:

**Comment by snakyjake1** [comment]
I'm wondering if the "cp" command is missing....

> $ make clean
> rm -rf translationfiles
> rm -f translationtool.phar
> rm -rf build
> rm -rf vendor
> rm -rf node_modules

> $ make
> Checking binaries needed to build the application
> Testing npm, curl, wget and bzip2. If one is missing, install it with the tools of your system.
> npm -v
> 3.5.2
> curl -V
> curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
> Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
> wget -V
> GNU Wget 1.17.1 built on linux-gnu.
> 
> +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls +ntlm
> +opie -psl +ssl/openssl
> 
> Wgetrc:
>     /etc/wgetrc (system)
> Locale:
>     /usr/share/locale
> Compile:
>     gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc"
>     -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib
>     -I../../lib -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include
>     -DHAVE_LIBSSL -DNDEBUG -g -O2 -fPIE -fstack-protector-strong
>     -Wformat -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64
>     -g -Wall
> Link:
>     gcc -DHAVE_LIBSSL -DNDEBUG -g -O2 -fPIE -fstack-protector-strong
>     -Wformat -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64
>     -g -Wall -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro
>     -Wl,-z,now -L/usr/lib -lpcre -luuid -lssl -lcrypto -lz -lidn
>     ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a
> 
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later
> <http://www.gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
> Please send bug reports and questions to <bug-wget@gnu.org>.
> composer install --prefer-dist
> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Package operations: 30 installs, 0 updates, 0 removals
>   - Installing christophwurst/nextcloud (v14.0.13): Loading from cache
>   - Installing symfony/polyfill-ctype (v1.13.1): Loading from cache
>   - Installing webmozart/assert (1.6.0): Loading from cache
>   - Installing phpdocumentor/reflection-common (2.0.0): Loading from cache
>   - Installing phpdocumentor/type-resolver (1.0.1): Loading from cache
>   - Installing phpdocumentor/reflection-docblock (4.3.4): Loading from cache
>   - Installing phpunit/php-token-stream (2.0.2): Loading from cache
>   - Installing sebastian/version (2.0.1): Loading from cache
>   - Installing sebastian/resource-operations (1.0.0): Loading from cache
>   - Installing sebastian/recursion-context (3.0.0): Loading from cache
>   - Installing sebastian/object-reflector (1.1.1): Loading from cache
>   - Installing sebastian/object-enumerator (3.0.3): Loading from cache
>   - Installing sebastian/global-state (2.0.0): Loading from cache
>   - Installing sebastian/exporter (3.1.2): Loading from cache
>   - Installing sebastian/environment (3.1.0): Loading from cache
>   - Installing sebastian/diff (2.0.1): Loading from cache
>   - Installing sebastian/comparator (2.1.3): Loading from cache
>   - Installing phpunit/php-text-template (1.2.1): Loading from cache
>   - Installing doctrine/instantiator (1.3.0): Loading from cache
>   - Installing phpunit/phpunit-mock-objects (4.0.4): Loading from cache
>   - Installing phpunit/php-timer (1.0.9): Loading from cache
>   - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
>   - Installing theseer/tokenizer (1.1.3): Loading from cache
>   - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
>   - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
>   - Installing phpspec/prophecy (v1.10.2): Loading from cache
>   - Installing phar-io/version (1.0.1): Loading from cache
>   - Installing phar-io/manifest (1.0.1): Loading from cache
>   - Installing myclabs/deep-copy (1.9.5): Loading from cache
>   - Installing phpunit/phpunit (6.4.0): Loading from cache
> sebastian/global-state suggests installing ext-uopz (*)
> phpunit/phpunit-mock-objects suggests installing ext-soap (*)
> phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
> phpunit/phpunit suggests installing ext-xdebug (*)
> phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
> Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
> Generating autoload files
> composer update --prefer-dist
> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
> Generating autoload files
> npm i
> facerecognition@0.5.8 /root/downloads/facerecognition
> ├─┬ handlebars@4.7.2
> │ ├── neo-async@2.6.1
> │ ├─┬ optimist@0.6.1
> │ │ ├── minimist@0.0.10
> │ │ └── wordwrap@0.0.3
> │ ├── source-map@0.6.1
> │ └─┬ uglify-js@3.7.6
> │   └── commander@2.20.3
> └── lozad@1.14.0
> 
> npm WARN facerecognition@0.5.8 license should be a valid SPDX license expression
> mkdir -p vendor/js
> cp node_modules/handlebars/dist/handlebars.js -f vendor/js/handlebars.js
> mkdir -p vendor/js
> cp node_modules/lozad/dist/lozad.js -f vendor/js/lozad.js
> **node_modules/handlebars/bin/handlebars js/templates -f js/templates.js**
> **/usr/bin/env: ‘node’: No such file or directory**
> **Makefile:106: recipe for target 'js-templates' failed**
> **make: *** [js-templates] Error 127**

>  $ ls -l /usr/bin/env
> -rwxr-xr-x 1 root root 31408 Mar  2  2017 **/usr/bin/env**

**Comment by matiasdelellis** [comment]
> /usr/bin/env: ‘node’: No such file or directory

Install nodejs. Search among your distribution packages... :wink:

**Comment by snakyjake1** [comment]
> $ apt install nodejs
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> **nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.2).**
> 0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.

**Comment by snakyjake1** [comment]
Is there supposed to be a copy command in the Makefile?

**[Makefile](https://github.com/matiasdelellis/facerecognition/blob/a6f9a387642988923ade75b7a9d5421a08a7bfe5/Makefile#L106)**
```
js-templates:
	node_modules/handlebars/bin/handlebars js/templates -f js/templates.js
```

**Comment by matiasdelellis** [comment]
Hi @snakyjake1 

> Is there supposed to be a copy command in the Makefile?

No.. The `handlebars` binary is a dependency for construction -This compiles the templates-, but it is not necessary for the execution of the application. However `handlebars.js` is necessary at runtime.

**Comment by matiasdelellis** [comment]
what files do you have in `node_modules/` ? :confused:

**Comment by snakyjake1** [comment]
I have these files in node_modules:

.:
commander  handlebars  lozad  minimist  neo-async  optimist  source-map  uglify-js  wordwrap

./commander:
CHANGELOG.md  LICENSE  Readme.md  index.js  package.json  typings

./commander/typings:
index.d.ts

./handlebars:
LICENSE          bin   lib           print-script      runtime.js
README.markdown  dist  package.json  release-notes.md  types

./handlebars/bin:
handlebars

./handlebars/dist:
amd                handlebars.amd.min.js  handlebars.runtime.amd.js      handlebars.runtime.min.js
cjs                handlebars.js          handlebars.runtime.amd.min.js
handlebars.amd.js  handlebars.min.js      handlebars.runtime.js

./handlebars/dist/amd:
handlebars  handlebars.js  handlebars.runtime.js  precompiler.js

./handlebars/dist/amd/handlebars:
base.js   decorators     exception.js  helpers.js  logger.js       runtime.js      utils.js
compiler  decorators.js  helpers       internal    no-conflict.js  safe-string.js

./handlebars/dist/amd/handlebars/compiler:
ast.js   code-gen.js  helpers.js              parser.js   visitor.js
base.js  compiler.js  javascript-compiler.js  printer.js  whitespace-control.js

./handlebars/dist/amd/handlebars/decorators:
inline.js

./handlebars/dist/amd/handlebars/helpers:
block-helper-missing.js  each.js  helper-missing.js  if.js  log.js  lookup.js  with.js

./handlebars/dist/amd/handlebars/internal:
create-new-lookup-object.js  proto-access.js  wrapHelper.js

./handlebars/dist/cjs:
handlebars  handlebars.js  handlebars.runtime.js  precompiler.js

./handlebars/dist/cjs/handlebars:
base.js   decorators     exception.js  helpers.js  logger.js       runtime.js      utils.js
compiler  decorators.js  helpers       internal    no-conflict.js  safe-string.js

./handlebars/dist/cjs/handlebars/compiler:
ast.js   code-gen.js  helpers.js              parser.js   visitor.js
base.js  compiler.js  javascript-compiler.js  printer.js  whitespace-control.js

./handlebars/dist/cjs/handlebars/decorators:
inline.js

./handlebars/dist/cjs/handlebars/helpers:
block-helper-missing.js  each.js  helper-missing.js  if.js  log.js  lookup.js  with.js

./handlebars/dist/cjs/handlebars/internal:
create-new-lookup-object.js  proto-access.js  wrapHelper.js

./handlebars/lib:
handlebars  handlebars.js  handlebars.runtime.js  index.js  precompiler.js

./handlebars/lib/handlebars:
base.js   decorators     exception.js  helpers.js  logger.js       runtime.js      utils.js
compiler  decorators.js  helpers       internal    no-conflict.js  safe-string.js

./handlebars/lib/handlebars/compiler:
ast.js   code-gen.js  helpers.js              parser.js   visitor.js
base.js  compiler.js  javascript-compiler.js  printer.js  whitespace-control.js

./handlebars/lib/handlebars/decorators:
inline.js

./handlebars/lib/handlebars/helpers:
block-helper-missing.js  each.js  helper-missing.js  if.js  log.js  lookup.js  with.js

./handlebars/lib/handlebars/internal:
create-new-lookup-object.js  proto-access.js  wrapHelper.js

./handlebars/types:
index.d.ts

./lozad:
LICENSE  README.md  dist  package.json

./lozad/dist:
lozad.es.js  lozad.js  lozad.min.js

./minimist:
LICENSE  example  index.js  package.json  readme.markdown  test

./minimist/example:
parse.js

./minimist/test:
bool.js  default_bool.js  long.js  parse.js           short.js
dash.js  dotted.js        num.js   parse_modified.js  whitespace.js

./neo-async:
LICENSE             detect.js        findSeries.js       omit.js           selectSeries.js
README.md           detectLimit.js   foldl.js            omitLimit.js      seq.js
all.js              detectSeries.js  foldr.js            omitSeries.js     series.js
allLimit.js         dir.js           forEach.js          package.json      setImmediate.js
allSeries.js        doDuring.js      forEachLimit.js     parallel.js       some.js
angelFall.js        doUntil.js       forEachOf.js        parallelLimit.js  someLimit.js
any.js              doWhilst.js      forEachOfLimit.js   pick.js           someSeries.js
anyLimit.js         during.js        forEachOfSeries.js  pickLimit.js      sortBy.js
anySeries.js        each.js          forEachSeries.js    pickSeries.js     sortByLimit.js
apply.js            eachLimit.js     forever.js          priorityQueue.js  sortBySeries.js
applyEach.js        eachOf.js        groupBy.js          queue.js          timeout.js
applyEachSeries.js  eachOfLimit.js   groupByLimit.js     race.js           times.js
async.js            eachOfSeries.js  groupBySeries.js    reduce.js         timesLimit.js
async.min.js        eachSeries.js    inject.js           reduceRight.js    timesSeries.js
asyncify.js         ensureAsync.js   iterator.js         reflect.js        transform.js
auto.js             every.js         log.js              reflectAll.js     transformLimit.js
autoInject.js       everyLimit.js    map.js              reject.js         transformSeries.js
cargo.js            everySeries.js   mapLimit.js         rejectLimit.js    tryEach.js
compose.js          fast.js          mapSeries.js        rejectSeries.js   unmemoize.js
concat.js           filter.js        mapValues.js        retry.js          until.js
concatLimit.js      filterLimit.js   mapValuesLimit.js   retryable.js      waterfall.js
concatSeries.js     filterSeries.js  mapValuesSeries.js  safe.js           whilst.js
constant.js         find.js          memoize.js          select.js         wrapSync.js
createLogger.js     findLimit.js     nextTick.js         selectLimit.js

./optimist:
LICENSE  example  index.js  package.json  readme.markdown  test

./optimist/example:
bool.js            default_hash.js     line_count.js          nonopt.js   string.js
boolean_double.js  default_singles.js  line_count_options.js  reflect.js  usage-options.js
boolean_single.js  divide.js           line_count_wrap.js     short.js    xup.js

./optimist/test:
_  _.js  dash.js  parse.js  parse_modified.js  short.js  usage.js  whitespace.js

./optimist/test/_:
argv.js  bin.js

./source-map:
CHANGELOG.md  LICENSE  README.md  dist  lib  package.json  source-map.d.ts  source-map.js

./source-map/dist:
source-map.debug.js  source-map.js  source-map.min.js  source-map.min.js.map

./source-map/lib:
array-set.js   base64.js         mapping-list.js  source-map-consumer.js   source-node.js
base64-vlq.js  binary-search.js  quick-sort.js    source-map-generator.js  util.js

./uglify-js:
LICENSE  README.md  bin  lib  package.json  tools

./uglify-js/bin:
uglifyjs

./uglify-js/lib:
ast.js       minify.js       output.js  propmangle.js  sourcemap.js  utils.js
compress.js  mozilla-ast.js  parse.js   scope.js       transform.js

./uglify-js/tools:
domprops.json  exit.js  exports.js  node.js  props.html

./wordwrap:
LICENSE  README.markdown  example  index.js  package.json  test

./wordwrap/example:
center.js  meat.js

./wordwrap/test:
break.js  idleness.txt  wrap.js
