### ISSUE TITLE
Not enough memory to run face recognition (with 2.6 GB)

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#220]
### Steps to reproduce
> sudo -u www-data php /var/www/nextcloud/occ face:background_job --user_id jake --timeout 900 -vvv

### Error Message / Log
> 1/10 - Executing task CheckRequirementsTask (Check all requirements)
>         **Found 2676 MB available to PHP**.
> 2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
> 3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
> 4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
> yielding
> 5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
>         Skipping stale images removal for user jake as there is no need for it
> 6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
>         Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
>         * have 1000 faces already processed (you have 0),
>         * have 100 images (you have 4),
>         * or you need to have 95% of you images processed (you have 0.00%)
> yielding
> 7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
>         Skipping full image scan for user jake
> 8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
> yielding
> 9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
>         NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
> yielding
>         Processing image /tmp/oc_tmp_oK09hp
>         **Image scaled from 3264x2448 to 1655x1242** (since max image area is 2055354 pixels^2)
> Error during background task execution
> If error is not transient, this means that core component of face recognition is not working properly
> and that quantity and quality of detected faces and person will be low or suboptimal.
> You probably want to file an issue (please include exception below) to: https://github.com/matiasdelellis/facerecognition/issues
> 
> In ImageProcessingTask.php line 186:
> 
>   [RuntimeException]
>   **Not enough memory to run face recognition**! Please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
> 
> Exception trace:
>  () at /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php:186
>  OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute() at /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php:120
>  OCA\FaceRecognition\BackgroundJob\BackgroundService->execute() at /var/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php:138
>  OCA\FaceRecognition\Command\BackgroundCommand->execute() at /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255
>  Symfony\Component\Console\Command\Command->run() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:908
>  Symfony\Component\Console\Application->doRunCommand() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:269
>  Symfony\Component\Console\Application->doRun() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:145
>  Symfony\Component\Console\Application->run() at /var/www/nextcloud/lib/private/Console/Application.php:213
>  OC\Console\Application->run() at /var/www/nextcloud/console.php:97
>  require_once() at /var/www/nextcloud/occ:11

#### Nextcloud log 
{"reqId":"cE6UlMhhdFgTmb7k9woZ","level":1,"time":"January 21, 2020 22:35:45","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"**Memcache** \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"17.0.2.1"}
{"reqId":"cE6UlMhhdFgTmb7k9woZ","level":1,"time":"January 21, 2020 22:35:45","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"**Memcache** \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"17.0.2.1"}
{"reqId":"cE6UlMhhdFgTmb7k9woZ","level":0,"time":"January 21, 2020 22:35:48","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"OC_Image->fixOrientation() Orientation: 6","userAgent":"--","version":"17.0.2.1"}

### System Info
- 5.2 GB Total
- According to https://[IP]/nextcloud/index.php/settings/admin/facerecognition, I have 2.6 GB of available memory.  
- PHP memory_limit = -1
  - /etc/php/7.3/apache2/php.ini
    memory_limit = -1
  - /etc/php/7.3/cli/php.ini:
     memory_limit = -1
- I have 4 images in the queue.
- No GPU.
- Nextcloud memory monitoring peaks at 3.7 when processing (230 MB idle).

* **PHP version:**
7.3

* **Nextcloud version:**
v17.0.2.1

**Comment by james-cook** [comment]
As I recall PHP has 2 separate configurations for available memory. 
One for web servers and one for the command line. 
You need to up the config for the command line.

**Comment by stalker314314** [comment]
Can you also paste full output of `occ face:background_job`. If I recall correctly, at the beginning of it should be memory settings

**Comment by snakyjake1** [comment]
Original post updated with additional requested information.  Thank you.

**Comment by stalker314314** [comment]
Oh, my bad. I forgot to mention that you also need to turn verbose logging. You can do it by appending `-vvv` to command, like:
```
sudo -u www-data php /var/www/nextcloud/occ face:background_job --user_id jake --timeout 900 -vvv
```

You should see somewhat more log lines if it is working! Can you paste that (this is where memory debug info is hidden:D)

Sorry once again!

**Comment by matiasdelellis** [comment]
> As I recall PHP has 2 separate configurations for available memory.
> One for web servers and one for the command line.
> You need to up the config for the command line.

I clarify that you need to touch both files. In some momment I suggested edit the command line config file to no use memory_limit (With -1) but just to make tests. Unfortunately we also need to touch the web server configuration file, due when you open the setting page to assign the memory limit it will read a lower value from that file. :disappointed:

**Comment by snakyjake1** [comment]
Original post updated with verbose logging enabled. Thank you.

**Comment by james-cook** [comment]
Just to report my recent experience - 
I'm testing a docker installation of facerecognition (https://github.com/matiasdelellis/facerecognition/issues/216) and though memory is not my focus at the moment I noticed many "killed" messages completely stopping `occ face:background_job`
This despite the fact that I've now increased the swap space to 3.5GB (in the nextcloud settings, and on my system `/usr/local/etc/php/conf.d/memory-limit.ini`)(I only have 1GB ram on the test droplet). 

This memory is reported:
```
/var/www/html # su www-data -s /bin/sh -c "php occ face:background_job -vvvv"
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Found 3500 MB available to PHP.
2/10 - Executing task CheckCronTask (Check t
```

The kind of errors seen:
```
#10 /var/www/html/occ(11): require_once('/var/www/html/c...')
#11 {main}
yielding
        Processing image /var/nc-data/admin/files/Photos/Coast.jpg
        Image scaled from 1100x734 to 2007x1339 (since max image area is 2688000 pixels^2)
Killed

```
and 

```
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
yielding
        Processing image /var/nc-data/admin/files/ddC/test.bmp
        Image scaled from 2592x1680 to 2036x1320 (since max image area is 2688000 pixels^2)
Killed
/var/www
```

Before I increased the memory limit the run was "killed" for far more files.
I am **assuming** these are still memory errors
If I look at `top` I can see swap use going to 99%

**Comment by snakyjake1** [comment]
My available swap space doesn't change when I run occ face:background_job.

https://192.168.1.156/nextcloud/index.php/settings/admin/serverinfo:
SWAP: Total: 1024 MB - Current usage: 241.4 MB

**Comment by james-cook** [comment]
Swap space / RAM will only be used up the the maximum you set. 
AFAICT you have 5..2GB RAM and 1GB swap - "but" php only "sees" 2676M
This is because php has been set up to "see" this amount
(in the nextcloud/facerecognition user interface and in your php.ini/config wherever that is.
`php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` will give you the location.)

If swap is not being used, it means the 2676M is being "taken" from your 5.2GB ram - which makes sense. I'd say the 2676M you set is being exhausted. As you can see from my comment above even 3.5GB is not enough for the stock image "Guest.jpg". My guess is this has to do with how dlib/pdlib is installed/compiled...

It is noticable that in your case you are getting a "real" error message with real handling:

> [RuntimeException]
> Not enough memory to run face recognition! Please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
> 
> Exception trace:

whereas I get:

> killed

This may be because my real memory (swap and ram) is actually smaller than the memory I specify for php (I am not exhaustively investigating this as I have "other" problems right now :)  ).

**Comment by snakyjake1** [comment]
@james-cook That you for the clear instructions.
From my /etc/php/7.3/cli/php.ini
memory_limit = -1

https://www.php.net/manual/en/ini.core.php#ini.memory-limit
"to have no memory limit, set this directive to -1"

I also do not see anything referenced to swap.

**Comment by james-cook** [comment]
My memory-limit in the ini file I mentioned is currently 4GB(!) and I have 6GB combined swap and ram.
BUT on the facerecognition settings page (see: https://github.com/matiasdelellis/facerecognition/wiki/Settings) I have "Memory limits" set to 512M for testing.
This way I am no longer running in to the "Killed" problem I was having before. So my hint for you at this point is to experiment with that setting (Note: my "Killed" message is different to yours so the issues may not be related).

You might find running the command in a loop useful to identify particular images that may always be leading to your error message:
`while (true) do su www-data -s /bin/sh -c "php occ face:background_job -vvvvvv"; done`

(background_job processes images in a random order)

**Comment by matiasdelellis** [comment]
Hi all,
Please try the latest in master. There was a major change in the form of memory calculation.

 * Now it will not work if you do not have 2Gb of ram (Ram+Swap)
 * The minimum memory configured to analisys is 1.2 GB. All this is very euristic, and in my case it ensures a minimum area of 640x480. [1]
 * Note that if php memory_limits is infinite, the application will self-restrict to 1/2 of the RAM, and may be confusion here. 

Please, I would like you try it.
 * Configure different memory values in settings.
 * Run the background job.
 * Use some tool to verify the maximum consumption of the process while analyzing. In particular I use [netdata](https://github.com/netdata/netdata/), but of course use what feels most comfortable.

[1]. It is very difficult to generalize this since it can depend on how I compile dlib, and obviously something as basic as architecture. We hope to improve, patience :disappointed: , but I have only tested it in X86 with packages compiled by me.
