### ISSUE TITLE
Show persons with a only 1 face found

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#224]
Tiny issue found in the admin settings.

Actual:
Show persons with a only 1 face found
![image](https://user-images.githubusercontent.com/8312560/73877241-28880900-480d-11ea-989a-b1da249db078.png)

Expected:
Show persons with only 1 face found.

The Admin web page doesn't tell me the version, but think its v0.5.11.

**Comment by matiasdelellis** [comment]
https://github.com/matiasdelellis/facerecognition/pull/227
