### ISSUE TITLE
"analysis is disabled"

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#225]
How do I enable "analysis"?
The button is checked:
![image](https://user-images.githubusercontent.com/8312560/73877599-d09dd200-480d-11ea-9d4f-f8a0c1b02ec6.png)

Or is it enabled, but the UI isn't working?

v0.5.11

**Comment by snakyjake1** [comment]
The "analysis" was enabled and started to work after several long minutes after I ran the occ face:background_job command.

So it was actually "enabled", and confusing because something was taking a long time for the photos to finally show up.

Or maybe it's because ran the occ face:background_job command a few more times and added more photos for analysis/clustering.

Or its because I later put a check box here:
![image](https://user-images.githubusercontent.com/8312560/73879439-58391000-4811-11ea-885b-d5de6a376861.png)

Either way, it would be nice if the UI didn't say the analysis is disabled, and provided more information (like couldn't find faces, waiting for something, something informational, or something actionable.

Thanks.

**Comment by matiasdelellis** [comment]
Ok.. It is a bug... Maybe tomorrow I'll fix it and upload a new nightly version. :wink:

**Comment by matiasdelellis** [comment]
Ok.. Must be fixed on https://github.com/matiasdelellis/facerecognition/pull/227
