### ISSUE TITLE
face-preview: Person photo is blank

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#226]
The face preview thumbnails are blank/empty/gray:
![image](https://user-images.githubusercontent.com/8312560/73880278-00030d80-4813-11ea-971e-aa4dae879cd1.png)

After some troubleshooting, I think it may have something to do with the URL path:
Mine is this:
https://192.168.1.156/nextcloud/

I suspect the code isn't expecting the "nextcloud" path?

v0.5.11
Thanks

**Comment by matiasdelellis** [comment]
See browser logs..

**Comment by snakyjake1** [comment]
It's looking for this:
https://192.168.1.156/index.php/apps/facerecognition/face/27/thumb/32

I think it should be looking for this:
https://192.168.1.156/nextcloud/index.php/apps/facerecognition/face/27/thumb/32

**Comment by matiasdelellis** [comment]
Ohh.. Now remember it. I thought it was fixed but no.

**Comment by matiasdelellis** [comment]
Must be fixed on https://github.com/matiasdelellis/facerecognition/pull/227
