### ISSUE TITLE
Dealing with misidentified faces

### ISSUE THREAD

**Issue by snakyjake1** [matiasdelellis/facerecognition#229]
Situation:  Lots of photos are misidentified, which is expected, but want a method to handle them better by the user.

1) Want to quickly mark identified faces as ignore/exclude.  

2) Want a feature to manually identify the face.  For example, there are two different faces in the photo, Facerecogniztion identifies two faces, unfortunately FaceRrecognition thinks they are the same face (and the same face shows up twice in the UI).

The way camera UI deal with face detection is nice to have.  I like that a box is created around the face.

Thanks.

**Comment by matiasdelellis** [comment]
Hi @snakyjake1 

You must tune the values of [Minimum confidence](https://github.com/matiasdelellis/facerecognition/wiki/Confidence), and [Sensitivity](https://github.com/matiasdelellis/facerecognition/wiki/Sensitivity)

MMm.. I use 0.99 of minimum confidence and 0.4 of sensitivity..

**Comment by matiasdelellis** [comment]
>    Want to quickly mark identified faces as ignore/exclude.
>  Want a feature to manually identify the face. For example, there are two different faces in the photo, Facerecogniztion identifies two faces, unfortunately FaceRrecognition thinks they are the same face (and the same face shows up twice in the UI).

This is discussed in other issues, try to look for references.  :wink: 

> The way camera UI deal with face detection is nice to have. I like that a box is created around the face.

This I do not understand what you expect, but if you expect that when you click on the person, highlight the face on the Viewer app this does not depend on us .. There is no api for it .. :disappointed:

**Comment by stalker314314** [comment]
We discussed what you are asking long time ago, and we refer to this as "2nd layer", above "automation layer". More details can be found in #168, #134 and #157. Novelty that you mentioned here is second point, which is basically "labeling" step - pick a detected face and "choose" person. I think this is sound idea, but I also think these are all "layer 2" features, and maybe we can just mention this in #168 and close this?
