### ISSUE TITLE
Provide precompiled libraries for Ubuntu Bionic 

### ISSUE THREAD

**Issue by iteco** [matiasdelellis/facerecognition#233]
Please consider to provide precompiled libraries for Ubuntu Bionic 

--
Looks that the hard way is not so hard either, but if you do provide precompiled libraries, I guess that you could provide it also for the most used ubuntu distro.

--
Otherways looks very interesting project!

**Comment by matiasdelellis** [comment]
Hi @iteco 
I just uploaded the first packages.

```
sudo sh -c 'echo "deb https://repo.delellis.com.ar bionic bionic" > /etc/apt/sources.list.d/20-pdlib.list'
wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
sudo apt update
sudo apt-get install php7.0-pdlib
```

Please, test it.. :wink:

**Comment by iteco** [comment]
That pdlib installation was smooth.

Then I proceeded to install FaceRecognition app according the instructions in [Wiki](https://github.com/matiasdelellis/facerecognition/wiki/Installation#install-facerecognition-app) 

> please use Nextcloud app store.

But I cannot find the app in the app store. 

Then I looked around and noticed [this](https://github.com/nextcloud/server/issues/10487) and [this](https://github.com/nextcloud/server/issues/2976).
 
Perhaps you should next make it more Official/Stable, that it would come visible?

(like e.g. [OnlyOffice app](https://apps.nextcloud.com/apps/documentserver_community), which don't look to be so ready either.. and you are ahead of them in version numbers anyway ;-D )

**Comment by matiasdelellis** [comment]
> That pdlib installation was smooth.

I'm glad it installed, but please test a real use.. :sweat_smile: 

* https://github.com/matiasdelellis/pdlib-min-test-suite#how-to-test-pdlib

> Then I proceeded to install FaceRecognition app according the instructions in Wiki
> 
>     please use Nextcloud app store.
> 
> But I cannot find the app in the app store.
> 
> Then I looked around and noticed this and this.
> 
> Perhaps you should next make it more Official/Stable, that it would come visible?
> 
> (like e.g. OnlyOffice app, which don't look to be so ready either.. and you are ahead of them in version numbers anyway ;-D )

Tomorrow I will probably release a new nightly version, but we are already close to a stable release .. maybe next .. :wink:

Also, I invite you to install it from git which is equally easy.. :smile:

**Comment by major-mayer** [comment]
For me installing the PDLib is no quite working.
Adding the repository was no problem, but apt always complains that it doesn't have a installation candidate:

```
root@d70929a426f4:/etc/apt/sources.list.d# apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://security-cdn.debian.org/debian-security buster/updates InRelease
Hit:4 https://repo.delellis.com.ar bionic InRelease
Reading package lists... Done
root@d70929a426f4:/etc/apt/sources.list.d# apt-get install php7.0-pdlib
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php7.0-pdlib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-pdlib' has no installation candidate
```

**Comment by matiasdelellis** [comment]
@major-mayer  
There are still no packages for Buster..

**Comment by major-mayer** [comment]
Oh my fault sorry, i thought the Nextcloud image were based on Ubuntu not Debian.

**Comment by matiasdelellis** [comment]
At some point I'll make the package .. :wink:

**Comment by major-mayer** [comment]
That's nice, i tried to compile it myself, but got stock with your instructions, because i wasn't able to install php7.3-dev on my system :/

**Comment by matiasdelellis** [comment]
MM.. Try install just php-dev

**Comment by major-mayer** [comment]
Ahh good to know, i just wanted to say that it always gives me this error:
``` E: Package 'php7.3-dev' (or 'php-dev') has no installation candidate```
I will try it

**Comment by major-mayer** [comment]
Yay, you are the best 😄  installation worked using this script:
```
apt-get -y install libx11-dev libopenblas-dev liblapack-dev git cmake 
mkdir /git
cd /git

git clone https://github.com/davisking/dlib.git
cd dlib/dlib
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
make install

cd /git
git clone https://github.com/goodspb/pdlib.git
cd pdlib
phpize
./configure
make
make install

touch /usr/local/etc/php/conf.d/pdlib.ini
echo "extension=\"pdlib.so\"" >> /usr/local/etc/php/conf.d/pdlib.ini
```
But I really don't know why, but i can't find the Face Recognition app in the App Store? What am i doing wrong?
And by the way, do you know if the PdLib libary support the integrated graphics from my AMD Ryzen 2200G for faster processing?

**Comment by iteco** [comment]
> > That pdlib installation was smooth.
> 
> I'm glad it installed, but please test a real use.. sweat_smile 
...
> Tomorrow I will probably release a new nightly version, but we are already close to a stable release .. maybe next .. wink

Looking forward that stable release.. :)

**Comment by matiasdelellis** [comment]
It was tested by other users. :wink: 
Thanks for all.

**Comment by e-alfred** [comment]
@matiasdelellis Bionic Beaver has PHP 7.2, so shouldn't it be `apt install php7.2-pdlib`?

**Comment by matiasdelellis** [comment]
Hi @e-alfred 
The name is wrong but it is compiled with 7.2. I will take this into account in the next package update.
