### ISSUE TITLE
Error with make (composer@ubuntu bionic)

### ISSUE THREAD

**Issue by SaschaMuehl** [matiasdelellis/facerecognition#238]
Hey, 
### Expected behaviour
I cannot make the file on ubuntu

### Actual behaviour
PHP Warning:  require(): open_basedir restriction in effect. File(/usr/share/php/Composer/autoload.php) is not within the allowed path(s): (/var/www/:/tmp/:/var/nextcloud_data) in /usr/bin/composer on line 8
PHP Warning:  require(/usr/share/php/Composer/autoload.php): failed to open stream: Operation not permitted in /usr/bin/composer on line 8
PHP Fatal error:  require(): Failed opening required 'Composer/autoload.php' (include_path='.:/usr/share/php') in /usr/bin/composer on line 8
Makefile:41: recipe for target 'composer' failed
make: *** [composer] Error 255

### Steps to reproduce
1. I tryied to install composer but I got: PHP Warning:  hash_file(): open_basedir restriction in effect. File(composer-setup.php) is not within the allowed path(s): (/var/www/:/tmp/:/var/nextcloud_data) in Command line code on line 1
PHP Warning:  hash_file(composer-setup.php): failed to open stream: Operation not permitted in Command line code on line 1
Installer corruptPHP Warning:  unlink(): open_basedir restriction in effect. File(composer-setup.php) is not within the allowed path(s): (/var/www/:/tmp/:/var/nextcloud_data) in Command line code on line 1

2. So I tried: wget https://getcomposer.org/installer
3. same make-problem

### Server configuration
LEMP-Stack

* **PHP version: 7.2
* **Web server: nginx
* **Database:mariadb
* **Nextcloud version: 16
### Client configuration

*

**Comment by matiasdelellis** [comment]
Hi @SaschaMuehl 
It seems you don't have permissions to write to the folder... Claim the permissions and run it again

```
sudo chown YUOR_USER_NAME:YOU_SERVER_GROUP -R .
```

**Comment by SaschaMuehl** [comment]
Hi @matiasdelellis , 
thanks for your fast answer. Unfort. Its not working.

`sudo chown root:www-data -R ` (normally me root has all rights)

He wants to have an operarand (chown: missing operand after ‘root:www-data’). Obviously it is asked for the install-path but I don't know which one is the right install path. 
Am I doing sth. wrong? 


I also tried to change step by step the open_basedir in /cli/php.ini: 
; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file.
; http://php.net/open-basedir
open_basedir = /var/www/:/tmp/:/var/nextcloud_data
open_basedir = /root
open_basedir = /usr/share/php
open_basedir = /usr/bin/composer

> > Warning: realpath(): open_basedir restriction in effect. File(/usr/bin/composer) is not within the allowed path(s): (/usr/share/php) in /usr/bin/composer on line 55
> 
> In Application.php line 130:
> 
>   file_exists(): open_basedir restriction in effect. File(./composer.json) is not within
>    the allowed path(s): (/usr/share/php)
> 
> 
> Makefile:41: recipe for target 'composer' failed
> make: *** [composer] Error 1

In exception of its not working. Is that a save way to modify the openbase_dir?

**Comment by matiasdelellis** [comment]
DO NOT USE ROOT!.

Sorry for the capitals!. I don't know if it fixes something, but it is well known that composer should not be used as root..

`[facerecognition]$ sudo -u www-data make`

**Comment by SaschaMuehl** [comment]
Thanks for your help. You are right. root isn't the best option. www-data wasn't available. so I created an user called "sascha". after giving sascha the sudo rights in visudo the problem still existed. I de-commended all restrictions in the php.ini (#open_basedir). Afterward I was able to install composer (still not lucky with this as a long-term-solution due to secruity reasons).  

1. Running with sudo -u www-data make: 
```
Writing lock file
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
npm i
npm ERR! correctMkdir failed to make directory /home/sascha/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/sascha/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/home/sascha/.npm"
Makefile:49: recipe for target 'npm-deps' failed
make: *** [npm-deps] Error 243
```

==>`sudo chown -R 33:33 "/home/sascha/.npm` it gaves me `chown: cannot access '/home/sascha/.npm': No such file or directory`

2. So I tried sudo -u sascha make
```
npm i
npm WARN checkPermissions Missing write access to /var/www/nextcloud/apps/facerecognition
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /var/www/nextcloud/apps/facerecognition
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/var/www/nextcloud/apps/facerecognition'
npm ERR!  { [Error: EACCES: permission denied, access '/var/www/nextcloud/apps/facerecognition']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/var/www/nextcloud/apps/facerecognition\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/var/www/nextcloud/apps/facerecognition' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sascha/.npm/_logs/2020-03-27T17_06_40_037Z-debug.log
Makefile:49: recipe for target 'npm-deps' failed
make: *** [npm-deps] Error 243

How do I give the right user the right (I mean which one) right?

```

**Comment by matiasdelellis** [comment]
Hi, 
> So I tried sudo -u sascha make

The facerecognition folder has the correct permissions ?? it must be owned by `sascha` for you to edit it, and group `www-data` so that your server can read...

**Comment by SaschaMuehl** [comment]
Thank you matiasdelellis, 
I finally deactivated the `open_basedir` in the php.ini. Afterwards the installation was successful. Consequently the Nextcloud isn't as save as before but I could live with it. 

Please help me for the last issue: The recognition was in the "deactivated app[s]" area. I wasn't able to activate ist. So I was so stupid to delete it. Now I connot find it anymore in the app-area. I tried to reinstall you facerecognition app und tried to update the pakage to get the activeting possablity back:

1. Updating-Issue: 
`cd var/www/nextcloud/apps/facerecognition/`
`git pull` 
but I got: 
> fatal: destination path 'facerecognition' already exists and is not an empty directory.

2. Deleting-Issue (to reinstall): 
`sudo apt-get --purge autoremove facerecognition`
but I got: 

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package facerecognition

Would you help me please a last time? Thanks

**Comment by matiasdelellis** [comment]
> I finally deactivated the open_basedir in the php.ini. Afterwards the installation was successful. Consequently the Nextcloud isn't as save as before but I could live with it.

Well I guess you can turn it back on after the installation is complete. 😉 

> sudo apt-get --purge autoremove facerecognition

MMmm.. This application, or even nextclound is not packaged as deb, and therefore forget about apt here... The only thing is the php7.0-pdlib packages, but I don't know if you are using it... 😕 

> fatal: destination path 'facerecognition' already exists and is not an empty directory.

Mm.. It seems more like a `git clone` message than `git pull`. 

Well, If you removed it, you may want to start again.

```
cd var/www/nextcloud/apps/
sudo rm -rf facerecognition
sudo git clone https://github.com/matiasdelellis/facerecognition.git
cd facerecognition
sudo chown sascha:www-data -R  .
make
```

Finally try to activate it from the command line.

```
cd var/www/nextcloud/
sudo -u www-data php occ app:enable facerecognition
```

**Comment by SaschaMuehl** [comment]
Thank you for your help, I saw your update information for dummies. (don't use root). honors me^^

This app cannot be installed due to dependency issues: 
 >    The library pdlib is not available. 

I updated to Nextcloud 18, I reinstalled facerecognition (thanks for the individualization), I activated in `extension=pdlib.so` in `/etc/php/7.#/cli/php.ini` i.a.w. @nhuhoai (apache and php conf.). I use nginx. I restarted nginx and php services. But same issue.

**Comment by matiasdelellis** [comment]
OK ok.. We have quite advanced .. :sweat_smile: 

> I updated to Nextcloud 18, I reinstalled facerecognition (thanks for the individualization), I activated in extension=pdlib.so in /etc/php/7.#/cli/php.ini i.a.w. @nhuhoai (apache and php conf.). I use nginx. I restarted nginx and php services. But same issue.

How did you install pdlib ??? 

Please show me the result of these commands

```
[matias@nube ~]$ php -v
PHP 7.3.15 (cli) (built: Feb 18 2020 09:25:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.15, Copyright (c) 1999-2018, by Zend Technologies

[matias@nube ~]$ php --ini | grep "Loaded Configuration"
Loaded Configuration File:         /etc/php.ini

[matias@nube ~]$ php -m | grep pdlib
pdlib
[matias@nube ~]$
```

**Comment by SaschaMuehl** [comment]
1. PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies

2. php --ini | grep "Loaded Configuration"
Loaded Configuration File:         /etc/php/7.2/cli/php.ini

3. php -m | grep pdlib:           I didn't, just found an installation guide for PDFlib but it isn't the same. Do you have a command for me?:)

**Comment by matiasdelellis** [comment]
>  I didn't, just found an installation guide for PDFlib but it isn't the same. Do you have a command for me?:)

 :weary:  :astonished:  :cold_sweat:  :anguished:

Didn't you know that it had to be installed ??? I ask to know how to improve and avoid this again.. 😕 

Well,
You are also lucky, because you use bionic and there are packages. 😅 

 * https://github.com/matiasdelellis/facerecognition/wiki/Installation#ubuntu-bionic

**Comment by SaschaMuehl** [comment]
Hournestly, I over read the requirements of pdlib. Maybe you could write under the requierements: "Please check in advance if you have installed PDLIB and the newest version of Nextcloud". I think "luser(s)" like me would understand that hint^^

Anyway, you helped me very much. The app is activated and no dependency-issues are shown. Thanks.
