### ISSUE TITLE
Image will be skipped because of the following error: Unable to open file: /tmp/oc_tmp_cb63bN

### ISSUE THREAD

**Issue by onkeljuergen** [matiasdelellis/facerecognition#242]
Hi,

since today after the newest git pull and make I get a strange error:

```
Mar 30 15:13:53 cloud php[1317]: 9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
Mar 30 15:13:53 cloud php[1317]:         NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
Mar 30 15:13:54 cloud php[1317]:         Processing image /mnt/[path].JPG
Mar 30 15:14:16 cloud php[1317]:         Faces found: 2
Mar 30 15:14:17 cloud php[1317]:         Processing image /mnt/[path].JPG
Mar 30 15:14:20 cloud php[1317]:         Faces found: 0. Image will be skipped because of the following error: Unable to open file: /tmp/oc_tmp_cb63bN

```

The permissions should be correct and I can see that below /tmp such file will be created with read and write permissions for www-data which is the user which executes the systemd script.

So do you have any hints what may cause that problem?
And it only occurs from the second image onwards. The first always processes as it should.

OS: Ubuntu 19.10
PHP: 7.4
All Installations were successful.

**Comment by matiasdelellis** [comment]
Hi @onkeljuergen 
Thanks for test and reporting, and sorry for the inconvenience.

What was the last version that worked for you correctly?

Does it continuously, or was it just an image?
The first image that shows that is converted and read it correctly, and the second one seems to have returned an error.

**Comment by matiasdelellis** [comment]
Ohh.. I was able to reproduce it .. Now investigating ... :wink:

**Comment by matiasdelellis** [comment]
Ok .. Another lesson learned .. Don't play with destroyers. :disappointed: 
I trusted the added Test, but I can't control the php garbage collector.. :sweat_smile: 

Now I upload a commit that fixes it. Sorry again..

**Comment by matiasdelellis** [comment]
Hi @onkeljuergen 
Pull request #243 should fix it.

**Comment by matiasdelellis** [comment]
Hi @onkeljuergen 
Merged to master. :wink: 

Also add an option to the reset command, so you can reset the image with errors, and you can analyze them again.

> occ face:reset --image-errors -u user_id

Now upload a new release as new version of emergency. :sweat_smile:

**Comment by onkeljuergen** [comment]
Hi @matiasdelellis 
thanks a lot. That was a quick fix.

Sorry I couldn't reply earlier.

Appreciate your effort.

And thanks again for that great application.
