### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by SaschaMuehl** [matiasdelellis/facerecognition#247]
Hey @matiasdelellis,
the installation is complete - no issues like missing pdlib library etc. are indicated.

### Expected behaviour

I activated the app and set the check in the facerecognition settings. I waited for 24h because I thought its analyzing the pics in the background. 

### Actual behaviour

"Your friends have not been recognized yet - Please, be patient" 

### Steps to reproduce
1. I waited 24h (was expecting an analyzing in the background)
2. tried to run the analyze for an hour with the user Sascha (33): `face:background_job --user_id 33 --timeout 3600`
But: `face:background_job: command not found`

3. All commands are not working. Do I sth. wrong?

4.  I did the pdlib test with your tool and got the error: `make: *** [php-test] Error 255` (please see below). So I tried to change the entry in the php.ini*s from `extension=pdlib.so` to `extension="pdlib.so"` (in quotation marks) and ran the make again. Wasn't working.  

### Server configuration

* **Operating system:** Ubuntu Bionic
* **Pdlib version:**
* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

> root@mail:~/pdlib-min-test-suite# make php-test
> mkdir -p vendor/models/1
> wget https://github.com/davisking/dlib-models/raw/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2 -O vendor/models/1/mmod_human_face_detector.dat.bz2
> --2020-04-07 08:23:37--  https://github.com/davisking/dlib-models/raw/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2
> Resolving github.com (github.com)... 140.82.118.3
> Connecting to github.com (github.com)|140.82.118.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/davisking/dlib-models/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2 [following]
> --2020-04-07 08:23:37--  https://raw.githubusercontent.com/davisking/dlib-models/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 694687 (678K) [application/octet-stream]
> Saving to: ‘vendor/models/1/mmod_human_face_detector.dat.bz2’
> 
> vendor/models/1/mmo 100%[===================>] 678.41K  --.-KB/s    in 0.07s
> 
> 2020-04-07 08:23:37 (9.38 MB/s) - ‘vendor/models/1/mmod_human_face_detector.dat.bz2’ saved [694687/694687]
> 
> bzip2 -d vendor/models/1/mmod_human_face_detector.dat.bz2
> mkdir -p vendor/models/1
> wget https://github.com/davisking/dlib-models/raw/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2 -O vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2
> --2020-04-07 08:23:38--  https://github.com/davisking/dlib-models/raw/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2
> Resolving github.com (github.com)... 140.82.118.3
> Connecting to github.com (github.com)|140.82.118.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/davisking/dlib-models/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2 [following]
> --2020-04-07 08:23:38--  https://raw.githubusercontent.com/davisking/dlib-models/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 21428389 (20M) [application/octet-stream]
> Saving to: ‘vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2’
> 
> vendor/models/1/dli 100%[===================>]  20.44M  11.7MB/s    in 1.7s
> 
> 2020-04-07 08:23:40 (11.7 MB/s) - ‘vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2’ saved [21428389/21428389]
> 
> bzip2 -d vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2
> mkdir -p vendor/models/1
> wget https://github.com/davisking/dlib-models/raw/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2 -O vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2
> --2020-04-07 08:23:44--  https://github.com/davisking/dlib-models/raw/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2
> Resolving github.com (github.com)... 140.82.118.3
> Connecting to github.com (github.com)|140.82.118.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/davisking/dlib-models/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2 [following]
> --2020-04-07 08:23:45--  https://raw.githubusercontent.com/davisking/dlib-models/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 5706710 (5.4M) [application/octet-stream]
> Saving to: ‘vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2’
> 
> vendor/models/1/sha 100%[===================>]   5.44M  11.5MB/s    in 0.5s
> 
> 2020-04-07 08:23:46 (11.5 MB/s) - ‘vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2’ saved [5706710/5706710]
> 
> bzip2 -d vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2
> php scripts/face_detect.php
> Welcome to pdlib min test suite for Facerecognition app...
> 
> First we try to open the models... Done
> 
> Processing file: input/Big Bang Theory.jpg
> PHP Fatal error:  Uncaught Exception: std::bad_alloc in /root/pdlib-min-test-suite/scripts/face_detect.php:35
> Stack trace:
> #0 /root/pdlib-min-test-suite/scripts/face_detect.php(35): CnnFaceDetection->detect('input/Big Bang ...')
> #1 /root/pdlib-min-test-suite/scripts/face_detect.php(53): findFaces('input/Big Bang ...')
> #2 {main}
>   thrown in /root/pdlib-min-test-suite/scripts/face_detect.php on line 35
> Makefile:27: recipe for target 'php-test' failed
> make: *** [php-test] Error 255

* **PHP version:** 7.2
* **Web server:** nginx
* **Database:** mariadb
* **Nextcloud version:** 18.0.3

### Client configuration

* **Browser:** Firefox
* **Operating system:** Win 8.1.

#### Nextcloud log (data/nextcloud.log)
The Nextcloud log shows nothing special..

**Comment by matiasdelellis** [comment]
> All commands are not working. Do I sth. wrong?

Can you pass the full log of background_job to see how you run it ????

> So I tried to change the entry in the php.ini*s from extension=pdlib.so to extension="pdlib.so" (in quotation marks) and ran the make again. Wasn't working.

If nextcloud allowed you to enable the application it means that it detected pdlib correctly. DO NOT TOUCH IT!.

> I did the pdlib test with your tool and got the error: make: *** [php-test] Error 255 (please see below)

I'm 99% sure it was only due to a lack of memory. Let's ignore it for now.

**Comment by SaschaMuehl** [comment]
> Can you pass the full log of background_job to see how you run it ????
I hope you mean the following one (its the full feedback from the console):

```
sascha@mail:/var/www/nextcloud/apps/facerecognition$ face:background_job --user_id 33 --timeout 3600
face:background_job: command not found
sascha@mail:/var/www/nextcloud/apps/facerecognition$
```

The same feedback I get for every command. Another example: 
```
sascha@mail:/var/www/nextcloud/apps/facerecognition$ face:progress
face:progress: command not found
```

Or is there a facerecognition.log?

**Comment by matiasdelellis** [comment]
You must run it from `/var/www/nextcloud/` and as `sudo -u www-data occ  face:background_job --user_id 33 --timeout 3600`

**Comment by SaschaMuehl** [comment]
> You must run it from `/var/www/nextcloud/` and as `sudo -u www-data occ face:background_job --user_id 33 --timeout 3600`

Unfortunately its not running: 
```
sascha@mail:/var/www/nextcloud$ sudo -u www-data occ face:background_job --user_id 33 --timeout 3600
sudo: occ: command not found
```
Also root: 
`root@mail:/var/www/nextcloud# sudo -u www-data occ face:background_job --user_id 33 --timeout 3600
sudo: occ: command not found
`
If that matters: the user 33 is "sascha"

**Comment by matiasdelellis** [comment]
haah.. Well,
> sudo -u www-data php occ face:background_job --user_id 33 --timeout 3600

**Comment by matiasdelellis** [comment]
p.s: 
> If that matters: the user 33 is "sascha"

I don't understand.. you must use the nextcloud user

**Comment by SaschaMuehl** [comment]
face:setup was working (I used model 2)

> sascha@mail:/var/www/nextcloud$ sudo -u www-data php occ face:setup -m 2
> The model 2 (DlibCnn68) will be installed
> Install model 2 (DlibCnn68) successfully done
> The model 2 (DlibCnn68) was configured as default


but: 

```
sascha@mail:/var/www/nextcloud$ sudo -u www-data php occ face:background_job -t 3600
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Seems that still don't configured the image area used for analysis.
Please contact administrator to configure it in the admin panel to continue.
Fill an issue here if that doesn't help: https://github.com/matiasdelellis/facerecognition/issues
Task CheckRequirementsTask signalled we should not continue, bailing out
```
Here I used it without User_ID. Because I don't know how to find the user ID of the nextcloud user. As far I know the User (admin is the only one) from nextcloud is written in the .htpasswd?
> > If that matters: the user 33 is "www-data"
> 
> I don't understand.. you must use the nextcloud user

**Comment by matiasdelellis** [comment]
https://github.com/matiasdelellis/facerecognition/issues/248

**Comment by SaschaMuehl** [comment]
It works! 1000 likes!
