### ISSUE TITLE
Issue - Seems that still don't configured the image area used for analysis

### ISSUE THREAD

**Issue by Floflobel** [matiasdelellis/facerecognition#248]
### Actual behaviour

The command background_job return an error. 

### Server configuration

* **Operating system:** Ubuntu 18.04.4 LTS

* **Pdlib version:** Build manually

* **How is DLib installed:** Build manually
pdlib-min-test-suite works 

* **How is PDlib installed:** Bruild manually
pdlib-min-test-suite works

* **PHP version:** 7.2

* **Web server:** Apache 

* **Database:** Postgres

* **Nextcloud version:** 17.0.2

### Client configuration

* **Browser:** Firefox

* **Operating system:** Linux

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
root@box:/var/www/nextcloud # sudo -u www-data php occ -vvv face:background_job
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Seems that still don't configured the image area used for analysis.
Please contact administrator to configure it in the admin panel to continue.
Fill an issue here if that doesn't help: https://github.com/matiasdelellis/facerecognition/issues
Task CheckRequirementsTask signalled we should not continue, bailing out
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing when run de background_job
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing 
```
</details>

**Comment by matiasdelellis** [comment]
Go to `[NEXTCLOUDURL]/settings/admin/facerecognition` :wink:

**Comment by Floflobel** [comment]
![Screenshot from 2020-04-07 14-21-26](https://user-images.githubusercontent.com/13889750/78668514-1bee6280-78db-11ea-9fb1-1393f21c3624.png)
Yes, but I don't see any parameters that would solve the error ...

**Comment by Floflobel** [comment]
Okay, I just hit the different bars and it's working. I looked all over the place but I didn't understand, it was so simple.

**Comment by matiasdelellis** [comment]
Ohh.. It is the option of "Temporary files". Assign an area that seems logical to you, I recommend only 1024x768, which gives good results to start. This has a direct impact on memory consumption, therefore I recommend testing and increasing it later.

**Comment by matiasdelellis** [comment]
I reopen as a reference, since I must improve the messages. 

Thanks!.

**Comment by florian-bellencontre** [comment]
When I try to set 1024x768 it return: 
```
The change could not be applied. - The model does not recommend an area greater than 836x627
```

**Comment by matiasdelellis** [comment]
Hi @florian-bellencontre 

The application limits itself to the maximum memory configuration of php (836x627=524172 => 512 MB ram)

Check it:
> php -i | grep memory_limit

See this::
 * https://www.php.net/manual/en/ini.core.php#ini.sect.resource-limits

Thanks again for report, it seems that this is not very clear in the procedure.

**Comment by Floflobel** [comment]
Sorry user @florian-bellencontre it's me too. 

Thanks a lot for your quick answer, I was able to play a little bit and see how the algorithm was behaving and I'm bluffed! Great job!

I have a few requests / questions:
- The first one is that I have my face in several "clusters", is it possible to group them together and make the algorithm learn that these clusters of faces are bothering me ? 
- Concerning the scrollbar setting, wouldn't it be possible to enter a value ? I tried to move the bar to go to 1024x768 but I can't perfectly fix this value (actually I set to 1023x767).
- Concerning the command "sudo -u www-data php occ face:setup" present in the documentation (https://github.com/matiasdelellis/facerecognition/wiki/Installation#install-facerecognition-app) I think it would be good to explain that you have to choose model 2. Then to put a link to the documentation of the models (https://github.com/matiasdelellis/facerecognition/wiki/Models) which explains very well why to choose it.

Thank again for your works !

**Comment by matiasdelellis** [comment]
> Sorry user @florian-bellencontre it's me too.

haha. I had a slight suspicion.. :wink: 

> The first one is that I have my face in several "clusters", is it possible to group them together and make the algorithm learn that these clusters of faces are bothering me ?

No.. There is still no way to change the clusters, neither to merge nor to separate groups. For now we are trying to rely on automatic grouping, and the improvements are for another stage.

About having several groups of the same person and merge it, it is not a priority. We have to find a balance and I prefer to have many groups, but of high quality, and not a large one with many errors.

Sensitivity has a good explanation of what I am saying.
 * https://github.com/matiasdelellis/facerecognition/wiki/Sensitivity

Also, personally, would rather delete the cluster view. It was added especially as a way to evaluate the quality of the clustering, but this is not a real view where you would look for your friends photos.

> Concerning the scrollbar setting, wouldn't it be possible to enter a value ? I tried to move the bar to go to 1024x768 but I can't perfectly fix this value (actually I set to 1023x767).

Don't worry about it, they are approximate values. Show a 4x3 image size for reference, but the resulting size depends on the ratio of the original image.

> Concerning the command "sudo -u www-data php occ face:setup" present in the documentation (https://github.com/matiasdelellis/facerecognition/wiki/Installation#install-facerecognition-app) I think it would be good to explain that you have to choose model 2

This are out of date .. Thanks..

> Then to put a link to the documentation of the models (https://github.com/matiasdelellis/facerecognition/wiki/Models) which explains very well why to choose it.

Yesterday I started to fix the wiki and readme documentation a bit.. See https://github.com/matiasdelellis/facerecognition/pull/249

The readme I think it is much better now, but still need to improve the wiki even more.

**Comment by matiasdelellis** [comment]
Well, add more info within Models wiki
* https://github.com/matiasdelellis/facerecognition/wiki/Models

...and a new entry with info about how to set de memory limits:
* https://github.com/matiasdelellis/facerecognition/wiki/PHP-memory_limit

**Comment by vaultec81** [comment]
Had similar issue... 
The command `occ config:app:set facerecognition analysis_image_area --value 307200` fixed it for me. Seems the slider bar does not save changes.

**Comment by elpraga** [comment]
@matiasdelellis I can confirm @vaultec81 's observation. The slider indeed does not save the settings. 

Can you, please, reopen the issue and let me know what additional information to provide?

**Comment by metbosch** [comment]
I had the same error message.
The problem is that the slider does not save the setting automatically, we *must* click the icon at right side.
This icon represents a "file" not a "save button" for me:
![Screenshot from 2021-02-19 10-59-15](https://user-images.githubusercontent.com/4162025/108489437-d859d880-72a1-11eb-909f-0d7401503441.png)
