### ISSUE TITLE
Support for shared storage

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#26]
`Watcher.php` has some TODO for this (`ISharedStorage`). But yeah, in general, we want to know are we shared-storage friendly, or not.

**Comment by stalker314314** [comment]
Just to add here, since I bumed into this recently - seems like these guys know how to deal with both external/group folders, we can _steal_ a thing of two from them: https://github.com/nextcloud/files_fulltextsearch/tree/master/lib/Service

**Comment by urlyb** [comment]
Thanks for the great app. So, if understand correctly, NC "External storages" are not supported yet?

**Comment by stalker314314** [comment]
Yes, you are correct. This app doesn't (yet) support neither shared nor external storage. I will surely work on external first, as this is where my photos are:) However, current thinking is that we want to release on store what we have up to now, and then continue from there, so expect something probably summer 2019 or so. Unless, you want to deal with it yourself, in which case, you are more than welcome!

**Comment by migueltg** [comment]
Hi, first of all, thanks for the app. One question, current first release supports external storage?

**Comment by stalker314314** [comment]
> 
> 
> Hi, first of all, thanks for the app. One question, current first release supports external storage?

No, unfortunately no. We plan to work on that next (at least I plan to, as this is my pain point, most of my photos are on external storage...)

**Comment by migueltg** [comment]
> > Hi, first of all, thanks for the app. One question, current first release supports external storage?
> 
> No, unfortunately no. We plan to work on that next (at least I plan to, as this is my pain point, most of my photos are on external storage...)

Thanks for your quick reply and your effort. If i can help with anything, tell to me :)

**Comment by matiasdelellis** [comment]
@stalker314314 
I've been thinking about this for quite a while ... and it became clear when I investigated to replace private api. Issue #191

Our limitation of shared folders is due pdlib needs physical access to the files..?
However, we don't work with real files either. We always create temporary files (With size according to memory allocation), and with PDlib we read these files..
So why not use the IPreview interface to get these temproral files?.

**Comment by stalker314314** [comment]
Your approach looks like it *could* work:) Here are my biggest pain points (let's use this issue for discussion, feel free to move this to #198 if you think it is more appropriate)
1. Does your PR handle external storage?
2. How to scope it only on files in shared folders (and external storage), not on trash, or some third-party app images (we should be careful what we are detecting:)
3. How to be notified when images are added/deleted (we could live without that, but 1) our logic for detecting images needs to be changed to always include new images, and 2) our resiliency when image does not exist should be improved (and when we are pointing to image that does not exists, to remove it in DB)
4. Rate of processing images between private and shared folders. My thinking is that we need to give priority to local images. Shared images may skew initial cluster generation, I think we want to prioritize private images before shared/external (either completely, or in some 80%/20% rates)
5. How we can keep your change in master with some "feature switch" where we don't expose it to users (yet) and not regress anything. And when we do enable it, how to give users ways to opt out from scans on shared/external images

And my most **important** point, the one why I didn't (yet) start working on this:

6. How to ensure that same image is scanned only once!

What do I mean by that - we can share folders with groups (groups can contain 10-100s of people). Also - external storage can be accessible by all users on instance, 100s of them. We certainly don't want to scan same image 100 x 60 sec = 1.5h for one image!

My solution to all of these problems was something like this (I am just dumping my brain, didn't spend too much time on this) - I was thinking more to add additional "layer" of DB table, where we can keep "pointers" to images. So, instead of having

```
facerec_images(id, user, file, model, is_processed...)
facerec_faces(id, image...)
```

we have something like this:
```
facerec_vimages(id, hash, model, is_processed...)
facerec_userimages(id, user, vimage)
facerec_faces(id, vimage...)
```

where we add new table that will represent various "virtual images" and where hash will somehow identify all images of same "origin". And `facerec_images` becomes `facerec_vimages` (and `file` becomes `hash`). And add `facerec_userimages`, which points to `facerec_vimage`. Biggest trick is keeping `hash` stable for local/shared/external/encrypted... For local, hash can be hash of `fileid` or even `fileid` itself. For remote unencrypted, it can be simply `md5($file->getInternalPath()`. For encrypted, it can be hash of temp file content... as long as hash is stable. So, task of adding missing images would boil down to adding entries to `facerec_vimages` and `facerec_userimages`. Task of doing face recognition would be to check if `vimage!=null` and if it is already processed. If it is already processed, we just add duplicate faces for it (or add `facerec_userfaces` table:D). Removing shared image would mean deleting row in `facerec_userimages` and delete it also from `facerec_vimages` if it is last virtual image ("refcounting" thing:)

Huh, very hard topic:) Don't trust me on anything I said, I am just blabbing:) If you want to go with your approach, go for it! I think this topic require bit more brainstorming and discussion on *how* to do it in best way. Your way is certainly 10x easier than what I am proposing, but I think we should consider "hard" way (if this will yield better code, separation of concerns, architecture, faster detection...). I am not even committing on what I am proposing to work on it (at least not this year), so I have no "credit" to complain to people (you!) actually doing stuff:)

**Comment by matiasdelellis** [comment]
> Your approach looks like it could work:)

Yes .. This may seem like a lot, but there is much more to do .. :wink: 

>    Does your PR handle external storage?

It works exactly the same. I just test it with SFTP storage. But do not test as a root folder, only as an external mount. However, I am almost certain it will be the same..

>    How to scope it only on files in shared folders (and external storage), not on trash, or some third-party app images (we should be careful what we are detecting:)

I don't have a good answer, but we would have to experiment. It should be easy, sure something is escaping us.

>    How to be notified when images are added/deleted (we could live without that)

In some cases we cannot control. When they are shared, and changed files on the original server, until we access to the folder it does not update.

> , but 1) our logic for detecting images needs to be changed to always include new images, and 2) our resiliency when image does not exist should be improved (and when we are pointing to image that does not exists, to remove it in DB)

Agree.

>    Rate of processing images between private and shared folders. My thinking is that we need to give priority to local images. Shared images may skew initial cluster generation, I think we want to prioritize private images before shared/external (either completely, or in some 80%/20% rates)

Agree +100!!!!,  I hadn't even thought about it.  But I would not get stuck for it. :disappointed: 

>    How we can keep your change in master with some "feature switch" where we don't expose it to users (yet) and not regress anything. And when we do enable it, how to give users ways to opt out from scans on shared/external images

I guess it would be best to focus on external storage ignoring the shares. We must focus on how to identify the storages, (It should be much easier than we think), and maybe use more hooks.

> >  And my most important point, the one why I didn't (yet) start working on this:
>
>    How to ensure that same image is scanned only once!

I am also worried about this, but I think I have decided, unfortunately, if there are two equal images we must scan it twice.
If you manage to identify duplicate files, it is a much more interesting application than what we are doing now. :sweat_smile: 
Seriously .. It is very difficult to search for duplicates with hashs or just file names. :disappointed: and the solution should be part of the Nextcloud core. 

P.s: https://github.com/mario/phenomena  :wink:

**Comment by stalker314314** [comment]
> Seriously .. It is very difficult to search for duplicates with hashs or just file names.

I was not thinking to search for them. When I said hash, I didn't mean proper "hashing", but just something that can tell us if two files are same (it could be `fileid`, it could be content, and *we* decide, for each storage type, how we define it!). When enumerating which images user can see (in AddMissingImages), this is a place where you do hash and "look up" do you have file or not. No searching at all. I didn't know about this Phenomena, but it will not solve our problems - even if this thing is part of core, we still need this "layering" and it can just help us with pre-existing hash (but hasing is not problem, problem is to create all of this infrastructure and to do it without bugs:)

> I am also worried about this, but I think I have decided, unfortunately, if there are two equal images we must scan it twice.

Well, that's fine. But if I ever start working on this solution (with layering and separation of images to virtual ones), promise me you will consider it:) I can promise you I will not do it this year:D

**Comment by matiasdelellis** [comment]
> Well, that's fine. But if I ever start working on this solution (with layering and separation of images to virtual ones), promise me you will consider it:) I can promise you I will not do it this year:D

haha.. Of course!. :smile:

**Comment by matiasdelellis** [comment]
Hi everyone,
The shared-storage-experiments branch just was merged.. :wink: 

This implies that they can already try it, but it is still experimental. There is no option on the fronted to enable it.
See: https://github.com/matiasdelellis/facerecognition/wiki/Settings#hidden-settings

Well, experimental in the sense that it is only tested by me, but it works. :sweat_smile: 

As always I invite you to try it .. :wink: 
Regards

**Comment by matiasdelellis** [comment]
Done on last nightly version.. :wink: 
If need other improvements open new issues.. :smile:

**Comment by DruculaC** [comment]
I have just move my Home directory(original 100GB) in Nextcloud to external storage(2TB)..

**Comment by matiasdelellis** [comment]
Great. I hope this helps you .. :wink:
