### ISSUE TITLE
Wiki Update needed to the - Schedule Background Task

### ISSUE THREAD

**Issue by GAS85** [matiasdelellis/facerecognition#274]
### Expected behaviour

There is a correction needed to the wiki section "[Schedule Background Task](https://github.com/matiasdelellis/facerecognition/wiki/Schedule-Background-Task#schedule-background-task)":

Which returns:

    [snip] */15 * * * * php -f /var/www/nextcloud/cron.php
    [snip] */30 * * * * php -f /var/www/nextcloud/occ face:background_job -t 900

### Actual behaviour

Which returns:

    [snip] */15 * * * * php -f /var/www/nextcloud/cron.php

**Comment by matiasdelellis** [comment]
Fixed..
Thank you very much for noticing.. :smiley:
