### ISSUE TITLE
Unhandled exception after "php occ face:setup"

### ISSUE THREAD

**Issue by sandetsky** [matiasdelellis/facerecognition#276]
### Expected behaviour
"php occ face:setup"
I'm expect to some setup process.

### Actual behaviour
An unhadled exception happened

```
sudo -u apache php /var/www/html/nextcloud/occ face:setup
You must indicate the ID of the model to install
An unhandled exception has been thrown:
Error: Call to a member function getId() on null in /var/www/html/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php:122
Stack trace:
#0 /var/www/html/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(77): OCA\FaceRecognition\Command\SetupCommand->dumpModels()
#1 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#7 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
```

### Steps to reproduce
1. sudo -u apache php /var/www/html/nextcloud/occ app:enable facerecognition
facerecognition enabled
2.sudo -u apache php /var/www/html/nextcloud/occ face:setup
You must indicate the ID of the model to install
An unhandled exception has been thrown:

### Server configuration

* CentOS 7 (7.8.2003)

* **Pdlib version:**
latest from github

DLib and PDLib tested with tool (https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**
7.4.6

* **Web server:**

Apache 2.4.6

* **Database:**
MariaDB 5.5.65

* **Nextcloud version:**
Nextcloud 18.0.4

### Client configuration

* **Browser:**
Chrome

* **Operating system:**
Windows 10

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

 sudo -u apache php /var/www/html/nextcloud/occ -vvv face:background_job
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Seems there are no installed models.
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"XsJ43sSY-uOzYyvYyLJKFgAAAAQ","level":3,"time":"2020-05-18T12:00:30+00:00","remoteAddr":"10.60.0.117","user":"sandeckij","a
pp":"index","method":"GET","url":"/settings/admin/facerecognition","message":{"Exception":"Exception","Message":"Call to a member fu
nction meetDependencies() on null","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":125,"
function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\Admin
SettingsController"},"index"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"
function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"
__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"facerecognition","_route":"settings.AdminSettings.index
"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"section":"facerecognition"
,"_route":"settings.AdminSettings.index"}]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":299,"function":"ca
ll_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"section":"facerecognition","_route":"settings.
AdminSettings.index"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","t
ype":"->","args":["/settings/admin/facerecognition"]},{"file":"/var/www/html/nextcloud/index.php","line":38,"function":"handleReques
t","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Pr
evious":{"Exception":"Error","Message":"Call to a member function meetDependencies() on null","Code":0,"Trace":[{"file":"/var/www/ht
ml/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\FaceRecognition\\Se
ttings\\Admin","type":"->","args":[]},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","li
ne":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":[{"20":[{"modelMa
nager":{"__class__":"OCA\\FaceRecognition\\Model\\ModelManager"},"settingsService":{"__class__":"OCA\\FaceRecognition\\Service\\Sett
ingsService"},"__class__":"OCA\\FaceRecognition\\Settings\\Admin"}]}]},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller
/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"-
>","args":["facerecognition"]},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":68,
"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["admin","facerecognit
ion"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"index","class":"OCA\\Se
ttings\\Controller\\AdminSettingsController","type":"->","args":["facerecognition"]},{"file":"/var/www/html/nextcloud/lib/private/Ap
pFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","a
rgs":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/html/nextcloud/lib/private/AppF
ramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC
A\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/Route
ActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\Admin
SettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"facerecognition","_route"
:"settings.AdminSettings.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args"
:[{"section":"facerecognition","_route":"settings.AdminSettings.index"}]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.
php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"section":"facere
cognition","_route":"settings.AdminSettings.index"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":1008,"function":"match",
"class":"OC\\Route\\Router","type":"->","args":["/settings/admin/facerecognition"]},{"file":"/var/www/html/nextcloud/index.php","lin
e":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/apps/facerecognition/lib/Setti
ngs/Admin.php","Line":77},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, li
</details>

**Comment by matiasdelellis** [comment]
Hi @sandetsky 

Ohh.. Thanks for reporting it ..

It is easy to fix, however meantime use the full command..  :wink: 

`sudo -u apache php /var/www/html/nextcloud/occ face:setup 1`

**Comment by sandetsky** [comment]
Thank you!
It's helped to start with facerecognition. But may be you meant "occ
face:setup -m 1"

пн, 18 мая 2020 г., 17:14 matiasdelellis <notifications@github.com>:

**Comment by matiasdelellis** [comment]
>Thank you!.
> It's helped to start with facerecognition.

Great..

> But may be you meant "occ
> face:setup -m 1"

Yes.. :)

MMM.. is there any guide that indicates the command without the MODEL_ID parameter?

**Comment by sandetsky** [comment]
Yes! )

It's on  project wiki page on github:

cd nextcloud/  # or whatever your path to Nextcloud is
sudo -u www-data php occ app:enable facerecognition # or ./occ
app:enable facerecognition
sudo -u www-data php occ face:setup # or ./occ face:setup


пн, 18 мая 2020 г., 18:43 matiasdelellis <notifications@github.com>:

**Comment by matiasdelellis** [comment]
Just merge a patch in master that fixes the problem ..
Thanks again for reporting it. :wink: 

>  It's on  project wiki page on github:

Ohh.. Fixed..
