### ISSUE TITLE
Error with memory size! Is it possible to turn it off?

### ISSUE THREAD

**Issue by jeffersvdwiel** [matiasdelellis/facerecognition#278]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

I try to run the following command 
"sudo -u www-data php occ face:background_job -t 900"

### Actual behaviour

It's telling me that i don't have enough memory. But instead i have.

Output PHP:

/var/www/nextcloud# php -i | grep memory_limit
memory_limit => 2048M => 2048M

/var/www/nextcloud# cat /proc/meminfo
MemTotal:        4051000 kB
MemFree:           80012 kB
MemAvailable:    3573972 kB
Buffers:          600220 kB
Cached:          3006876 kB
SwapCached:          560 kB
Active:           292560 kB
Inactive:        3522980 kB
Active(anon):      95380 kB
Inactive(anon):   143428 kB
Active(file):     197180 kB
Inactive(file):  3379552 kB
Unevictable:        1372 kB
Mlocked:            1372 kB
HighTotal:       3315712 kB
HighFree:          52672 kB
LowTotal:         735288 kB
LowFree:           27340 kB
SwapTotal:       8122364 kB
SwapFree:        8108540 kB
Dirty:              2768 kB
Writeback:             0 kB
AnonPages:        209112 kB
Mapped:            70308 kB
Shmem:             29076 kB
Slab:              98076 kB
SReclaimable:      62888 kB
SUnreclaim:        35188 kB
KernelStack:        1416 kB
PageTables:         3652 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    10147864 kB
Committed_AS:    2015736 kB
VmallocTotal:     245760 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:              704 kB
CmaTotal:          65536 kB
CmaFree:           28104 kB

### Server configuration

* **Operating system:**
/var/www/nextcloud# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg
Number of faces detected: 0
Processing file: input/Big Bang Theory.png
Number of faces detected: 4
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**
php 7.3
* **Web server:**
lighttpd
* **Database:**
Mysql
* **Nextcloud version:**
Nextcloud 18.0.4
### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

/var/www/nextcloud# sudo -u www-data php occ face:background_job -t 900 -vvv
An unhandled exception has been thrown:
TypeError: Return value of OC\MemoryInfo::memoryLimitToBytes() must be of the type int, float returned in /var/www/nextcloud/lib/private/MemoryInfo.php:82
Stack trace:
#0 /var/www/nextcloud/lib/private/MemoryInfo.php(58): OC\MemoryInfo->memoryLimitToBytes(2147483648)
#1 /var/www/nextcloud/lib/private/MemoryInfo.php(42): OC\MemoryInfo->getMemoryLimit()
#2 /var/www/nextcloud/lib/private/Console/Application.php(111): OC\MemoryInfo->isMemoryLimitSufficient()
#3 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#5 {main}root@rasp2-srv:/var/www/nextcloud# php -i | grep memory_limit
memory_limit => 2048M => 2048M

Please advise what to do!
Is it also possible to turn off the memory check? So i can test if it works.

Jeffrey de Jong

**Comment by matiasdelellis** [comment]
Hi @jeffersvdwiel 
It is a recurring problem, but this error is being returned by nextcloud. Not our application. :sweat_smile: 

Looking for some info, I found this:
* https://help.nextcloud.com/t/index-typeerror-return-value-must-be-of-the-type-integer-float-returned/42930/6

Apparently it's a php limitation with 32-bit systems, and rapsbian is compiled with 32bit compatibility mode.. 

So change the memory_limit to at smaller values.. :wink:

**Comment by pharmarin** [comment]
I run into the same error, but if we set a smaller value to memory_limit (or -1), face:background_jobs now complains that there is not enough memory. 
I run on a 32bits device, but have 4Go RAM (3 at least are free to use).

**Comment by matiasdelellis** [comment]
Hi @pharmarin 
Please share the complete log to understand the error. :wink:

**Comment by pharmarin** [comment]
Was throwing error :
`An unhandled exception has been thrown:
TypeError: Return value of OC\MemoryInfo::memoryLimitToBytes() must be of the type int, float returned in /var/www/html/lib/private/MemoryInfo.php:84
Stack trace:
#0 /var/www/html/lib/private/MemoryInfo.php(58): OC\MemoryInfo->memoryLimitToBytes(2147483648)
#1 /var/www/html/lib/private/MemoryInfo.php(42): OC\MemoryInfo->getMemoryLimit()
#2 /var/www/html/lib/private/Console/Application.php(112): OC\MemoryInfo->isMemoryLimitSufficient()
#3 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/occ(11): require_once('/var/www/html/c...')
#5 {main}`

Fixed this by setting memory_limit to a numeric value instead of "2G" or "2048M" (2048*1024*1024). 

It is a bug in Nextcloud as reported in [#16647](https://github.com/nextcloud/server/pull/16647).

Sorry for the flooding.

**Comment by pharmarin** [comment]
BTW still getting `1/10 - Executing task CheckRequirementsTask (Check all requirements)
	Your system does not meet the minimum of memory requirements.
Face recognition application requires at least 2 GB of system memory.`
Whereas my memory_limit is set to 3 GB (numeric format of course 😉).

**Comment by matiasdelellis** [comment]
Hi @pharmarin 
Run the command with debug (Adding `-vvv`), and shre me the full log since you launch it, until it ends ...

**Comment by pharmarin** [comment]
Here is the output : 
`php occ -vvv face:background_job
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        Your system does not meet the minimum of memory requirements.
Face recognition application requires at least 2 GB of system memory.`
Thank’s for the support

**Comment by matiasdelellis** [comment]
Ohh .. I was hoping to see something that I would never see ... haha..

To keep you calm, the original problem of this report abount NC was fixed well, and now yes is our problem ..  :sweat_smile:

Well .. I'm going to ask you to change our code .. 
```
[matias@nube Tasks]$ git diff .
diff --git a/lib/BackgroundJob/Tasks/CheckRequirementsTask.php b/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
index 86af917..7880db4 100644
--- a/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
+++ b/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
@@ -74,6 +74,13 @@ class CheckRequirementsTask extends FaceRecognitionBackgroundTask {
        public function execute(FaceRecognitionContext $context) {
                $this->setContext($context);
 
+               $systemMemory = MemoryLimits::getSystemMemory();
+               $this->logDebug("System memory: " . ($systemMemory > 0 ? $systemMemory : "Unknown"));
+
+               $phpMemory = MemoryLimits::getPhpMemory();
+               $this->logDebug("PHP Memory Limit: " . ($phpMemory > 0 ? $phpMemory : "Unknown"));
+
+
                if (!Requirements::pdlibLoaded()) {
                        $error_message =
                                "The PDlib PHP extension is not loaded. Cannot continue without it." .
@@ -136,11 +143,6 @@ class CheckRequirementsTask extends FaceRecognitionBackgroundTask {
                        return false;
                }
 
-               $systemMemory = MemoryLimits::getSystemMemory();
-               $this->logDebug("System memory: " . ($systemMemory > 0 ? $systemMemory : "Unknown"));
-
-               $phpMemory = MemoryLimits::getPhpMemory();
-               $this->logDebug("PHP Memory Limit: " . ($phpMemory > 0 ? $phpMemory : "Unknown"));
 
                return true;
        }
```

That debug is what I expected to see, but it never ran ... :disappointed:

**Comment by pharmarin** [comment]
I understand... 😉 
Here is the debug output : 
`System memory: Unknown
PHP Memory Limit: 2147483647`
Unfortunately I cannot explain why system memory is unknown... (I have 4G RAM)

**Comment by matiasdelellis** [comment]
We had the same problem as NC, (Basically integer overflow.) but I thought it was solved..

But now I have another suspicion .. New test .. :wink: 

```
[matias@nube facerecognition]$ git diff lib/
diff --git a/lib/BackgroundJob/Tasks/CheckRequirementsTask.php b/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
index 86af917..54bfe96 100644
--- a/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
+++ b/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
@@ -74,6 +74,13 @@ class CheckRequirementsTask extends FaceRecognitionBackgroundTask {
        public function execute(FaceRecognitionContext $context) {
                $this->setContext($context);
 
+               $systemMemory = MemoryLimits::getSystemMemory();
+               $this->logDebug("System memory: " . $systemMemory);
+
+               $phpMemory = MemoryLimits::getPhpMemory();
+               $this->logDebug("PHP Memory Limit: " . ($phpMemory > 0 ? $phpMemory : "Unknown"));
+
+
                if (!Requirements::pdlibLoaded()) {
                        $error_message =
                                "The PDlib PHP extension is not loaded. Cannot continue without it." .
@@ -136,11 +143,6 @@ class CheckRequirementsTask extends FaceRecognitionBackgroundTask {
                        return false;
                }
 
-               $systemMemory = MemoryLimits::getSystemMemory();
-               $this->logDebug("System memory: " . ($systemMemory > 0 ? $systemMemory : "Unknown"));
-
-               $phpMemory = MemoryLimits::getPhpMemory();
-               $this->logDebug("PHP Memory Limit: " . ($phpMemory > 0 ? $phpMemory : "Unknown"));
 
                return true;
        }
diff --git a/lib/Helper/MemoryLimits.php b/lib/Helper/MemoryLimits.php
index 353e0fe..c60a2cd 100644
--- a/lib/Helper/MemoryLimits.php
+++ b/lib/Helper/MemoryLimits.php
@@ -77,6 +77,7 @@ class MemoryLimits {
         * Only linux is currently supported.
         */
        public static function getSystemMemory(): int {
+               echo "\n System: " . php_uname("s") . "\n";
                if (php_uname("s") !== "Linux")
                        return -1;
 
[matias@nube facerecognition]$
```

**Comment by pharmarin** [comment]
Hi ! The output is : 
`System: Linux
	System memory: Unknown
	PHP Memory Limit: 2147483647

 System: Linux
	Your system does not meet the minimum of memory requirements.
Face recognition application requires at least 2 GB of system memory.`

**Comment by matiasdelellis** [comment]
> System: Linux System memory: Unknown

You did not apply the new patch of this part.

>  System: Linux .

OK .. Raspbian is reported as linux :wink: 

Again:

```
[matias@nube lib]$ git diff .
diff --git a/lib/BackgroundJob/Tasks/CheckRequirementsTask.php b/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
index 86af917..54bfe96 100644
--- a/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
+++ b/lib/BackgroundJob/Tasks/CheckRequirementsTask.php
@@ -74,6 +74,13 @@ class CheckRequirementsTask extends FaceRecognitionBackgroundTask {
        public function execute(FaceRecognitionContext $context) {
                $this->setContext($context);
 
+               $systemMemory = MemoryLimits::getSystemMemory();
+               $this->logDebug("System memory: " . $systemMemory);
+
+               $phpMemory = MemoryLimits::getPhpMemory();
+               $this->logDebug("PHP Memory Limit: " . ($phpMemory > 0 ? $phpMemory : "Unknown"));
+
+
                if (!Requirements::pdlibLoaded()) {
                        $error_message =
                                "The PDlib PHP extension is not loaded. Cannot continue without it." .
@@ -136,11 +143,6 @@ class CheckRequirementsTask extends FaceRecognitionBackgroundTask {
                        return false;
                }
 
-               $systemMemory = MemoryLimits::getSystemMemory();
-               $this->logDebug("System memory: " . ($systemMemory > 0 ? $systemMemory : "Unknown"));
-
-               $phpMemory = MemoryLimits::getPhpMemory();
-               $this->logDebug("PHP Memory Limit: " . ($phpMemory > 0 ? $phpMemory : "Unknown"));
 
                return true;
        }
diff --git a/lib/Helper/MemoryLimits.php b/lib/Helper/MemoryLimits.php
index 353e0fe..fa03e7e 100644
--- a/lib/Helper/MemoryLimits.php
+++ b/lib/Helper/MemoryLimits.php
@@ -77,13 +77,21 @@ class MemoryLimits {
         * Only linux is currently supported.
         */
        public static function getSystemMemory(): int {
+               echo "\n System: " . php_uname("s") . "\n";
+
                if (php_uname("s") !== "Linux")
                        return -1;
 
+               echo "\n IsLinux!\n";
+
+
                $linuxMemory = MemoryLimits::getTotalMemoryLinux();
                if ($linuxMemory <= 0) {
                        return -2;
                }
+
+               echo "\n Linux Memory: " . $linuxMemory . "\n";
+
                return $linuxMemory;
        }
 
@@ -92,21 +100,27 @@ class MemoryLimits {
         * zero if we don't know any better.
         */
        private static function getTotalMemoryLinux(): int {
+               echo "\n Opening proc\n";
                $fh = fopen('/proc/meminfo','r');
                if ($fh === false) {
                        return 0;
                }
-
                $mem = 0;
                while ($line = fgets($fh)) {
                        $pieces = array();
                        if (preg_match('/^MemTotal:\s+(\d+)\skB$/', $line, $pieces)) {
+                               echo "\n LINE: " .  $line . "\n";
                                $mem = $pieces[1];
+                               echo "\n Mem: " .  $mem . "\n";
                                break;
                        }
+
                }
                fclose($fh);
                $memKb = intval($mem);
+
+               echo "\n MemKb: " . $memKb . "\n";
+
                return intval($memKb * 1024);
        }
 
[matias@nube lib]$
```

**Comment by pharmarin** [comment]
This returns that : 
System: Linux

 IsLinux!

 Opening proc

 LINE: MemTotal:        3898628 kB


 Mem: 3898628

 MemKb: 3898628
	System memory: Unknown
	PHP Memory Limit: 2147483647

 System: Linux

 IsLinux!

 Opening proc

 LINE: MemTotal:        3898628 kB


 Mem: 3898628

 MemKb: 3898628
	Your system does not meet the minimum of memory requirements.

**Comment by matiasdelellis** [comment]
> System memory: Unknown

You are misapplying the patch.. :see_no_evil: 

USE THAT!.
> $this->logDebug("System memory: " . $systemMemory);

NOT THAT..
> $this->logDebug("System memory: " . ($systemMemory > 0 ? $systemMemory : "Unknown"));

:sweat_smile:

**Comment by pharmarin** [comment]
Feeling dumb... 
getSystemMemory -> -2

**Comment by matiasdelellis** [comment]
Ok .. It definitely looks like an integer overflow.. again due to the limitation of php in 32 bits that we discussed..
We have two options, use the floats which is strange when speaking from memory, or work with kbytes, but which can result in floats again. :sweat_smile: 

So... I guess it is best to use floats directly .. :wink:

**Comment by matiasdelellis** [comment]
Well.. I think this is enough ... :smiley: 

https://github.com/matiasdelellis/facerecognition/pull/283

Please test...

@jeffersvdwiel his was your report originally, so I would like you to try it too .. :wink:

**Comment by pharmarin** [comment]
😇 Works like a charm !

**Comment by matiasdelellis** [comment]
Great.. Merged..
Next week surely I'll release a minor revision with these fixes. :smiley:

**Comment by EliranHayun** [comment]
I am having the same issue on a freeNAS (freeBSD), will this fix resolve it also?

**Comment by matiasdelellis** [comment]
Hi @EliranHayun 
Not because currently obtaining system memory is only implemented in Linux :disappointed: 

I could take ideas from here to implement it, but I won't be able to test it. Can you help us with this?

* https://github.com/nextcloud/serverinfo/pull/210

Regards,
Matias,

p.s: I ask you something else. Could you compile pdlib and it worked? https://github.com/matiasdelellis/facerecognition/issues/261

**Comment by EliranHayun** [comment]
Hi @matiasdelellis,

I am happy to help with anything you need :)
Just FYI, I am not a developer but have a little understanding in code.

Will take a look at the items you ask for me later today.

Best Regards,
Eliran
