### ISSUE TITLE
Docker image missing bzip2

### ISSUE THREAD

**Issue by DillonHansen71** [matiasdelellis/facerecognition#281]
https://github.com/matiasdelellis/pdlib/wiki/Docker

The image build below is missing bzip2

#
# Use a temporary image to compile and test the libraries
#
FROM nextcloud:apache as builder

# Build and install dlib on builder

RUN apt-get update ; \
    apt-get install -y build-essential wget cmake libx11-dev libopenblas-dev

ARG DLIB_BRANCH=v19.19
RUN wget -c -q https://github.com/davisking/dlib/archive/$DLIB_BRANCH.tar.gz \
    && tar xf $DLIB_BRANCH.tar.gz \
    && mv dlib-* dlib \
    && cd dlib/dlib \
    && mkdir build \
    && cd build \
    && cmake -DBUILD_SHARED_LIBS=ON --config Release .. \
    && make \
    && make install

# Build and install PDLib on builder

ARG PDLIB_BRANCH=master
RUN apt-get install unzip
RUN wget -c -q https://github.com/matiasdelellis/pdlib/archive/$PDLIB_BRANCH.zip \
    && unzip $PDLIB_BRANCH \
    && mv pdlib-* pdlib \
    && cd pdlib \
    && phpize \
    && ./configure \
    && make \
    && make install

# Enable PDlib on builder

# If necesary take the php settings folder uncommenting the next line
# RUN php -i | grep "Scan this dir for additional .ini files"
RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Test PDlib instalation on builer

RUN apt-get install -y git
RUN git clone https://github.com/matiasdelellis/pdlib-min-test-suite.git \
    && cd pdlib-min-test-suite \
    && make

#
# If pass the tests, we are able to create the final image.
#

FROM nextcloud:apache

# Install dependencies to image

RUN apt-get update ; \
    apt-get install -y libopenblas-base

# Install dlib and PDlib to image

COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib

# If is necesary take the php extention folder uncommenting the next line
# RUN php -i | grep extension_dir
COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20180731/pdlib.so /usr/local/lib/php/extensions/no-debug-non-zts-20180731/

# Enable PDlib on final image

RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Increse memory limits

RUN echo memory_limit=1024M > /usr/local/etc/php/conf.d/memory-limit.ini

# Pdlib is already installed, now without all build dependencies.
# You could test again if everything is correct, uncommenting the next lines
#
# RUN apt-get install -y git wget
# RUN git clone https://github.com/matiasdelellis/pdlib-min-test-suite.git \
#    && cd pdlib-min-test-suite \
#    && make

#
# At this point you meet all the dependencies to install the application
# If is available you can skip this step and install the application from the application store
#
ARG FR_BRANCH=master
RUN apt-get install -y wget unzip nodejs npm
RUN wget -c -q -O facerecognition https://github.com/matiasdelellis/facerecognition/archive/$FR_BRANCH.zip \
  && unzip facerecognition \
  && mv facerecognition-*  /usr/src/nextcloud/facerecognition \
  && cd /usr/src/nextcloud/facerecognition \
  && make

**Comment by gijoe88** [comment]
To add bzip2 support and be able to install FaceRecognition app:
`RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libbz2-dev && \
    docker-php-ext-install bz2
`

**Comment by matiasdelellis** [comment]
Hi @markuman 
Do you confirm that this change fixes the problem?

**Comment by matiasdelellis** [comment]
p.s: @DillonHansen71 thank for report and thank to @gijoe88 for propose change.
Excuse me, do not answer before. :disappointed:

**Comment by markuman** [comment]
> Hi @markuman
> Do you confirm that this change fixes the problem?

Yes, I can confirm. It works.

**Comment by rnujic** [comment]
I have an updated dockerfile to add bzip, pdlib & sudo included. Can drop here if needed.

**Comment by markuman** [comment]
@rnujic yeah, show us.  
for what do you included `sudo`?

**Comment by rnujic** [comment]
[Dockerfile.txt](https://github.com/matiasdelellis/facerecognition/files/5582333/Dockerfile.txt)
I've attached the file. For building 'docker build . -t mynextcloud'

Sudo i used to start the analyze thru command line, as i sent the command to the container like:
docker exec -it nextcloud sudo -u www-data php occ face:background_job

I guess if you dont want to run any commands thru the shell you wont need sudo.

**Comment by markuman** [comment]
@rnujic you don't need `sudo` in that case. You can `exec` with a different user like 

```
 /usr/bin/docker exec -u www-data nextcloud ./occ face:background_job -u m -t 300
```

**Comment by rnujic** [comment]
Ah nice!

**Comment by matiasdelellis** [comment]
Ok.. Migrate the update wiki on https://github.com/matiasdelellis/facerecognition/wiki/Docker 

Thanks for all, and sorry for the delay !!. . 😅

**Comment by iamklaus** [comment]
Hey guys, I've build a docker image and published it on docker hub. I will maintain this image. Everything is build on top of the official nextcloud apache image. Feel free to use it: https://hub.docker.com/r/iamklaus/nextcloud
