### ISSUE TITLE
No faces

### ISSUE THREAD

**Issue by Happyfeet01** [matiasdelellis/facerecognition#282]
Hello,

Today i have setup Facerecognition on my new Server. 
In the Personal settings i get this message: 

Your friends have not yet been analyzed

But under the system Settings Facerecognition tells me that the scan is finished.

Is that an Bug?

My settings 

![image](https://user-images.githubusercontent.com/3295104/84696697-2bc69a80-af4d-11ea-9f41-2db9729af646.png)

**Comment by matiasdelellis** [comment]
Hi @Happyfeet01 

How did you run the analysis?. You check that the background task command does not return any error?

**Comment by matiasdelellis** [comment]
Well, taking into account your comment in #158 i can close this issue ...
