### ISSUE TITLE
 Exception: Call to a member function meetDependencies() on null

### ISSUE THREAD

**Issue by HollowedEmpire** [matiasdelellis/facerecognition#284]
### Steps to reproduce
1. Go to Nextcloud's Settings
2. Click on Face Recognition under the Administration section

### Expected behaviour
When going to Face Recognition under the Admin section of Nextcloud's Settings page, I'm expecting some sort of page with settings.

### Actual behaviour
When going to Face Recognition under the Admin section of NextCloud's Settings page, I am directed to an internal error page and an exception is logged:

Exception: Call to a member function meetDependencies() on null

## Server configuration detail

**Operating system:** Linux 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l

**Webserver:** Apache/2.4.38 (Raspbian) (fpm-fcgi)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.14-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, pdlib, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, apc, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, wikidiff2, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Pdlib version:**
PHP won't give a version number for pdlib, and readme from source does not have version either. It was freshly compiled as of today.

**How is DLib installed:** 
Via following the manual install steps from wiki - the "hard way"
https://github.com/matiasdelellis/facerecognition/wiki/Installation#hard-way
Testing detects few faces but it passes without error. (0 in frist image, 4 in second)

**How is PDlib installed:** 
Via following the manual install steps from wiki - the "hard way"
https://github.com/matiasdelellis/facerecognition/wiki/Installation#hard-way
Testing detects few faces but it passes without error. (0 in frist image, 4 in second)

**Nextcloud version:** 18.0.6 - 18.0.6.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from previous versions

**Where did you install Nextcloud from:** Download

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - apporder: 0.10.0
 - bookmarks: 3.2.1
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.4
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - cookbook: 0.7.4
 - dav: 1.14.0
 - deck: 1.0.2
 - drawio: 0.9.6
 - external: 3.5.0
 - facerecognition: 0.6.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_automatedtagging: 1.8.3
 - files_lock: 0.8.2
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.4.0
 - maps: 0.1.6
 - metadata: 0.11.1
 - news: 14.1.11
 - nextbackup: 20.4.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - passwords: 2020.6.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - timetracker: 0.0.42
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.3
 - twofactor_u2f: 5.1.0
 - unsplash: 1.1.6
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - activity
 - admin_audit
 - encryption
 - end_to_end_encryption
 - files_external
 - files_fulltextsearch
 - fulltextsearch
 - notes
 - social
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "dbtype": "mysql",
    "version": "18.0.6.0",
    "overwriteprotocol": "https",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "installed": true,
    "maintenance": false,
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "theme": "",
    "logfile": "\/var\/log\/nextcloud.log",
    "loglevel": 2,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

**Operating system:** Ubuntu 19.10

## Logs

<details><summary>Nextcloud log</summary>

```
[index] Error: Exception: Call to a member function meetDependencies() on null at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "index")
1. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", OC\AppFramework\ ... {}, {section: "facer ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({section: "facer ... "})
3. /var/www/html/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {section: "facer ... "})
4. /var/www/html/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/settings/admin/facerecognition")
5. /var/www/html/nextcloud/index.php line 38
   OC::handleRequest()
```
</details>

**Comment by matiasdelellis** [comment]
Hi @HollowedEmpire 
Thank you very much for completing the issue template. :smile: 

Please, test the path of this PR. https://github.com/matiasdelellis/facerecognition/pull/285

**Comment by HollowedEmpire** [comment]
Works great!

**Comment by matiasdelellis** [comment]
Great.. Merged..
Next week surely I'll release a minor revision with these fixes.
