### ISSUE TITLE
Nudity Detection

### ISSUE THREAD

**Issue by chettyfj** [matiasdelellis/facerecognition#289]
Is there a way to tweak this app to use it as nudity detection app

**Comment by matiasdelellis** [comment]
Hi @chettyfj 
You can use a lot of the infrastructure of the application. but of course it is far from the objectives of that.

In principle, you must train a neural network model to detect it. Maybe https://github.com/arrufat/wallyfinder (And http://dlib.net/dnn_mmod_train_find_cars_ex.cpp.html) is a good example to start.

After that doing the application it should be relatively easy. :wink:
