### ISSUE TITLE
Can you actively trigger analysis when a file changes (such as uploading a new file)?

### ISSUE THREAD

**Issue by medivh-jay** [matiasdelellis/facerecognition#290]
Can you actively trigger analysis when a file changes (such as uploading a new file)?

Thank you very much

**Comment by matiasdelellis** [comment]
HI @medivh-jay 
The new images are queued and analyzed correctly, but are not incorporated into the facial clustering until there are 10 new faces.. This is to avoid re-clusterig continuously. But it is certainly something to improve.

**Comment by medivh-jay** [comment]
thank you very much. another problem is that there seems to be no Person tab in the left panel of the File or the left panel of the album

**Comment by matiasdelellis** [comment]
Hi @medivh-jay 

> The new images are queued and analyzed correctly, but are not incorporated into the facial clustering until there are 10 new faces.. This is to avoid re-clusterig continuously. But it is certainly something to improve.

Ok. In #291 check the conditions of the recreation of the clusters.
As I said there was a minimum of 10 new faces (Beyond that it is mainly a cleaning, I increased it to 25 in #291) to recreate these, but there is also a 2 hour max condition. So if there is at least one face that was analyzed more than two hours ago, the clusters will be recreated to incorporate it. This never worked for you?

> thank you very much. another problem is that there seems to be no Person tab in the left panel of the File or the left panel of the album

This is strange, can you give details about your installation, browser and please check the logs? :confused:

**Comment by medivh-jay** [comment]
Hi @matiasdelellis 

> So if there is at least one face that was analyzed more than two hours ago, the clusters will be recreated to incorporate it. This never worked for you? 

It's worked, thank you for your reply

> This is strange, can you give details about your installation, browser and please check the logs? 😕

My nextcloud server version is 18.0.6,
and my browser is Chrome latest version
and my PHP version is 7.4.6
Here are all the plug-ins I installed
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.10.0
  - audioplayer_editor: 0.2.2
  - breezedark: 18.0.20
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - documentserver_community: 0.1.7
  - drawio: 0.9.6
  - external: 3.5.0
  - facerecognition: 0.6.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.4.1
  - files_automatedtagging: 1.8.3
  - files_external: 1.9.0
  - files_markdown: 2.3.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - music: 0.15.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocdownloader: 1.7.8
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - passwords: 2020.7.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - side_menu: 1.7.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - notes
  - user_ldap

When I refresh my nextcloud homepage , Chrome console has only one error
`Refused to execute script from 'https://xxx/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`
no PHP errors and nextcloud server errors.

This is my current page
![nextcloud](https://user-images.githubusercontent.com/23169872/87110594-fb4af580-c299-11ea-96ce-b6c3333e1ba2.png)

The theme is **breezedark**

**Comment by matiasdelellis** [comment]
Hi @medivh-jay 
I still haven't learned which is the right and the left...  :sweat_smile: :smile: :smiley: hahahaha..

Well, The left panel is not implemented. There were a couple of experiments, but it was always quite hacked, and we preferred not to implement it. If you want, please start a new issue to request this feature, and describing what you expect from it. :wink: 

In the only implemented panel, it is the tab in the right panel, that you should see in files and photos.

**Comment by medivh-jay** [comment]
I'm awfully sorry

> In the side panel of the file application, a 'Persons' tab is added where you can see a list of your friends in the photo, and rename them.

I read that `README.md` thought it was on the File left panel, I'm really sorry to bother you

**Comment by matiasdelellis** [comment]
Don't worry..
You are right that it is not very clear. I will try to improve the message..  :wink:
