### ISSUE TITLE
./configure returns dlib-1 not found

### ISSUE THREAD

**Issue by preludeofme** [matiasdelellis/facerecognition#298]
i'm trying to manually install this for my nextcloud server, i tried from the appstore but got the error message about pdlib not being found. So i followed all the steps and tried several of the recommendations in some of the issue threads, but i'm just stuck. 

**What I have:**
freenas server FreeNAS-11.3-U1
nextcloud: 19.0

**What I've done:**
followed the "Hard Way" installation instructions:
installed DLib 
   followed all the steps listed
installed PDLib (using matiasdelellis's forked version to get the expanded config output)
   followed all the steps but got to the ./configure and it gives me the output "dlib-1 not found"

i'm not sure what i'm missing or if there's a config file missing or that needs updating. 

any help would be appreciated

**Comment by matiasdelellis** [comment]
Hi @preludeofme 

I don't have any FreeBSD experience

> installed DLib

How did you install it? Did you test with python binging to make sure it's working?

> followed all the steps but got to the ./configure and it gives me the output "dlib-1 not found"

It does not detect dlib-1 library, in Linux you can check like this. 

```
[matias@ideapad pdlib]$ pkg-config --libs dlib-1
-ldlib -lpthread /usr/lib64/libX11.so /usr/lib64/libpng.so /usr/lib64/libz.so /usr/lib64/libjpeg.so /usr/lib64/libopenblas.so /usr/lib64/libsqlite3.so
```

However, try to follow this issue..  https://github.com/matiasdelellis/facerecognition/issues/261

**Comment by preludeofme** [comment]
aha! so for any other freenas users....

the config --libs dlib-1 command (leaving off the other "libx11.so part") gave me:

```
root@Cloud:~/pdlib # pkg-config --libs dlib-1Package dlib-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `dlib-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dlib-1', required by 'virtual:world', not found
```

as soon as i added the environment variable, it worked.... kind of. now i have another error but i'm going to troubleshoot that a bit more. Thanks!
