### ISSUE TITLE
Support for Nextcloud 14.0

### ISSUE THREAD

**Issue by marove2000** [matiasdelellis/facerecognition#3]
I just wanted to test this app but unfortunately it only works with Version 13 or lower. Error: Server version 13 or lower is required.

**Comment by stalker314314** [comment]
I think you probably have NC14? If so, and to unblock you, you should change number 13 to 14 in [info.xml](https://github.com/matiasdelellis/facerecognition/blob/master/appinfo/info.xml), line 23 in your code. I think it should be trivial to bump this in master branch, but let's wait for @matiasdelellis to confirm

**Comment by matiasdelellis** [comment]
Hi @marove2000 
In principle, as @stalker314314 says just modifying that line could work..
Although the fronted application will look bad. :disappointed: 

Officially, let's wait to finish the new version of the branch backward-incompatible-v2 before publish a release to NC 14.. :wink:

**Comment by stalker314314** [comment]
Latest push request also added fixed support for v14. As @matiasdelellis said - it is not ready for release to NC 14
