### ISSUE TITLE
no photos scanned

### ISSUE THREAD

**Issue by darmbrust** [matiasdelellis/facerecognition#302]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Do something :)

### Actual behaviour

Not scanning photos?

### Steps to reproduce
Tried to install / setup - think I did everything right, but these commands lead to nothing happening, and I don't see any errors:

darmbrust@webserver-vm:/opt/storage/website/nextcloud$ sudo -u www-data php occ face:background_job 
1/10 - Executing task CheckRequirementsTask (Check all requirements)
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Skipping image scan for user dans_phone that has disabled the analysis
        Skipping image scan for user dryer that has disabled the analysis
        Skipping image scan for user karens_phone that has disabled the analysis
        Skipping image scan for user karmbrust that has disabled the analysis
        Skipping image scan for user kitchen_laptop that has disabled the analysis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
10/10 - Executing task UnlockTask (Release obtained lock)
darmbrust@webserver-vm:/opt/storage/website/nextcloud$ sudo -u www-data php occ face:progress
+--------+-----------+-----+
| Images | Remaining | ETA |
+--------+-----------+-----+
| 0      | 0         | -   |
+--------+-----------+-----+

### Server configuration

* **Operating system:**
Linux webserver-vm 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:26:28 UTC 2019 i686 i686 i686 GNU/Linux

* **Pdlib version:**
commit c7d57a7a1b12865096e98c08e6eb2b6daed1dc52 (HEAD -> master, tag: 1.0.1, origin/master, origin/HEAD)

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
built from source commit 5650ce45a14cc08d5c156fc342e3c416d96d2aaf (HEAD -> master, origin/master, origin/HEAD)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
build from source

* **PHP version:**
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )

* **Web server:**
apache
* **Database:**
mysql
* **Nextcloud version:**
18.0.7

Not sure what I'm doing wrong....

**Comment by matiasdelellis** [comment]
> Skipping image scan for user dans_phone that has disabled the analysis
> Skipping image scan for user dryer that has disabled the analysis
> Skipping image scan for user karens_phone that has disabled the analysis
> Skipping image scan for user karmbrust that has disabled the analysis
> Skipping image scan for user kitchen_laptop that has disabled the analysis

Go to to settings panel..

**Comment by darmbrust** [comment]
I did enable it for the account darmbrust, however, and I set 

occ config:app:set facerecognition handle_shared_files --value true

and several of the accounts above have shared folders with the darmbrust account - why isn't it scanning the shared folders?

**Comment by darmbrust** [comment]
so, setting the option in one of the other accounts seems to make it find photos for that account, but not across shared folders?
Maybe I don't understand what that hidden setting is supposed to do.
Now, I'm stuck with https://github.com/matiasdelellis/facerecognition/issues/278 however... will see if I can manually get your patch in :)

**Comment by matiasdelellis** [comment]
> and several of the accounts above have shared folders with the darmbrust account - why isn't it scanning the shared folders?

It was disabled by default for performance, and there are discussions about shared file privacy. 

> occ config:app:set facerecognition handle_shared_files --value true

Try:
* `sudo -u apache php occ user:setting darmbrust facerecognition full_image_scan_done false`

**Comment by matiasdelellis** [comment]
>  but not across shared folders?

All your files are shared ??? How were they shared ???

**Comment by darmbrust** [comment]
I have an account just for my phone - where my phone auto-uploads.  Inside that account, I have shared the folder(s) that the phone uploads with my main account, and a few others, all within the same server.

**Comment by matiasdelellis** [comment]
> I have shared the folder(s) that the phone uploads with my main account

Simple sharing??? Group folder and circle sharing is not implemented.

In any case, test:
> sudo -u apache php occ user:setting USER_THAT-RECEIVE-SHARING facerecognition full_image_scan_done false

And test background task again...

**Comment by darmbrust** [comment]
Looks like the full_image_scan_done false has helped - now it is finding images across the share.

Though, it appears it isn't clever enough to realize that is already scanned these photos for the other account?  Does it keep everything separate per user?  Names, groups, etc?

**Comment by matiasdelellis** [comment]
> Looks like the full_image_scan_done false has helped - now it is finding images across the share.

Great.

> Though, it appears it isn't clever enough to realize that is already scanned these photos for the other account?

You're right. These will be analyzed once for each account that receives the shared file.
In principle it is something to improve, but I must tell you that it is not among the priorities.

> Does it keep everything separate per user? Names, groups, etc?

Yes. If you share pictures with your whole family, in your photos, you probably call yourself by name, your parents as Son/daughter, and your brothers maybe with a funny nickname :sweat_smile: . So this is absolutely personal and the names and groups correspond to each user.. :wink:

**Comment by darmbrust** [comment]
I'll go ahead and close this, since it was obviously user error - not sure which part of the doc might be improved to help others not hit this, but, I know my use case is likely not the normal one :).  I was able to hack my way around the problems with 32 bit linux and the 2 GB limit... still playing with it.  Great promise in this app, once the ability to correct this grouping mistakes is implemented.
