### ISSUE TITLE
[Enhancement] Name Completion / Assist

### ISSUE THREAD

**Issue by onkeljuergen** [matiasdelellis/facerecognition#306]
Hi,

just an Idea what could help maintain a pretty large image collection (as mine).

It would be very helpful if I had some kind of name completion or assitance while I rename the detected clusters.

E.g. I want to rename a cluster from "New person 1984" to "Max" and now a dropdown with possible names from either already named clusters or from contacts would appear depicting to choose "Max Mustermann", "Max Herre", etc.

Best 
Jürgen

**Comment by cliffalbert** [comment]
Maybe also add to the selection potential exif tags that depict people in the picture. For example digikam (and old picasa) used exiftags for the region where the face was and add the name to it.

**Comment by matiasdelellis** [comment]
Hi both,
Finally, implement it in #461 
It must be improved, since it does not end up integrating very well with the dialog when there are many suggestions, but I think it is functional.
