### ISSUE TITLE
Cleanup after user is deleted

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#32]
When user is deleted, we should remove all persons, images and faces associated with this user. This can be implemented either as a hook or part of background job. I guess hook will block more, but we can detect issues better with this approach:)

**Comment by stalker314314** [comment]
I played a bit with this - it seems that Nextcloud is not emitting postDelete hook when file is deleted as part of user deletion.

1. Create user
2. Add some files for that user
3. Remove user
4. Users' files are gone

We get postUserDelete hook for user, but not for users' files. So, that means we need to have either postUserDelete hook or new background task. More I think about it, more I think we should go with new background task - it concentrates all our "business" logic in one place (in tasks), it does not block user deletion, and this cleanup is not something to be done immediately after user deletion. To answer to myself too:
> we can detect issues better with this approach:)

Not necessarily. If we have bug on this path, it is better to block and fail in our command (later, asynchronously), than to block basic functionality of deleting user.

**Comment by matiasdelellis** [comment]
I still want to investigate this a bit more, but I can accept #32 for an initial version.

**Comment by stalker314314** [comment]
"data" as oc_facerecognition_(faces|persons|images)? Yes, that's the goal of this PR (not to delete actual image files). 
Yes, we can use hook postUserDelete, I was reluctant to use it because:
* it will slow down deletion
* it will scatter business logic all around

If you think we should do "reset_all", I will do that

**Comment by stalker314314** [comment]
to clarify - if you think we should do "reset" *method inside postUserDelete*, I will do that:)

**Comment by stalker314314** [comment]
Completely changed PR, I think you will like this version;) Take a look
