### ISSUE TITLE
Facerecognition on Yunohost - Report

### ISSUE THREAD

**Issue by Thovi98** [matiasdelellis/facerecognition#323]
Hello @matiasdelellis 😄  

As you know, my server is on Yunohost and I wanted to install your app.
So I have installed php-pdlib by your repository (https://github.com/matiasdelellis/facerecognition/issues/275), which works fine : after that I’ve updated my default php by `sudo update-alternatives --config php`, when I type

```
$php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"
/etc/php/7.3/cli/php.ini
```
And

```
$ php -m | grep pdlib
pdlib
```
And 

I had no issue with installing the different models. I’ve just analysed my entire database (+- 20 000 photos), and it works great !! 🥳 

I’ve modified the PHP memory_limit, as proposed at https://github.com/matiasdelellis/facerecognition/wiki/PHP-memory_limit. Just one issue about this : when I typed 2048MB, an error occured, but with 2048M (without the B), everything worked fine. I don’t know if it’s a typo issue or configuration related. 

Anyway, I had also to modify the `php_admin_value[memory_limit]` to 2048M in `nano /etc/php/7.3/fpm/pool.d/nextcloud.conf`. I didn’t see this in the Wiki for your information. 

So this message especially to thank you for this app and all your hard work ! It works fine, I’m very impressed 😃 And thank you again for your assistance !

**Comment by matiasdelellis** [comment]
Wow.. @Thovi98 
Thank you very much for the report. I hope you enjoy the application.

> Anyway, I had also to modify the php_admin_value[memory_limit] to 2048M in nano /etc/php/7.3/fpm/pool.d/nextcloud.conf. I didn’t see this in the Wiki for your information.

Ohh.. Now change the recommendations .. :wink:

**Comment by matiasdelellis** [comment]
Just update the documentaion..

Thanks again.. :grinning:
