### ISSUE TITLE
Missing documentation to install the model 4 (DlibCnnHog5)

### ISSUE THREAD

**Issue by phdelodder** [matiasdelellis/facerecognition#332]
Skipping the template, Can the documentation be add on how to install model 4 with DlibCnnHog5?

**Comment by matiasdelellis** [comment]
Hi @phdelodder 
* https://github.com/matiasdelellis/facerecognition/wiki/Models#model-4

This was added on last realese..
 *https://github.com/matiasdelellis/facerecognition/pull/325/files

MM.. You see that??

**Comment by matiasdelellis** [comment]
p,s. Just update that clarifying that models 1 and 2 must also be installed. 😉 

Thanks.

**Comment by phdelodder** [comment]
How do you install those models? I have now selected model 1. 

When selecting 4 I get the msg, unfortunately it's unclear on how to install the dependencies .

**Comment by matiasdelellis** [comment]
Just:
```
#Install dependencies
occ face:setup --model 1
occ face:setup --model 2
```
..and:
```
#Install new model
occ face:setup --model 3
```

**Comment by NeroBurner** [comment]
@matiasdelellis shouldn't the last command to install model 4 actually be `--model 4` instead of `--model 3`?

```
#Install new model
occ face:setup --model 4
```

**Comment by matiasdelellis** [comment]
Hi @NeroBurner 
Of courses.. 😅
