### ISSUE TITLE
Show count of clustered faces

### ISSUE THREAD

**Issue by escoand** [matiasdelellis/facerecognition#334]
### Expected behaviour
The current overview in the personal settings is quite good with just showing the first 14 faces. But it would be nice to have also the count of all available faces. Additionally it should show a loading indicator when clicking one cluster.

### Actual behaviour
Currently the user has no idea if there are only 14 faces or thousands. And when clicking the cluster name and the system is currently doing the detection/recognition in the background it's jumping to the top but you have to wait until the request has finished to know if you click worked.

**Comment by matiasdelellis** [comment]
Hi @escoand 
Honestly it is something that at some point I thought too.  I'll probably add it .. 😉 

Thanks,

p.s.: I wrote a very long message explaining why this information is irrelevant. But I guess it would just excuses .. hahah

**Comment by matiasdelellis** [comment]
Hi @escoand 
As you already know, this will be fixed in #336 , I would appreciate tests and comments.. :smile:

**Comment by matiasdelellis** [comment]
Fixed on last release.. :smile: 

Thanks-
