### ISSUE TITLE
Pre-generate the face thumbnails

### ISSUE THREAD

**Issue by escoand** [matiasdelellis/facerecognition#335]
### Expected behaviour
Would be nice to have the face thumbnails pre-generated. Not sure if you could hook into `preview generator` or do you need to create a own one.

### Actual behaviour
It seems the thumbnails are generated everytime when they are not in the cache of the user's browser.

**Comment by escoand** [comment]
If I got it right then the preview generator in core is not able to cut out a face of the complete image. So you need to handle the thumbnails in the addon. But instead create an extra background task a first good step would also be to save the generated thumbnail to a file and deliver this if already existing.

**Comment by matiasdelellis** [comment]
Hi @escoand

The reason for not doing this yet is that this view should never exist. I mean, do you really expect to see your friends' faces? It's weird .. haha.. What you want to see are the photos you have with them. So the real view should be a photo view, and my expectations is to make an integration with the official Nextckoud Photos.

Well, deleting a view like this, you will never see more than 10 faces of your friends, and your server load will be zero.

Lately it seems that I answer you excuses for not working.. haha.. Sorry..

I close it in favor of https://github.com/matiasdelellis/facerecognition/issues/193
