### ISSUE TITLE
[Feature request] Ability to merge clusters

### ISSUE THREAD

**Issue by ohthehugemanatee** [matiasdelellis/facerecognition#340]
My wife is detected as two separate clusters. Rather than run the entire detection again with different settings, I would like to be able to explicitly merge two clusters into one. This could be a simple option on th Faces listing page. 

How can I help?

**Comment by NeroBurner** [comment]
I think this is a duplicate of https://github.com/matiasdelellis/facerecognition/issues/134

**Comment by ohthehugemanatee** [comment]
It's not a duplicate of the original Issue, but it is defnitely a duplicate of https://github.com/matiasdelellis/facerecognition/issues/134#issuecomment-615009764 . Closing this one in favor of that more complete discusson.
