### ISSUE TITLE
Nextcloud compatibility

### ISSUE THREAD

**Issue by ntimo** [matiasdelellis/facerecognition#347]
### Expected behaviour
The app is compatible with Nextcloud version 20.0.0

### Actual behaviour

The apps is listed as incompatible in the nextcloud app store.

### Steps to reproduce
1. Open the Nextcloud App Store on your v20 Nextcloud
2. Search for Facerecognition
3. See the red warning that the app is incompatible

![Screenshot 2020-10-18 at 16 58 00](https://user-images.githubusercontent.com/6145026/96371677-1cf22d80-1163-11eb-9a6f-eddd657a9d2c.png)

**Comment by matiasdelellis** [comment]
See #344 we need testers.. 😁

**Comment by ntimo** [comment]
Works fine so far for me but I am always running in https://github.com/matiasdelellis/facerecognition/issues/295 :(

**Comment by matiasdelellis** [comment]
Fixed on last release..

Thanks!
