### ISSUE TITLE
Thumbnails missing for some persons in new view

### ISSUE THREAD

**Issue by Derkades** [matiasdelellis/facerecognition#351]
I just updated to 0.7.0 on Nextcloud 19.0.4. The new persons view looks great, unfortunately it's missing a few thumbnails:
![Screenshot_20201024_215922](https://user-images.githubusercontent.com/15892014/97092473-7915ef80-1644-11eb-8260-ec7244ef50b6.jpeg)
![image](https://user-images.githubusercontent.com/15892014/97092396-0d338700-1644-11eb-8134-4e898384bd80.png)

### Server configuration

* **Operating system:** debian

* **Pdlib version:** 1.0.2

* **How is DLib installed:** From source, working with test suite

* **How is PDlib installed:** From source, working with test suite

* **PHP version:** 7.4.11

* **Web server:** Nginx

* **Database:** MySQL

* **Nextcloud version:** 19.0.4

### Client configuration

* **Browser:** Firefox 82

* **Operating system:** Ubuntu 20.10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[PHP] Error: Error: Undefined offset: 0 at /var/www/html/apps/facerecognition/lib/Controller/FaceController.php#93 at <<closure>>

0. /var/www/html/apps/facerecognition/lib/Controller/FaceController.php line 93
   OC\Log\ErrorHandler::onError(8, "Undefined offset: 0", "/var/www/html/a ... p", 93, {id: "241",size: ... l})
1. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\FaceRecognition\Controller\FaceController->getThumb("241", "128")
2. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\FaceRecognit ... {}, "getThumb")
3. /var/www/html/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\FaceRecognit ... {}, "getThumb")
4. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\FaceRecogn ... r", "getThumb", OC\AppFramework\ ... {}, {id: "241",size: ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "241",size: ... "})
6. /var/www/html/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {id: "241",size: ... "})
7. /var/www/html/lib/base.php line 1011
   OC\Route\Router->match("/apps/facerecog ... 8")
8. /var/www/html/index.php line 37
   OC::handleRequest()

GET /apps/facerecognition/face/241/thumb/128
```
</details>

**Comment by Derkades** [comment]
It's working now, no idea why. I refreshed many times during 10 minutes and thumbnails never appeared, now half an hour later they do.

**Comment by andreicociuba** [comment]
I have a similar problem

i can see thumbnails in the face recognition page of my user, but if i click on any of them, thepreviews for that person are all grey.

if i go to "show all groups with the same name", the thumbnails are all visible again.

i checked, and in the first instance when they are grey, the requests are slightly wrong, in that my installation runs under a subfolder of domain.name/nextcloud, and the requests are domain.name/core/preview?fileId......

in the second instance, where the thumbnails are all visible again, their requests are of the form domain.name/nextcloud/index.php/apps/facerecognition/face/....

**Comment by Derkades** [comment]
@andreicociuba Your issue is probably related to this commit: https://github.com/matiasdelellis/facerecognition/commit/81c6157c23db250641e49611a1d523f8c8530a23

You can try manually editing the file with this change

**Comment by andreicociuba** [comment]
Gee! Thanks! Yeah, that fixed it. I edited the file manually. Can't wait for the official update (there is little I dislike more than maintaining manual modifications to a thing that I use only as a hobby,but other than that I appreciate the quick reply! )
