### ISSUE TITLE
Translating into French

### ISSUE THREAD

**Issue by Thovi98** [matiasdelellis/facerecognition#355]
Hey @matiasdelellis ! 😄 
Thank you for this huge update, it’s far better now (although it was already very good) !

I have just one question : how to translate this new release ? On Transifex, it says that the French language is completly translated : 
![2020-10-26 10_48_40-Nextcloud Facerecognition _ Resources](https://user-images.githubusercontent.com/51749973/97158322-8b457a00-1779-11eb-85a3-ffa5d32c7e2f.jpg)

But on Nextcloud, there are still some sentences in English : 
![2020-10-26 10_48_59-Face Recogntion](https://user-images.githubusercontent.com/51749973/97158423-b039ed00-1779-11eb-8dd4-ebca1868d376.jpg)

![2020-10-26 10_49_29-Face Recogntion](https://user-images.githubusercontent.com/51749973/97158377-9dbfb380-1779-11eb-8274-ad47222722ec.jpg)

Thanks for your help, and thanks again !! 😃

**Comment by matiasdelellis** [comment]
Hi @Thovi98 
Do not send the translations to transifex because I expected some feedback about the new texts. There were no comments (Beyond an typo) .. so now I update it.. Please check if any are missing .. 

> Thank you for this huge update, it’s far better now (although it was already very good) !

Thanks.. :smile:

**Comment by Thovi98** [comment]
Thank you 🥳
