### ISSUE TITLE
Consider adding the "hacktoberfest" topic to this repository

### ISSUE THREAD

**Issue by strugee** [matiasdelellis/facerecognition#360]
(Omitting the usual issue template for obvious reasons.)

[Hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update) became [opt-in only this year](https://hacktoberfest.digitalocean.com/hacktoberfest-update) due to a spam problem. [Most (all?)](https://github.com/search?q=topic%3Ahacktoberfest+org%3Anextcloud+fork%3Atrue) Nextcloud repos are opting in; thought you might want to do the same :-)

**Comment by matiasdelellis** [comment]
I honestly don't know him, and I don't understand what he contributes either. :see_no_evil: 
But I guess it's not bad either. So.. done.. :sweat_smile:
