### ISSUE TITLE
How to scan Groupfolders?

### ISSUE THREAD

**Issue by trvrcr** [matiasdelellis/facerecognition#364]
### Expected behaviour

When starting a scan, not only the personal folders but also the groupfolders.
I tried it by enabling the following options:
config:app:set facerecognition handle_shared_files --value true

### Actual behaviour

nothing happens

### Server configuration

* **Operating system:** Raspbian (on Raspberry Pi4  4GB got it working)

* **PHP version:** 7.4

* **Web server:** Nginx 1.18

* **Database:**Mariadb 10.3

* **Nextcloud version:** 20.0.1

### Client configuration

* **Browser:** Mozilla 82.0

* **Operating system:** Windows

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 3562459136
        PHP Memory Limit: 2146435072
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
yielding
yielding
yielding
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
        Skipping stale images removal for user XXX as there is no need for it
        Skipping stale images removal for user XXX as there is no need for it
        Skipping stale images removal for user XXX as there is no need for it
        Skipping stale images removal for user XXX as there is no need for it
        Skipping stale images removal for user XXX as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Found 0 faces without associated persons for user XXX and model 2
        Clusters already exist, but there was some change that requires recreating the clusters
        67 faces found for clustering
        40 persons found after clustering
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Skipping image scan for user XXX that has disabled the analysis
        Skipping image scan for user XXX that has disabled the analysis
        Skipping image scan for user XXX that has disabled the analysis
        Skipping full image scan for user XXX
        Skipping image scan for user XXX that has disabled the analysis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
10/10 - Executing task UnlockTask (Release obtained lock)
</details>

**Comment by matiasdelellis** [comment]
Hi @trvrcr 
Still never add support for it. It's probably easy, if I do a PR do you dare to be a tester?

**Comment by trvrcr** [comment]
Absolutely,
lets give it a go...

**Comment by matiasdelellis** [comment]
Hi @trvrcr 
I didn't try it, but this should be enough. Please, test it. :grimacing: 
You can apply the patch by hand (It is less than 20 lines), or replace the entire facerecognition folder. 

You need to enable it:
`config:app:set facerecognition handle_group_files --value true`

And then indicate that need to search new files.
`occ user:setting USER_ID facerecognition full_image_scan_done false`

**Comment by trvrcr** [comment]
hi @matiasdelellis 
- Changed the code,
- Enabled the config handle
- indicated a new search 

yet in settings status:

>  Current status
> 
> Analyzing images - 1072 images detected - 1 image in queue - Ends approximately in a few seconds
> 

trying to force the rescan with the following command

`occ face:background_job`

stuck in step

> 7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)

was probably already the case before the last command.
Will let it run for a while and I'll come back for a full report...

**Comment by matiasdelellis** [comment]
> stuck in step
>
>  7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
>
> was probably already the case before the last command.
> Will let it run for a while and I'll come back for a full report...

Yes.. Be patient at this point. :see_no_evil: 
Previously, all your photos on group folders were ignored. Now the process must go through your entire disk, to search for new images. Depending on the number of photos, this may take time, and it will take time for each user to share these files.

**Comment by matiasdelellis** [comment]
> Backgroundjob identified all pictures in groupfolders,
> step 9/10 is busy, will continue for 2 days...
>
> reporting back later, but is looking great..

Great.. :smile: 

> Maybe a new feature could be an indication of a backgroundjob running with stepnumber shown?

Maybe https://github.com/matiasdelellis/facerecognition/issues/70
However at this point we have no way of knowing the total images to calculate the time, but of course it could be improved ..

**Comment by trvrcr** [comment]
Yeah, 

My idea is the next:

> Current status - Backgroundjob running - step 7/10 (Crawl for missing images)
> 
>     Analyzing images - 1072 images detected - 1 image in queue - Ends approximately in a few seconds

Just an idea...

**Comment by trvrcr** [comment]
It's not finished checking everything,
but i can confirm it is working.
It finds the pictures in groupfolders
and it recognizes faces.

btw, is there a way of removing a face from a cluster?

**Comment by matiasdelellis** [comment]
> It's not finished checking everything,
> but i can confirm it is working.
> It finds the pictures in groupfolders
> and it recognizes faces.

Great.
When finished, you should try adding new images and deleting others to see if the changes are detected correctly.

> btw, is there a way of removing a face from a cluster?

Not currently.  What kind of errors do you want to fix?
What model are you using? and how many images do you have?

**Comment by trvrcr** [comment]
Model 2
I have a face that is inside a cluster from one person, but it is from another (twins)...

I have 120000pictures so it’s Gina take a while...

**Comment by matiasdelellis** [comment]
@trvrcr 
Model 2 is discouraged because it causes many errors, and with this amount of images it is probably very bad. :disappointed:
I recommend model 4 (but it's slower) or in any case 1.
Sorry if you have to start from scratch, but honestly you will not have good results with model 2.. :disappointed:

**Comment by trvrcr** [comment]
What is the best command to change the model?
Without having to rescan all the pictures?

**Comment by matiasdelellis** [comment]
Always is better to start from scratch, but of course it is annoying and we implement a basic migration command for that. See https://github.com/matiasdelellis/facerecognition#migrate-models and https://github.com/matiasdelellis/facerecognition/issues/317

```
#Setup new model.
occ face:setup --model 4
#Migrate faces from old model
occ face:migrate --model 2
```

**Comment by matiasdelellis** [comment]
ps.: The new model must be clean. If you have already analyzed even a single photo, you must reset this model.

```
#Make sure you are in the new model !!
occ face:setup --model
#Reset just current new model.
occ face:reset --model
```

**Comment by matiasdelellis** [comment]
Hi @trvrcr 
Did you finish the analysis?. 
Did you try removing and adding new images?

Thanks!.

**Comment by trvrcr** [comment]
Back in town,
Analysis finished.
I will add some images with faces and delete them afterwards.
Do you want me to test something specific?

**Comment by matiasdelellis** [comment]
> Analysis finished.

Great.. Model 4 worked better?

> I will add some images with faces and delete them afterwards.
> Do you want me to test something specific?

Just add some images. Run the backgroud task to see if hooks discovered them. and delete them, to know if I delete them correctly (Just look at the number of photos in the administrator view)

**Comment by trvrcr** [comment]
> 
> 
> > Analysis finished.
> 
> Great.. Model 4 worked better?

Yes, Model 4 worked better, Although it does not seem to find all the faces.
and some clusters still have 2 different person in it and no possibility of removing images from cluster, so the cluster is unusable.

> > I will add some images with faces and delete them afterwards.
> > Do you want me to test something specific?
> 
> Just add some images. Run the backgroud task to see if hooks discovered them. and delete them, to know if I delete them correctly (Just look at the number of photos in the administrator view)

I can confirm that the number of photos add the number of images added in the folders.
And diminish when deleted

**Comment by matiasdelellis** [comment]
> Yes, Model 4 worked better, Although it does not seem to find all the faces.

It finds them all, but the faces that potentially cause problems do not group them. You can add one by one as you view the images and mustbe improved on #262 

> and some clusters still have 2 different person in it and no possibility of removing images from cluster, so the cluster is unusable.

The twins is a problem even for google, but I will try to improve it in the future.. :disappointed: 

> I can confirm that the number of photos add the number of images added in the folders.

I will merge it.. :grimacing:

**Comment by matiasdelellis** [comment]
Well. Release the update with that..

Thanks for all feedback.. 😄
