### ISSUE TITLE
Transifex Dutch language

### ISSUE THREAD

**Issue by Derkades** [matiasdelellis/facerecognition#366]
I would like to translate this app to Dutch and have created a language request on Transifex. It's not accepted yet so I guess it doesn't send notifications to the project author. When you have time, could you accept the language request? Thanks

**Comment by matiasdelellis** [comment]
Done.. note that you only requested the language.. and you still have to request to be a translator...it's a pretty annoying thing about transifex... 😞

**Comment by matiasdelellis** [comment]
..and thanks for translate!. It is a very important thing.! 😄

**Comment by Derkades** [comment]
>and you still have to request to be a translator

Yeah, I was not able to do that before the language was added. I have sent a request now.

**Comment by matiasdelellis** [comment]
Done.. Thanks again.. 😃

**Comment by Derkades** [comment]
All strings translated now :tada:
