### ISSUE TITLE
No Picture Previews of Persons

### ISSUE THREAD

**Issue by lukaskretzschmer** [matiasdelellis/facerecognition#379]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour
When entering **`/index.php/settings/user/facerecognition?name=[saved name of the person]`** we should see a grid of all the pictures of that person but right now is appearing nothing and in the picture background, `**background-image:url('[the url]')**` when inspecting the element it says _Could not load the image_.

We should see a grid of the previews of all the pictures belonging to the group of that person.

We see no images, like if the link is broken.
We do however see all the faces on **`/index.php/settings/user/facerecognition`**

### Steps to reproduce
1. The common installation steps.

### Server configuration

* **Operating system:**
Debian, Raspbian

### Client configuration

* **Browser:**
Firefox, Chrome, Chromium

* **Operating system:**
Debian, Windows, Android

**Comment by matiasdelellis** [comment]
HI @lukaskretzschmer

See https://github.com/matiasdelellis/facerecognition/issues/351 and test https://github.com/matiasdelellis/facerecognition/pull/365

**Comment by lukaskretzschmer** [comment]
I tried it, and I was noticing that the url for the background-image is starting on root like: `https://192.168.0.21/core/preview?fileId=[...]` and there was Not Found error. My nextcloud installation is on `https://192.168.0.21/nextcloud/` I was testing the same url but coming from /nextcloud like:
`https://192.168.0.21/nextcloud/core/preview?fileId=2111&x=256&y=256&a=false&v=3b5143493301e05cf4e48d7f841caca1` and I received an empty JSON response, maybe that could help figure out the issue. I hope it helps.

**Comment by matiasdelellis** [comment]
With the patch, you should see:

`https://192.168.0.21/nextcloud/index.php/core/preview?fileId=2111&x=256&y=256&a=false&v=3b5143493301e05cf4e48d7f841caca1`

**Comment by matiasdelellis** [comment]
Must be fixed on last release.. Test and confirm.

**Comment by lukaskretzschmer** [comment]
This is working incredibly perfect now, I have nothing to say but thank you for this project and your time. I hope I can give back to you and this project.
