### ISSUE TITLE
Typo in page title

### ISSUE THREAD

**Issue by Cubevoid** [matiasdelellis/facerecognition#380]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

The tab title should be "Face Recognition"

### Actual behaviour

Under the settings page in Nextcloud, clicking on Face Recognition makes the tab title "Face Recogntion".

### Steps to reproduce
1. Go to Nextcloud
2. Under settings, click on "Face Recognition" (under Personal)
3. Look at tab title in web browser

### Server configuration

* **Operating system:** Ubuntu 20.04

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi @Cubevoid 
Reported on https://github.com/matiasdelellis/facerecognition/issues/357 and fixed on https://github.com/matiasdelellis/facerecognition/pull/358

However, thank you very much for taking the trouble to report it! :grimacing:

**Comment by Cubevoid** [comment]
Whoops, I only searched open issues. My bad!
