### ISSUE TITLE
The library pdlib is not available.

### ISSUE THREAD

**Issue by retiolus** [matiasdelellis/facerecognition#383]
After installing all dependencies and making tests, still can't download and active face recognition app.

An error occurred during the request. Unable to proceed.
App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available.

**Comment by jakobroehrl** [comment]
I have the same problem. Using Ubuntu 18.4, installed php7.0-pdlib but the message 
"App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available."
is still there

**Comment by hahagu** [comment]
Have you enabled pdlib on php?
Try `phpenmod pdlib`

**Comment by matiasdelellis** [comment]
The configuration of the Cli is different from the server. You have to make sure it is enbaled on both!.

Depending on the system you use, you can use different ways to activate them, but when in doubt, please check the links inside the /etc/php* folders.

**Comment by jakobroehrl** [comment]
Thanks for you replies. 
I installed php7.0-pdlib but it seems I need it for 7.3
So I tried this, and now it's working 👍 
https://github.com/matiasdelellis/facerecognition/wiki/Installation#debian-buster

**Comment by matiasdelellis** [comment]
Hi @jakobroehrl 
> I have the same problem. Using Ubuntu 18.4, installed php7.0-pdlib but the message

Ubuntu 18.04, AKA Bionic has php [7.2](https://packages.ubuntu.com/bionic/php/php-dev)

> I installed php7.0-pdlib but it seems I need it for 7.3

The correct package for bionic is the one indicated in the instructions!. The name was wrong, but it is correctly compiled for 7.2!.  Now add a note about it. 😞 

If you are using a special repository to get php 7.3, you must compile pdlib on your own!. If debian packages work for you, it's just by chance!. 😅

**Comment by matiasdelellis** [comment]
Ok.. According to the questions in #392 , I understand that this error was fixed.. :grimacing: 

Thanks..
