### ISSUE TITLE
Photo added in a shared folder isn't analyzed

### ISSUE THREAD

**Issue by maucem** [matiasdelellis/facerecognition#384]
### Expected behaviour

Pictures added in a shared directory needs to be processed only on the owner user. 
This issue could be linked to #377. 

### Actual behaviour

Photo added to a shared folder isn't processed by face recognition. Pictures are ignored by facerecognition both for "uploader user" and "owner user" of the shared dir.

In our case, we have three personal account and one "owner photos" which have the ownership of all pictures that are shared to other users (directly or via group, but it's not relevant).

Only on "onwer photos" account we have enabled face recognition in order to have the same clusterization and it works well. When "owner photos" upload pictures, these are processed.

When a simple user upload a file on the shared dir, the ownership of the file is assigned to "user" but I suppose no events are signaled to  facerecognition, so the image isn't processed.

We also try to transfer ownership to "owner photos" with "occ files:transfer-ownership", but hasn't worked and pictures were moved and doesn't analyzed.

```
$ sudo -u www-data /var/www/nextcloud/occ files:transfer-ownership --path="Media/IMG_0076(2).jpeg" simpleuser ownerphotos
Validating quota
Analysing files of simpleuser ...
    0 [->--------------------------]
Collecting all share information for files and folders of simpleuser ...
    1 [============================]
Transferring files to ownerphotos/files/transferred from simpleuser on 2020-11-19 02-02-09 ...
Restoring shares ...
    0 [>---------------------------]`
```

**Comment by matiasdelellis** [comment]
Hi @maucem 
The event/hook of new files, are sent to the user who performs the action. This is how nextcloud works and we can't fix it efficiently. 😞 
The only way is to go through all the files to find new files. Try for example:

```
[matias@nube nextcloud]$ sudo -u apache php occ user:setting matias facerecognition full_image_scan_done false
[matias@nube nextcloud]$ sudo -u apache php occ face:background_job -u matias
1/10 - Executing task CheckRequirementsTask (Check all requirements)
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Clusters already exist, estimated there is no need to recreate them
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Finding missing images for user matias
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
        Processing image /media/datos/Services/nextcloud/data/user//files/Photos/Share Test/0fa5d93a-3e6b-491d-8d70-bc260232f345-XXX_100297149.JPG
        Faces found: 1
        Processing image /media/datos/Services/nextcloud/data/user/files/Photos/Gorilla.jpg
        Faces found: 0
        Processing image /media/datos/Services/nextcloud/data/user/files/Photos/Nextcloud community.jpg
....
```

If it still doesn't work, you must force nextcloud to find the files before..
```
[matias@nube nextcloud]$ sudo -u apache php occ files:scan --path="/matias/files/"
Starting scan for user 1 out of 1 (matias)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 6465    | 70257 | 00:10:25     |
+---------+-------+--------------+
```

**Comment by fuco809** [comment]
is this option default value true?
occ config:app:set facerecognition handle_shared_files --value true
what i start with false and later change to true - will that work?

i have a shared photo folder which isnt processed by my user.

so every user which has the share has it own processing and his own clusters for the same photos?

**Comment by matiasdelellis** [comment]
> is this option default value true?

MM... By default it doesn't even exist, that would be false. :sweat_smile: 

> occ config:app:set facerecognition handle_shared_files --value true
> what i start with false and later change to true - will that work?

Yes. But you have to take into account the previous comment.

> so every user which has the share has it own processing and his own clusters for the same photos?

Yes.. .. and I'm sorry but it will continue like this !.
