### ISSUE TITLE
Offloading first run

### ISSUE THREAD

**Issue by jfdhuiz** [matiasdelellis/facerecognition#388]
I run NC on my NAS, and I was wondering what is the best way to offload the data to an other computer? I got a Zen 2 Ryzen 9 available, to name an example. Especially for the initial analysis this is going to be very useful. After that, I'm not too worried.

I suppose I could install/replicate a Nextcloud install on the Zen machine, copy the data over, while still communicating to the Postgres on the NAS. After that, the PostgreSQL DB is filled with the correct data while I can spin down the Nextcloud install on the Zen machine and have the NAS do the common work in cron every X minutes (or at night).

**Comment by muebau** [comment]
I had the same questions and ideas. I suggested very early in the project to have some kind of interface to connect to.
It was #210 and was not as long as I remembered 😂

If there would be a "model" of type "external" the images could be send and the answer would be the position with the descriptor.

I started the development of a simple app with the ML part based on JavaScript (face-api.js). Face recognition is just a small part of that app. Some apps could send (via NC Events) a request for some ML invocation.

The app has a queue to take input (eg. image & model) and would process the request. If the task is done the app which invoked the original request is notified with a event again.

This way the installation and usage of ML models is unified. If the ML app would have a external interface itself it could transit the requests.

NC (on RPi) => (ML App on RPi) => (daemon on Computer with CUDA)

**Comment by matiasdelellis** [comment]
Hi both,
There is no easy way to analyze on a computer and then migrate. But there was a lot of progress in the modularization of the application, and now should be quite easy to make an external model. :grimacing: 

The only thing stopping me from writing this, is that this can easily tear down all the privacy of the application. :thinking:

**Comment by escoand** [comment]
My deep wish is still to save the face data back to the images (and christmas is near :-D). Then on any other system you could restore this information. But I understand that @matiasdelellis has other priorities.

**Comment by matiasdelellis** [comment]
https://github.com/matiasdelellis/facerecognition-external-model
:see_no_evil: :shushing_face:

**Comment by jfdhuiz** [comment]
I believe general purpose (PC) computing comes with freedom, and freedom implies responsibility. If one were to use a cloud for the computation, why not? If one hosts Nextcloud in the cloud, why not? (Of course, it gets more complex than that, because what if someone shot pictures of you? An interesting social problem, though beyond the scope in this matter.)

If someone were to pwn that Ryzen machine, they'd have access to my Nextcloud machine as well. So in my use case, doing the analysis on another machine I own (with 12 cores, 64 GB DDR4, and an AMD GPU so no CUDA) is going to help massively versus some old slow Intel Synology NAS.

Thanks @matiasdelellis gonna give it a whirl during off-time

**Comment by matiasdelellis** [comment]
Hi @jfdhuiz 
We have something functional.. but I don't expect to work much more on it .. 

If you want to try.. https://github.com/matiasdelellis/facerecognition/pull/389#issuecomment-731872724 :wink:

**Comment by matiasdelellis** [comment]
Hi @jfdhuiz @muebau 

Here my first real test... It seems very promising .. :wink: :stuck_out_tongue_winking_eye: 

* https://github.com/matiasdelellis/facerecognition/pull/389#issuecomment-732466204

If you want to try, you just have to replace the facerecognition folder with this [tarball](https://github.com/matiasdelellis/facerecognition/pull/389#issuecomment-732457637), and follow the instructions of  https://github.com/matiasdelellis/facerecognition-external-model

it should be easy.. :smile:

**Comment by muebau** [comment]
>  It seems very promising
Hi @matiasdelellis,
thank you for the mentioning. Sorry I was able to read all this just now (weekend).

It looks very promising indeed! 👍👍👍

Now I have to find time to test it. 😂

I think this is a very great thing.

**Comment by ei-ke** [comment]
@matiasdelellis Thank you very much for facerecognition-external-model. Works flawlessly.
I do understand the privacy concerns I read in one of the issues here. I think this feature is still very useful for. I'm for example rolling my cloud at home on an Intel NUC. For the initial indexing it's really nice to do share my desktop's GPU with the NUC to do the hard work for 15k+ files.
In my mind this is also a plus as a user experience as you don't overload the system for days or weeks.
And for those who use it on larger scale it might be a good thing to just have one server with some GPU/TPU oomph to do the recognition.

For testing puposes I quickly spun up [this](VM from https://www.hanssonit.se/nextcloud-vm/) VM.

Host
`Intel Core i7-7820X, 32GB RAM, GeForce GTX 1060 6GB, Arch Linux using cuda-11.1.1-1 cudnn-8.0.5.39-1
`
(N.B. cuda-11.2 is currently broken for Arch as the NVIDIA driver version lags behing)

Guest:
`8 cores, 8GB RAM
`

More or less default settings
```
Temporary files: 2311x1733 (4x3)
Sensitivity: 0.4
Minimum confidence: 0.99
```

10 photos - 44,2MB, approx. 20MP each

model 1
```
real	1m31.334s
user	2m45.651s
sys	0m50.550s
```
9,1s/image

model 5
```
real	0m46.800s
user	0m6.674s
sys	0m0.456s
```
4,7s/image

additional 126 photos
```
real	8m22.748s
user	1m24.036s
sys	0m1.850s
```
4s/image
