### ISSUE TITLE
Not analysing new images

### ISSUE THREAD

**Issue by retiolus** [matiasdelellis/facerecognition#392]
This 2 images are being analysed for past 2 days... And other new images not. How can I fix that?

![image](https://user-images.githubusercontent.com/65604466/100528220-91949f00-31da-11eb-871a-d6c7a501582d.png)

**Comment by matiasdelellis** [comment]
Hi @retiolus 
Can you show the log of face:backgroud_task command?

Remember that the process is thinking for a continuous execution... :wink:

**Comment by matiasdelellis** [comment]
Also keep in mind that this progress indicates the photos of all users ... Maybe you are analyzing only one user and you have two images pending in another user ...

**Comment by retiolus** [comment]
How can I get log of face:background_job ? And I'm analysing images of one single user...

**Comment by matiasdelellis** [comment]
Great.. :smile: 

Remember that the application registers new images automatically, but to analyze it you must run the command regularly.

See. 
https://github.com/matiasdelellis/facerecognition/wiki/Schedule-Background-Task
