### ISSUE TITLE
Not detecting new images 

### ISSUE THREAD

**Issue by retiolus** [matiasdelellis/facerecognition#393]
Yesterday I added 6 GB of images on my Nextcloud, Face Recognition app hasn't detected them... How can I fix that? Background job is already enabled.

**Comment by matiasdelellis** [comment]
HI @retiolus 
How did you upload the 6 Gb of images? The progress that indicates?.

**Comment by retiolus** [comment]
I don't know why, but after running face:background_job several times it finally worked... But I have already that on crontab, it should have done that automatically every 30 min...

**Comment by matiasdelellis** [comment]
Ok.. the application is working .. Make sure the cron is working ..

And you can save the cron log adding an pipeline.... ie.

```
[matias@nube ~]$ sudo crontab -u apache -e
 #*/30 * * * * php -f /var/www/html/nextcloud/occ face:background_job -t 900 >> /var/log/facerecognition.log 2>&1
```
