### ISSUE TITLE
Issue compiling pdlib when following Docker documentation

### ISSUE THREAD

**Issue by jszejner** [matiasdelellis/facerecognition#394]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Pdlib should compile and generate new docker image to use

### Actual behaviour

Error: 
```
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++11 -I. -I/var/www/html/pdlib -DPHP_ATOM_INC -I/var/www/html/pdlib/include -I/var/www/html/pdlib/main -I/var/www/html/pdlib -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /var/www/html/pdlib/pdlib.cc  -fPIC -DPIC -o .libs/pdlib.o
In file included from /usr/include/sched.h:29,
                 from /usr/include/pthread.h:23,
                 from /usr/include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/8/bits/gthr.h:148,
                 from /usr/include/c++/8/ext/atomicity.h:35,
                 from /usr/include/c++/8/bits/basic_string.h:39,
                 from /usr/include/c++/8/string:52,
                 from /usr/local/include/dlib/algs.h:93,
                 from /usr/local/include/dlib/matrix/matrix_exp.h:6,
                 from /usr/local/include/dlib/matrix/matrix.h:6,
                 from /usr/local/include/dlib/matrix.h:6,
                 from /usr/local/include/dlib/cuda/tensor.h:8,
                 from /usr/local/include/dlib/dnn.h:12,
                 from /var/www/html/pdlib/src/face_recognition.h:8,
                 from /var/www/html/pdlib/pdlib.cc:33:
/var/www/html/pdlib/pdlib.cc: In function 'void php_face_recognition_free(zend_object*)':
/var/www/html/pdlib/pdlib.cc:139:72: warning: offsetof within non-standard-layout type 'face_recognition' {aka '_face_recognition'} is conditionally-supported [-Winvalid-offsetof]
  face_recognition *fr = (face_recognition*)((char*)object - XtOffsetOf(face_recognition, std));
/var/www/html/pdlib/pdlib.cc:139:61: note: in expansion of macro 'XtOffsetOf'
  face_recognition *fr = (face_recognition*)((char*)object - XtOffsetOf(face_recognition, std));
```

### Steps to reproduce
1. use docker steps for nextcloud:apache https://github.com/matiasdelellis/facerecognition/wiki/Docker
2. run docker build . -t <name-of-your-container>

### Server configuration

* **Operating system:**
Ubuntu 20.04 running docker 19.03.13
* **Pdlib version:**
master
* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
not installed
* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
not installed
* **PHP version:**
version inside 
* **Web server:**

* **Database:**
none
* **Nextcloud version:**
20.0.2

**Comment by jszejner** [comment]
Increased my virtual machine from 1 CPU core and 1024mb RAM to 6 CPU cores and 2048mb RAM and it got passed this step. The error was still thrown though

**Comment by iamklaus** [comment]
Hey guys, I've build a docker image and published it on docker hub. I will maintain this image. Everything is build on top of the official nextcloud apache image. Feel free to use it: https://hub.docker.com/r/iamklaus/nextcloud
