### ISSUE TITLE
Would it be possible to make the avatar images in the rename person dialog box clickable links?

### ISSUE THREAD

**Issue by rhatguy** [matiasdelellis/facerecognition#396]
Make the avatar images in the rename person dialog box clickable links?

The images displayed in the "rename person" dialog when initially tagging people are very small (50x50 thumbnail image).  Sometimes (seems worse with babies) these pictures are difficult to tell who a person is with such a small shot.  Would it be possible to make these images clickable links to the full size photo for verification?  It might only take a person looking at a single full size picture to recognize the entire group either due to other context inside the full picture, or due to the time the picture was taken.

**Comment by rhatguy** [comment]
Here is an example.  The face on the left is very hard to see at the 50 pixel thumbnail size that is the default, however if I pull up a larger version of the thumb (200px for instance) I can determine who this is.  If I go to the actual image and see the context of everything that is in the image its much easier to understand who this is.
![rename_example](https://user-images.githubusercontent.com/11964411/101928760-fde0ac80-3ba3-11eb-922d-024a46c8b11c.JPG)

**Comment by matiasdelellis** [comment]
It is something that I was thinking too .. :wink:

**Comment by matiasdelellis** [comment]
Hi @rhatguy 
Fixed on last pull request.. #467 

Son, an update to include it.. .. 😄 

Thanks again.
