### ISSUE TITLE
Analysis isn't start after uploading new photos

### ISSUE THREAD

**Issue by XDavidT** [matiasdelellis/facerecognition#398]
### Expected behaviour

view photos in the queue or in face recognition after upload few photos

### Actual behaviour

After install and uploading photo, the temporary files is NaNxNaN
trying to change it, getting the error:

> The change could not be applied. - Seems you haven't set up any analysis model yet 

and **Configuration information** is in red
**Current Model** is -1
https://imgur.com/a/BkionNg

### Steps to reproduce
1. Install NC
2. install php7.4-pdlib
3. install face recognition plugin
4. upload photos
5. ask for analyze in setting

### Server configuration

* **Operating system:**   Linux 5.4.0-56-generic x86_64 UBUNTU
* **Pdlib version:** 7.4

* **How is DLib installed:** 

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
Ubuntu Focal - ssh to machine

* **PHP version:** 7.4.3

* **Web server:** apache

* **Database:** PostgreSQL 12.5

* **Nextcloud version:** 20.0.2

### Client configuration

* **Browser:** Firefox

* **Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)

https://file.io/H1fgX9dumIYi
#### Browser log
https://imgur.com/a/TEVIXuG

**Comment by matiasdelellis** [comment]
Hi @XDavidT

> Current Model is -1

You never set the model to use!

> Steps to reproduce
>
>    Install NC
>    install php7.4-pdlib
>    install face recognition plugin
>    upload photos
>    ask for analyze in setting

Set model!.

https://github.com/matiasdelellis/facerecognition#configuration
