### ISSUE TITLE
This image is not yet analyzed Please, be patient

### ISSUE THREAD

**Issue by arthurcoudron** [matiasdelellis/facerecognition#400]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Recognizing a face or let me give up who's face the image contains.

### Actual behaviour

Just shows "This image is not yet analyzed please be patient", already waiting for a day. This message only appears on the new images (last 20).
When I execute the backgroundjob command, it works and processes the new images in step 9. But the web interface still shows that they are being analyzed.

* **Nextcloud version:**
20.0.3

**Comment by XDavidT** [comment]
Same here, I try to update to nextcloud 20.0.3 to fix it, but still nothing: https://imgur.com/a/giQqMJW (screenshot)

**Comment by matiasdelellis** [comment]
Hi @arthurcoudron 

The command is a continuous execution task. Do not cluster new faces unless two hours have passed since the last clustering. This is so as not to continually cluster the faces since it can be an expensive process. If you run it again, you will see your faces.

**Comment by matiasdelellis** [comment]
Hi @XDavidT 

It seems to never execute the command. https://github.com/matiasdelellis/facerecognition#test-the-application

**Comment by arthurcoudron** [comment]
> Hi @arthurcoudron
> 
> The command is a continuous execution task. Do not cluster new faces unless two hours have passed since the last clustering. This is so as not to continually cluster the faces since it can be an expensive process. If you run it again, you will see your faces.

Indeed, now I do see all the faces. Thank you for your fast reply. This can be closed.
