### ISSUE TITLE
Feature Request - Make Corrections possible

### ISSUE THREAD

**Issue by TheColin21** [matiasdelellis/facerecognition#402]
It would be great to be able to correct the decision the AI made. There are persons in my account, that were recognized as 6 different ones and there are some faces which consist of multiple persons. It would be great to at least be able to merge persons to help the AI match them better next time and not having to look through six different "folders" to see all pictures of a person.

**Comment by TheColin21** [comment]
correction: I just noticed that different faces with the same name get paired. A feature to move faces to another group would still be great.

**Comment by matiasdelellis** [comment]
Hi @TheColin21 
Now we are focused on automatic recognition. You can try reducing the sensitivity, or use model 4.

Close this in flavour of #158

**Comment by matiasdelellis** [comment]
p.s: Thanks for try to report that... :grimacing:
