### ISSUE TITLE
how to handle crash with "Call to a member function file_get_contents() on null in /var/www[...]"

### ISSUE THREAD

**Issue by htc1977** [matiasdelellis/facerecognition#403]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

face:background_job should scan all images. 36 images where left, after I ran this job about 500 times, because of file_get_contents crashes.

### Actual behaviour

It should scan those images or if the images or files are broken, it should mark them as "not scanable" and continue.
In the log, I do see a path to /tmp/ but I don't want to scan /tmp/ and the file mentioned don't exists.
Nextcloud tells me, there a 36 files in the queue, but I think, they are not available on the system, how can I "reset" this list?

### Steps to reproduce
1. sudo -u www-data php /var/www/nextcloud/occ face:background_job -u [USER]
2.
3.

### Server configuration

* **Operating system:**
Ubuntu 20.04.1 LTS, kernel 5.4.0-56
* **Pdlib version:**
1.0.2
* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
via repository for Ubuntu 20.04
* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
see DLib
* **PHP version:**
7.4.3
* **Web server:**
Apache 2.4.41
* **Database:**
MariaDB 10.3.25
* **Nextcloud version:**
20.0.3
### Client configuration

* **Browser:**
Google Chrome for Ubuntu v 87.0
* **Operating system:**
Ubuntu 20.04
#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
	System: Linux
	System memory: 4127367168
	PHP Memory Limit: Unknown
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
	Skipping stale images removal for user christian@frey.com as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Found 0 faces without associated persons for user christian@frey.com and model 1
	Clusters already exist, estimated there is no need to recreate them
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
	Skipping full image scan for user christian@frey.com
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
	NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
yielding
	Processing image /tmp/oc_tmp_hnDA26
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/nextcloud/lib/private/Files/Filesystem.php:716
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/OC_Image.php(624): OC\Files\Filesystem::file_get_contents()
#1 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(112): OC_Image->loadFromFile()
#2 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#3 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct()
#4 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage()
#5 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute()
#6 /var/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#7 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#8 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#9 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#11 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
dup of #295
