### ISSUE TITLE
Please be patient / No faces shown

### ISSUE THREAD

**Issue by ggeorgg** [matiasdelellis/facerecognition#409]
Hi, I want to use the facerecognition app, but unfortunately, I am not able to.

Please let me know if you need more information. I did not fill out the whole template.
I am not sure if this is maybe related to [https://github.com/matiasdelellis/facerecognition/issues/97](https://github.com/matiasdelellis/facerecognition/issues/97) somehow.

### Expected behaviour

The app should recognize the the faces in the images and display them

### Actual behaviour

No faces are shown under settings - facerecognition even though some faces have been recognized. 
![grafik](https://user-images.githubusercontent.com/13244552/102929430-dc809a00-449a-11eb-9665-fda52de9e8cd.png)
The faces can also be found in the database: 
![grafik](https://user-images.githubusercontent.com/13244552/102930043-04bcc880-449c-11eb-923f-0146270887d6.png)

(By the way, it would be "Ihre Freunde..." in german. There is an "e" missing. Where could I contribute this? Or can you change it?)

### Steps to reproduce
1. Create new "testuser"
2. Upload two additional test images "Big Bang Theory.jpg" and "Big Bang Therory.png" which can be found here: [https://github.com/matiasdelellis/pdlib-min-test-suite/tree/master/input](https://github.com/matiasdelellis/pdlib-min-test-suite/tree/master/input)
3. Enable the face recognition for this test user. Start the image processing with the command line "php occ face:background_job"

### Server configuration

![grafik](https://user-images.githubusercontent.com/13244552/102930864-911bbb00-449d-11eb-97c7-64f927c33ff1.png)

* **Operating system:**
* Open Suse Leap

* **Pdlib version:**
* 1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
See [https://github.com/matiasdelellis/pdlib-min-test-suite/issues/5](https://github.com/matiasdelellis/pdlib-min-test-suite/issues/5)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
* See [https://github.com/matiasdelellis/pdlib-min-test-suite/issues/5](https://github.com/matiasdelellis/pdlib-min-test-suite/issues/5)

* **PHP version:**
* 7.4

* **Web server:**
* nginx

* **Database:**
* mariadb

* **Nextcloud version:**
* 20.0.4

### Client configuration

* **Browser:**
* Firefox / Edge

* **Operating system:**
* Windows 10

#### Background task log with debug.
<details>
<summary>sudo -u nginx /srv/www/nextcloud/occ -vvv face:background_job</summary>

```
georg@Quetzal:~> sudo -u nginx php /srv/www/nextcloud/occ face:background_job -u testuser -vvv
[sudo] Passwort für georg:
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 8265134080
        PHP Memory Limit: 2147483648
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
        Skipping stale images removal for user testuser as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Finding missing images for user testuser
        Found /testuser/files/Nextcloud.png
        Found /testuser/files/Photos/Big Bang Theory.jpg

        Found /testuser/files/Photos/Big Bang Theory.png
        Found /testuser/files/Photos/Birdie.jpg
        Found /testuser/files/Photos/Frog.jpg
        Found /testuser/files/Photos/Gorilla.jpg
        Found /testuser/files/Photos/Library.jpg
        Found /testuser/files/Photos/Nextcloud community.jpg
        Found /testuser/files/Photos/Steps.jpg
        Found /testuser/files/Photos/Toucan.jpg
        Found /testuser/files/Photos/Vineyard.jpg
yielding
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Toucan.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Gorilla.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Big Bang Theory.png
        Faces found: 5
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Frog.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Library.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Steps.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Nextcloud community.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Nextcloud.png
        Faces found: 0 (image will be skipped because it is too small)
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Vineyard.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Birdie.jpg
        Faces found: 0
yielding
        Processing image /nextcloud-data/testuser/files/Photos/Big Bang Theory.jpg
        Faces found: 0
10/10 - Executing task UnlockTask (Release obtained lock)
georg@Quetzal:~>

```

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

#### Additional information
```
georg@Quetzal:~/pdlib> sudo -u nginx php /srv/www/nextcloud/occ face:stats -u testuser
[sudo] Passwort für georg:
+----------+--------+-------+---------+
| User     | Images | Faces | Persons |
+----------+--------+-------+---------+
| testuser | 11     | 5     | 5       |
+----------+--------+-------+---------+
georg@Quetzal:~/pdlib>
```

Thanks a lot
Best regards
Georg

**Comment by matiasdelellis** [comment]
Hi @ggeorgg 
You have 5 "persons", with 5 faces.. The main page only suggests you assign names to persons with more than one face!.

If you go to the images in the files or photos view, you can assign them names and see them later in the main view..

**Comment by ggeorgg** [comment]
Great! Thanks for the information! Is this already mentioned somewhere in the wiki? If yes, sorry I didn't find it.
After assigning names to the found faces in the photo view, I switched back to the main view. The faces were listed!
![grafik](https://user-images.githubusercontent.com/13244552/102937574-c7ac0280-44aa-11eb-85db-8fb0698d2701.png)

Now I only have to figure out, why only 5 faces are found. I guess I will have to "tune" the settings a bit... I will try it.

**Comment by ACarolan** [comment]
I'm having a similar issue but the stats are showing 0 persons. I'm running Nextcloud through docker on my Unraid server. My db is SQLite because I wanted to make sure I could get facial recognition working before doing a main install. Would that be causing this issue? If not I have no idea why it shouldn't be working. 

For the dependencies I used the docker image found [here](https://hub.docker.com/r/iamklaus/nextcloud) and increased PHP memory to 2GB.

Everything else is roughly the same as @ggeorgg's installation.

![image](https://user-images.githubusercontent.com/6604386/104115319-df64f280-52c2-11eb-9797-fa9a54863538.png)

**Comment by ACarolan** [comment]
> 
> 
> I'm having a similar issue but the stats are showing 0 persons. I'm running Nextcloud through docker on my Unraid server. My db is SQLite because I wanted to make sure I could get facial recognition working before doing a main install. Would that be causing this issue? If not I have no idea why it shouldn't be working.
> 
> For the dependencies I used the docker image found [here](https://hub.docker.com/r/iamklaus/nextcloud) and increased PHP memory to 2GB.
> 
> Everything else is roughly the same as @ggeorgg's installation.
> 
> ![image](https://user-images.githubusercontent.com/6604386/104115319-df64f280-52c2-11eb-9797-fa9a54863538.png)

Nevermind, got it working running after switching to mariadb and running the background_job again!

**Comment by Playragnarok** [comment]
@ggeorgg How to do sovole

**Comment by ggeorgg** [comment]
1. See https://github.com/matiasdelellis/facerecognition/issues/409#issuecomment-749777057
2. "Now I only have to figure out, why only 5 faces are found. I guess I will have to "tune" the settings a bit... I will try it." -> The images had a quite bad quality. With the better quality, more faces were found.
