### ISSUE TITLE
Continuous integration support

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#41]
Add support for Travis. With existing tests. Code coverage is bonus:)

**Comment by stalker314314** [comment]
Heya @matiasdelellis, I am trying to do this, but I am not seeing this project in travis [here](https://travis-ci.org/account/repositories). Can you somehow go to settings and make sure this repo is set to "ON"? Maybe I will see it after that.
I kind of started working on this on [this branch](https://github.com/matiasdelellis/facerecognition/tree/travis-ci-onboarding), but it is all "theory" for now, as I cannot get to Travis to try it out:) Thanks!

**Comment by stalker314314** [comment]
Yap, I think I cannot do it, as I am not owner of this repo, says [here](https://docs.travis-ci.com/user/tutorial/). @matiasdelellis, you have to set this repo for continuous integration first (and hopefully, I can see it after that)

**Comment by stalker314314** [comment]
If you don't see it soonish, I just figured out I can just fork repo, then I will be owner, so I can try it like this:D

**Comment by matiasdelellis** [comment]
Ohhh..
I had not understood this well .. :disappointed_relieved: 

I already registered in travis, and activate the repository..  Please tell me what is needed..

**Comment by stalker314314** [comment]
I am not sure how this works, but maybe Travis is not finding `.travis.yml` file and that's why I am not seeing this repo. Let me merge my PR for this and then we can see where we are and what else is needed.

**Comment by stalker314314** [comment]
OK, @matiasdelellis - merged. Travis is _almost_ passing, but you need to onboard `matiasdelellis/facerecognition` repo to https://scrutinizer-ci.com, I cannot do it:

![pic](https://user-images.githubusercontent.com/188751/48408254-2e418c80-e739-11e8-8aed-d582a805bcaf.png)

Let me know once you do this and we _should_ have first passing build:)

P.S. If there is some options over [Scrutinizer](https://scrutinizer-ci.com) to give me some role (contributor, admin...), please add me, it will be faster to iterate that way

**Comment by matiasdelellis** [comment]
The access privileges for "Branko Kokanovic" were updated.  :wink:

**Comment by stalker314314** [comment]
Thanks!
So, with badges, I think we are all good for this, we got some basic stuff, that's it:) Will maybe beef it up once more important stuff are out of the way
