### ISSUE TITLE
Problem with starage support

### ISSUE THREAD

**Issue by dubzap** [matiasdelellis/facerecognition#411]
Hello. I have a problem with face detection. I was install nextcloud 20.0.4 from docker alpine image. 
I have 2 storages. first is ssd 240 gb and 3tb hdd. add external storage as HDD.
I was copy my photos from iphone and puy it in hdd. but face app cant check images and says "This image is not yet analyzed
Please, be patient"
Then i copy folder with images to ssd, but ahve same problem. 
What i do wrong?
![Снимок экрана от 2020-12-23 14-15-23](https://user-images.githubusercontent.com/45031970/102974820-5a8b8200-4529-11eb-81db-f180d48a42f3.png)

**Comment by matiasdelellis** [comment]
occ face:backgroud_job log????

**Comment by dubzap** [comment]
> occ face:backgroud_job log????

how can i get it from docker container? 
occ command not work
"sh: occ: not found"

**Comment by matiasdelellis** [comment]
:facepalm: 

Please!,. See documentation!.

* https://github.com/matiasdelellis/facerecognition/wiki/Docker#run-the-facerecognition-background_job

However I don't know how you installed it. Follow the instructions with which you installed the application!.

**Comment by matiasdelellis** [comment]
Close in favor of #160.. :wink: 
Read all that!.
