### ISSUE TITLE
Model recommendation confusion

### ISSUE THREAD

**Issue by ggeorgg** [matiasdelellis/facerecognition#412]
Here [https://github.com/matiasdelellis/facerecognition/wiki/Comparative-analysis-of-the-models#first-conclusions](https://github.com/matiasdelellis/facerecognition/wiki/Comparative-analysis-of-the-models#first-conclusions), model 2 is recommended.
Here [https://github.com/matiasdelellis/facerecognition/wiki/Models#model-2-discouraged](https://github.com/matiasdelellis/facerecognition/wiki/Models#model-2-discouraged), model 2 is discouraged.

This was a bit confusing for me. I think the first link should also recommend model 1? (You also recommend model 1 or 4 in this [comment](https://github.com/matiasdelellis/facerecognition/issues/364#issuecomment-720125788).

By the way: In the table under [https://github.com/matiasdelellis/facerecognition/wiki/Models#comparison](https://github.com/matiasdelellis/facerecognition/wiki/Models#comparison), I think the table header in column 2 should be "MODEL 2 (CNN68)" instead of "MODEL 1 (CNN68)"?

Best regards
Georg

**Comment by matiasdelellis** [comment]
Hi @ggeorgg 

> Here https://github.com/matiasdelellis/facerecognition/wiki/Comparative-analysis-of-the-models#first-conclusions, model 2 is recommended.
> Here https://github.com/matiasdelellis/facerecognition/wiki/Models#model-2-discouraged, model 2 is discouraged.
> This was a bit confusing for me. I think the first link should also recommend model 1? (You also recommend model 1 or 4 in this comment.

:facepalm: 
Again outdated information.. Model 2 is definitely not recommended.. :disappointed: 

When I did this test, I did not take into account the quality of the clusters.. See https://github.com/matiasdelellis/facerecognition/pull/313#issuecomment-668262032 for resume of new conclusions. Hovewer, I still have pending do the same test adding model 4.

So, yes, use model 1 or 4.

> By the way: In the table under https://github.com/matiasdelellis/facerecognition/wiki/Models#comparison, I think the table header in column 2 should be "MODEL 2 (CNN68)" instead of "MODEL 1 (CNN68)"?

Yes..

**Comment by matiasdelellis** [comment]
See https://github.com/matiasdelellis/facerecognition/wiki/Models#comparison and comment.. :wink:

**Comment by matiasdelellis** [comment]
And https://github.com/matiasdelellis/facerecognition/wiki/Comparative-analysis-of-the-models

**Comment by ggeorgg** [comment]
Thanks for confirming and updating!
