### ISSUE TITLE
CUDA inside a docker container

### ISSUE THREAD

**Issue by jmigual** [matiasdelellis/facerecognition#416]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Face recognition uses the GPU

### Actual behaviour

The GPU usage is always at 0%

### Steps to reproduce
1. Install nvidia drivers
2. Install nvidia docker runtime (https://github.com/NVIDIA/nvidia-container-runtime)
3. Compile image following steps from wiki (https://github.com/matiasdelellis/facerecognition/wiki/Docker)
4. Start analyzing images, GPU usage is 0%

### Server configuration

* **Operating system:** Ubuntu-20.04. Container running on docker. Docker engine version: 1.41

* **Pdlib version:** v1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

By compiling it from source with the examples provided in the wiki

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

By compiling it from source with the examples provided in the wiki

* **PHP version:** 7.4.13

* **Web server:** Apache

* **Database:** MariaDB 10.5.8

* **Nextcloud version:** 20.0.4

### Client configuration

* **Browser:** Firefox 84.0.1

* **Operating system:** Windows 10 20H2

**Comment by hrolofs** [comment]
In addtion to the steps that are discribed you need the cuda toolkit and the cudnn inside the nextcloud docker container.

https://registry.hub.docker.com/r/nvidia/cuda#!
https://gitlab.com/nvidia/container-images/cuda

I have build a image starting withc nextcloud:apache and the cuda 10.2/cudnn7/dev files from the second link. And this works for me.

**Comment by isaacolsen94** [comment]
How would one go about adding this to the Linuxserver Nextcloud docker image on Unraid?

**Comment by jmigual** [comment]
I'm not entirely sure as I haven't used Unraid but if you cannot build custom images in Unraid you could try building an image from your PC and pushing it to Dockerhub, then you can pull it from Unraid

**Comment by kalamataz** [comment]
> In addtion to the steps that are discribed you need the cuda toolkit and the cudnn inside the nextcloud docker container.
> 
> https://registry.hub.docker.com/r/nvidia/cuda#! https://gitlab.com/nvidia/container-images/cuda
> 
> I have build a image starting with nextcloud:apache and the cuda 10.2/cudnn7/devel files from the second link. And this works for me.

Would you mind sharing your dockerfile ? 
Thanks

**Comment by wuast94** [comment]
> In addtion to the steps that are discribed you need the cuda toolkit and the cudnn inside the nextcloud docker container.
> 
> https://registry.hub.docker.com/r/nvidia/cuda#! https://gitlab.com/nvidia/container-images/cuda
> 
> I have build a image starting with nextcloud:apache and the cuda 10.2/cudnn7/devel files from the second link. And this works for me.

Would appreciate if you could share this dockerfile ☺️

**Comment by isaacolsen94** [comment]
> In addtion to the steps that are discribed you need the cuda toolkit and the cudnn inside the nextcloud docker container.
> 
> https://registry.hub.docker.com/r/nvidia/cuda#! https://gitlab.com/nvidia/container-images/cuda
> 
> I have build a image starting with nextcloud:apache and the cuda 10.2/cudnn7/devel files from the second link. And this works for me.

Throwing it out there that I also would love it if you could share your dockerfile? :P

**Comment by LemiSt24** [comment]
FWIW I made this Dockerfile for recognize, it probably works with facerecognition to (you may have to adjust the cuda version etc.):

https://gist.github.com/LemiSt24/72443ded6680cf6fadbe966febd50946

I just pasted together the different build stages from Nvidia for Ubuntu 20.04 and Cuda 11.8 (https://gitlab.com/nvidia/container-images/cuda).

**Comment by quinlan96** [comment]
Thanks for the jumping off point @LemiSt24. I combined your dockerfile with [this one](https://github.com/samssausages/nextcloud-dlib-pdlib-ffmpeg/tree/main) that builds Nextcloud with pdlib.

https://gist.github.com/quinlan96/6300376b9bba7b88256f56ae1982f606

A couple notes:
 - I tried to cut the size of the container down (over 9GB for me), but any fewer CUDA packages breaks compilation of `DLIB_WITH_CUDA`
 - I went with CUDA 12.2 over 12.3 as it doesn't yet support [cuDNN and cuBLAS](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html)
 - You can verify CUDA is enabled by running `php --ri pdlib` inside the container
 - You can verify facerecognition is using the GPU by running `nvidia-smi` inside the container while the `face:background_job` is running (memory usage will get above 0)

For reference, I'm running Nextcloud in a container on Unraid with a GTX 1050ti installed. Tested on a library of 79k photos, which estimates over 2 days to complete. Definitely faster than CPU (especially on bigger files) but not quite the 50-100x ballpark mentioned in the wiki. Could be something with my setup, or maybe I'm expected a bit much of the 1050ti. Either way, my CPU is no longer being hammered for days at a time so I'm happy.

Lastly, here's a sample `docker-compose.yml` below for those who aren't familiar with Nvidia passthrough in Docker:

```
version: '3.8'

services:
  nextcloud:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: nextcloud
    restart: unless-stopped
    privileged: true
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/user/appdata/nextcloud/config:/var/www/html
      - /mnt/user/nextcloud:/var/www/html/data
    environment:
      - PHP_MEMORY_LIMIT=4096M
      - NVIDIA_VISIBLE_DEVICES=all
```
