### ISSUE TITLE
Specify location to process images?

### ISSUE THREAD

**Issue by voarsh2** [matiasdelellis/facerecognition#418]
I have my photos at a folder: /shared/Photos

When I run 
```
sudo -u www-data php /var/www/nextcloud/occ -vvv face:background_job
```
It scans Nextcloud's demo image in the root, which is obviously not going to give any results.

What can I do about this?

**Comment by matiasdelellis** [comment]
I guess later you discovered the settings for shared folders.. :sweat_smile:
