### ISSUE TITLE
Cannot preview recognized image

### ISSUE THREAD

**Issue by voarsh2** [matiasdelellis/facerecognition#420]
When I click to view a recognized image/person it opens a new tab where the image is located.

It doesn't load as this folder has thousands of pictures and my browser freezes.

Might I suggest an actual image preview the way NextCloud normally shows image previews instead of this behaviour?

Could be as simple as making the link of the preview like this: https://xxx/remote.php/dav/files/admin/share/Photos/IMG_7809.PNG

**Comment by matiasdelellis** [comment]
Hi @voarsh2 
From my part, I hope the integration in the photos application https://github.com/matiasdelellis/facerecognition/issues/338

In any case, it seems to me that it is a nectcloud bug, which is already more than documented. Sorry.. Close that
