### ISSUE TITLE
Incorrectly identified face - rename doesn't re-assign single image

### ISSUE THREAD

**Issue by voarsh2** [matiasdelellis/facerecognition#421]
I have a group of photos and a few are wrong, I edit a single one and rename thinking it will correct this one.

Later I find it's renamed all of them in group.

I don't expect this behaviour.

**Comment by baahver** [comment]
Yes, I see the same thing. If I edit a single photo in Nextcloud from the people tab, I expect to change this photo only. But to my horror all photo's from the same recognised group are renamed! I do not see a method to undo this!

**Comment by JakobGode** [comment]
Same problem.
Maybe it's possible to include a tool to correct this.

**Comment by baahver** [comment]
The manual setting should kind of override the algorithm. Is it not?

**Comment by JakobGode** [comment]
That would be nice to make the learning process better.
It would be nice if you can select or unselect the mini fotos at the part where you manually recognise the founded group.
Unselected will not join the group and selectet will join the group.

Das wäre schön wenn das so wäre um das Learning besser zu machen.
Schön wäre auch wenn man die mini-Fotos auswählen oder abwählen kann, dort wo man der erkannten Gruppe den Namen gibt.
Abgewählte würden der Gruppe nicht hinzugefügt und ausgewählte würden der Gruppe hinzugefügt.

**Comment by voarsh2** [comment]
> That would be nice to make the learning process better.
> It would be nice if you can select or unselect the mini fotos at the part where you manually recognise the founded group.
> Unselected will not join the group and selectet will join the group.

Agree.
All of these are good enhancements that make it easier to manage recognized faces.

**Comment by matiasdelellis** [comment]
Hi,
Sorry for the delay,
And sorry due this can be annoying, but is already considered in https://github.com/matiasdelellis/facerecognition/issues/158

I will probably have news about this soon.. :see_no_evil: 

Meanwhile, use the clusters view to fix multiple persons with wrong name, (and you can try to reduce the sensitivity a bit, but there may still be a wrong face within another group)
