### ISSUE TITLE
Temp file could not be set if the external model is not running.

### ISSUE THREAD

**Issue by lannyyip** [matiasdelellis/facerecognition#423]
### Expected behaviour
Face recognition should work properly. Temp file could be set.

### Actual behaviour
After I checked to enabel FR, by checkbox  in FR app  , FR does not work

Tell us what happens instead

### Steps to reproduce
1.docker exec --user www-data nextcloud   php occ -vvv face:background_job
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 16432766976
        PHP Memory Limit: 2147483648
        Seems that still don't configured the image area used for temporary files.
Please read the documentation about this: https://github.com/matiasdelellis/facerecognition/wiki/Settings#temporary-files
and then configure it in the admin panel to continue
2. I tried to change the "Temporary files", but after I changed, I could not be saved. This is not happended to other settings. 
3. docker exec --user www-data nextcloud  php occ config:app:set facerecognition max_image_area --value 786432
I tried to use this cmd to set the value. But the value did not changed. even if i restart the container.

### Server configuration

* **Operating system:**

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

###Dockers  from
iamklaus/nextcloud
### Client configuration

* **Browser:**
Both Firefox and Chrome
* **Operating system:***
Windows 10
#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 16432766976
        PHP Memory Limit: 2147483648
        Seems that still don't configured the image area used for temporary files.
Please read the documentation about this: https://github.com/matiasdelellis/facerecognition/wiki/Settings#temporary-files
and then configure it in the admin panel to continue
```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
{"reqId":"QZxtAFE81jOdeslFhDPt","level":3,"time":"2021-01-14T13:14:12+00:00","remoteAddr":"192.168.1.12","user":"lanny","app":"index","method":"POST","url":"/apps/facerecognition/setappvalue","message":{"Exception":"Exception","Message":"Cannot connect to external model: Failed to connect to 192.168.1.16 port 8090: Connection timed out","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/facerecognition/lib/Model/ExternalModel/ExternalModel.php","line":107,"function":"open","class":"OCA\\FaceRecognition\\Model\\ExternalModel\\ExternalModel","type":"->","args":[]},{"file":"/var/www/html/custom_apps/facerecognition/lib/Controller/SettingsController.php","line":173,"function":"getMaximumArea","class":"OCA\\FaceRecognition\\Model\\ExternalModel\\ExternalModel","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"setAppValue","class":"OCA\\FaceRecognition\\Controller\\SettingsController","type":"->","args":["analysis_image_area","4298400"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\FaceRecognition\\Controller\\SettingsController"},"setAppValue"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\FaceRecognition\\Controller\\SettingsController"},"setAppValue"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\FaceRecognition\\Controller\\SettingsController","setAppValue",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"facerecognition.settings.setAppValue"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/facerecognition/setappvalue"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/facerecognition/lib/Model/ExternalModel/ExternalModel.php","Line":138,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":"20.0.4.0"}
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Please, upload an screenshot of when set temp file size!.

**Comment by lannyyip** [comment]
I clicked the icon where the red arrow is pointing. It was remain unsaved.
While the other parameters in this page is savabel.
![Snipaste_2021-01-15_05-56-10](https://user-images.githubusercontent.com/3487748/104654088-88ae4d00-56f6-11eb-956d-ce1d53b7fbaf.png)

**Comment by matiasdelellis** [comment]
> I clicked the icon where the red arrow is pointing.

Thank you. More than anything I wanted to check that you clicked that same icon. :see_no_evil: 

> It was remain unsaved.
> While the other parameters in this page is savabel.

This parameter is limited by the assigned memory. In your case 2GB. And this probably not enough for the required size.

You should see a notification like this.
![imagen](https://user-images.githubusercontent.com/733715/104654906-a4383a00-569b-11eb-9442-e2d00173ce1b.png)

Try reducing the size even a little bit... :wink:

**Comment by lannyyip** [comment]
Thank you for your quick rsp. 
I tried to use size 640×480, but still not savable. 
I also notice that I have no block ad. plugin enabled and still not see the hints you paste. :(

**Comment by matiasdelellis** [comment]
Hi, 
Now see your log!.

> Cannot connect to external model: Failed to connect to 192.168.1.16 port 8090: Connection timed out","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/facerecognition/lib/Model/ExternalModel

Make sure you have the external model working.

https://github.com/matiasdelellis/facerecognition-external-model#test

:wink:

**Comment by lannyyip** [comment]
Thank you. I thought it would download the model to local storage. Do I need to keep the external server running all the time?

**Comment by matiasdelellis** [comment]
The external model must work in conjunction with the face:background_job task. so, you must make sure that it is working before running it.
On the other hand, it is also necessary for the configuration. It is something that I had ignored until the last comment. :sweat_smile:  Thanks. :grimacing: 

Change the title of issue to reflect it.. In any case, it should show the notification saying that the model is not working.

**Comment by lannyyip** [comment]
I think it would be more reasonable that the model file could be saved locally, so that the flask could be turn off after the model is downloaded.
Thank you for contributing this good app. 👍

**Comment by matiasdelellis** [comment]
> I think it would be more reasonable that the model file could be saved locally, so that the flask could be turn off after the model is downloaded.

The problem is not the files. The problem is All the grace of the external model depends on the computer running that. Ie, the limitation of the image size is given by the amount of computer memory running the model.

If you don't want to do this, you must use models 1 or 4 locally. . :sweat_smile:

**Comment by lannyyip** [comment]
I am inside the wall. github file repository is inaccessable in docker. May I can change the URL in the code.

**Comment by sebaxakerhtc** [comment]
Same here.
![1](https://user-images.githubusercontent.com/32651506/197387422-1bdbc930-c11a-4162-ba39-f9ddec5fae0d.png)
![2](https://user-images.githubusercontent.com/32651506/197387423-f27bf0ef-8572-497c-8cb8-14ca37fc3a1f.png)

Any changes on temporary files not saved

**Comment by sebaxakerhtc** [comment]
![3](https://user-images.githubusercontent.com/32651506/197391784-52355ae7-7f6d-4f04-9ec7-ab914f68c4ef.png)
Problem was here:
display: none;
Why by default these buttons (save and restore) are hidden?

**Comment by cyberpower678** [comment]
I had to make it a button so I could actually render something to click on.

**Comment by matiasdelellis** [comment]
Hey everyone,
The button is hidden, until you modify something that needs to be saved. 🙈 

This bug refers to the fact that while the external model is not running you cannot change anything (And therefore not save). Which, as annoying as it may be, is 100% logical. 😅 

I have to show a better message informing better that the external model is off. However, tomorrow I do some test to check the behavior.. 🤔

**Comment by cyberpower678** [comment]
> Hey everyone, The button is hidden, until you modify something that needs to be saved. 🙈
> 
> This bug refers to the fact that while the external model is not running you cannot change anything (And therefore not save). Which, as annoying as it may be, is 100% logical. 😅
> 
> I have to show a better message informing better that the external model is off. However, tomorrow I do some test to check the behavior.. 🤔

That may be the case, but my model is running, and it still wouldn't let me save.  I moved the slider around and nothing showed.  Turns out the <a> object does not show on newer versions of Nextcloud.  I recommend changing <a> to <button>.  That will make it show up and work.

**Comment by sebaxakerhtc** [comment]
Guys, there's a beta release on official page for NC25 where all works
