### ISSUE TITLE
Put the face recognition app for individual users inside the Picture app

### ISSUE THREAD

**Issue by ozls** [matiasdelellis/facerecognition#424]
This is actually just a suggestion: Could we put the face recognition app for individual users inside the Picture app ? I think it would be more natural to look for it there than in the settings. Please note I have no idea of how hard it would be to do. I am joining a quickly gimped example of what I mean.

![image](https://user-images.githubusercontent.com/34961309/104849647-2d917b80-58eb-11eb-8e9c-ac285c5506d4.png)

Otherwise let me say I just installed the app, it takes a little more effort than others but it works like a charm on my Raspberry. So thank you very much for this amazing app. It really makes a lot of difference for someone trying to get rid of Google!

**Comment by Kalembang** [comment]
Totally agree!

**Comment by matiasdelellis** [comment]
Hi Both,
Dup of #338 

Thanks
