### ISSUE TITLE
Unable to run background job - problem with the the configured image area 

### ISSUE THREAD

**Issue by f34rffm** [matiasdelellis/facerecognition#425]
Hello, 

whenever I run a background job I get the following error:
```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        There are inconsistencies between the configured image area (2734800 pixels^2) which is
greater that the maximum allowed by the model (1942180 pixels^2).
Please check and fix it in the admin panel to continue.
```

I tried chaning configured image area, as follows:
`occ config:app:set facerecognition max_image_area --value 1942180 `
which gives me positive result:
`Config value max_image_area for app facerecognition set to 1942180`

But it seems not to have any effect. Can you please help me out? Thanks

**Comment by matiasdelellis** [comment]
The db setting is `analysis_image_area`, but please, you must set it in `SERVER/settings/admin/facerecognition`

**Comment by f34rffm** [comment]
> 
> 
> The db setting is `analysis_image_area`, but please, you must set it in `SERVER/settings/admin/facerecognition`

Thank you for the fast response, I can't belive I missed that. Guess I'm just a terminal fan. 
Is there a way I could increase my configured image area, which model should I use? All my photos are mostly in high-res. Thanks

**Comment by matiasdelellis** [comment]
> Is there a way I could increase my configured image area

Increase your memory assigned to PHP.

> which model should I use?

Model 1 or 4..
