### ISSUE TITLE
How can i reset images that have been incorrectly grouped together??

### ISSUE THREAD

**Issue by adamnmcc** [matiasdelellis/facerecognition#426]
i inadvertently tagged a group of faces of my son as my Daughter and now i have 11k images that have my daughters name tagged with half them being my son.. 

is there a way to reset this through the DB? i am using mysql backend and am happy to reset if you can give me some info on what tables need modified. 

Many thanks.

**Comment by ccharlot** [comment]
I think there is an option for that : when you see all of the photos of your daughter (with half of them being you son), at the bottom of the page, there is a button "show all groups..."

If you click on it, you should find the group you incorrectly tagged, and then click on the pencil and change the name..

**Comment by adamnmcc** [comment]
I dont seem to have that option at the bottom. Is there a link i can paste into the address bar to activate it??

![Screenshot 2021-01-25 at 12 20 44](https://user-images.githubusercontent.com/2370463/105705261-e0736200-5f07-11eb-80a5-91d1306aa5d1.png)

**Comment by matiasdelellis** [comment]
Hi @adamnmcc 
These three photos that you want to separate? Of the whole group?

If so, we cannot help you.. :disappointed: 
The trained model was trained with older people. The resnet model was trained with people on average older, and with few boys. therefore, it cannot identify childrens correctly.

Ideally, it would be to train a new model, which includes more kids (More non-Caucasian people, etc.), but for this, you would have to request images from the community, which would probably already be frowned upon. :thinking: :disappointed: 

On the other hand, what you need now is covered by this issue... #158

**Comment by adamnmcc** [comment]
Hi @ccharlot , 

no, i was just showing that there is now option at the bottom of the screen to show all the different groups. 

i am happy that the groups where definitely identifying my son and daughter separately in distinct groups, but i'm an idiot and labelled them incorrectly and not seems to think they are the same person. 

i was wondering if there was a way to relabel them somehow in the Database?

**Comment by matiasdelellis** [comment]
> i am happy that the groups where definitely identifying my son and daughter separately in distinct groups,

OK.. So you can use this view of the clusters to rename each group of your daughter. Use pen.. 

![imagen](https://user-images.githubusercontent.com/733715/105724613-cbe29a00-5f06-11eb-8876-254a6c2a6f6d.png)

> i was wondering if there was a way to relabel them somehow in the Database?

According to you comment, you don't need it, but maybe the `face:reset --clusterin`????? https://github.com/matiasdelellis/facerecognition#resetting-information

**Comment by adamnmcc** [comment]
Can i train it myself? i actually have pictures of the kids seperated in folders on my hard drive, so could feed those in to a model if needed.

**Comment by adamnmcc** [comment]
Anyway, i've reset the clustering, issue closed. Thanks for the support.
