### ISSUE TITLE
Person option missing

### ISSUE THREAD

**Issue by Kalembang** [matiasdelellis/facerecognition#427]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

In the side panel of the file application, a 'Persons' tab is added where you can see a list of your friends in the photo, and rename them.

### Actual behaviour

Not seeing any person option listed on the left side. Am I missing something. 
![image](https://user-images.githubusercontent.com/71909170/105753067-1ae3fb80-5f16-11eb-8eae-be65627b7233.png)

### Steps to reproduce
I have installed face recognition and analyzed my photos and named each face. However, I am not seeing the person section

### Server configuration

Unraid 6.8.3 - Running Nextcloud in a Docker 

Pdlib version: 1.0.2

* **How is DLib installed:** Installed via console commanded:
apk add make cmake gcc g++ php7-dev libx11-dev openblas-dev
echo "Restart Docker"
git clone https://github.com/davisking/dlib.git
cd dlib/dlib
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install

cd / 

git clone https://github.com/goodspb/pdlib.git
cd pdlib
phpize
PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig ./configure
make
sudo make install

occ face:background_job

* **PHP version:**

* **Web server:**

* **Database:**

Nextcloud 20.0.5

### Client configuration

Chrome

Windows 10

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi @Kalembang 
Select a photo and see right sidebar.. :sweat_smile:
