### ISSUE TITLE
Nextcloud 21 compatibility

### ISSUE THREAD

**Issue by Derkades** [matiasdelellis/facerecognition#429]
Issue for tracking Nextcloud 21 compatibility. I have not tried upgrading and force enabling it yet.

**Comment by dblazquezl** [comment]
Hi, I already installed it with version 21, still working in the initial process of all my photos. It will take some time.

I just need to modify a couple of thing in the dockerfile in order to get the image:

1.- bz2 was not present, so I copied the 2 lines installing it to the end of the dockerfile instead in the intermediate image and then 
     it worked.
2.- change this path to the latest version:
      COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pdlib.so /usr/local/lib/php/extensions/no- 
      debug-non-zts-20190902/
3.- add backslash at the end of this line (it got an error without it)
      COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib/


I think that was all, I will try to update when the initial process of the images finish

**Comment by markuman** [comment]
I've  moved from NC 20 php 7.4 to NC21 php 8.0 and it seems there is an issue with the temporary path.


```
Faces found: 0. Image will be skipped because of the following error: Error during image resize
```

any ideas? @matiasdelellis

**Comment by markuman** [comment]
I've patched the upstreamd nextcloud docker image like that: https://github.com/nextcloud/docker/issues/1421#issuecomment-783499435  
It's build as `nextcloud21`.  
And this is my multi-stage build on that for facerecognition dependencies: https://git.osuv.de/m/osuv/src/branch/main/roles/containers/files/nextcloud.Dockerfile

You can pull it from here `registry.gitlab.com/markuman/container-images:home.21.0.0.1`

**Comment by markuman** [comment]
Rolling back to php 7.4 works.

**Comment by jmigual** [comment]
Hi @markuman I just used your Docker file and the PDLIB tests failed.

I got the following error:

<details>
<summary>Log</summary>

```
----------------------------------------------------------------------
Libraries have been installed in:
   /var/www/html/pdlib/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.


Build complete.
Don't forget to run 'make test'.


=====================================================================
PHP         : /usr/local/bin/php
PHP_SAPI    : cli
PHP_VERSION : 7.4.15
ZEND_VERSION: 3.4.0
PHP_OS      : Linux - Linux 3512554091f3 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
INI actual  : /var/www/html/pdlib/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /usr/local/bin/phpdbg
PHP_SAPI    : phpdbg
PHP_VERSION : 7.4.15
ZEND_VERSION: 3.4.0
PHP_OS      : Linux - Linux 3512554091f3 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
INI actual  : /var/www/html/pdlib/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
CWD         : /var/www/html/pdlib
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2021-02-27 12:47:55
=====================================================================
PASS Check for pdlib presence [tests/001.phpt]
PASS Basic tests for chinese_whispers [tests/chinese_whispers_basic.phpt]
PASS Edge given in edges array for chinese_whispers functions is associative array [tests/chinese_whispers_edge_associative_array_error.phpt]
PASS Edge elements given in edges array for chinese_whispers functions are not of long type [tests/chinese_whispers_edge_elements_not_long.phpt]
PASS Edge given in edges array for chinese_whispers functions is not having all values to be arrays with 2 elements [tests/chinese_whispers_edge_not_2_element_error.phpt]
PASS Edge given in edges array is not array for chinese_whispers functions [tests/chinese_whispers_edge_not_array_error.phpt]
PASS Args given to chinese_whispers functions is not correct [tests/chinese_whispers_wrong_arg_type_error.phpt]
PASS Testing CnnFaceDetection constructor without arguments [tests/cnn_face_detection_ctor_error.phpt]
PASS Testing CnnFaceDetection constructor with model that do not exist [tests/cnn_face_detection_ctor_model_not_found_error.phpt]
PASS Frontal face detection. [tests/dlib_face_detection.phpt]
PASS Testing FaceLandmarkDetection constructor without arguments [tests/face_landmark_detection_ctor_error.phpt]
PASS Testing FaceRecognition constructor without arguments [tests/face_recognition_ctor_error.phpt]
FAIL Full test for face recognition - download models, detect faces, landmark detection and face recognition. [tests/integration_face_recognition.phpt]
PASS Basic tests for dlib_vector_length [tests/vector_length.phpt]
PASS Just test php extension version [tests/version.phpt]
=====================================================================
TIME END 2021-02-27 12:48:19

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   33
---------------------------------------------------------------------

Number of tests :   15                15
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  6.7%) (  6.7%)
Tests passed    :   14 ( 93.3%) ( 93.3%)
---------------------------------------------------------------------
Time taken      :   24 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Full test for face recognition - download models, detect faces, landmark detection and face recognition. [tests/integration_face_recognition.phpt]
=====================================================================

You may have found a problem in PHP.
This report can be automatically sent to the PHP QA team at
http://qa.php.net/reports and http://news.php.net/php.qa.reports
This gives us a better understanding of PHP's behavior.
If you don't want to send the report immediately you can choose
option "s" to save it.  You can then email it to qa-reports@lists.php.net later.
Do you want to send this report now? [Yns]:
Notice: Trying to access array offset on value of type bool in /var/www/html/pdlib/run-tests.php on line 934

Please enter your email address.
(Your address will be mangled so that it will not go out on any
mailinglist in plain text):
Posting to http://qa.php.net/buildtest-process.php
```

</details>

**Comment by sowoi** [comment]
Yes had the same error. You need to rollback to PHP 7.4.

**Comment by matiasdelellis** [comment]
Hi #429
Sorry for the little development of the last time.. Much work, and honestly I was surprised by the publication of NC21..  :disappointed:  and still haven't received the notification to install it despite having the stable channel configured .. :sweat_smile: 


About php 8.0, NC21 is the first version to support it, but they still recommend php 7.4. https://docs.nextcloud.com/server/21/admin_manual/installation/system_requirements.html#server, So, please, downgrade it.. :see_no_evil: 

About NC21, if you do the relevant tests and assure me that it continues to work correctly, I can publish a version that enables it to install.. :wink:

**Comment by Derkades** [comment]
I have not encountered issues on 21 yet.

> and still haven't received the notification to install it despite having the stable channel configured

The rollout is slow, it can take months. Set channel to "beta" to jump to 21 immediately

>  Much work, and honestly I was surprised by the publication of NC21

Do you know about this page? https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule It's not updated that well but at least it gives some idea

**Comment by Derkades** [comment]
Found this issue, not sure if related to the Nextcloud 21 update but I haven't seen it before
![image](https://user-images.githubusercontent.com/15892014/109973585-df003b00-7cf8-11eb-8229-cb6a461dc050.png)

**Comment by szaimen** [comment]
Since this is a javascript error, I don't think that it is related. But I could be wrong.

**Comment by SigLinJo** [comment]
I can confirm that most things seem to work in NC 21 but the persons tab in the details side-bar is not there anymore. Was present in NC 20.

**Comment by matiasdelellis** [comment]
> I can confirm that most things seem to work in NC 21 but the persons tab in the details side-bar is not there anymore. Was present in NC 20.

D'OH!.
We must fix it.  :disappointed:

Thanks for following this ..

**Comment by matiasdelellis** [comment]
Hi all,
Thank to @szaimen, we enable NC21 in master, with the corresponding tests. These tests only represent the "core", which is already very important, but the fronted must be fixed separately.. 

I will not install NC21 on my main server yet, but I am going to see how to investigate the side panel error. Maybe with the virtual machine I can do something.

Thank you all for your patience and reports.. :smiley:

**Comment by szaimen** [comment]
> Maybe with the virtual machine I can do something.

If you need an advice, [this](https://cloud.kafit.se/s/7qzap5RL6EF3RyZ?path=%2F21.0.0%20-%20HUB) is probably the fastest way to get a NC21 VM up and running.

Herr is some documentation on this: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions

**Comment by matiasdelellis** [comment]
Ok Ok..
Our Nextcloud friends did it again. :disappointed: :cry: :sob: 
They changed the way to register the tabs, and again it is not compatible with the previous version. Nor did they leave any kind of compatibility. :disappointed: 

See: 
https://github.com/nextcloud/spreed/pull/4291

The change seems to be relatively simple, but I cannot maintain compatibility even with NC20. And let me tell you that between NC13 and NC 17, I could keep a single release for all those versions!. So please understand my frustration about it! :angry: :disappointed: :disappointed: :sob:

**Comment by szaimen** [comment]
What I wonder is how the metadata app is able to be compatible with so many NC versions although it must have faced the same problems when registerung the tab, as far as I understand it. 🤔
https://github.com/gino0631/nextcloud-metadata

**Comment by SigLinJo** [comment]
Thank you for the effort you put in! I really appreciate face recognition in Nextcloud and it has made me rediscover a lot of pictures and memories from more than 15 years of photography. One of the best things with migrating to a more powerful home server was being able to install this! Keep up the good work!

**Comment by szaimen** [comment]
I can only second what @SigLinJo said. 👍
And it is because of that one of the best Nextcloud apps, IMHO.

**Comment by matiasdelellis** [comment]
> Unfortunate to hear that they've made it that hard for app developers to be compatible with more than the latest NC release slightly_frowning_face
> 
> Though, I wonder how the metadata app is able to be compatible with so many NC versions although it must have faced the same problems when registerung the tab, as far as I understand it. thinking
> https://github.com/gino0631/nextcloud-metadata
> 
> Edit: Maybe the app can be of some help to figure some things out? :)

This application uses a "compatibility" option (OK, I have to admit that they did something about it. haha) but note that this only shows the tab in the files application. From NC17 with the new photos application, we have to use VUE to show there.. :disappointed:

**Comment by matiasdelellis** [comment]
There is progress on this... :grimacing: 
![imagen](https://user-images.githubusercontent.com/733715/111462696-7ef89400-86fd-11eb-942a-83447a73ea7b.png)

**Comment by Insomniacnomis** [comment]
> > Unfortunate to hear that they've made it that hard for app developers to be compatible with more than the latest NC release slightly_frowning_face
> > Though, I wonder how the metadata app is able to be compatible with so many NC versions although it must have faced the same problems when registerung the tab, as far as I understand it. thinking
> > https://github.com/gino0631/nextcloud-metadata
> > Edit: Maybe the app can be of some help to figure some things out? :)
> 
> This application uses a "compatibility" option (OK, I have to admit that they did something about it. haha) but note that this only shows the tab in the files application. From NC17 with the new photos application, we have to use VUE to show there.. 😞

Maybe use the Checksum App as reference? It has a sidebar for the photos app also, and it uses VUE. I checked what has changed because it has both versions available (20 or lower, and 21), and are some small changes. But I'm a noob, so you never know

**Comment by matiasdelellis** [comment]
> Maybe use the Checksum App as reference? It has a sidebar for the photos app also, and it uses VUE. I checked what has changed because it has both versions available (20 or lower, and 21), and are some small changes. But I'm a noob, so you never know

Ohh.. I did not test this application for a long time, and I did not know that they had migrated to vue and it worked :smile: 
A little hack (Same as [this](https://github.com/matiasdelellis/facerecognition/pull/344) for php on NC20), but it can be made compatible.. :sweat_smile: 

Thanks you!.
However, discouraged I already migrated the server to NC21, and now i can't ensure nc20 compatibility. :sweat:
So, today I upload a version compatible only with nc21 :wink:

**Comment by Derkades** [comment]
Old Nextcloud versions aren't supported for that long so compatibility is not that big of a deal, especially because this facial recognition app is targeted towards home users who are probably all on 21 in a couple months anyway. (my opinion as a lazy developer)

**Comment by matiasdelellis** [comment]
> Old Nextcloud versions aren't supported for that long so compatibility

Officially nc19 is still supported, and although it is true that the cycles are short, that is not a problem, they simply should not introduce so many incompatibilities between versions.
At least they should introduce LTS versions, where they ensure support and guaranteed compatibility!. 

> specially because this facial recognition app is targeted towards home users.

But it is a clear mistake of users to update so soon..
![imagen](https://user-images.githubusercontent.com/733715/111486855-9b54fa80-8716-11eb-9fbb-2ee06a4ec4ab.png)
..and if you open the browser inspector console, you will also see many errors! :disappointed: 

But enough catharsis for today. :sweat_smile: 

Here is a test version, which only supports NC21 and finally introduces the unified search. :wink: :stuck_out_tongue_winking_eye: 

https://services.delellis.com.ar/data/facerecognition/facerecognition.tar.gz

Please, test. just replace them in the apps/facerecognition folder with this.

**Comment by Derkades** [comment]
Sidebar works after uploading the zip and running `occ app:update facerecognition`

**Comment by markuman** [comment]
> But it is a clear mistake of users to update so soon..

but but but ... all the other features you're losing when you're not updating :)  
I guess many updated soon because of the performance update in this case.  NC21 feels a lot of faster as NC20.

**Comment by matiasdelellis** [comment]
> but but but ... all the other features you're losing when you're not updating :)
> I guess many updated soon because of the performance update in this case. NC21 feels a lot of faster as NC20.

Well, "a lot of faster as NC20.", does not mean faster than NC19. They just fixed the problems introduced in NC20. :sweat_smile:

Going back to the important thing, finally publish the update: :grimacing: 
 * https://apps.nextcloud.com/apps/facerecognition
 * https://github.com/matiasdelellis/facerecognition/releases/tag/v0.8.0

Thank you very much for the reports, contributions and words of encouragement!. :smile: 

Regards,
Matias

**Comment by szaimen** [comment]
@matiasdelellis Thank you for the new release! Because of that I was finally able to finish https://github.com/nextcloud/vm/pull/1871 😊

**Comment by Zocker1304** [comment]
> I've moved from NC 20 php 7.4 to NC21 php 8.0 and it seems there is an issue with the temporary path.
> 
> ```
> Faces found: 0. Image will be skipped because of the following error: Error during image resize
> ```
> 
> any ideas? @matiasdelellis

Is there any way to get face recognition working with php8, or is there an update coming? I am just asking so that I know if it is worth waiting for a fix or that I should just downgrade php.

**Comment by matiasdelellis** [comment]
Hi @Zocker1304 
Unfortunately I still couldn't test php8. About our code, according to the php lintian (See https://github.com/matiasdelellis/facerecognition/runs/2175793217), it seems to be compatible with php 8.0, but there are nextcloud apis that still don't work with php 8.0.

Specifically, there are tests that fail in php 8.0, but they preferred to just ignore them rather than fix the problems. 
See: https://github.com/nextcloud/server/commit/d690f909284ae4bb4dee7d00318104ee76720bfa#diff-59830ebc3a4184110566bf1a290d08473dfdcbd492ce498b14cd1a5e2fa2e441

Our application makes intensive use of the OC\Image class, and as you can see it fails with php 8. :disappointed: 
I have to do more research, but with that, I understand that it is a Nextcloud regression.

On the other hand, I will insist on something.

> About php 8.0, NC21 is the first version to support it, but they still recommend php 7.4. https://docs.nextcloud.com/server/21/admin_manual/installation/system_requirements.html#server, So, please, downgrade it.. see_no_evil

Sorry, I know it is not a very happy answer, but at least in that, they were reasonable, and ignoring the fabulous announcement they made, in the documentation do not recommend it.

**Comment by joao-p-marques** [comment]
Hi, I think this is still not working perfectly, as I commented in https://github.com/matiasdelellis/facerecognition/issues/166#issuecomment-813014769
Can this be reopened to track those problems?

**Comment by matiasdelellis** [comment]
@joao-p-marques 
You don't reopen it, but open a new one and refer to them. Thanks..
