### ISSUE TITLE
 Module 'pdlib' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by dbaldoni** [matiasdelellis/facerecognition#430]
I installed dlib and pdlib following the tutorial: app is installed but can't be enabled.

Error reported: 
The library pdlib is not available.
face detect test is ok

`caravaggio@terraveler:~/pdlib-min-test-suite$` php scripts/face_detect.php
PHP Warning:  Module 'pdlib' already loaded in Unknown on line 0
Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg
Number of faces detected: 3
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Processing file: input/Big Bang Theory.png
Number of faces detected: 7
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
`
`caravaggio@terraveler:~/pdlib-min-test-suite$ php -m | grep pdlib
PHP Warning:  Module 'pdlib' already loaded in Unknown on line 0
pdlib
`

Server configuration

ubuntu 20.04:**

Pdlib version:**

PHP version: 7.4

Web server: apache

Database: mariadb

Nextcloud version: 20.0.7

**Comment by matiasdelellis** [comment]
Hi @dbaldoni 
Surely you have two files enabling the extension pdlib. Just check /etc/php.d/*.ini and make sure there is only one file referred to pdlib
