### ISSUE TITLE
CSRF check failed when trying to access '/facerecognition/persons' API 

### ISSUE THREAD

**Issue by nikhilsjohn** [matiasdelellis/facerecognition#433]
Hi,

I am new to using nextcloud and the face recognition app. In my instance, the face detection works as expected and is detecting faces correctly. This data is displayed when I go to user > setting > Face Recognition. This part is all good.

However when I try to access the REST API via curl to obtain the result as a json, it is showing me the following error : "message : CSRF check failed"

My Curl command: **curl --silent -u username:password -X GET 'http://192.168.1.44/index.php/apps/facerecognition/persons'**

I use Nextcloud version 20.0.7 via docker on my PC.

Is there a configuration or header that I missed? Thank you very much for your time.

### Expected behaviour

A json responds as described here: https://github.com/matiasdelellis/facerecognition/wiki/RESTful---Endpoint---API

### Actual behaviour

"message : CSRF check failed"

### Server configuration

* **Operating system:** Official Nextcloud image + Added Pdlib, Dlib

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
Compiled

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
Compiled

* **PHP version:** 

* **Web server:** Apache

* **Database:** mariadb (also via docker)

* **Nextcloud version:** 20.0.7

### Client configuration

* **Browser:** Terminal

* **Operating system:** Ubuntu 18

**Comment by matiasdelellis** [comment]
Hi @nikhilsjohn 
This documentation is out of date. Change completely, and security was improved by preventing its use with CURL.. 

Now we have to make an official API out of the application endpoints. :disappointed:

**Comment by nikhilsjohn** [comment]
Hi @matiasdelellis 

Thank you for the reply. If needed, I will be able to help you with it when I get some time.
