### ISSUE TITLE
background_job ignores .noimage

### ISSUE THREAD

**Issue by FlattusBlastus** [matiasdelellis/facerecognition#446]
Whatever folder you place a .noimage file in, that folder should be skipped by the backup_job. Instead, .noimage files placed in any folder are not respected.

Repro
1. Create Samba share of 2nd local disk
2. Add local disk as "local external storage" to nextcloud
3. Create a powershell script to write .noimage in every folder of my share except the folder with the family pics in it.

Running Ubuntu Server Focal, installed Pdlib using the easy way, php7.4-fpm, Apache, MariaDB, NC21

Clients are Win10 using IE, Chrome, and Edge. I'll be back with some logs later...

**Comment by matiasdelellis** [comment]
Hi @FlattusBlastus
The .nomedia file is respected, because we consider it more "standard". however, I think we offer a better alternative. Just open the side panel of the files app, and you can ignore all the folders you think necessary.

**Comment by matiasdelellis** [comment]
Fixed on #463 

Thanks
