### ISSUE TITLE
Dockerfile no-debug-non-zts-20180731/pdlib.so not found

### ISSUE THREAD

**Issue by Joshua2504** [matiasdelellis/facerecognition#449]
Hello,

please verify the Dockerfile for nextcloud:apache2.

Step 16/21 : COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20180731/pdlib.so /usr/local/lib/php/extensions/no-debug-non-zts-20180731/
ERROR: Service 'app' failed to build: COPY failed: stat usr/local/lib/php/extensions/no-debug-non-zts-20180731/pdlib.so: file does not exist

 I can confirm that the file isn't present in the repository.

**Comment by crenz** [comment]
Hi @Joshua2504, try using **no-debug-non-zts-2019902** instead.

**Comment by matiasdelellis** [comment]
Hi @Joshua2504 
According to our little introduction about docker:

> # If is necesary take the php extention folder uncommenting the next line
> # RUN php -i | grep extension_dir

This results in the line that @crenz tells you, and you must use that, or the folder that returns in your case.

In any case, I recommend using dockers prepared specifically for the application as https://hub.docker.com/r/iamklaus/nextcloud
Use docker from Use @iamklaus https://hub.docker.com/r/iamklaus/nextcloud
