### ISSUE TITLE
Enhancement: Persons list

### ISSUE THREAD

**Issue by mrekin** [matiasdelellis/facerecognition#451]
HI!
Thanks for nice app. It was not easy, but Installed with docker.

Is it possible to implement
1. Link NC user to person (Automatic or manual).
I have photo in account settings - can it be recognized ?
2. Offer a list persons name in recognition page. Now I need to enter it manual a lot of times

Thanks a lot.

* **Pdlib version:**
1.02

* **Nextcloud version:**
21.0
### Client configuration

* **Browser:**
Vivaldi
* **Operating system:**
Win10

**Comment by matiasdelellis** [comment]
Hi @mrekin

Thanks for taking the job of writing here, but both reports already have their own tiket.. :sweat_smile: 

> Link NC user to person (Automatic or manual).

Dup of #8 

> I have photo in account settings - can it be recognized ?

No.. We cannot simply trust the avatar because many times users do not put personal photos. :disappointed: 

> Offer a list persons name in recognition page. Now I need to enter it manual a lot of times

Dup of #306 


Thanks again,
Regards,
Matias
