### ISSUE TITLE
Individual change of recognized person affects whole group

### ISSUE THREAD

**Issue by vesperkasper** [matiasdelellis/facerecognition#453]
While trying to sort out faulty recognitions by changing the person on the details tab of the individual picture the whole group of pictures gets changed. With this two groups are merged ending up in a mix group of two people that can not be seperated anymore.

### Expected behaviour

If you change a name of a recognized person in the details of an individual picture only this specific picture should be regrouped to the correct person.

### Actual behaviour

Instead of the above the whole group that the individual picture belongs to is regrouped to the other new ending up with a merge of two people or groups

### Steps to reproduce
1. In the face recognition select a picture for to view - it opens in the respective directory with a preview in the details
2. From the details choose the "Person" tab - the recognized person and the name1 will be shown
3. Press the pencil to rename the person to an other existing person - the name1 will be changed to name2
4. going back to the overview you will find all pictures belonging to the group of name1 merged with the group of name2

--- only the individual picture with renamed to name2 should be added to the group of name2 - not the whole group of pictures

### Server configuration

* **Operating system:**
 Centos8

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
* checked ok.

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
* checked ok.

* **PHP version:**
* PHP Version => 7.4.13

* **Web server:**
* apache

* **Database:**
* mariadb

* **Nextcloud version:**
* Nextcloud 20.0.2

### Client configuration

* **Browser:**
* edge

* **Operating system:**
* windows10

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi @vesperkasper 
Go to the large group of the mixed person, and click on "Show all groups with the same name" button. There you can correct those kinds of errors. :wink:

**Comment by vesperkasper** [comment]
Hi @matiasdelellis,

I did not expect an answer that fast. Thank you. And yes, this is what I have tried. I can see different groups with the same name by the method you mentioned but one of these groups consists of ~ 400 Pictures with at least 3 Persons (Son, daughter and a friend of the son)
Let's get back in time for a second because it was not like this in the beginning. Having some thousand pictures processed the groups of sun and daughter were clearly seperated. Then I have overseen in one group that ther was a picture of my daughter  mixed in pictures of my son. I named this group son. Later i recognized  that mistake and renamed the individual picture in the details of that file on the persons tap. I guess this is where the trouble started. All pictures named daughter were mereged to son. After a while I noticed that the group was growing an other persons were added. 
So the Question remains.
 How to remove or rename an individual 
picture from a group?

Thanks Martin

**Comment by matiasdelellis** [comment]
Hi @vesperkasper 

Everything you see in those groups is an automatic task and depends specifically on the models used. So, If there are persons mixed in the same group, it is the responsibility of the model, not because you have mixed them.

Beyond renaming an entire group believing that you were only renaming the face of that photo, today is the expected behavior. I'm not saying it's okay, I'm saying that today we choose to trust the automatic models.

Unfortunately, what you need is a "This person is not 'Son'" option, which is not yet implemented. This request is covered by issue #158 that I hope to improve soon.

Meanwhile, you can try reducing the "Clustering threshold" (Aka Sensitivity) parameter, and the algorithm will be a bit more stricter to clustering the persons.

**Comment by vesperkasper** [comment]
Thanks again @matiasdelellis 

dealing with my question, and much more on providing this easy access for face recognition in nextcloud. I read alot about it but now its getting to life with a practical approach. 
Yes I started to play with the cluster threshold, and it is getting better. The model clusters quite good for adults and ages down to 8-9 years, but below it is messing around. It seems as if the lower the age the more the model destinguishes between adult and child instead of the specific face or person.
Somewhere I read that the model is not trained on children, that would explain it.
Thanks for linking to #158 I think that would be the solution also for this thread.

**Comment by matiasdelellis** [comment]
OK.. We hope to improve everything soon ..

Thanks to you.. 
:smile:
