### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by niladrishekhar** [matiasdelellis/facerecognition#454]
Hi When I am trying to manually install - I am getting an error - 
1299 error   File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 33, in <module>
1299 error     sys.exit(load_entry_point('gyp==0.1', 'console_scripts', 'gyp')())
1299 error   File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 22, in importlib_load_entry_point
1299 error     for entry_point in distribution(dist_name).entry_points
1299 error   File "/usr/local/lib/python3.9/importlib/metadata.py", line 524, in distribution
1299 error     return Distribution.from_name(distribution_name)
1299 error   File "/usr/local/lib/python3.9/importlib/metadata.py", line 187, in from_name
1299 error     raise PackageNotFoundError(name)

I went back a few steps to see if the DLib and PDLib have been installed correctly with the testing modules - 
php scripts/face_detect.php ran perfectly fine
python3 scripts/face_detect.py gave me an error "it seems you don't have python binding installed"
While installing I passed the test with 
python scripts/face_detect.py

Do you think the issue could be with the bindings ? I am attaching the debug log for your reference. In case if I need a binding what binding should I provide ?

Next Cloud Version Nextcloud 21.0.0
Python 3.9.2
npm 7.5.2

file:///root/Downloads/2021-04-06T12_27_59_089Z-debug.log

**Comment by matiasdelellis** [comment]
Hi @niladrishekhar 
This error does not seem to have anything to do with our application. If you do not explain better what you are doing, we will not be able to help you. :thinking:
