### ISSUE TITLE
"Backport" to NC 20 ?

### ISSUE THREAD

**Issue by ccharlot** [matiasdelellis/facerecognition#455]
Hi !

Version 8.x of the app are not available to download/update from within NC 20.

Any chance these latest versions could be set as compatible with older versions of Nextcloud ? (if they actually are compatible)

Thanks in advance :)

**Comment by matiasdelellis** [comment]
Hi @ccharlot
Unfortunately I can't do it myself..
There were some incompatible changes in NC21, which made it impossible to have a compatible release between both versions.. :disappointed: 

A backport can probably be done, but this forced me to upgrade my servers to NC21, and I have no NC20 instance to test. :disappointed_relieved: 

See https://github.com/matiasdelellis/facerecognition/issues/429 for context.

**Comment by matiasdelellis** [comment]
Sorry, but I won't be able to do this. We hope to maintain better compatibility for the next version. :disappointed:
