### ISSUE TITLE
PHP 8 support of php extension

### ISSUE THREAD

**Issue by BigMichi1** [matiasdelellis/facerecognition#456]
### Expected behaviour

the php extension that is needed should also be available for PHP 8

### Actual behaviour

we are using https://launchpad.net/~ondrej/+archive/ubuntu/php to have a recent up-to-date version of PHP but currently the pdlib extension is not available for PHP 8

### Steps to reproduce
1. use php-8 to serve nextcloud
2. pdlib extension is not available

### Server configuration

* **Operating system:**
Ubuntu 20.04.2 LTS

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**
8.0.3-1.ubuntu20.04.1+deb.sury.org+1

* **Web server:**
Nginx

* **Database:**
PostgreSql

* **Nextcloud version:**
21.0.1

**Comment by matiasdelellis** [comment]
Hi @BigMichi1 

pdlib supports php 8 since [1.0.1](https://github.com/goodspb/pdlib/releases/tag/1.0.1), but you have to compile it on your own, because I can't make packages for custom repositories.

However, I clarify that it is not yet officially supported by the application. Most likely it will work, but it is not supported yet. See #444

**Comment by hunterzero99** [comment]
I'd like to expand this bug report to include errors that seem to be associated with php8.  I get the following when trying to run the scan:

`Faces found: 0. Image will be skipped because of the following error: Error during image resize
`

I see mention of this in other bug reports that have been closed out (#429 for example).

Is there any way I can get more debug logging out of the run to see where in the resize process things fail?

**Comment by gchmurka123** [comment]
I have the same problem, I am unable to debug why I have the same error:
`         Faces found: 0. Image will be skipped because of the following error: Error during image resize `

**Comment by Kitt3120** [comment]
Same problem. Using dlib-cuda 19.22-1 and php-pdlib 1.0.2-4 for the AUR.

```
Processing image /mnt/Media3/NextcloudData/username/files/Kamera Upload/Pixel 3 XL/2021/08/PXL_20210810_121912205.MP.jpg
        Faces found: 0. Image will be skipped because of the following error: Error during image resize
        RuntimeException: Error during image resize in /var/lib/nextcloud/apps/facerecognition/lib/Helper/TempImage.php:153
Stack trace:
#0 /var/lib/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(125): OCA\FaceRecognition\Helper\TempImage->resizeImage()
#1 /var/lib/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#2 /var/lib/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct()
#3 /var/lib/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage()
#4 /var/lib/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute()
#5 /var/lib/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#6 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#7 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#11 /usr/share/webapps/nextcloud/console.php(99): OC\Console\Application->run()
#12 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
#13 {main}
yielding

```

**Comment by matiasdelellis** [comment]
Need help..
https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/legacy/OC_Image.php#L918-L944

You have to see more info in the nextcloud logger. Please comment what it says ..

**Comment by matiasdelellis** [comment]
Hi everyone,
Just comment that thanks to the investigation of @guystreeter in the next version of Nextcloud we will have support for php8 in this application. 

Thanks you so much!! 😃 🎉

**Comment by Kitt3120** [comment]
Nice! Have been waiting for this since php8 came out. Tried the Face Recognition app occasionally to check if it has been fixed, but eventually just found this GitHub issue and watched it. Looking forward to it, thanks to all people involved :)

**Comment by guystreeter** [comment]
The necessary fixes have been pulled in the master on github today.
https://github.com/nextcloud/server/pull/29479

**Comment by martadinata666** [comment]
rebuild my php-fpm to experiment this, but seems another wait for nextcloud release update, is the zip [release](https://download.nextcloud.com/server/releases/) latest, will do?

**Comment by guystreeter** [comment]
I was mistaken. Only part of the patch-set was pulled in the master branch. It does not include the fixes we need. :(

**Comment by FernandoMarques-Santos** [comment]
> Hi everyone, Just comment that thanks to the investigation of @guystreeter in the next version of Nextcloud we will have support for php8 in this application.
> 
> Thanks you so much!! 😃 🎉

Thank you Matias and all! After the nextcloud update, the icing on the cake would be an update to the [precompiled](https://github.com/matiasdelellis/facerecognition/wiki/Installation) PDLib PHP libraries for PHP 8.

**Comment by EWouters** [comment]
The Nextcloud update is now live! (https://github.com/nextcloud/server/pull/29519)

**Comment by martadinata666** [comment]
Is this compatible after all with nextcloud 22? i got this error on enabling, #https://github.com/matiasdelellis/facerecognition/issues/500#issuecomment-913228610

**Comment by jakobroehrl** [comment]
Can't activate the app with PHP8 an NC 22.2.2. or NC 23 RC2:
![image](https://user-images.githubusercontent.com/24530680/141683154-4a504548-55ec-4bf7-ae0a-dca9cadfe916.png)

![image](https://user-images.githubusercontent.com/24530680/141683170-7d129a2b-651d-47f2-9703-3b3a5072f40d.png)

**Comment by EWouters** [comment]
> Can't activate the app with PHP8 an NC 22.2.2. or NC 23 RC2

This is off-topic, but you need to follow [Hard way](https://github.com/matiasdelellis/facerecognition/wiki/Installation#hard-way).

**Comment by Kitt3120** [comment]
Can confirm that it works!

**Comment by matiasdelellis** [comment]
Hi everyone,
Please, wait for Nextcloud 22.2.2 (NOT 22.2.1... see https://github.com/nextcloud/server/issues/29678 and https://help.nextcloud.com/t/nc-22-2-1-performance-warning/127169/1), and should test against Facerecognition from git master ...

**Comment by guystreeter** [comment]
I pulled NC 22.2.2 and built facerecognition from git master, and it seems to be working just fine!

**Comment by jandr** [comment]
This works fine also in NC 22.2.3 by installing manually facerecognition from git.  Hopefully the app from the NC repository will be updated soon to not necessarily require PHP <= 7.4, and will support PHP 8 as well!

**Comment by matiasdelellis** [comment]
Great. Thank you all very much!. 🎉  😄 
Probably tomorrow I will upload an update enabling php 8.. 😬

**Comment by matiasdelellis** [comment]
Just published on Nextcloud appstrore.. 😄 🎉 

Please update from there and report back here.. 😉

**Comment by FernandoMarques-Santos** [comment]
Ubuntu 20.04, Nextcloud 22.2.3, PHP8.0, I had compiled pdlib to support PHP 8. Today installed the Facerecognition 0.8.5 directly from gitmaster and I confirm that everything is working well. You guys made an excellent job.

However, I got a bit confused by this thread. Are we still needing to compile the pdlib part (see the OP problem)? Or with this facerecognition 0.8.5 (from the app store) we don't need to do that anymore? Sorry I don't see how the update relates to the original problem.

Marginally related to this, are you guys using some of the apps for android? nkming version can show the faces *when* the facerecognition is pulled directly from the master. It is working pretty well.... butI just wished to not having to compile anything =)

**Comment by guystreeter** [comment]
I modified by build to pull the latest Nextcloud docker image and only build dlib and pdlib. Then I downloaded and enabled facerecognition from the app store. Everything seems to be working fine.

**Comment by matiasdelellis** [comment]
Hi @FernandoMarques-Santos 

The issue started as a problem that there was no pdlib for php8, but it mutated to the application support for php8 since that was the real problem.

Now Nextcloud added the necessary patches that make this application work with PHP8 and then we enable their support in last release. 😉 

About pdlib, except Ubuntu Impish and Fedora 35 no distribution uses php 8 by default. This implies that practically everyone is using third-party repositories to update php, and is simply impossible for me to generate the necessary packages for third party repositories.

So, unfortunately, if you use third-party repositories, you have to compile pdlib on your own.

**Comment by matiasdelellis** [comment]
Just update package for fedora 35 with php8.. 
* https://copr.fedorainfracloud.org/coprs/matias/dlib/

Tomorrow I will probably do the package for Ubuntu Impish.. :wink:

**Comment by Ornias1993** [comment]
> So, unfortunately, if you use third-party repositories, you have to compile pdlib on your own.

Calling the official Nextcloud Docker images out for using "third-party repositories" is pretty weird imho
