### ISSUE TITLE
An unhandled exception has been thrown

### ISSUE THREAD

**Issue by Rothammel** [matiasdelellis/facerecognition#458]
Hy, I have a folder with broken jpg files, they are only 28bytes.

`Faces found: 0
        Processing image /mnt/hdd/ncdata/admin/files/backup/Franzis Stick/Bilder/Urlaub/Urlaub 2019/20190422_142231.jpg
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/nextcloud/lib/private/Files/Filesystem.php:716
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/OC_Image.php(645): OC\Files\Filesystem::file_get_contents()
#1 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(112): OC_Image->loadFromFile()
#2 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#3 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct()
#4 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage()
#5 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(136): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute()
#6 /var/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(148): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#11 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')`

**Comment by matiasdelellis** [comment]
Hi @Rothammel 
Dup of #295
I hope to fix it soon.

Thanks..
