### ISSUE TITLE
Feature Request: Suggest auto complete names

### ISSUE THREAD

**Issue by MetallicAchu** [matiasdelellis/facerecognition#459]
First, let me thank you so much for this application, it's amazing!

When naming a person, is it possible to have the system auto complete based on current names / contacts?
For example if I have John, Dave, Martha, and I start typing J in a new face, I would like the system to suggest John to me.

Thanks!

**Comment by matiasdelellis** [comment]
Hi @MetallicAchu 
This was a duplicate report of #306 and now it's fixed with #461 for next release :smile:
