### ISSUE TITLE
Different/Alternative ml architecture

### ISSUE THREAD

**Issue by marcelklehr** [matiasdelellis/facerecognition#464]
Hi there,

facerecognition is a really cool feature to have. I've been looking into how to do ML in PHP for some time and have come up with a somewhat hacky, but rather portable way to run neural networks: 

https://github.com/marcelklehr/recognize ships with a node.js binary and runs tensorflow models with tfjs in a separate spawned node.js process. The beauty of this approach is that it requires zero setup on the part of the admin.

I've also discovered a nice node.js library for doing facerecognition: https://github.com/marcelklehr/recognize/issues/7

What do you think about switching to a node.js based ML backend?

**Comment by matiasdelellis** [comment]
Hi @marcelklehr 
Congratulations on the application, I'm going to test it .. 😄 
I had planned to do something similar using our infrastructure with the resnet34_1000_imagenet_classifier model. 😅 

> https://github.com/marcelklehr/recognize ships with a node.js binary and runs tensorflow models with tfjs in a separate spawned node.js process.

Your application is probably much larger than this one, the mere fact of adding the node binary, must add 100mb, and you must also add the models. I'm sure this causes more frustration for users when they can't download a 100 MB application. 😞 

> The beauty of this approach is that it requires zero setup on the part of the admin.

I can accept this point, but it is still a design decision. The only important setting is the image size (Do you want quality? Enlarge the images and it will be slow, do you want to be fast? Shrink the image and you will have half the faces). The rest of the settings 90% of people shouldn't even think about it, but there are 10% who probably need it.
These are problems that you will encounter if you want to add this feature. The same with the size of the application, they are things that we already live. 😅 

I think nobody is scared of our application. Once you install pdib, the rest is very well documented.

> I've also discovered a nice node.js library for doing facerecognition: marcelklehr/recognize#7

* https://github.com/justadudewhohacks/face-api.js#face-recognition-model

As you can see, your proposed library uses the same neural network as us, therefore I am more than happy with our choice.

* https://github.com/justadudewhohacks/face-api.js#face-detection-models

However, the face detector is different, and of course I am predisposed to evaluate them. To do this, the best you can do is modify the external model, using these libraries. See:
* https://github.com/matiasdelellis/facerecognition-external-model
* https://github.com/matiasdelellis/facerecognition/releases/tag/v0.7.2

> What do you think about switching to a node.js based ML backend?

Convince me that Mobilenet or any other offers us better results, and I can evaluate it

**Comment by marcelklehr** [comment]
Thank you for your detailed answer. :heart: 

> I think nobody is scared of our application. Once you install pdib, the rest is very well documented.
> [...] Convince me that Mobilenet or any other offers us better results, and I can evaluate it

My main goal with this proposal was making things easier. I see that you are convinced things are already easy. I tend to disagree, but I don't think I will be able to convince you otherwise.

Cheers!
