### ISSUE TITLE
Can't set up in NC 21

### ISSUE THREAD

**Issue by joao-p-marques** [matiasdelellis/facerecognition#465]
### Expected behaviour

After the basic install (all the dependencies and the app itself), I should be able to access the admin interface and tweak the correct settings to run the app correctly and start the recognition process.

### Actual behaviour

When I try to run the initial photo scan, I get an error saying that some parameters are not set, like the temporary files image size. AFAICS the only way of setting those is through the admin UI, but when I access it I can't change those values or do anything else:

![image](https://user-images.githubusercontent.com/38977934/116587181-24647180-a912-11eb-9bd0-f386c5faddfb.png)

### Server configuration

* Docker image from https://hub.docker.com/layers/144177690/jotamarques/docker-nextcloud/21-fpm/images/sha256-d1f2953c17fdc48651e95998c3bb671cc11b03261aaa1851cea546d9454491b3?context=explore

* **Database:** Postgres 

* **Nextcloud version:** 21

### Client configuration

* **Browser:** Firefox and Chromium

* **Operating system:** Fedora 33

**Comment by narcotico-g** [comment]
I am installing/testing this app too and it get the same issue.

I could solve it assigning model with "su - www-data -s /bin/bash -c "occ face:setup -m 1" for model 1 (min. 1 Gb php memory limit for this model).

**Comment by matiasdelellis** [comment]
Hi @joao-p-marques 
Thanks for creating the ticket.  😄 
Something fundamental to see and that you did not share, are the nextcloud and browser logs.
Also, it would be important to see you api responses: ie:

![imagen](https://user-images.githubusercontent.com/733715/116609126-65588800-a90a-11eb-867f-dfcc1dc5f498.png)

**Comment by matiasdelellis** [comment]
Close since dont share the corresponding logs.

**Comment by joao-p-marques** [comment]
Sorry for not providing them, I ended up uninstalling the app in the 
meantime and never had the chance/time to try it again... Maybe someone 
else can provide them if they run into the same issue and reopen 
this... Thanks for the work! 👍
