### ISSUE TITLE
A way to remove similar person from group

### ISSUE THREAD

**Issue by b10102016** [matiasdelellis/facerecognition#466]
Hi,
Thanks for your great work.
All things work fine, but there's a small question.
Is there a way to remove a picture of similar person from group?

BTW,

Maybe can add a new feature to do recognition again in the group with similar person and adjust the threshold and sensitivity for it?

Sincerely,
Ian

**Comment by matiasdelellis** [comment]
Hi @b10102016 
Dup of #158 
I hope to give news soon. Thanks.. 😉
