### ISSUE TITLE
NC21 missing button in file app.

### ISSUE THREAD

**Issue by storm1er** [matiasdelellis/facerecognition#469]
### Expected behaviour

As the doc says: 
> In the side panel of the file application, a 'Persons' tab is added where you can see a list of your friends in the photo, and rename them.

### Actual behaviour

No button in file app, as shown:
![image](https://user-images.githubusercontent.com/9821946/117327772-44a4ab00-ae93-11eb-9841-88c8c7ba82c8.png)

### Steps to reproduce
1. Install app from store
2. Follow the install / first scan instructions
3. Go to file app

### Server configuration

* **Operating system:** Debian 10

* **Pdlib version:** 1.0.2

* **How is DLib installed:** Using docker build, tested and working

* **How is PDlib installed:** Using docker build, tested and working

* **PHP version:** 7.4.18

* **Web server:** Not relevent

* **Database:** MariaDb

* **Nextcloud version:** 21

### Client configuration

* **Browser:** Chrome 89

* **Operating system:** Win10

#### Background task log with debug.
Not relevant, everything else is working fine.

#### Web server error log
Not relevant, everything else is working fine.

#### Nextcloud log (data/nextcloud.log)
Not relevant, everything else is working fine.

#### Browser log
Nothing relevant, I think
<details>
<summary>Browser log</summary>

![image](https://user-images.githubusercontent.com/9821946/117329394-e678c780-ae94-11eb-92af-af4e59da743a.png)
</details>

**Comment by matiasdelellis** [comment]
Hi @storm1er 
This refers to the right panel. Look at the screenshots.. 😉
