### ISSUE TITLE
Error while deleting from other app.

### ISSUE THREAD

**Issue by storm1er** [matiasdelellis/facerecognition#471]
### Expected behaviour

All deletion should happen correctly

### Actual behaviour

Deleting files with faces from the duplicate finder app gives this error:

```
Argument 1 passed to OCA\FaceRecognition\Db\PersonMapper::removeIfEmpty() must be of the type int, string given, called in /var/www/html/custom_apps/facerecognition/lib/Hooks/FileHooks.php on line 297
```

### Steps to reproduce
1. Install and use facerecognition app
2. Install and use duplicatefinder app
3. Remove a duplicate photo with face from duplicate finder app

### Server configuration

* **Nextcloud version:** 21

**Comment by matiasdelellis** [comment]
Hi @storm1er 

It's strange.. 🤔 
It may be that you're using PHP 8?

**Comment by storm1er** [comment]
Nope, php 7.4.18

Just realized I have the same problem by deleting any photo with a face from the file explorer, so no third app concerned.

**Comment by matiasdelellis** [comment]
Hi @storm1er,
You're right. I was able to reproduce the error easily. 😞 

I hope to give news soon.
Thanks

**Comment by matiasdelellis** [comment]
Must be fixed on last release.. Please, test.. 😬

**Comment by storm1er** [comment]
Fixed :D
