### ISSUE TITLE
Feature Request - Split groups / Select specific faces within groups

### ISSUE THREAD

**Issue by kbftech** [matiasdelellis/facerecognition#476]
Current workflow:
1. Face detection / recognition
2. Grouping
3. Present group of similar faces
    ---> End user is asked to "Rename Group" (Person)

Desired workflow:
1. Same
2. Same
3. Present groups of similar faces
    ----> End user is asked to confirm that all pictures are from the same person
         ----> End user can "click" each face to toggle between "selected" and "unselected"
    ----> "Renaming group" remains the same, except that unselected faces are thrown back in the "unrecognized" pile.

Linked to issue #477

**Comment by matiasdelellis** [comment]
Hi @kbftech 
Thanks for taking the trouble to report it, but it is still unlikely to implement in the short term, since we are focused on 100% automatic clustering..

Likewise, it is a step that we hope to take at some point.. :wink:

Meanwhile, I recommend you to use model 4, and if you still have mixed people, reduce the value theshlod..

Dup of #158

**Comment by kbftech** [comment]
Sorry for the duplicate. I used model #4. I don't think the algorithm will ever be able to accurately tell apart everyone, regardles of the level of confidence (twins or young kids for instance). I strongly believe this feature is a requirement, although I fully understand that focus can't be sustained on everything at once.

Thanks for getting back to me!

**Comment by matiasdelellis** [comment]
>  I don't think the algorithm will ever be able to accurately tell apart everyone, regardles of the level of confidence (twins or young kids for instance).

You are 100% right there, and for this reason it is clear that at some point I must implement it.. 😉 
But unfortunately, today we must accept it as a limitation (of the trained model) and we must set priorities.. 

Thanks again,

**Comment by kbftech** [comment]
Hi again!

While there is no possibilities to "teach" the algorithm that both my kids aren't the same person (on the same picture!), do you have any idea how I could tweak the system to be more "exclusive"? Here are my settings as of now:
https://nextcloud.kfoster.tech/s/JDFkMNH9dxSWCNp/preview

With theses settings, it still cannot tell apart my two kids (which are not twins). My oldest son is 2.5 years older than my youngest and even when they appear on the same picture, the algorithm thinks they're the same person, twice.

CPU/Memory is no object (32 cores, 200GB available on the host).

**Comment by GAS85** [comment]
I made a mistake, I put to "to be checked" on different groups of people that I do not remember. But they were merged in 1 group "to be checked". Now there is no way to drop this group.
