### ISSUE TITLE
Feature Request - Merge/Split groups

### ISSUE THREAD

**Issue by kbftech** [matiasdelellis/facerecognition#477]
From within groups with the same name

MERGE:
1. Add a checkbox besides every occurrence of the name
2. Add a "Merge" button
3. When the end user clicks the "Merge" button, selected groups are merged together and become a single group
4. NICE TO HAVE: The algorithm learns from this action and can recognize future occurrences. 

SPLIT:
1. Add a "Split" button at the bottom of each occurrence of the name
2. Clicking the "Split" button pops-up the same window as described in issue #476 allowing the user to toggle between selected and unselected (for each face).
3. Saving changes removes the pictures from the group and adds them back to the "unknown" pile for future "renaming".

**Comment by matiasdelellis** [comment]
Hi @kbftech 
As I comment you in another report, I hope to implement it at some point but it is not a priority yet... Sorry.. 😞 

It is an dup of #134 and #158
