### ISSUE TITLE
Suggestions for a better user experience

### ISSUE THREAD

**Issue by storm1er** [matiasdelellis/facerecognition#480]
## 1) Routes

Going to settings page to see person list feels weird.

Maybe use a custom app page could be better for this.

## 2) View a person

Each photo redirect to file app

Therefore we can't slide each photo of someone.  
Plus clicking open a new tab, so if I want to see multiple photos of a given person, I have to open XX tabs, clicking on them, etc

Maybe a carousel/popin to see the clicked photos with quick actions could be better, allowing us to left/right to see prev/next photo of the given person

**Comment by matiasdelellis** [comment]
Hi @storm1er 
The solution in any case is in the integration with the photo application #338 or maybe the tags #292

But in both implementations we are limited by the nextcloud api.. 😞
