### ISSUE TITLE
Issue reinstalling models

### ISSUE THREAD

**Issue by BurningTheSky** [matiasdelellis/facerecognition#483]
### Expected behaviour

Installation of models via occ face:setup -m 1 to work.

### Actual behaviour

I acted without reading and removed 3 before installing 4 which was stupid. When I try and reinstall 3 it says " The file /mnt/ncdata//appdata_oc9k17bhaf4u/facerecognition/models//3/shape_predictor_5_face_landmarks.dat exists or is not writable" even though there isn't anything in the folder. I have tried removing and recreating the models folder but that doesn't help. 

### Steps to reproduce
Run command sudo -u www-data php /var/www/nextcloud/occ face:setup -m 1

### Server configuration

* **Operating system:** Ubuntu 20.04.2 LTS

* **Pdlib version:** 1.0.2

* **How is DLib installed:** Not sure, but the test runs correctly

* **How is PDlib installed:** sudo echo "deb https://repo.delellis.com.ar focal focal" > /etc/apt/sources.list.d/20-pdlib.list

* **PHP version:** 7.4.3

* **Web server:** Apache/2.4.41

* **Database:**  10.4.19

* **Nextcloud version:** 21.0.1

#### Background task log with debug.
<details>
<summary>sudo -u www-data php /var/www/nextcloud/occ face:setup -m 1</summary>

```
The model 1 (Default) will be installed

In FileService.php line 383:

  The file /mnt/ncdata//appdata_oc9k17bhaf4u/facerecognition/models//1/mmod_human_face_detector.dat exists or is not writable


face:setup [-m|--model [MODEL]]
```
</details>

**Comment by matiasdelellis** [comment]
Hi @BurningTheSky 
Please, show me the content of /mnt/ncdata//appdata_oc9k17bhaf4u/facerecognition/

in my case:
```
[matias@nube ~]$ tree /media/datos/Services/nextcloud/data/appdata_ocs84jb72zk9/facerecognition/
/media/datos/Services/nextcloud/data/appdata_ocs84jb72zk9/facerecognition/
└── models
    ├── 1
    │   ├── dlib_face_recognition_resnet_model_v1.dat
    │   ├── mmod_human_face_detector.dat
    │   └── shape_predictor_5_face_landmarks.dat
    ├── 2
    │   ├── dlib_face_recognition_resnet_model_v1.dat
    │   ├── mmod_human_face_detector.dat
    │   └── shape_predictor_68_face_landmarks.dat
    └── 3
        ├── dlib_face_recognition_resnet_model_v1.dat
        └── shape_predictor_5_face_landmarks.dat

4 directories, 8 files
[matias@nube ~]$ 

```

**Comment by BurningTheSky** [comment]
Hi @matiasdelellis 
Only models shows, nothing below. I've included permissions too:
```
burningsky@nextcloud:/mnt/ncdata/appdata_oc9k17bhaf4u/facerecognition# tree
.
└── models

1 directory, 0 files
burningsky@nextcloud:/mnt/ncdata/appdata_oc9k17bhaf4u/facerecognition# ll
total 0
drwxrwx--- 1 www-data www-data  12 May 24 08:26 ./
drwxrwx--- 1 www-data www-data 150 May 21 19:20 ../
drwxrwx--- 1 www-data www-data   0 May 24 08:26 models/

```

**Comment by matiasdelellis** [comment]
Create a subfolder model/1 and try again.

**Comment by BurningTheSky** [comment]
That worked! Thanks!
