### ISSUE TITLE
Renaming individual persons in 'File Detail'>'Persons' renames the whole group (cluster)

### ISSUE THREAD

**Issue by gb-123-git** [matiasdelellis/facerecognition#484]
### Expected behavior

Renaming should only change the person in the file. i.e. Only that file should have the person name pointer changed.

### Actual behavior

Renaming changes all the files. eg. if a photo is from cluster of person GroupA, and you name the person in File details as GroupB, the whole GroupA changes to GroupB.

### Steps to reproduce
1. Recognize a cluster of faces as 'GroupA'
2. Go to one of the files of the recognized cluster.
3. Change the recognized name to 'GroupB'

### Server configuration

* **Operating system:**

Ubuntu 20.04

* **Pdlib version:**

1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

*Working Correctly

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

*Working Correctly

* **PHP version:**
*7.4

* **Web server:**
NginX

* **Database:**
*MySQL

* **Nextcloud version:**
*21.0.2 stable

### Client configuration

* **Browser:**
*Brave

* **Operating system:**
*Windows 10

**Comment by matiasdelellis** [comment]
Hi @gb-123-git 
You're right, this function, rename the person, (A person is a group of similar faces) What you want is a function "This face is not NAME" that would be implemented in https://github.com/matiasdelellis/facerecognition/issues/158

I hope you can implement it soon.. Sorry if it causes you problems.. 😞 

Close as dup of #158
