### ISSUE TITLE
Installing model went wrong

### ISSUE THREAD

**Issue by nefus8** [matiasdelellis/facerecognition#491]
Hello, I tried to install the model 1 and this is the error I got : 
```
You do not meet the dependencies to install the model 1 (Default)
Summary: Your system does not meet the minimum memory requirements
Please read the documentation for this model to continue: https://github.com/matiasdelellis/facerecognition/wiki/Models#model-1
```

And I don't know why because my system does have enough memory... it has 16Gb of ram and I allowed 2 for php... Here is my nextcloud configuration information for face recognition: 

```
Configuration information 
System memory: 15.5 GB

Memory assigned to PHP: 2 GB

Maximum memory for facial recognition: 2 GB
```

**Comment by matiasdelellis** [comment]
Hi @nefus8 
Excuse me for the delay in answering...

Please check the memory assigned in the CLI:

```
[matias@nube nextcloud]$ php -i | grep memory_limit
memory_limit => -1 => -1
```

In my case it is unlimited ..
