### ISSUE TITLE
Which model?

### ISSUE THREAD

**Issue by rodude123** [matiasdelellis/facerecognition#492]
I've read the documentation and I'm wondering which model is the best one to choose from. I currently use model 1. I'm considering switching to model 4 as I want to recognize as many faces as possible and get a high enough accuracy.

**Comment by matiasdelellis** [comment]
Hi @rodude123 
Sorry the delay.. 

Yes.. Model 4 would be recommended. You will have to name more groups, but it will have much more quality.
