### ISSUE TITLE
Command face:reset freezes

### ISSUE THREAD

**Issue by tetebueno** [matiasdelellis/facerecognition#493]
I can't seem to reset data either for clustering, errors or all. I can't find a way for any command to log anything to give me a clue on what might be going on (`-vvv` doesn't show anything either).

```bash
$ occ face:stats -vvv
+------+--------+-------+---------+
| User | Images | Faces | Persons |
+------+--------+-------+---------+
| user | 61726  | 59332 | 17086   |
+------+--------+-------+---------+
```

### Expected behaviour

After executing `occ face:reset` should wipe data (as described [here](https://github.com/matiasdelellis/facerecognition#resetting-information)).

### Actual behaviour

After prompting for confirmation, process never returns.

### Steps to reproduce
1. Execute `occ face:reset --clustering` (for example)
2. Answer `y` to the warning displayed
3. Wait (a lot... I even had it running for one entire day since there are a lot of images processed)

### Server configuration

* **Operating system:** Ubuntu (Apache Docker image)

* **Pdlib version:** 1.0.2

* **How is DLib installed:** Compiled from source enabling CUDA.

* **How is PDlib installed:** Installed from `master` release artifact running `phpize && ./configure && make && make install`.

* **PHP version:** 7.4.19

* **Web server:** Apache

* **Database:** MariaDB (10.4.18)

* **Nextcloud version:** 21.0.2

### Client configuration

* **Browser:** Chromium 91.0.4472.101

* **Operating system:** Ubuntu 18.04

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tetebueno** [comment]
Well, did find something under https://hostname/settings/integrity/failed after seeing a warning in the Settings -> Administration -> Overview section:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- face
	- EXCEPTION
		- Exception
		- App not found

Raw output
==========
Array
(
    [face] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

)
```

I get the same error when executing what the documentation recommends in such cases but I get the same result:

```bash
$ occ integrity:check-app face
  - EXCEPTION:
    - class: Exception
    - message: App not found
```

**Comment by Lajull-fr** [comment]
Hello i have the same Integrity message :/

**Comment by matiasdelellis** [comment]
Hi @tetebueno @Lajull-fr 
Sorry for the delay in answering...

This function is done with a single sql query. I probably can't improve it..  😞 
Probably the easiest thing would be to do the queries by hand in your database... 

```
UPDATE `oc_facerecog_faces` SET person = NULL;
DELETE FROM `oc_facerecog_persons`;
```

This is all magic .. but it still takes time. 😉 

p.s: About
> occ integrity:check-app face

Must be `occ integrity:check-app facerecognition`, however its result is not relevant for this report.

**Comment by Lajull-fr** [comment]
@matiasdelellis Thanks for reply
With `occ integrity:check-app facerecognition` now i have 
`-  #EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.
`

And my report is now:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- pdlib/configure
		- pdlib/.git/description
		- pdlib/.git/index
		- pdlib/.git/config
		- pdlib/.git/hooks/pre-push.sample
		- ...

You think i do reset facerecognition and pdlib and reinstall ?

**Comment by matiasdelellis** [comment]
Hi @Lajull-fr 
Apparently, you installed pdlib by hand, and compiled it into the 'facerecognition' folder.

As for the integrity report, it says that you have unnecessary files .. You can delete this folder, but the integrity errors do not affect the operation of the application.

**Comment by Lajull-fr** [comment]
Ok super, thanks bro and Good job :+1:
