### ISSUE TITLE
RAW image processing

### ISSUE THREAD

**Issue by D34DC3N73R** [matiasdelellis/facerecognition#494]
### Expected behaviour
I just started with this app, but so far I'm only seeing jpgs and pngs processed. Are there plans to support raw image formats? Selfishly, I was hoping for ARW support (based on the TIFF specification) but I'm sure others would appreciate common raw formats.

### Actual behaviour

only standard image formats are processed

### Steps to reproduce
1. attempt to process a directory containing raw images
2. no images are processed

### Server configuration

* **Operating system:**
unraid

* **Pdlib version:**
1.0.2-r0

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
installed via linuxserver custom scripts
```
!/bin/bash

echo "**** installing php7-pdlib (dependency for facerecognition app) ****"
apk update
apk add --upgrade -X http://dl-cdn.alpinelinux.org/alpine/edge/testing php7-pdlib

echo "**** installing bzip (dependency for facerecognition app) ****"
apk add bzip2-dev

echo "*** enable face recognition model***"
occ face:setup -m 1
```
install log
```
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/5) Installing libquadmath (10.2.1_pre1-r3)
(2/5) Installing libgfortran (10.2.1_pre1-r3)
(3/5) Installing openblas (0.3.13-r0)
(4/5) Installing dlib (19.18-r1)
(5/5) Installing php7-pdlib (1.0.2-r0)
OK: 355 MiB in 224 packages
```

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
see above

* **PHP version:**
PHP 7.4.19

* **Web server:**
nginx

* **Database:**
mariadb

* **Nextcloud version:**
Nextcloud 20.0.10

### Client configuration

* **Browser:**
chome

* **Operating system:**
windows 10

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
currently running initial scan after enabling group folders 
occ face:background_job
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi @D34DC3N73R 
It is surely an expected feature, and I would like to implement it.. in particular I think it is more fundamental to add support to the HEIC format, but the implementation is the same. Once a new format is achieved, we can add the rest of the formats..

p.s:
In particular, it's something that I'm probably forced to do due to changes in PHP 8 and NC21, but I still couldn't implement it. 😞

**Comment by D34DC3N73R** [comment]
After doing some more digging, I thought this would have to be implemented in dlib. Is that not the case?

**Comment by matiasdelellis** [comment]
Hi,
Theoretically, with #616 , we could read raw files.
