### ISSUE TITLE
Error enabling facerecongnition PHP 7.4.3

### ISSUE THREAD

**Issue by H0tmilk** [matiasdelellis/facerecognition#495]
Hello,

### The issue

I followed the nextcloud setup and everything works fine until I want to enable facerecognition : 
`sudo -u www-data php occ app:enable facerecognition`

I have this error : 
`Column "oc_facerecog_persons"."is_valid" is type Bool and also NotNull, so it can not store "false".`

### Server configuration
* **OS:** Ubuntu 20.04.2 LTS (Focal Fossa)
* **Pdlib version:** Version provided by "easy" installer

* **How is DLib and PDlib installed:** following the [readme](https://github.com/goodspb/pdlib/blob/master/README.md) of PDlib. 

* **PHP version:** PHP 7.4.3

* **Web server:** Apache/2.4.41

* **Database:** MariaDB 10.3.29

* **Nextcloud version:** 22.0.0

If anyone can help. Thanks.

**Comment by mtungtn** [comment]
same problem :(

**Comment by matiasdelellis** [comment]
Hi @H0tmilk @mtungtn 
This is due Nextcloud 22... 😞

**Comment by matiasdelellis** [comment]
Hi @H0tmilk @mtungtn
See https://github.com/matiasdelellis/facerecognition/pull/497 and please test..

**Comment by H0tmilk** [comment]
Thanks @matiasdelellis,

As you said, I replaced nextcloud/apps/facerecognition with this : https://services.delellis.com.ar/data/facerecognition/nc22/facerecognition.tar.gz

Nice work, thanks again.
