### ISSUE TITLE
Button to Skip range of faces

### ISSUE THREAD

**Issue by nssatlantis** [matiasdelellis/facerecognition#504]
Hello!

I've been using this app for quite a while now, and while the recognition part isn't 100% fine It works for me, so I'd like to say cheers for making this and I hope to see more advanced/better trained models come through at some point.

My main suggestion honestly is to have some kind of button beside "I am not sure" and "rename" to "skip this range of faces".
Reason for this is because I imported a massive amount of pictures of all shapes and sizes, and while it does a good job finding what I need, it also forces me to go through 10 pages worth of random people, random babies, random faces, as far as Meme faces, and even game character faces! (Clash of clans)

We know the system can detect and (usually) properly throw them into a small cluster/list of the same people. All I'd like is to be able to say "Ok Skip those Clash of Clans faces so I don't have to repeat clicking 'i am not sure' "every time I want to add someone else.

I hope this makes sense, if not please let me know!

**Comment by matiasdelellis** [comment]
Hi @nssatlantis 
Thanks for the words of encouragement. 😄 

> I hope to see more advanced/better trained models come through at some point.

I have the illusion of making a community model where usera offer their images to train a better model, however it is very sensitive information (I don't know how many users would share it), and it may have legal implications that escape me. Issue #448

> My main suggestion honestly is to have some kind of button beside "I am not sure" and "rename" to "skip this range of faces". 

Yes.. I have pending it and there is a similar report #486

> Meme faces, and even game character faces! (Clash of clans)

Haha! Personally I find it impressive that he groups certain cartoons, animojis, etc..
If you have more less organized, you always can ignore the folders that include them. 😉 

> I hope this makes sense, if not please let me know!

Yes,, Lot of sense, and more or less planned .. I just need a little time to do it. :wink:

Thanks again
