### ISSUE TITLE
How do I fix an DLIB_NO_GUI_SUPPORT error?

### ISSUE THREAD

**Issue by SamGreenwood1** [matiasdelellis/facerecognition#507]

**Comment by ThomSerg** [comment]
I got the same error and managed to fix it by deleting the Dlib and PDlib folders, install libx11-dev and then redo the steps for Dlib and PDlib. Source: https://github.com/goodspb/pdlib/issues/12

**Comment by matiasdelellis** [comment]
Well, this usually happens when mixing dlib versions on build instruccions.. 😞
