### ISSUE TITLE
image will be skipped because it is too small

### ISSUE THREAD

**Issue by guystreeter** [matiasdelellis/facerecognition#519]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

I have a lot of old images that are 640x480 that I want to process.

### Actual behaviour

These images are skipped because they are "too small"

### Steps to reproduce
1. upload a 640x480 jpg file
2. run the background_job

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
	Processing image /nextcloud-data/__groupfolders/1/Guy Streeter/Montgomery Family Reunion 2006/Elisabeth&Gordon.jpg
	Faces found: 0 (image will be skipped because it is too small)
```
</details>

I searched for documentation about the minimum image size and could not find any mention of it, so this behavior was unexpected. Please document this limitation, and if it is possible, explain how to override it.

**Comment by matiasdelellis** [comment]
Hi @guystreeter 

See:
* https://github.com/matiasdelellis/facerecognition/wiki/Settings#hidden-settings

But probably will be better to also put it in the FAQ

**Comment by matiasdelellis** [comment]
Added to FAQ.. Thanks again.
