### ISSUE TITLE
BUG: Rename Individual Faces Changes Collection

### ISSUE THREAD

**Issue by farhills** [matiasdelellis/facerecognition#522]
### Expected behaviour

Renaming an individual face (editing via sidebar properties) should change the name for only that face on that file.

### Actual behaviour

Renaming a person appears to rename the entire cluster.  

This is especially an issue where the facerecognition algorithm is struggling with baby faces.  I have many photos where two different people (babies) in the same photo are being assigned to the same cluster.  Renaming one, automatically renames the cluster, thus both faces in the photo still have the same name.

### Steps to reproduce
1.  Process a batch of photos
2.  Identify a cluster with errors (more than one person in the cluster)
3.  Rename one of the erroneous people by directly editing the file via sidebar
4.  The collection rather than the single file has been renamed.

### Server configuration

* **Operating system: Unraid/Docker**

* **Pdlib version:** 1.0.2

* **How is DLib installed:** custom script after container creation

* **How is PDlib installed:** custom script after container creation

*  **Model:** 4

* **PHP version:** 7.4.23

* **Web server:** nginx 20.x

* **Database:** mariadb 10.5.12

* **Nextcloud version:** 22.1.1 community edition

**Comment by matiasdelellis** [comment]
Hi @farhills
Sorry the delay.. Little free time.. 😞 

What you are looking for is the option "This is not SUCH PERSON" that unfortunately is not yet implemented. 

I hope to do something soon .. 😉 
Close as dup of #158
