### ISSUE TITLE
From Appstore I only get the 0.7.2 version

### ISSUE THREAD

**Issue by jakobroehrl** [matiasdelellis/facerecognition#524]
Tried on 2 different NC22 servers
But there is a 0.8.3: https://github.com/matiasdelellis/facerecognition/releases

![image](https://user-images.githubusercontent.com/24530680/139068981-4b66dbf0-8fa9-4789-bfae-35761ecbae96.png)
![image](https://user-images.githubusercontent.com/24530680/139069008-3f832f22-c553-406e-a40b-285437497f63.png)

**Comment by andrey18106** [comment]
@jakobroehrl Hi! That's probably because of PHP version limitations (as I checked, latest version supports only PHP 7.3 and 7.4). Check your PHP version, I assume that you have PHP 8, NC doesn't show you uncompatible app versions.

**Comment by jakobroehrl** [comment]
Thanks @andrey18106 
This is right, so I have to wait, toll PHP8 is supported?

**Comment by andrey18106** [comment]
@jakobroehrl I don't know, I'm not a developer of this application. I was just passing by apps and issues and found familiar issue (I developing another Nextcloud app - MediaDC), so decided to help)

**Comment by matiasdelellis** [comment]
Hi @jakobroehrl 
Until now it depends on cd Nextcloud. Please, follow the progress on #456 

@andrey18106 
Thank you very much for answering. 😄
