### ISSUE TITLE
Current model: Not installed

### ISSUE THREAD

**Issue by Amursky1988** [matiasdelellis/facerecognition#530]
### Expected behavior

installation of models

### Actual behavior

I get an error

An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA \ FaceRecognition \ Model \ ModelManager :: getModel () must be of the type int, string given, called in /usr/share/nginx/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php on line 81 and defined in /usr/share/nginx/nextcloud/apps/facerecognition/lib/Model/ModelManager.php:99
Stack trace:
0 /usr/share/nginx/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(81): OCA \ FaceRecognition \ Model \ ModelManager-> getModel ()
1 /usr/share/nginx/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA \ FaceRecognition \ Command \ SetupCommand-> execute ()
2 /usr/share/nginx/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony \ Component \ Console \ Command \ Command-> run ()
3 /usr/share/nginx/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony \ Component \ Console \ Application-> doRunCommand ()
4 /usr/share/nginx/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony \ Component \ Console \ Application-> doRun ()
5 /usr/share/nginx/nextcloud/lib/private/Console/Application.php(209): Symfony \ Component \ Console \ Application-> run ()
6 /usr/share/nginx/nextcloud/console.php(99): OC \ Console \ Application-> run ()
7 / usr / share / nginx / nextcloud / occ (11): require_once ('/ usr / share / ngin ...')

### Steps to reproduce
1.execute the command sudo -u www-data php / usr / share / nginx / nextcloud / occ face: setup -m MODEL_ID

### Server configuration

* ** UBUNTU Server 20.04: **

* ** Pdlib version latest from repository: **

* ** PHP version: 7.4 **

* ** Web server: nginx 1.18 **

* ** Database: Maria DB **

* ** Nextcloud version: 22 **

### Client configuration

* ** Browser: Chorme **

**Comment by guystreeter** [comment]
Did you actually put `MODEL_ID` on the command line? You're supposed to enter an integer model number.

**Comment by cybergigz** [comment]
sudo -u www-data php occ face:setup -m 1 

//model_id = 1

**Comment by guystreeter** [comment]
I have never seen this happen, even when I was on PHP 7.4. I can't reproduce it now, with Nextcloud 22 and PHP 8. I looked at the code path in the facerecognition app, and I don't see any recent changes that could have affected this.
Maybe @matiasdelellis has a clue, but I've run out of ways to help :(

**Comment by Amursky1988** [comment]
guystreeter and cybergigz thank you. I took the tuning recommendations too literally. Now everything has worked out. I also use model number 3

**Comment by matiasdelellis** [comment]
Brilliant. Thank you all!
