### ISSUE TITLE
it seems you don't have python binding installed

### ISSUE THREAD

**Issue by thenamelessthing** [matiasdelellis/facerecognition#531]
In my personnal face recognition page, It seem to work properly but in the system face recognition page I have the following message: 

Current model: 1

It seems that you do not meet the dependencies to use the current model.

![image](https://user-images.githubusercontent.com/10235448/142775913-ec1580c5-9a7f-47a8-9630-fd77b8d5546d.png)

When I check the progress I also see this warning:

![image](https://user-images.githubusercontent.com/10235448/142776183-032481fa-2fe0-4ca4-a0ba-ca67acc87011.png)

How can I fix these message?
### Server configuration

* **Operating system:**
Ubuntu 20.04

* **Pdlib version:**
1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
seem to be okay, no error
* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
seem to be okay too

* **PHP version:**
7.4.3
* **Web server:**
apache 2.4.1
* **Database:**
mariadb
* **Nextcloud version:**
22.2.3
### Client configuration

* **Browser:**
edge
* **Operating system:**
Win10 21H2
#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

![image](https://user-images.githubusercontent.com/10235448/142776338-2c0843d6-5093-4c93-9dbe-f300c5220fc2.png)
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
{"reqId":"n1NO9aw41ARkUUthoqKq","level":3,"time":"2021-11-21T18:50:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Module 'pdlib' already loaded at Unknown#0","userAgent":"--","version":"22.2.3.0","id":"619a9bfe22d57"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi @thenamelessthing 
About the title that does not correspond to the rest of the report,  but I guess that's what the test tells to you.. if php test is ok, you can ignore the rest. ;)

About:
> It seems that you do not meet the dependencies to use the current model.

You have to increase the memory assigned to php.. 512mb is too low..

About:
> 'pdlib' is already loaded...

..you have at least two files in /etc/php/php.d enabling the module .. leave just one..

**Comment by matiasdelellis** [comment]
Hi @thenamelessthing 
To avoid some of this confusion I made some changes in #534
It will be annoying for everyone, but it will also avoid a lot of problems. 😅

**Comment by thenamelessthing** [comment]
Thank you, adjusting the mem to 1GB and remove the duplicate entry in my php config solved the problem!
