### ISSUE TITLE
dplib: make problems

### ISSUE THREAD

**Issue by jakobroehrl** [matiasdelellis/facerecognition#535]
Hi, do you guys could help me going the "hard way" https://github.com/matiasdelellis/facerecognition/wiki/Installation#hard-way?
I have PHP8 and ubuntu.
DLib install worked, but with pdlib the make fails:

`root@localhost:~/pdlib# make
/bin/bash /root/pdlib/libtool --mode=compile g++ -I. -I/root/pdlib -I/root/pdlib/include -I/root/pdlib/main -I/root/pdlib -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++11 -c /root/pdlib/src/face_recognition.cc -o src/face_recognition.lo
libtool: compile:  g++ -I. -I/root/pdlib -I/root/pdlib/include -I/root/pdlib/main -I/root/pdlib -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++11 -c /root/pdlib/src/face_recognition.cc  -fPIC -DPIC -o src/.libs/face_recognition.o
In file included from /usr/include/sched.h:29,
                 from /usr/include/pthread.h:22,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/gthr.h:148,
                 from /usr/include/c++/9/ext/atomicity.h:35,
                 from /usr/include/c++/9/bits/basic_string.h:39,
                 from /usr/include/c++/9/string:55,
                 from /usr/local/include/dlib/algs.h:97,
                 from /usr/local/include/dlib/matrix/matrix_exp.h:6,
                 from /usr/local/include/dlib/matrix/matrix.h:6,
                 from /usr/local/include/dlib/matrix.h:6,
                 from /usr/local/include/dlib/cuda/tensor.h:8,
                 from /usr/local/include/dlib/dnn.h:12,
                 from /root/pdlib/src/face_recognition.h:8,
                 from /root/pdlib/src/face_recognition.cc:2:
/root/pdlib/src/face_recognition.cc: In function ‘face_recognition* php_face_recognition_from_obj(zend_object*)’:
/root/pdlib/src/face_recognition.cc:12:58: warning: offsetof within non-standard-layout type ‘face_recognition’ {aka ‘_face_recognition’} is conditionally-supported [-Winvalid-offsetof]
   12 |     return (face_recognition*)((char*)(obj) - XtOffsetOf(face_recognition, std));
/root/pdlib/src/face_recognition.cc:12:47: note: in expansion of macro ‘XtOffsetOf’
   12 |     return (face_recognition*)((char*)(obj) - XtOffsetOf(face_recognition, std));
      |                                               ^~~~~~~~~~
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [Makefile:217: src/face_recognition.lo] Error 1
root@localhost:~/pdlib#
`

Thanks a lot!

**Comment by matiasdelellis** [comment]
Hi @jakobroehrl 

> std)); | ^~~~~~~~~~ g++: fatal error: Killed signal terminated program cc1plus compilation terminated. make: *

On which computer are you compiling pdlib?. It seems that it is being killed by the kernel probably because it is running low on RAM

**Comment by jakobroehrl** [comment]
Thanks for your reply. It's a 4 GB VM on linode.

**Comment by matiasdelellis** [comment]
Well .. Is it enough ram, but how much memory do you have free?. Create a swap file to momentarily increase memory.. 😉

**Comment by matiasdelellis** [comment]
RAM!.

```
[matias@bangho-mdl ~]$ free -h
               total        used        free      shared  buff/cache   available
Mem:           7,6Gi       1,3Gi       4,8Gi       297Mi       1,5Gi       5,7Gi
Swap:          7,6Gi          0B       7,6Gi

```

**Comment by jakobroehrl** [comment]
This was the problem, thanks a lot.
No problem to build with 8GB Ram

**Comment by jakobroehrl** [comment]
@matiasdelellis 
It's working and I love it!
Is there a chance to get a precomplied PHP8 ubuntu lib?

**Comment by matiasdelellis** [comment]
Hi @jakobroehrl 
Follow the discussion in #456 

The only package I'm going to do is Ubuntu Impish

**Comment by jakobroehrl** [comment]
Thanks a lot. 
Last question: I I compile myself I have to redo this when there is an update to PHP 8.1. e.g., right?

**Comment by matiasdelellis** [comment]
Yes.. 😉

**Comment by count00zero** [comment]
I graciously fail when building from source; but just for php8.0.15 specifically.
There is no phpize for php8*; just calling phpize only lists the php7.4 version:
PHP Api Version:         20190902.

Therefore make test results in:
```
=====================================================================
PHP         : /usr/bin/php7.4
PHP_SAPI    : cli
PHP_VERSION : 7.4.28
ZEND_VERSION: 3.4.0
PHP_OS      : Linux - Linux AMDSERVER 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64
INI actual  : /opt/_Build/pdlib/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /usr/bin/phpdbg8.1
PHP_SAPI    : phpdbg
PHP_VERSION : 8.1.2
ZEND_VERSION: 4.1.2
PHP_OS      : Linux - Linux AMDSERVER 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64
INI actual  : /opt/_Build/pdlib/tmp-php.ini
More .INIs  :
Warning: PHP Startup: pdlib: Unable to initialize module
Module compiled with module API=20190902
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
```

And so even if I copy the resulting pdlib.so for 7.4 to php8.0 ... it won't work (of course) ....

Any help is appreciated!
