### ISSUE TITLE
how to delete data after removing Face Recognition app

### ISSUE THREAD

**Issue by meonkeys** [matiasdelellis/facerecognition#537]
This is a question, not an issue. I disabled and removed the Face Recognition app from Nextcloud. I'd like to clean up anything it left behind. Is any/all data it created also deleted automatically? If not, would you tell me a few commands and/or SQL queries I could run to clean up any data it created? At least whatever I could clean up without breaking other functionality in Nextcloud.

I do see four tables starting with `oc_facerecog_%`... can I safely drop those?

It's not a huge deal either way, looks like they don't take up much space.

And just to be clear, I think I know what I'm in for... for example, I'm assuming if I re-install and enable the app later I'll have to start from scratch recognizing faces.

**Comment by matiasdelellis** [comment]
> I do see four tables starting with oc_facerecog_%... can I safely drop those?

Yes.. Just drop this tables.. It is 100% safe.

DROP TABLE `oc_facerecog_faces`
DROP TABLE `oc_facerecog_images`
DROP TABLE `oc_facerecog_models`
DROP TABLE `oc_facerecog_persons`

Then...
DELETE from `oc_appconfig` WHERE `appid` = `facerecognition`
DELETE from `oc_preferences` WHERE `appid` = `facerecognition`
DELETE from `oc_migrations` WHERE `app` = `facerecognition`

...and this application never existed for you .. 🙈 😅

**Comment by meonkeys** [comment]
Thank you. Here's what I used, for posterity (only sight punctuation differences):

```sql
DROP TABLE `oc_facerecog_faces`; 
DROP TABLE `oc_facerecog_images`; 
DROP TABLE `oc_facerecog_models`; 
DROP TABLE `oc_facerecog_persons`; 
DELETE from `oc_appconfig` WHERE `appid` = 'facerecognition'; 
DELETE from `oc_preferences` WHERE `appid` = 'facerecognition'; 
DELETE from `oc_migrations` WHERE `app` = 'facerecognition';
```
