### ISSUE TITLE
Enable for Nextcloud 23

### ISSUE THREAD

**Issue by guystreeter** [matiasdelellis/facerecognition#539]
I have verified that facerecognition works on a fresh install of Nextcloud 23. I think that version can be enabled in in the app.

**Comment by matiasdelellis** [comment]
Hi @guystreeter 
Thanks for reporting... 😃 

Hopefully tomorrow I finish #536 and with that I release a new version.. :wink:

**Comment by matiasdelellis** [comment]
Enabled on last release.. 🎉
