### ISSUE TITLE
Rephrase "I'm not sure" button to better indicate what it does

### ISSUE THREAD

**Issue by guystreeter** [matiasdelellis/facerecognition#544]
Great work on the newest updates to this app. Thanks for working on it!

This is a minor thing, but it might help new users: It isn't clear what happens when you click the "I'm not sure" button on the rename dialog. I think changing the wording to "Not Now" or "Skip for now" or something similar might help. That way, the user knows they will get another chance to name the cluster later.

**Comment by matiasdelellis** [comment]
Hi  @guystreeter 
You're right!. I will change it soon for the next version. (But not for v0.9.1)
