### ISSUE TITLE
can't set memory: (Or any occ face: command)

### ISSUE THREAD

**Issue by jakobroehrl** [matiasdelellis/facerecognition#545]
root@server:~# sudo -u www-data /usr/bin/php /var/www/nextcloud/occ face:setup --memory 2GB
Segmentation fault
root@server:~# sudo -u www-data /usr/bin/php /var/www/nextcloud/occ face:setup --memory 1GB
Segmentation fault

no log messages

**Comment by leonardohlee** [comment]
> sudo -u apache php occ face:stats

remove an app called "backup".  and try again. mine works

**Comment by matiasdelellis** [comment]
D'Oh!. 😞 
https://github.com/nextcloud/backup/issues/116

**Comment by jakobroehrl** [comment]
Thanks @leonardohlee 
It's working.
