### ISSUE TITLE
Errors in Dockerfile

### ISSUE THREAD

**Issue by shperrung** [matiasdelellis/facerecognition#550]
Expected behaviour:
Build docker image using author's Dockerfile
Tell us what should happen:
Expecting image for Nextcloud with Face Recognition
### Actual behaviour
Dockerfile execution in docker builder stops with error
### Steps to reproduce
1. Try to build docker image in Portainer.
Sorry, that I do not provide other relevant details. Just see what is wrong in my opinion.
This your original part of Dockerfile causing error:
```
COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib

# If is necesary take the php extention folder uncommenting the next line
# RUN php -i | grep extension_dir
COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20180731/pdlib.so /usr/local/lib/php/extensions/no-debug-non-zts-20180731/

# Enable PDlib on final image

RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Increse memory limits

RUN echo memory_limit=1024M > /usr/local/etc/php/conf.d/memory-limit.ini
```

Corrected part of your Dockerfile that successfully build an image:
```
COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib/

# If is necesary take the php extention folder uncommenting the next line
#RUN php -i | grep extension_dir
COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20200930/pdlib.so /usr/local/lib/php/extensions/no-debug-non-zts-20200930/

# Enable PDlib on final image

RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Increse memory limits

RUN echo memory_limit=1024M > /usr/local/etc/php/conf.d/memory-limit.ini
```
1) Increase of memory limits doesn't work as you expecting. You better to modify ENV for this.
2) /usr/local/lib/php/extensions/no-debug-non-zts-20180731 - wrong file name.
3) COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib - slash at the end is missing while it's required.

**Comment by guystreeter** [comment]
The files in `/usr/local/etc/php/conf.d/` are read in alphabetic order. There is a `nextcloud.ini` in that directory, and it sets `memory_limit` to the value of `PHP_MEMORY_LIMIT`. This will override `memory_limit` set in `memory-limit.ini` because it is read later.
If you really want to set `memory_limit` to something other than `PHP_MEMORY_LIMIT`, maybe call your file `zzz-memory-limit.ini` or something, but I think using the env var is probably the right way to go.

**Comment by shperrung** [comment]
Another doubtful thing is in "builder" part there:
```
# Install bzip2 needed to extract models

RUN apt-get install -y libbz2-dev
RUN docker-php-ext-install bz2
```
It should be moved below into final builded image command block, because this required package remains in "builder" image and you get error while enable Face Recognition application in Nextcloud gui.

Also you better keep version number in commands calling "builder" and "final" images. Now these rows call "latest" Nextcloud:23-apache version that in not compatible with current Face Recognition application in Nextcloud. Version 22 works good with Face Recognition.
`FROM nextcloud:22.2.3-apache` - is right to avoid problems with a need in version downgrade.

Latest part of Dockerfile related to "test" and install of Face Recognition application into image is not good idea. I got compatibility problems during upgrade Nextcloud 21 with existing FR app and Nextcloud 22 image with added FR app.
I think it better stop at this row and comment that FR app is to be installed manually.
```
# Increse memory limits

RUN echo memory_limit=1024M > /usr/local/etc/php/conf.d/memory-limit.ini
```

**Comment by shperrung** [comment]
That Dockerfile works fine for me
`#
# Use a temporary image to compile and test the libraries
#
FROM nextcloud:22.2.3-apache as builder

# Build and install dlib on builder

RUN apt-get update ; \
    apt-get install -y build-essential wget cmake libx11-dev libopenblas-dev

ARG DLIB_BRANCH=v19.19
RUN wget -c -q https://github.com/davisking/dlib/archive/$DLIB_BRANCH.tar.gz \
    && tar xf $DLIB_BRANCH.tar.gz \
    && mv dlib-* dlib \
    && cd dlib/dlib \
    && mkdir build \
    && cd build \
    && cmake -DBUILD_SHARED_LIBS=ON --config Release .. \
    && make \
    && make install

# Build and install PDLib on builder

ARG PDLIB_BRANCH=master
RUN apt-get install unzip
RUN wget -c -q https://github.com/matiasdelellis/pdlib/archive/$PDLIB_BRANCH.zip \
    && unzip $PDLIB_BRANCH \
    && mv pdlib-* pdlib \
    && cd pdlib \
    && phpize \
    && ./configure \
    && make \
    && make install

# Enable PDlib on builder

# If necesary take the php settings folder uncommenting the next line
# RUN php -i | grep "Scan this dir for additional .ini files"
RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Test PDlib instalation on builder

RUN apt-get install -y git
RUN git clone https://github.com/matiasdelellis/pdlib-min-test-suite.git \
    && cd pdlib-min-test-suite \
    && make

#
# If pass the tests, we are able to create the final image.
#

FROM nextcloud:22.2.3-apache

# Install dependencies to image

RUN apt-get update ; \
    apt-get install -y libopenblas-base libmagickcore-6.q16-2-extra

# Install dlib and PDlib to image

COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib/

# If is necesary take the php extention folder uncommenting the next line
#RUN php -i | grep extension_dir
COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20200930/pdlib.so /usr/local/lib/php/extensions/no-debug-non-zts-20200930/

# Enable PDlib on final image

RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Increse memory limits

ENV PHP_MEMORY_LIMIT=1024M
ENV PHP_UPLOAD_LIMIT=1024M
RUN echo memory_limit=1024M > /usr/local/etc/php/conf.d/memory-limit.ini

# Install bzip2 needed to extract models

RUN apt-get install -y libbz2-dev
RUN docker-php-ext-install bz2`
Face Recognition app I install manually.

**Comment by guystreeter** [comment]
I don't have any problem with the current facerecognition app and the current nextcloud 23 docker file.

**Comment by shperrung** [comment]
> I don't have any problem with the current facerecognition app and the current nextcloud 23 docker file.

Hi!
Thank you for response)
I get this during image build
```
Step 15/21 : COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib


When using COPY with more than one source file, the destination must be a directory and end with a /
```
[FaceRec.log](https://github.com/matiasdelellis/facerecognition/files/7852789/FaceRec.log)

**Comment by guystreeter** [comment]
oh I didn't notice I have that fixed locally. Just add the `/` on the end like it says.

**Comment by maexbower** [comment]
for increasing the memory limit i changed the line to use sed
`RUN sed -i 's/memory_limit=512M/memory_limit=2048M/g' /usr/local/etc/php/conf.d/nextcloud.ini`

but having the512M in the searchstring is not sustainable, maybe someone has a better idea how to change the line even when nextcloud changes the default value in a upcoming release.
