### ISSUE TITLE
Something to add to the installation guide

### ISSUE THREAD

**Issue by roninvanderwerke** [matiasdelellis/facerecognition#552]
It doesn't mention on this github to add 

[pdlib]
extension="pdlib.so"

to your php.ini. And without it, it gives you an error message.

-And thanks for your work!

**Comment by MaKraMc** [comment]
Dude you are the best!
I was wondering for 24 hours straight why the libary wasn't working. Those two lines fixed it. I feel so stupid.

**Comment by jkubala4454** [comment]
THANK YOU!!!  I have been scratching my head for over a week with this issue.

**Comment by matiasdelellis** [comment]
https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation#pdlib-configuration
