### ISSUE TITLE
Renaming person from Photo viewer affects entire cluster and not single photo!

### ISSUE THREAD

**Issue by diyoyo** [matiasdelellis/facerecognition#557]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

When looking at an individual photo, if I change the name on the assigned face, I want only this photo to be reassigned to the new/other person

### Actual behaviour

Instead, it renames the entire cluster in which the current pic belonged. The worst part is that if the other person is existing, then it will merge the entire person's picset with the other person's.

### Steps to reproduce
1. Tag two different clusters with two different people
2. select one picture of the first person in the photo metadata viewer and edit the person's name
3. Enter the second person's name and Hit "rename"
4. Go check your new face organization in the settings

### Server configuration

* **Operating system:**

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by guystreeter** [comment]
The sidebar has 2 buttons by each name: `Rename person` and `This person is wrong`
`Rename person` will change that person's name everywhere.
`This person is wrong` will take that face out of the cluster. You can give that face a new name at the same time.
