### ISSUE TITLE
Impossible to remove face from a cluster when tagging

### ISSUE THREAD

**Issue by diyoyo** [matiasdelellis/facerecognition#558]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

I'd like to remove one or two wrong faces when clusters are shown for person naming.

### Actual behaviour

Either you skip, or you assign the entire cluster to the majority, which messes up the library.

### Steps to reproduce
1.
2.
3.

### Server configuration

* **Operating system:**

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Cebrain** [comment]
Also see this really important, i have some faces that are in the wrong cluster / group.
Would like to move single faces to another person.

**Comment by matiasdelellis** [comment]
Hi Both,
Use the sidebar option "This person is not THAT"
![imagen](https://user-images.githubusercontent.com/733715/207343965-bc216459-5fc0-4c7e-b3b0-813739e97505.png)

**Comment by matiasdelellis** [comment]
Now you can also use Memories. 😬
