### ISSUE TITLE
APT gpg key expired

### ISSUE THREAD

**Issue by bonswouar** [matiasdelellis/facerecognition#561]
_I couldn't find any existing issue about that, sorry if I missed it_

### Expected behaviour

Should be able to use the apt repo

### Actual behaviour

```logs
Err:11 https://repo.delellis.com.ar buster InRelease
  The following signatures were invalid: EXPKEYSIG 39217939ED3D07DB Matias De lellis <mati86dl@gmail.com>
[...]
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.delellis.com.ar buster InRelease: The following signatures were invalid: EXPKEYSIG 39217939ED3D07DB Matias De lellis <mati86dl@gmail.com>
W: Failed to fetch https://repo.delellis.com.ar/dists/buster/InRelease  The following signatures were invalid: EXPKEYSIG 39217939ED3D07DB Matias De lellis <mati86dl@gmail.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Steps to reproduce
1.  `echo "deb https://repo.delellis.com.ar buster buster" > /etc/apt/sources.list.d/20-pdlib.list`
1. `wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -`
1. `apt update`

### Server configuration

* **Operating system:**
Debian Buster

### Complementary information

It expired 3 days ago:
```logs
 pub   rsa3072 2020-03-12 [SC] [expired: 2022-03-12]
      8307CAB2B61BF4075378A94E39217939ED3D07DB
uid           [ expired] Matias De lellis <mati86dl@gmail.com>
```

**Comment by thenamelessthing** [comment]
same thing here!

**Comment by dmgeurts** [comment]
Yup, has anyone got a fix for this yet?

**Comment by matiasdelellis** [comment]
Hello everyone...
Excuse my little progress lately. 😞 

Just extend the gpk key but now you must update the certificate again..

```
wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
sudo apt update
```

**Comment by bonswouar** [comment]
Thanks @matiasdelellis ! I think I can close this now ;)
