### ISSUE TITLE
After change model, analyse began from start

### ISSUE THREAD

**Issue by PadseGaming** [matiasdelellis/facerecognition#564]
### Expected behaviour

Hi there! Hope that no one has ask for this before :) . I have analysed all my 40k pictures with Model 5 external on my GTX980. After the complete analyse i switched to model 1 and the analyse began again from the start. 

### Actual behaviour

I thought if i switch after the complete analyse back to model 1, the database save all the analysed pictures and i can continue with model 1. Isnt it so? 

### Steps to reproduce
1. Analyse Pictures external with Model 5 on a remote System in Network
2. Wait to complete
3. Switch back to Model 1
4. The external analyse should deletet and now u have to analyse all pictures again with model 1

### Server configuration

* **Operating system:**
Linux 5.15.27-v8+ aarch64 Raspberry 4B
NextcloudPI 23.0.2

* **PHP version:**
7.4.28
* **Web server:**
NextcloudPI
* **Database:**
MySQL

pdlib extension version => 1.0.2
dlib library version => 19.23.99

**Comment by matiasdelellis** [comment]
Use migrante command.. 😉

**Comment by PadseGaming** [comment]
ahhhhm, sorry i may can get ur app to work, but not without a explain xD what should i do, btw, how? Do u have allready written a explain for the migrante command?  :)

**Comment by PadseGaming** [comment]
Found it in ur description from the App. Now IT runs the Migrante :)) thanks!
