### ISSUE TITLE
WebDav external storage

### ISSUE THREAD

**Issue by diyoyo** [matiasdelellis/facerecognition#567]
Not an Issue, but a question before starting configuring FaceRecognition (FR) in my new instance of NextCloud.
Is it possible for FR to access files from the External Storage folders of NextCloud?
I would like to analyze images present in my pCloud account, connected to nextcloud using webdav.
Thanks.
Best,

**Comment by matiasdelellis** [comment]
Hi @diyoyo 
See https://github.com/matiasdelellis/facerecognition/wiki/Settings#hidden-settings

In spacial  `handle_external_files`
