### ISSUE TITLE
Read/write metadata for additional face identification 

### ISSUE THREAD

**Issue by MatthewBraun** [matiasdelellis/facerecognition#568]
I've used Digikam to sort faces/people for a while. I've also had Digikam write the face/people information into the picture metadata. I've attached an example below for person named BOBBY 

It would be awesome if nextcloud-facerecognition could read this metadata and start with a base of names & already tagged faces. All before a new scan is done. 

I have 4000+ images so not having to rescan and rename faces would be great! This would also help if someone ever had to start nextcloud from scratch after a boot drive died. 

Thumbnail Length                : 9586
XMP Toolkit                     : XMP Core 4.4.0-Exiv2
Warning                         : [minor] Fixed incorrect URI for xmlns:MicrosoftPhoto
Categories                      : <Categories><Category Assigned="0">People<Category Assigned="1">BOBBY</Category></Category></Categories>
Region Type                     : Face
Region Area Y                   : 0.38
Region Area W                   : 0.15599999999999997
Region Area X                   : 0.52800000000000002
Region Area H                   : 0.20799999999999996
Region Area Unit                : normalized
Region Extensions Angle Info Yaw: 0
Region Extensions Angle Info Roll: 0
Region Extensions Confidence Level: 396
Region Extensions Face ID       : 3
Region Applied To Dimensions H  : 3024
Region Applied To Dimensions W  : 4032
Region Applied To Dimensions Unit: pixel
Tags List                       : People/BOBBY
Last Keyword XMP                : People/BOBBY
Hierarchical Subject            : People|BOBBY
Catalog Sets                    : People|BOBBY
Subject                         : BOBBY

**Comment by matiasdelellis** [comment]
Hi @MatthewBraun 
Sorry the delay in answering..

Unfortunately, is unlikely that we will do this. See https://github.com/matiasdelellis/facerecognition/issues/321
