### ISSUE TITLE
Cluster creation not work after faces:reset --clustering

### ISSUE THREAD

**Issue by mostofthetime** [matiasdelellis/facerecognition#584]
Hi, 
i reset the cluster after an issue that faces from 7000 new processed photos not showing up in the Face Recognitaion UI. Now the backround job says after clustering "Skipping cluster creation, not enough data (yet) collected". This will be happend after every run.
All photos are fully processed

### Expected behaviour

----------------
Stats
+--------------+--------+-------+---------+---------+
| User         | Images | Faces | Cluster | Persons |
+--------------+--------+-------+---------+---------+
| User 1| 32031  | 23013 | 11414   | 0       |
| User 2| 0      | 0     | 0       | 0       |
+--------------+--------+-------+---------+---------+

Progress

+--------+-----------+-----+
| Images | Remaining | ETA |
+--------+-----------+-----+
| 32031  | 0         | -   |
+--------+-----------+-----+

![grafik](https://user-images.githubusercontent.com/58307448/173068250-9adf07f3-3f9f-41e6-88de-cda680a64c90.png)

### Actual behaviour

Tell us what happens instead

### Steps to reproduce
1. Scan 7000 new photos
2. Issue no new faces or cluster showing up in UI
3. Reset cluster with faces:reset --clustering
4. Runing face:background_job -vvv many times

### Server configuration

* **Operating system:** Debian 11

* **Pdlib version:** 

* **How is DLib installed:** Clone git / latest version

* **How is PDlib installed:** Clone git / latest version

* **PHP version:** 7.4-fpm

* **Web server:** nginx

* **Database:** MariaDB

* **Nextcloud version:** 24.0.1

### Client configuration

* **Browser:** IE, Chrom, Firefox

* **Operating system:**  Windows 11

### Logs
No Errors in Log

#### Background task log with debug.
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
        Skipping stale images removal for user User 1as there is no need for it
        Skipping stale images removal for user User 2 as there is no need for it
**6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Face clustering will be created for the first time.
        23013 faces found for clustering
        11414 persons found after clustering
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress**
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Skipping full image scan for user User 1
        Skipping image scan for user User 2 that has disabled the analysis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/fac>
10/10 - Executing task UnlockTask (Release obtained lock)

#### Web server error log
No errors in log

**Comment by matiasdelellis** [comment]
Hi @mostofthetime 
You seem to confuse a detail, the background task, group the faces into clusters, 

+--------------+--------+-------+---------+---------+
| User | Images | Faces | Cluster | Persons |
+--------------+--------+-------+---------+---------+
| User 1| 32031 | 23013 | 11414 | 0 |
| User 2| 0 | 0 | 0 | 0 |
+--------------+--------+-------+---------+---------+

See.. You have 11414 and 0 persons.. and persons are just named clusters. 

However, I also recognize that the second message is confusing, I will review it.. 🤔

**Comment by mostofthetime** [comment]
Ho @matiasdelellis 
correct, but i can't recognize any face in the ui. The button "There are more persons to recognize" isn't showing after the "faces:reset --clustering". Is there any chance to force the recognize?
