### ISSUE TITLE
Installation on Ubuntu 20.04.4 Focal Fossa LTS with arm64 on raspberry pi 4

### ISSUE THREAD

**Issue by exaveal** [matiasdelellis/facerecognition#587]
When trying to install PDLib on Ubuntu according to the insatallation guide, i just get this:
`root@frida:~# echo "deb https://repo.delellis.com.ar focal focal" > /etc/apt/sources.list.d/20-pdlib.list
root@frida:~# wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
OK
root@frida:~# apt update
Hit:1 https://deb.troglobit.com/debian stable InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease                 
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease         
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease       
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:6 https://repo.jellyfin.org/ubuntu focal InRelease       
Get:7 https://repo.delellis.com.ar focal InRelease [3654 B]  
Fetched 3654 B in 3s (1437 B/s)                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'focal/binary-arm64/Packages' as repository 'https://repo.delellis.com.ar focal InRelease' doesn't support architecture 'arm64'
root@frida:~# apt install php7.4-pdlib
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.4-pdlib
E: Couldn't find any package by glob 'php7.4-pdlib'
`

So is there a away to install the face recognition app on Ubuntu 20.04 LTS on ARM64 (Raspberrypi 4)?

**Comment by mostofthetime** [comment]
You can try to install pdlib and dlib manually.

https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation#install-dlib
https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation#install-pdlib

**Comment by exaveal** [comment]
Thanks, the guide was really perfect for newbies like me!

**Comment by sirdrakeistda** [comment]
@exaveal How did you managed to compile this? I get a lot of error messages.

It would be much easier if the repository would also include the architecture for the raspberry pi.

**Comment by sirdrakeistda** [comment]
@matiasdelellis If found my problem:
https://github.com/goodspb/pdlib/issues/50
Could you update the wiki or should this be fixed by pdlib? Maybe this could help other people to get pdlib running.
