### ISSUE TITLE
Auto tagging based on faces recognized

### ISSUE THREAD

**Issue by servoronine** [matiasdelellis/facerecognition#588]
Hi,

Apologies, this is more of a question then an issue, but I could not work out if this is possible. The app does a great job of recognizing and grouping faces (and adding metadata).

However this does not help with the Nextcloud Photos app which cannot use (as far as I can tell) the metadata to cluster photos. The description of the application says that it could be possible to automatically tag photos based on faces recognized but I cannot work out how to do it...

Could you please help?

Kind Regards,
Sergey

**Comment by matiasdelellis** [comment]
Ohh,
I understand the confusion, but we don't tag using the nextcloud tagging system, because we think it's wrong. See https://github.com/matiasdelellis/facerecognition/issues/292

Sorry..
😞
