### ISSUE TITLE
add support für Nextcloud 25

### ISSUE THREAD

**Issue by jakobroehrl** [matiasdelellis/facerecognition#595]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by jakobroehrl** [comment]
Tested in my NC25 instance. There are no pics shown:

![image](https://user-images.githubusercontent.com/24530680/192492067-16b9dcf7-6fbe-4e39-8cf8-85463de8224a.png)

**Comment by jakobroehrl** [comment]
It would be awesome if we could show up the faces here in the photo app:
![image](https://user-images.githubusercontent.com/24530680/192492429-8e006df1-a45b-4efe-a034-322c24aa5ead.png)

https://apps.nextcloud.com/apps/recognize is doing that.

**Comment by matiasdelellis** [comment]
Hi @jakobroehrl 
About Nextcloud 25, just uploaded an update that enables it. 😉 

About recognize/nextcloud 25, I want to be respectful and not start any controversy. See #593

**Comment by jakobroehrl** [comment]
Thanks a lot. :)
What I also noticed: The Person tab is shown on all file types, I don't know if this is a problem:
![image](https://user-images.githubusercontent.com/24530680/192691431-6f87f327-2ba0-48ef-a8ab-1bd1e2b8c924.png)

**Comment by martadinata666** [comment]
just adding, for nextcloud 25, when renaming or adding label no suggested name pop up, like 0.9.5 has.

**Comment by Newinvestcoin** [comment]
hm.. in apps in nc25 only 0.9.5 version. How update? And how add link in photos to facerecognition?

**Comment by martadinata666** [comment]
you can download the beta version release and extract to `custom_apps` directory

**Comment by matiasdelellis** [comment]
> Thanks a lot. :) What I also noticed: The Person tab is shown on all file types, I don't know if this is a problem: ![image](https://user-images.githubusercontent.com/24530680/192691431-6f87f327-2ba0-48ef-a8ab-1bd1e2b8c924.png)

I will probably have to abandon jquery and migrate this page to vue too.. 😞

**Comment by matiasdelellis** [comment]
I just released an update that can be installed from the app store.. 😉 

He has things pending, but at least it will work for everyone ..

**Comment by matiasdelellis** [comment]
p.s: Install [memories](https://github.com/pulsejet/memories). 😉 😄 😬
