### ISSUE TITLE
Allow edition from other apps outside Nextcloud (API needed)

### ISSUE THREAD

**Issue by luckkmaxx** [matiasdelellis/facerecognition#598]
Hi there! As some people requested integration with built-in Photos app, there are apps outside nextcloud that could need edition access to face recognition app.
My case is with Photos app from "nkming" (https://gitlab.com/nkming2/nc-photos) and the need to edit people names from there. I opened an issue there (https://gitlab.com/nkming2/nc-photos/-/issues/127). Im contributor there but just for translations and I have no idea about any programming language. I hope you guys make possible the external edition some day.
Thanks for your work!

**Comment by matiasdelellis** [comment]
Done on last beta.. 😉

**Comment by luckkmaxx** [comment]
Wow very nice!
A thousand Thanks!
