### ISSUE TITLE
background_job log

### ISSUE THREAD

**Issue by brccabral** [matiasdelellis/facerecognition#601]
Hi,
When running background_job it produces many messages into stdout. Are they saved in any log file? Regular "data/nextcloud.log" doesn't show any facerecognition messages.
Thanks

**Comment by matiasdelellis** [comment]
Hi @brccabral
The command while running print a lot of info just to track the progress, however it does not send this info to the nextcloud log.

In case of errors, which are relevant to the administrator, will be sent to this log as expected, but the progress information not.

If you want to keep this info log, just add a pipe to the command.

```sudo -u apache php occ face:background_job >> /tmp/facereconition.log```

**Comment by brccabral** [comment]
Understood, thanks
