### ISSUE TITLE
Unable to set memory limit with occ command

### ISSUE THREAD

**Issue by Nomcon** [matiasdelellis/facerecognition#605]
I just installed the face recognition app and everything is looking fine. But when i try to run the commands from [https://github.com/matiasdelellis/facerecognition/wiki/Installation#setup](https://github.com/matiasdelellis/facerecognition/wiki/Installation#setup) nextcloud throws the error ``cannot write to "config" directory.``

### Expected behaviour
command should set memory limit for face recognition app.

### Actual behaviour
error

### Server configuration

* **Operating system:**
* Ubuntu 20.04

* **Pdlib version:**
*  php7.4-pdlib                          1.0.2-1
* 
* **How is DLib installed:**
* Through the commands provided [here](https://github.com/goodspb/pdlib#dlib)

* **How is PDlib installed:** 
* Through the [provided repo](https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation#ubuntu-focal)

* **PHP version:**
* 7.4.3

* **Web server:**
* apache2

* **Database:**
* mysql

* **Nextcloud version:**
* 23.0.10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Pls let me know what logs u might need and where to find them
```
</details>

I was ofc searching the web for this issue already but it accurs on so many different versions of nextcloud that its 1st hard to figure out what the solution was and 2nd the solution might not be applicable for my install.
I tried every solution i've come across on which i could figure out how to execute it in my install but nothing  helped.

Therefore, i came here hoping that there might be another way to set those values supposed to be set by the commands.
Maybe I could alter the nextclouds config.php or a different config file?

**Comment by matiasdelellis** [comment]
Hi @Nomcon 
Very strange.. The application does not write to the config/config.php.. It writes to the database. 🤔 

In general, any similar report is usually folder permissions... I can't help you much more.

**Comment by matiasdelellis** [comment]
Well, Information is missing. 😞
