### ISSUE TITLE
Can not save image area used for temporary files due to missing CSS

### ISSUE THREAD

**Issue by florianwgnr** [matiasdelellis/facerecognition#610]
### Expected behaviour

A save button should appear after setting the size of temporary files. 

### Actual behaviour

The save button does not appear. DevTools show that /apps/facerecognition/css/facerecognition.**css** is missing.

After looking on my server, there is only a facerecognition.**scss** file.

I installed the app through nextcloud app store. 

=> The file is missing in the latest release. See .tar.gz at https://github.com/matiasdelellis/facerecognition/releases/tag/v0.9.5

**Comment by Cebrain** [comment]
Same problem for me

**Comment by rhatguy** [comment]
Same problem.  I installed the latest version from the app store into the Nextcloud docker image.  No save button, so I can't configure a temporary directory, so can't start the background_job.  This is what the custom_apps folder has in my install.

I have no name!@f563de84d67b:/var/www/html/custom_apps/facerecognition/css$ ls -l
total 8
-rw-rw-rw- 1 99 users 1391 Dec  9 12:36 facerecognition.scss
-rw-rw-rw- 1 99 users  812 Dec  9 12:36 fr-dialogs.scss

**Comment by matiasdelellis** [comment]
Hello everyone,
It was due to an unnecessary change from Nextcloud, and there was a beta that fixed the problem a long time ago. however it was not installable from the store..

Now you can update... 😉
