### ISSUE TITLE
Face Recognition is really slow

### ISSUE THREAD

**Issue by sirdrakeistda** [matiasdelellis/facerecognition#612]
### Expected behaviour

I read your limitations:
https://github.com/matiasdelellis/facerecognition/wiki/Requirements-and-Limitations
according to this an image should be processed in a few minutes. Changing the temporary file size should make the processing faster

### Actual behaviour

Processing one image is really slow. I run a cron job every 30 minutes (described in the installation section). Per day only ~100 images are processed. This is much less then expected. Changing the temporary file size does not speed up the process. The model 1 is used. Also the server has no significant load.

### Steps to reproduce
1. Install App
2. create cron job or process the images manually.
3. really slow

### Server configuration

* **device**
Raspberry Pi 4 8GB
* **Operating system:**
Debian bullseye
* **Pdlib version:**
newest github version
* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
self compiling,, tested succesfully
* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
self compiling, tested succesfully
* **PHP version:**
8.1.13
* **Web server:**
Apache
* **Database:**
Mysql
* **Nextcloud version:**
25.0.1
* **PHP memory_limit**
5,7GB
* **App memory limit**
4GB

#### Web server error log
 no error

#### Nextcloud log (data/nextcloud.log)
no error

**Comment by matiasdelellis** [comment]
Hi @sirdrakeistda 
I'm surprised it's so slow. Maybe dlib was compiled in debug mode, however, after verifying that, for a raspberry pi, I would recommend using an external model.

I hope to be able to do a test soon at RPI 🤔

**Comment by sirdrakeistda** [comment]
I am unaware of compiling it in debug mode, I followed your instructions. The only thing I changed was the c version. I had to switch c version (c14 is needed without tweaking c11 is used and wont compile). It might be helpfull to add this info to the installation instructions.

**Comment by SKB-CGN** [comment]
An RP4 is also not the best choice for doing picture jobs with that small CPU.
Even on my new server, the image scanning takes 60 sec per picture and the CPU is fired with 45%.

**Comment by sirdrakeistda** [comment]
I recompiled it. It is a lot faster. I think it was my fault. Sorry for this issue. This is  great app. Keep developing.
