### ISSUE TITLE
Allow user to specify used memory

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#62]
We can have some setting (not per person, it needs to be admin setting) to allow admin to choose amount of memory for our app to use. This will, in turn, affect image size that we scale image to, and that means more faces that can be recognized. This should be some advanced setting. It should be in [1GB, `memory_limit`] range. Use cases:
* User have `memory_limit` to 8GB and do not want PHP to use whole 8GB, but only 4GB
* User have `memory_limit` to -1, and system RAM to 4GB and do not want our app to use 2GB, but 3GB.

**Comment by matiasdelellis** [comment]
Clone via #144
