### ISSUE TITLE
debian 11 support for php8.1

### ISSUE THREAD

**Issue by blackwhitebear8** [matiasdelellis/facerecognition#625]
when will there be a php8.1 version for debian?

**Comment by tellustheguru** [comment]
Check this: https://computingforgeeks.com/how-to-install-php-on-debian-linux-2/

**Comment by matiasdelellis** [comment]
About a pdlib package with php 8.1 I'm not going to do it since it should be done against the repository you're using to backport php.. Sorry.

maybe you can easily compile it using the new effort to use pecl.. 
* https://github.com/goodspb/pdlib/issues/56

**Comment by matiasdelellis** [comment]
Hi,
I invite you to try the [external model](https://github.com/matiasdelellis/facerecognition-external-model), using the [latest version](https://github.com/matiasdelellis/facerecognition/releases/tag/v0.9.30) released.

Open a new issue to see how we continue. 😬
