### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by tekntrash** [matiasdelellis/facerecognition#627]
I have followed the steps at https://github.com/goodspb/pdlib to install PDLIB and even used https://github.com/matiasdelellis/pdlib-min-test-suite to try it and it runs just fine

Still, when I try to install it using the store it says "An error occurred during the request. Unable to proceed. App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available."

Then I try to install it manually as instructed by https://github.com/matiasdelellis/facerecognition/wiki/Installation#install-facerecognition-app and put it at /var/snap/nextcloud/33054/nextcloud/extra-apps where my apps are located, everything seems to go fine, and when I type nextcloud.occ app:enable facerecognition it still says the annoying "App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available"

I am using nextcloud snap Hub 3 25.0.2 over Linux Mint 20.3, PHP 7.4.3, npm 6.14.4, node v10.19.0, snap 2.57.6

**Comment by guydelarea** [comment]
did you checked the php.ini config to see if the pdlib libary got added?
what happend if your run: `php -m | grep pdlib` ?

**Comment by tekntrash** [comment]
Actually, I found out the problem is that it will NEVER apply to a snap, as that will require recompiling it and that's something only the company that created it (canonical) will do, so the only option is to completely remove nextcloud and reinstall it as a server. Which I did and after trying 12 times and not getting support from its people I was able to finally get it working

**Comment by NikitaKorneev** [comment]
If this is true - this is extremely sad. Is there anything we can do to make the two worlds collide? (Snap and pdlib)

**Comment by matiasdelellis** [comment]
Hi,
I invite you to try the [external model](https://github.com/matiasdelellis/facerecognition-external-model), using the [latest version](https://github.com/matiasdelellis/facerecognition/releases/tag/v0.9.30) released.

Open a new issue to see how we continue. 😬
