### ISSUE TITLE
Unable to delete app

### ISSUE THREAD

**Issue by GUNT0815** [matiasdelellis/facerecognition#629]
- I use Nextcloud-aio (docker) version 4.1.0
- installed face recognition v0.9.11
- deactivated the app
- now want to delete the app
- message: "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden."
- expected behaviour:  app is deleted

**Comment by matiasdelellis** [comment]
Hi,
There is no limitation on our part to delete the app.. But I understand that within nextcloud AIO, you cannot delete applications like that.

https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
