### ISSUE TITLE
Unable to install | repo key is unavaliable

### ISSUE THREAD

**Issue by enoch85** [matiasdelellis/facerecognition#631]
**wget https://repo.delellis.com.ar/repo.gpg.key**

```

--2023-01-20 13:44:04--  https://repo.delellis.com.ar/repo.gpg.key
Resolving repo.delellis.com.ar (repo.delellis.com.ar)... 108.161.143.36
Connecting to repo.delellis.com.ar (repo.delellis.com.ar)|108.161.143.36|:443... connected.
ERROR: cannot verify repo.delellis.com.ar's certificate, issued by ‘emailAddress=support@fortinet.com,CN=FortiGate CA,OU=Certificate Authority,O=Fortinet,L=Sunnyvale,ST=California,C=US’:
  Self-signed certificate encountered.
To connect to repo.delellis.com.ar insecurely, use `--no-check-certificate'.
```

**wget --no-check-certificate https://repo.delellis.com.ar/repo.gpg.key**

```
--2023-01-20 13:45:43--  https://repo.delellis.com.ar/repo.gpg.key
Resolving repo.delellis.com.ar (repo.delellis.com.ar)... 108.161.143.36
Connecting to repo.delellis.com.ar (repo.delellis.com.ar)|108.161.143.36|:443... connected.
WARNING: cannot verify repo.delellis.com.ar's certificate, issued by ‘emailAddress=support@fortinet.com,CN=FortiGate CA,OU=Certificate Authority,O=Fortinet,L=Sunnyvale,ST=California,C=US’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 403 Forbidden
2023-01-20 13:45:44 ERROR 403: Forbidden.
```

**wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -**

`gpg: no valid OpenPGP data found.
`
## Possible fix

I think you need to fix your TLS certificates on the Fortigate firewall. :)

**Comment by hillbicks** [comment]
The certificate was valid until yesterday
![image](https://user-images.githubusercontent.com/3480073/213790961-abe66927-4941-4cdc-8a14-edf65a0a9ca4.png)

Seems like the certbot systemd.timer or cronjob failed to renew the cert :p

**Comment by enoch85** [comment]
> The certificate was valid until yesterday ![image](https://user-images.githubusercontent.com/3480073/213790961-abe66927-4941-4cdc-8a14-edf65a0a9ca4.png)
> 
> Seems like the certbot systemd.timer or cronjob failed to renew the cert :p

Yup, or some port that's closed , or a new firewall in place without proper configuration, or something similar. Cronjob timer actually never failed me - if setup correctly.

**Comment by matiasdelellis** [comment]
Updated several days ago. Thank you for reporting it. 😄

**Comment by jivanpal** [comment]
Looks like it's that time again; the current cert expired 5 hours ago :grinning:
