### ISSUE TITLE
Review found people not showing the detected face

### ISSUE THREAD

**Issue by ManuXD32** [matiasdelellis/facerecognition#636]
### Expected behaviour

Show the faces you are going to name on the thumbnails after pressing the button "Review found people"

### Actual behaviour

After waiting 18 days for the recognition to be finished, finally the button appeared and i tried to put a name to the grouped faces but i do not know which face it's asking me about.

![imagen](https://user-images.githubusercontent.com/49831470/218327015-cd3c136b-6c9b-49dc-ac25-47fd7c94277d.png)

### Server configuration

* **Operating system:**
Ubuntu server 22.04 LTS

* **PHP version:**
8.1

* **Web server:**
Apache2

* **Database:**
PostgreSQL

* **Nextcloud version:**
25.02

### Client configuration

* **Browser:**
Firefox

* **Operating system:**
Fedora

**Comment by ManuXD32** [comment]
So... any news about this?

**Comment by matiasdelellis** [comment]
Hi @ManuXD32 
Two questions.. .

How you install the app?.
If you just installed from git and in particular the Imaginary branch, there is a bug that imaginary doesn't resize images correctly and causes this problem.

If not, are there faces in these images?
The face detector can have false positives, and they can be grouped as "persons"

**Comment by ManuXD32** [comment]
Yeah, there are faces on those images and i installed the app from nextcloud app store.

**Comment by ManuXD32** [comment]
> Can you send me a photo with the side panel in one of those photos.. ? Maybe you could send me a test photo privately.
> 
> For example, this is a false positive.. see_no_evil ![imagen](https://user-images.githubusercontent.com/733715/222172397-6fafdd12-1753-44d8-b115-c9234d8dfc4b.png)
> 
> Just fix the imaginary branch, but your case seems very strange to me since you are using the program from the appstore. thinking

Yeah, i'll send it to you as soon as the button appears again :'(

**Comment by matiasdelellis** [comment]
Well... I guess I can close this issue.. 

Thanks-
