### ISSUE TITLE
Failed to install Model 1

### ISSUE THREAD

**Issue by someone132s** [matiasdelellis/facerecognition#637]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Couldn't install model 1 or 2 or 3 or 4, and having no error messages.

### Actual behaviour

I successfully set the PHP's memory to 1024MB, and tried to install the model 1. And I have no error messages like

 'The current PHP memory limit is below the recommended value of 512MB.' 

it's just prompted me like this.

'
You do not meet the dependencies to install the model 1 (Default)
Summary: Seems that you still have to configure the assigned memory for image processing.
Please read the documentation for this model to continue: https://github.com/matiasdelellis/facerecognition/wiki/Models#model-1
'
 i checked the memory limits i set, it's correct. And when i set the limits below 512M, the message of recommand value appears again.

### Steps to reproduce
1. install normally until the installation of models
2. try to install models
3. happens

### Server configuration

* **Operating system:** Centos 8 updated to Centos Stream

* **Pdlib version:** 1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:** 8.2.3

* **Web server:** Apache/2.4.37 (centos)

* **Database:** php-mysqlnd-8.1.16-1.el8.remi.x86_64

* **Nextcloud version:25.3

### Client configuration

* **Browser:Firefox

* **Operating system:Win11_Worstation

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
PHP Warning:  Module "imagick" is already loaded in Unknown on line 0
1/8 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 67116191744
        PHP Memory Limit: 1073741824
        Seems there are no installed models.
Please read the documentation about this: https://github.com/matiasdelellis/facerecognition/wiki/Models#install-models
and install them with the 'occ face:setup --model MODEL_ID' command.

Fill an issue here if that doesn't help: https://github.com/matiasdelellis/facerecognition/issues
Task CheckRequirementsTask signalled we should not continue, bailing out

```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by DeerMaximum** [comment]
I have the same issue. Is there any fix?
