### ISSUE TITLE
Not using GPU despite being installed

### ISSUE THREAD

**Issue by tekntrash** [matiasdelellis/facerecognition#640]
I have a GPU and correctly installed CUDA and the system uses the CPU instead which takes forever to identify images

Being able to use my GPU would be nice, thanks

**Comment by matiasdelellis** [comment]
Hi @tekntrash 
I don't have any experience with CUDA as unfortunately it is out of my financial means. hahaha..

But theoretically if I have CUDA correctly installed, you must compile dlib yourself, and then pdlib. 

Try it, it shouldn't be complicated... 😬
