### ISSUE TITLE
Master ranch not passing integrity check : not signed

### ISSUE THREAD

**Issue by nyok92** [matiasdelellis/facerecognition#643]
Neextcloud / Administration / Overview : Some files have not passed the integrity check

Master branch not[ code signed by Nextcloud ](https://docs.nextcloud.com/server/25/developer_manual/app_publishing_maintenance/code_signing.html#how-to-get-your-app-signed)

```
Security & setup warnings
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the linked documentation for more information.

There are some errors regarding your setup.
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the [documentation ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-code-integrity). ([List of invalid files…](XXX))
Please double check the [installation guides ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-install), and check for any errors or warnings in the [log](XXX).

Check the security of your Nextcloud over [our security scan ↗](https://scan.nextcloud.com/).
```

**Comment by matiasdelellis** [comment]
The app is only signed for the app store, if you build the app from git/tarball, it will always show something like that, even though it works fine..

maybe you have to install it in the `custom_apps` folder, although I never use it because it is not well documented. 🤔

**Comment by nyok92** [comment]
Issue solved, i was using an old version.
ok with v0.9.11
