### ISSUE TITLE
Sidebar: "Image not analysed", Progress: "0 left for analyse"

### ISSUE THREAD

**Issue by lippoliv** [matiasdelellis/facerecognition#644]
### Expected behaviour

Once uploaded, face recognition should analyze images in the background job, which I run every 5 minutes. If the progress tells me, that there are no images left, I considere it to have done all analytics.

### Actual behaviour

I uploaded a new image two hours ago. In the sidebar I see "This picture is not analysed yet, please wait" (translated from german), but in the progress on `occ face:progress`, I see 0 remaining.

### Steps to reproduce
1. Upload a new image
2. Run the background job
3. Check the progress
4. Review which faces where recognized

### Server configuration

* **Operating system:** Docker `nextcloud:25.0.4-apache`

* **Pdlib version:**
    ```
    ARG DLIB_BRANCH=v19.24
    ARG PDLIB_BRANCH=master
    ```

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:** `PHP 8.1.16`

* **Web server:** `Apache`

* **Database:** `mariadb:10.5`

* **Nextcloud version:** 25.0.4

### Client configuration

* **Browser:** Tested in Brave

* **Operating system:** Windows 10

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>
```
1/8 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 134862925824
        PHP Memory Limit: 2147483648
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
yielding
yielding
yielding
yielding
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
        Skipping stale images removal for user 1 as there is no need for it
        Skipping stale images removal for user 2 as there is no need for it
        Skipping stale images removal for user 3 as there is no need for it
        Skipping stale images removal for user 4 as there is no need for it
        Skipping stale images removal for user 5 as there is no need for it
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Found 1 faces without associated persons for user oliver and model 2
        Oldest face without persons for user 5 and model 2 is from 2023-03-11 07:25:06
        Clusters already exist, estimated there is no need to recreate them
yielding
6/8 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
        Skipping image scan for user 1 that has disabled the analysis
        Skipping image scan for user 2 that has disabled the analysis
        Skipping image scan for user 3 that has disabled the analysis
        Skipping image scan for user 4  that has disabled the analysis
        Skipping full image scan for user 5
7/8 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
8/8 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Unrelated
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Unrelated
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Unrelated
```
</details>

#### Stats (in case needed)
<details>
<summary>sudo -u apache php occ face:stats</summary>

| User         | Images | Faces | Clusters | Persons |
|---|---|---|---|---|
| 1 | 0      | 0     | 0        | 0       |
| 2 | 0      | 0     | 0        | 0       |
| 3 | 0      | 0     | 0        | 0       |
| 4 | 0      | 0     | 0        | 0       |
| 5 | 17091  | 5454  | 2783     | 82      |
</details>

**Comment by xwyangjshb** [comment]
My problem is same as you. Why cannot seen any Clusters and Persons?  thanks.
www-data@a0135ed2509e:~/html$ ./occ face:stats

> +---------+--------+-------+----------+---------+
> | User    | Images | Faces | Clusters | Persons |
> +---------+--------+-------+----------+---------+
> | admin   | 9      | 0     | 0        | 0       |
> | andy    | 139610 | 8044  | 0        | 0       |
> | honey   | 25882  | 5520  | 0        | 0       |
> | jessica | 0      | 0     | 0        | 0       |
> | xiaoxia | 0      | 0     | 0        | 0       |
> +---------+--------+-------+----------+---------+

**Comment by lippoliv** [comment]
@xwyangjshb if you're doing initial scan, this is because not 95% of your data hase been scanned, see background job output 

```
For cluster creation, you need either one of the following: 
* have 1000 faces already processed 
* or you need to have 95% of you images processed
```

**Comment by xwyangjshb** [comment]
> @xwyangjshb if you're doing initial scan, this is because not 95% of your data hase been scanned, see background job output
> 
> ```
> For cluster creation, you need either one of the following: 
> * have 1000 faces already processed 
> * or you need to have 95% of you images processed
> ```

yes. You're right. I have process my photoes more than 24 hours. Thank u!

**Comment by matiasdelellis** [comment]
I guess it worked. 🙈 

Thanks.
