### ISSUE TITLE
How/which config to detect dogs? 

### ISSUE THREAD

**Issue by Chuckame** [matiasdelellis/facerecognition#647]
Hey, I just wanted to know how to configure well to detect dog face, or full dog body since some text from screenchots or other dogs/monkeys are detected, and also another white dog... But not my dog!! 😃

**Comment by matiasdelellis** [comment]
😅 
This is very foreign to the original project, limited to faces, but to give you an idea of the work you can see this project.

https://hypraptive.github.io/bearid-project/
