### ISSUE TITLE
PHP8.2 support /Debian 11 - pdlib and rest is working well (self compiled)

### ISSUE THREAD

**Issue by axeljerabek** [matiasdelellis/facerecognition#648]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Want to activate the facerecognition app

### Actual behaviour

App not able to be activated. Says that php8.2 is not supported

### Steps to reproduce
1. Install facerecognition app
2. Activate it

### Server configuration

Raspberry Pi 4 - Debian 11 - Kernel  5.15.84-v8+- PHP 8.2.3

* **Pdlib version:**

1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
manual

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
manual

* **PHP version:*8.2.3

* **Web server:** Apache/2.4.54 (Debian)

* **Database:** mysqld 10.5.18-MariaDB-0+deb11u1

* **Nextcloud version:** 26RC2

### Client configuration

* **Browser:**
any

* **Operating system:** Debian 11 64bit

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by axeljerabek** [comment]
Thanks! :)

**Comment by axeljerabek** [comment]
Just edited the info.xml and the background job works again. Also everything seems back to normal again, no errors.

**Comment by matiasdelellis** [comment]
Thanks
