### ISSUE TITLE
PHP7.4, Debian 11, face recognition installation is complaining of missing pdlib

### ISSUE THREAD

**Issue by drumstick77** [matiasdelellis/facerecognition#649]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

it should just install facerecognition via app via Web UI

### Actual behaviour

PHP7.4, Debian 11, face recognition installation is complaining of missing pdlib

### Steps to reproduce
1. went to app within the webui
2. searched for facerecognition
3. click download and enable

### Server configuration

* **Operating system:**
debian bullseye

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**
7.4
* **Web server:**

* **Database:**
mySQL
* **Nextcloud version:**
25.04
### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi,
I invite you to try the [external model](https://github.com/matiasdelellis/facerecognition-external-model), using the [latest version](https://github.com/matiasdelellis/facerecognition/releases/tag/v0.9.30) released.

Open a new issue to see how we continue. 😬
