### ISSUE TITLE
Do not do face recognition for small images

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#65]
I got bunch of small files in my instance (from random programs, games, books, backups, I don't even know from where:)). They are not in my "main" directory of photos. I do not want recognition on them, because it will take needless time, needless DB space and will add noise to results. I think proper solution might be having whitelist/blacklist of folders per user, but it adds another layers of complexity. I think what we can do now is to ignore small files. Let's say - all files:
* with less than 0.5MP (megapixels), **or**
* width < 500px, **or**
* height < 500px
are most likely not coming from digital camera and we should be ignoring them. This should be configurable though, so advanced users can set this config.

**Comment by stalker314314** [comment]
So, I was thinking a bit about this. There are different ways to fix this. Here is 3 that came to my mind:
1. Ignore small images in both `AddMissingImagesTask` **AND** `Watcher::postWrite`. Read image from those places in code, and just don't add it to `facerecognition_images` table. I don't like this as we need to
    * open image/read file when we didn't do it before (I would like to read file from one task only),
    * complicate Watcher logic (and Watcher should be rock solid). We also need to be careful in Watcher::postDelete
    * duplicates this "ignore" filter to two places (code will be reused, but filtering logic will be in two places)
2. Just throw exception in `ImageProcessingTask`. Some new exception, let's say `ImageTooSmallException`. That exception will be remembered in `facerecognition_images` and image will be ignored in future. However, I don't like this because:
    * We use exception for non-exceptional situations
    * We complicate handling of images with exceptions between real exceptions and non-real exceptions
    * In future, we might show images with exception to users, or show some statistics about number of non-processed images and we will count all those small images in this statistics (witch doesn't makes sense to me)
3. Just ignore it from `ImageProcessingTask`. No exceptions, just ignore, mark it as processed, with no faces found in these images.

Number 3 looks most logical, cleanest and easiest to me. Do you agree, @matiasdelellis ? (asking before pushing any code)

**Comment by stalker314314** [comment]
OK, I see three different issues here:
1. Do we need per-folder settings  with some .nofacemedia settings (I would say this is separate issue than this and would ignore it in this chat). If you are OK with it, I will create separate task to brainstorm on this.
2. Do you agree with my solution *how** to ignore small images. This is blocking me to send PR.
3. What is default value for ignoring? Currently, I put it to 512x512. But if you say whatsapp is having images lower than this, we can lower that value. In fact, we can even put it to 0x0 (effectively "do not ignore small images at all"), but face recognition is currently unusable for me, and I would change config value for this, so I can change value to what suits me

**Comment by stalker314314** [comment]
So, I created push request, to explain better what was my proposal (code speaks better than words:D) Check it out, please

> On the other hand, these imaganes are so small that the analysis is relatively fast.

Unfortunately, with latest calculations I introduced, even small images are getting upscaled, so even 512x512 image might get resized to 2048x2045 (of course, depending on memory). I think we should also fix this, but not sure what should be proper algorithm:)

**Comment by matiasdelellis** [comment]
I had not noticed this.. :sweat_smile:

MM... In terms of development, it should be easy..
https://github.com/matiasdelellis/facerecognition/blob/001730d82ce1bd122715dce3a274b51bab76cd2f/lib/BackgroundJob/Tasks/ImageProcessingTask.php#L272

> if (scaleFactor > 1.0)
> scaleFactor = 1.0..

Without thinking much ... maybe it's wrong .. :sweat_smile: 
My doubt now is if I saw good results due the oversizing of images, but in any case I would prefer that they not be enlarged.
