### ISSUE TITLE
Full analysis does not start - ends with skipping of clustering 

### ISSUE THREAD

**Issue by SaschaMuehl** [matiasdelellis/facerecognition#654]
Hallo, 
unfortunatelly the full analysis does not start. It ends with skipping of the clustering. Does I do sth. wrong? (I also run the Nextcloud app recognition and was running the index before)

### Expected behaviour

Start of full anaylsis with: 
`sudo -u www-data php /var/www/nextcloud/occ face:background_job -u Sascha`
and with special setup
`sudo -u www-data php /var/www/nextcloud/occ face:background_job -u Sascha -t 900 --defer-clustering --max_image_area 1671x1253`

### Actual behaviour

ends with skipping of clustering
![image](https://user-images.githubusercontent.com/62723171/226843717-958d8410-d273-44db-b789-6576f5bcc071.png)

### Steps to reproduce
1. Model and Memory settled up
![image](https://user-images.githubusercontent.com/62723171/226839543-e9776519-0aad-47a8-af72-074bc297428b.png)

2. Analysis for user "Sascha" is activated
![image](https://user-images.githubusercontent.com/62723171/226839735-1688aecf-ff37-4b11-892f-164615537d42.png)

3. running Test for User Sascha
![image](https://user-images.githubusercontent.com/62723171/226841880-8c39e992-0ce6-4a17-a14f-92a0e2e36c02.png)

4. checking progress
![image](https://user-images.githubusercontent.com/62723171/226842176-7bb41b9c-7014-44e5-ac2a-7e071c525785.png)

5. checking stats
![image](https://user-images.githubusercontent.com/62723171/226842554-d20a1e0c-2231-49b6-acfb-aeec43403563.png)

6. Wait for 24h

Also crontab does not work: 
![image](https://user-images.githubusercontent.com/62723171/226845798-8c8036ed-6dde-48b0-a579-f60cc5db23b8.png)

### Server configuration

* **Operating system: Linux 5.4.0-144-generic x86_64

* **Pdlib version:** newest (from 20.02.2023)

* **How is DLib installed: pdlib-min-test-suite says "all ok"

* **How is PDlib installed: pdlib-min-test-suite says "all ok"

* **PHP version: 8.1.17

* **Web server: nginx

* **Database:  mysql Version: 10.6.12

* **Nextcloud version: Nextcloud Hub 3 (25.0.4)

#### Background task log with debug.
![image](https://user-images.githubusercontent.com/62723171/226841404-abb020d4-4e2b-409d-811b-aa335d46c250.png)

```

**Comment by matiasdelellis** [comment]
Did you enable analysis in your personal settings?

**Comment by SaschaMuehl** [comment]
With the new update and the "crawl missing" option it seems it work out:
1. reset: `occ face:reset --all and occ face:reset --all -u USER_ID`
2. handle external files: `occ config:app:set facerecognition handle_external_files --value true`
3. restart the recognition `occ user:setting USER_ID facerecognition full_image_scan_done false`
4. `sudo -u www-data php /var/www/nextcloud/occ face:background_job -u USER_ID --crawl-missing`
