### ISSUE TITLE
Please, make the app compatible with Nextcloud 26

### ISSUE THREAD

**Issue by elpraga** [matiasdelellis/facerecognition#655]
Thank you for your great and very useful app!

Could you make it compatible with the new Nextcloud 26? (Hub 4)

Thank you for your great work!

**Comment by stweil** [comment]
The latest code from git master seems to work with Nextcloud 26. I could install and enable it, and it is now detecting faces in my images. Up to now I only noticed a minor issue in the admin settings for face recognition: it displayed `NaNxNan (4x3)` for the size of temporary files. That could be fixed by setting the size manually.

**Comment by F3rd1Fuch5** [comment]
> The latest code from git master seems to work with Nextcloud 26. I could install and enable it, and it is now detecting faces in my images. Up to now I only noticed a minor issue in the admin settings for face recognition: it displayed `NaNxNan (4x3)` for the size of temporary files. That could be fixed by setting the size manually.

Works for me too with nc 26.

**Comment by llucax** [comment]
Anyone tried if the release version in the nextcloud app store works with NC26 if it is force-enabled?

**Comment by sowoi** [comment]
Before you start: **I am still with PHP 8.1!** 
I just did the update to NC 26 and forced enabling the app.  it works! I also haven't faced any issues with the admin interface so far.  
for anyone looking for the command: `occ app:enable facerecognition -f `

**Comment by llucax** [comment]
Thanks for reporting back!

**Comment by lippoliv** [comment]
For me after the update, the app was disabled, but as @sowoi mentioned, it can be re-enabled cia CLI.

**Comment by matiasdelellis** [comment]
Hello everyone,
Sorry for such a delay. I'm short on time.. 

Just I uploaded an update enabling NC26 and 27 but without all the features I expected. I hope to be able to work soon with some features and fixes..

This update is well tested on NC26 but nothing on NC27. Regarding this report, we can close it, but if things come up, please open the necessary issues.


Thanks for all,
Regards,
Matias
