### ISSUE TITLE
Thumbs missing after server restore (facerecognition app deleted)

### ISSUE THREAD

**Issue by SKB-CGN** [matiasdelellis/facerecognition#661]
Hi,
is there perhaps any chance, to get the thumbs created for already scanned pictures?

I have had a server crash this weekend - so all VM's where gone and i had to re-install all stuff.
After reinstalling nextcloud, the facerecognition folder was recreated - but i could lukily restore all data and database for this server ;)

But now, the thumbs inside the Face-Recognition Area are missing.

Is there maybe a command, to create such thumbs again?

Thank you in advance!

**Comment by matiasdelellis** [comment]
Hi @SKB-CGN 
The thumbnails (Speaking of the cropped image), are generated when viewing them. They are not saved anywhere on the server. 🤔 

These are generated with the information from the database (Table oc_facerecog_faces), and if you lost this, I don't see how to recover it.. 😞

**Comment by SKB-CGN** [comment]
Ah, ok. Thanks a lot. I will rescan them.
