### ISSUE TITLE
Imaginary autorotate post call times out too quickly for large HEIC panorama image

### ISSUE THREAD

**Issue by tejus** [matiasdelellis/facerecognition#662]
I have a 16382x3762 panorama image from an iPhone in HEIC format. The background_job task fails at an autorotate operation [here](https://github.com/matiasdelellis/facerecognition/blob/2585ed6137d58717ab888da19b62f6a4460cf277/lib/Helper/Imaginary.php#L130) with this image due to a timeout of 30s:

```
Error generating temporary image in Imaginary: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://imaginary:9000/pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22resize%22%2C%22params%22%3A%7B%22width%22%3A3702%2C%22height%22%3A850%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22png%22%2C%22norotation%22%3A%22true%22%2C%22force%22%3A%22true%22%7D%7D%5D
```

My imaginary instance seems to need a bit more time to complete processing this request.

```
172.28.0.7 - - [05/May/2023 08:03:09] "POST /info HTTP/1.1" 200 122 0.0936
172.28.0.7 - - [05/May/2023 08:03:42] "POST /pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22resize%22%2C%22params%22%3A%7B%22width%22%3A3702%2C%22height%22%3A850%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22png%22%2C%22norotation%22%3A%22true%22%2C%22force%22%3A%22true%22%7D%7D%5D HTTP/1.1" 200 3916 33.0521
```

**Comment by matiasdelellis** [comment]
Hi @tejus 
Imaginary is bringing many problems with HEIC files.. 😞 

In particular:
* https://github.com/nextcloud/server/issues/35643

And seems that I at least have to prevent autorotate.. 😞 
* https://github.com/nextcloud/server/pull/37140

I will investigate it a little more. thanks for the report

**Comment by matiasdelellis** [comment]
Hi again,
I have this pending.. I hope to do it soon..  😞
