### ISSUE TITLE
Nextcloud 26

### ISSUE THREAD

**Issue by Timojl1** [matiasdelellis/facerecognition#669]
Is a Compatible version for Nextcloud 26 planed?

**Comment by IndrekHaav** [comment]
There's already issue #655.

But you could edit this issue to be about Nextcloud 27, which was just released.

**Comment by matiasdelellis** [comment]
Hi both,
Thanks for the reports. I'm short on time, so I uploaded an update enabling NC26 and 27 but without all the features I expected.. 😞
