### ISSUE TITLE
App is insanely hard to install (foreign libraries which wont install, need compiling or outright are deprecated)

### ISSUE THREAD

**Issue by Haui1112** [matiasdelellis/facerecognition#685]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

App should install the dependencies by itself.

### Actual behaviour

Hours of work to get obscure libraries which are often already obsolete. This is nextcloud, not kali-linux.

### Steps to reproduce
1. Install current nextcloud instance
2. Try to download and activate face recognition
3. spend hours on multiple github repo's without finding the libraries that should already be in the installation

### Server configuration

* **Operating system:**
Ubuntu 22.04.2 (debian bullseye in docker container for some reason)
* **Pdlib version:**
None, unable to install. Installs have no download candidate.
* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi,
I invite you to try the [external model](https://github.com/matiasdelellis/facerecognition-external-model), using the [latest version](https://github.com/matiasdelellis/facerecognition/releases/tag/v0.9.30) released.

Open a new issue to see how we continue. 😬
