### ISSUE TITLE
How to use with Nextcloud AIO Docker

### ISSUE THREAD

**Issue by kaibagley** [matiasdelellis/facerecognition#687]
### Server configuration
- Old laptop
- HDD

* **Operating system:**
- Ubuntu server 22.04

* **How is DLib and Pdlib installed:** 
- Following the wiki guide, passes the suite test

* **PHP version:**
- 8.1

* **Nextcloud version:**
Latest AIO (6.3.0)
Nextcloud 27

All of this is installed on the host machine, but I understand that I need to do something different for a Docker setup. 
Unfortunately I don't know too much about Docker, so could someone explain to me how to use this information (https://github.com/matiasdelellis/facerecognition/wiki/Docker) on a Docker AIO setup?

Thanks,
Kai

**Comment by matiasdelellis** [comment]
Hi,
I invite you to try the [external model](https://github.com/matiasdelellis/facerecognition-external-model), using the [latest version](https://github.com/matiasdelellis/facerecognition/releases/tag/v0.9.30) released.

Open a new issue to see how we continue. 😬
