### ISSUE TITLE
Setup doesn't work on objectstore

### ISSUE THREAD

**Issue by mrAceT** [matiasdelellis/facerecognition#694]
Exactly the same as: https://github.com/matiasdelellis/facerecognition/issues/381

but the "2023 version".. I get this:

```
#sudo -u [user] php81 -d apc.enable_cli=1 -d memory_limit=1024M [folder]occ  face:setup -M 1Gb -m 1
System memory: 7.7 GB (8313696256B)
Memory assigned to PHP: 1 GB (1073741824B)

Minimum value to assign to image processing.: 682.7 MB (715827882B)
Maximum value to assign to image processing.: 1 GB (1073741824B)

Maximum memory assigned for image processing: 1 GB (1073741824B)

The model 1 (Default) will be installed

In FileService.php line 392:

  The file [folder]/data//appdata_[something]/facerecognition/models//1/mmod_human_face_detector.dat exists or is not writable


face:setup [-M|--memory MEMORY] [-m|--model MODEL]
```

I (also) have S3 as a primary storage. I have this set up via: https://github.com/mrAceT/nextcloud-S3-local-S3-migration

Further, I have PDlib installed on my AlmaLinux 8.7 (Stone Smilodon)

**Comment by matiasdelellis** [comment]
Mmm. you tried this.? https://github.com/matiasdelellis/facerecognition/pull/391#issuecomment-1245336811 🤔

**Comment by mrAceT** [comment]
Bingo, that worked, I have installed the model!

I can continue testing, tahnks!

For others who run into the same problem: https://github.com/matiasdelellis/facerecognition/pull/391#issuecomment-1245336811 : 
> > Hi, can you describe how to use this Setting? I also use S3 Storage, but can't figure out to get this solution running...
> 
> https://github.com/matiasdelellis/facerecognition/blob/9b4ebc9e8eab169444653c90d87237a8ce2b4561/lib/Service/SettingsService.php#L133
> 
> in `config/config.php` of your NextCloud installation, define `facerecognition.model_path` to your wanted model path.

**Comment by mrAceT** [comment]
Bingo, that worked, I have installed the model!

I can continue testing, thanks!

For others who run into the same problem: https://github.com/matiasdelellis/facerecognition/pull/391#issuecomment-1245336811 : 
> > Hi, can you describe how to use this Setting? I also use S3 Storage, but can't figure out to get this solution running...
> 
> https://github.com/matiasdelellis/facerecognition/blob/9b4ebc9e8eab169444653c90d87237a8ce2b4561/lib/Service/SettingsService.php#L133
> 
> in `config/config.php` of your NextCloud installation, define `facerecognition.model_path` to your wanted model path.

**Comment by mrAceT** [comment]
PS: I have a 'datadirectory' configured in my config.php, would it be an idea that the software checks (and uses) that folder before giving the error? (which could use some rewriting?)

I now have:
```
..
  'datadirectory' => '/[folder]/data',
..
  'facerecognition.model_path' => '/[folder]/data/facerecognition/',
..
```
