### ISSUE TITLE
Imaginary service?

### ISSUE THREAD

**Issue by j3ffery17** [matiasdelellis/facerecognition#700]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

Trying to run initial background job 

     sudo -u www-data ./occ face:background_job -u user
 
### Actual behaviors

Getting the following:

1/8 - Executing task CheckRequirementsTask (Check all requirements)
        An Imaginary service (http://127.0.0.1:8080) was configured to manage temporary images, but it is inaccessible.Check out the service, or set the 'preview_imaginary_url' key appropriately.

### Steps to reproduce
1.
2.
3.

### Server configuration

* **Operating system:**

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by alsoszaa** [comment]
I think I had this issue as well because I was running a local instance of Nextcloud. 
Go to /var/www/NextCloud directory and edit the config.php file to allow local instances

'allow_local_remote_servers' => true,

**Comment by j3ffery17** [comment]
Rhabks. Truied that and still saw the error wo I commented out rhe preview_imaginary_url line in config.php and then it worked.

**Comment by GuillaumePod** [comment]
I have the same problem, preview_generator works perfectly with an imaginary service but if I run `php occ face:background_job -t 900 ` I have the same message.

```
1/8 - Executing task CheckRequirementsTask (Check all requirements)
       An Imaginary service (http://nextcloud-imaginary:9000) was configured to manage temporary images, but it is inaccessible.Check out the service, or set the 'preview_imaginary_url' key appropriately.
Task CheckRequirementsTask signalled we should not continue, bailing out

```

**Comment by Dams07** [comment]
I'm running into the same issue. 

`1/8 - Executing task CheckRequirementsTask (Check all requirements)
        An Imaginary service (http://nextcloud-aio-imaginary:9000) was configured to manage temporary images, but it is inaccessible.Check out the service, or set the 'preview_imaginary_url' key appropriately.
Task CheckRequirementsTask signalled we should not continue, bailing out`

If i run `docker logs -f nextcloud-aio-imaginary` i see `172.18.0.10 - - [23/Apr/2024 10:02:23] "GET / HTTP/1.1" 401 53 0.0002
` so i think Face Recognition doesnot support API Keys (HTTP 401) ?

Thank you for your help

**Comment by fabalexsie** [comment]
Looks like face recognition does not use the api key

https://github.com/matiasdelellis/facerecognition/blob/d5478c5035844b092ea403adcda14b6a059268c3/lib/Helper/Imaginary.php#L70

This call is used to check the accessability of the imaginary service, but it is missing the key.

According to the imaginary documentation the key can be passed as query parameter [h2non/imaginary: Authorization](https://github.com/h2non/imaginary?tab=readme-ov-file#authorization)

So in this example line it could be fixed with:
```
$response = $httpClient->get($imaginaryUrl . '/?key=' . $imaginaryKey); 
```

And similar for the other requests in the ImaginaryHelper file.

**Comment by fabalexsie** [comment]
I've created a small pull request which should fix the issue with not used api keys.

And to improve on the last comment, the httpClient has a better way of adding query parameters (which is also used in the PR):
```php
$response = $httpClient->get($imaginaryUrl . '/', [ 'query': [ 'key' => $key ] ]);
```
