### ISSUE TITLE
only recognizing 15 persons per User

### ISSUE THREAD

**Issue by KoMa1012** [matiasdelellis/facerecognition#706]
### Expected behaviour

1. show (way) more clusters/persons
2. not always show message clustering will be created for the first time.

### Actual behaviour

1. (exactly) 15 persons are being detected, but there are ~6k Clusters/User
3. message: Face clustering will be created for the first time. always show up

### Steps to reproduce
1. follow basic setup of facerecognition using external model
4. install external model on gaming PC running ubuntu with CUDA for DLIB active
5. do some tests to get it up and running
6. run occ recognize:reset-faces to get a fresh start once the validation of the system is done
7. run occ face:background_job -t x (tested with different time limits, even one with time limit of 30 which ended up detecting all faces in one run)

### Server configuration

* **Operating system:** unraid/official nextcloud docker

* **Pdlib version:** according to https://github.com/matiasdelellis/facerecognition-external-model 

* **How is DLib installed:** according to https://github.com/matiasdelellis/facerecognition-external-model (with cuda support)

* **How is PDlib installed:** according to https://github.com/matiasdelellis/facerecognition-external-model 

* **PHP version:**

* **Web server:** apache

* **Database:** Mariadb

* **Nextcloud version:** 27.1.2

### Client configuration

* **Browser:** chrome/firefox

* **Operating system:** Windows/iOS/Ubuntu/

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
	System: Linux
System memory: 33428856832
PHP Memory Limit: 9663676416
Clustering backend: PHP (Not recommended.
Image Backend: Imagick
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
yielding
yielding
yielding
yielding
yielding
yielding
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
Skipping stale images removal for user admin as there is no need for it
Skipping stale images removal for user dominic as there is no need for it
Skipping stale images removal for user hedwig as there is no need for it
Skipping stale images removal for user markus as there is no need for it
Skipping stale images removal for user nora as there is no need for it
Skipping stale images removal for user norbert as there is no need for it
Skipping stale images removal for user uwe as there is no need for it
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
* have 1000 faces already processed
* or you need to have 95% of you images processed
Use stats command to track progress
yielding
Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
* have 1000 faces already processed
* or you need to have 95% of you images processed
Use stats command to track progress
yielding
Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
* have 1000 faces already processed
* or you need to have 95% of you images processed
Use stats command to track progress
yielding
Face clustering will be created for the first time.
10207 faces found for clustering
6706 clusters found after clustering
yielding
Face clustering will be created for the first time.
1958 faces found for clustering
1245 clusters found after clustering
yielding
Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
* have 1000 faces already processed
* or you need to have 95% of you images processed
Use stats command to track progress
yielding
Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
* have 1000 faces already processed
* or you need to have 95% of you images processed
Use stats command to track progress
yielding
6/8 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
Skipping image scan for user 1 that has disabled the analysis
Skipping image scan for user 2 that has disabled the analysis
Skipping image scan for user 3 that has disabled the analysis
Skipping full image scan for user 4
Skipping full image scan for user 5
Skipping image scan for user 6 that has disabled the analysis
Skipping image scan for user 7 that has disabled the analysis
7/8 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
8/8 - Executing task ImageProcessingTask (Process all images to extract faces)
NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
n.A. not found
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
n.A. no message related to face recognition
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n.A. 
```
</details>

**Comment by matiasdelellis** [comment]
Hi @KoMa1012 
Sorry for delay.. I'm very busy.. 😞 

> install external model on gaming PC running ubuntu with CUDA for DLIB active

Brilliant. I think you are the first person to use the GPU in the external model. 😄 

> (exactly) 15 persons are being detected, but there are ~6k Clusters/User

15 people seems not enough to me, but it can happen. Since the latest versions, it only shows to assign name to clusters with at least 5 faces.

Well, try to reduce the "Minimum of faces in cluster" parameter in the settings.. 😉

**Comment by KoMa1012** [comment]
> Hi @KoMa1012 Sorry for delay.. I'm very busy.. 😞
> 
> > install external model on gaming PC running ubuntu with CUDA for DLIB active
> 
> Brilliant. I think you are the first person to use the GPU in the external model. 😄
> 
wow, that's a new one. I was patching some tutorials together, so you are saying I should have documented what I did? :-)
> > (exactly) 15 persons are being detected, but there are ~6k Clusters/User
> 
> 15 people seems not enough to me, but it can happen. Since the latest versions, it only shows to assign name to clusters with at least 5 faces.
> 
> Well, try to reduce the "Minimum of faces in cluster" parameter in the settings.. 😉

I just noticed I was a moron, somehow I was looking at the faces which are generated by recognize. Is there a way to get the recogniced persons from face recognition into the photos/memory app?
