### ISSUE TITLE
Pdlib missing, but installed

### ISSUE THREAD

**Issue by Happyfeet01** [matiasdelellis/facerecognition#710]
Hello,

Can anyone help me? I have installed dlib and pdlib. But make test fails. 
I don't know why. 

`Build complete.
Don't forget to run 'make test'.

=====================================================================
PHP         : /usr/bin/php8.2 
Warning: PHP Startup: pdlib: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 8.2.12
ZEND_VERSION: 4.2.12
PHP_OS      : Linux - Linux livesystem-debian 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1 (2023-03-19) x86_64
INI actual  : /home/lars/pdlib/tmp-php.ini
More .INIs  :   
---------------------------------------------------------------------
PHP         : /usr/bin/phpdbg8.2 
PHP_SAPI    : phpdbg
PHP_VERSION : 8.2.12
ZEND_VERSION: 4.2.12
PHP_OS      : Linux - Linux livesystem-debian 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1 (2023-03-19) x86_64
INI actual  : /home/lars/pdlib/tmp-php.ini
More .INIs  : 
Warning: PHP Startup: pdlib: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0

---------------------------------------------------------------------
CWD         : /home/lars/pdlib
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2023-11-19 09:22:20
=====================================================================
SKIP Check for pdlib presence [tests/001.phpt] 
SKIP Basic tests for chinese_whispers [tests/chinese_whispers_basic.phpt] 
SKIP Edge given in edges array for chinese_whispers functions is associative array [tests/chinese_whispers_edge_associative_array_error.phpt] 
SKIP Edge elements given in edges array for chinese_whispers functions are not of long type [tests/chinese_whispers_edge_elements_not_long.phpt] 
SKIP Edge given in edges array for chinese_whispers functions is not having all values to be arrays with 2 elements [tests/chinese_whispers_edge_not_2_element_error.phpt] 
SKIP Edge given in edges array is not array for chinese_whispers functions [tests/chinese_whispers_edge_not_array_error.phpt] 
SKIP Args given to chinese_whispers functions is not correct [tests/chinese_whispers_wrong_arg_type_error.phpt] 
SKIP Testing CnnFaceDetection constructor without arguments [tests/cnn_face_detection_ctor_error.phpt] 
SKIP Testing CnnFaceDetection constructor with model that do not exist [tests/cnn_face_detection_ctor_model_not_found_error.phpt] 
SKIP Frontal face detection. [tests/dlib_face_detection.phpt] reason: pdlib extension missing
SKIP Testing FaceLandmarkDetection constructor without arguments [tests/face_landmark_detection_ctor_error.phpt] 
SKIP Testing FaceRecognition constructor without arguments [tests/face_recognition_ctor_error.phpt] 
SKIP Full test for face recognition - download models, detect faces, landmark detection and face recognition. [tests/integration_face_recognition.phpt] reason: pdlib extension missing
SKIP Basic tests for dlib_vector_length [tests/vector_length.phpt] 
SKIP Just test php extension version [tests/version.phpt] 
=====================================================================
TIME END 2023-11-19 09:22:20

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   16
---------------------------------------------------------------------

Number of tests :   15                 0
Tests skipped   :   15 (100.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :    0 seconds
=====================================================================

This report can be saved and used to open an issue on the bug tracker at
`

**Comment by matiasdelellis** [comment]
Hi @Happyfeet01 

Sorry for  delay...  I'm very busy.. 😞 

Were you able to solve it?. What was the last thing you did? This test is not important..

**Comment by Happyfeet01** [comment]
@matiasdelellis i solved it. 

Module compiled with module API=20200930
PHP compiled with module API=20220829

I compiled with 2 different php Versions. My mistake. It works fine currently
