### ISSUE TITLE
Make the app works with Memories and external storage

### ISSUE THREAD

**Issue by Bishaady** [matiasdelellis/facerecognition#728]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

Hello, I'm using the app Memories to manage my photos library, arround 70 000 files. All my files are located into an external storage and the Memories app detected all of my folders and photos. 
Currently i'm running the app Recognize for facial recognition but I would like to try Face Recognition.
After installation and configuration, everything seems to be good, 4GB of RAM assigned and model 1 assigned.

But when I'm going into the app settings or running occ faces:progress I have only 36 files detected, probably the few files I have locally. 

Is there a way to tell to the app which folder to scan ? 

![image](https://github.com/matiasdelellis/facerecognition/assets/47696152/ee1caa4d-1a81-4274-bbfd-3557196d33d9)

![image](https://github.com/matiasdelellis/facerecognition/assets/47696152/ea3d4f36-ee9e-4d1e-a3ed-f75ae9ebba67)

Thank you for your help. 

### Server configuration

* **Operating system: Ubuntu 22.04.1 (VM)

* **Pdlib version:19.24.2

* **How is DLib installed: working correctly

* **How is PDlib installed:working correctly 

* **PHP version:8.1.2

* **Web server: Apache 2.4.52

* **Database: PostgreSQL 14.11

* **Nextcloud version:28

### Client configuration

* **Browser: Chrome

* **Operating system: Windows 11

**Comment by IndrekHaav** [comment]
Scanning files on external storage is disabled by default, see the FAQ:

https://github.com/matiasdelellis/facerecognition/wiki/FAQ#q-facerecognition-ignore-shared-files-external-storage-or-group-folders
