### ISSUE TITLE
facerecognition not compatible with NextCloud 28.0.3

### ISSUE THREAD

**Issue by jw1720** [matiasdelellis/facerecognition#732]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

I have face recognition running on NextCloud 28.0.2. I installed the instance from Hansson IT VM. However, NextCloud now reports it is not compatible when NextCloud 28.0.3 is available. I love this app and hope it can be updated to support new version of NextCloud.

See attached screenshot.

<img width="533" alt="Screenshot 2024-03-22 at 10 15 09 AM" src="https://github.com/matiasdelellis/facerecognition/assets/101196094/14dde5f8-937b-4be7-9bab-2ef8a95ff343">
### Server configuration

* **Operating system:**
Linux 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

* **PHP version:**
php 8.1

**Comment by elpraga** [comment]
Is there any update on NC28 compatibility?

I know it has been discussed [here](https://github.com/matiasdelellis/facerecognition/issues/714).

It is one of two apps that still preventing me from upgrading. (Because I think it's great and I don't want to be without it!) 

But soon NC27 will stop to be supported...

**Comment by matiasdelellis** [comment]
D'Oh!
I really am very complicated, and I couldn't dedicate even a little bit of love to just publishing a version with the current code..

I will review the current changes, and post a version with current status.

**Comment by matiasdelellis** [comment]
Done!.
I hope there is no regression but I had been using it for months, and I never had time to publish it. I guess everything is fine.


Thanks for the patience! 😄
