### ISSUE TITLE
Image tag `matiasdelellis/facerecognition-external-model:latest` not available

### ISSUE THREAD

**Issue by aseering** [matiasdelellis/facerecognition#733]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

I'm not sure if this is the right place to report this issue?

When I install the facerecognition community container [here](https://github.com/nextcloud/all-in-one/blob/main/community-containers/facerecognition/facerecognition.json), I would expect that the container successfully starts.

### Actual behaviour

The container fails to start.  It fails to fetch the image `matiasdelellis/facerecognition-external-model` (which Docker infers to be `matiasdelellis/facerecognition-external-model:latest`.

The Docker Hub repository doesn't have a `latest` tag for this image.  I was able to work around this issue by doing:

```
docker pull matiasdelellis/facerecognition-external-model:v1
docker tag matiasdelellis/facerecognition-external-model:v1 matiasdelellis/facerecognition-external-model:latest
```

### Steps to reproduce
1. Start the NextCloud AIO Container with `-e AIO_COMMUNITY_CONTAINERS="facerecognition"`
2. Start NextCloud using the AIO Web interface
3. Check to see which containers start.  The facerecognition container should be listed (it is) and it should successfully start (it does not).

This may not reproduce if you already have a local version of the `:latest` tag, either due to the workaround above or because it was built or fetched through some other means.  In this case, first do a `docker image rm matiasdelellis/facerecognition-external-model:latest`.

Alternative shorter reproducer:
```
docker pull matiasdelellis/facerecognition-external-model:latest
```
This command should succeed.

### Server configuration

* **Operating system:**
NextCloud AIO, running on an Ubuntu 22.04 host

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

### Client configuration

* **Browser:**

* **Operating system:**

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Hi, the facerecognition container in AIO should use the image tag v1: https://github.com/nextcloud/all-in-one/blob/20bd9ed82e0f4ceacd8f512b4ad9c88213fd0459/community-containers/facerecognition/facerecognition.json#L7-L8

**Comment by matiasdelellis** [comment]
Hi @aseering 
Thanks for the report, but it was a design decision to use a semi-versioned tag, and not use the common 'latest' tag.

I understand that it is a very common pattern in Docker, but there are no advantages to using it. I Just prefer to use versioned tags, where I can better control their use.
