### ISSUE TITLE
unable to install on ubuntu 20.04 - key expired

### ISSUE THREAD

**Issue by joskapista44** [matiasdelellis/facerecognition#744]
System: ubuntu 20.04 server
I tried to install it but I run into a key issue. I'm a bit noob so maybe I make something wrong:

root@nextcloud:/home/user# echo "deb https://repo.delellis.com.ar focal focal" > /etc/apt/sources.list.d/20-pdlib.list
root@nextcloud:/home/user# wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
root@nextcloud:/home/user# apt update
.....                       
Get:14 https://repo.delellis.com.ar focal InRelease [3,654 B]                                                             
Err:14 https://repo.delellis.com.ar focal InRelease           
  The following signatures were invalid: EXPKEYSIG 39217939ED3D07DB Matias De lellis <mati86dl@gmail.com>
Reading package lists... Done
W: https://repo.delellis.com.ar/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://repo.delellis.com.ar focal InRelease: The following signatures were invalid: EXPKEYSIG 39217939ED3D07DB Matias De lellis <mati86dl@gmail.com>
E: The repository 'https://repo.delellis.com.ar focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by DoctorMcKay** [comment]
+1, the key at https://repo.delellis.com.ar/repo.gpg.key has expired on 2024-03-20.

**Comment by piflixe** [comment]
+1

**Comment by matiasdelellis** [comment]
PLease... Try again..

**Comment by joskapista44** [comment]
works now thank you
