### ISSUE TITLE
Nextcloud 29 missing icon sidebar

### ISSUE THREAD

**Issue by dtony974** [matiasdelellis/facerecognition#752]
Hello I would like to know if is normal with the 29 version of Nextcloud that I have not the shortcut (icon) to go to the "facerecognition" application in the Nextcloud toolbar, only in the admin setting.
So facerecognition work well for me but I need every time to go to admin setting to use the service. 
Please Someone can tell me if something is wrong or is just normal with the version 29 of nextcloud, thank you.
Tony,

### Server configuration
Raspberry 5

* **Operating system:**

Ubuntu server 23.10

#### Nextcloud log (data/nextcloud.log)
Erreur: Undefined array key 0
Date: 2024-05-22
Heure: 02:18:35 (UTC)
Adresse IP: 37.XX.XXX.XX
Utilisateur: tony
Navigateur: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Version de l'application: 29.0.0.19
Message: Clé de tableau non définie 0 à /var/www/html/nextcloud/apps/facerecognition/lib/Controller/FaceController.php ligne 102

Erreur: Appel à une méthode sur un objet nul
Date: 2024-05-22
Heure: 02:18:35 (UTC)
Adresse IP: 37.1.x.x.x
Utilisateur: tony
Navigateur: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Version de l'application: 29.0.0.19
Message: Appel à une méthode sur un objet nul dans le fichier '/var/www/html/nextcloud/apps/facerecognition/lib/Controller/FaceController.php' ligne 105
'/var/www/html/nextcloud/apps/facerecognition/lib/Controller/FaceController.php' line 105","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":170,"Previous":{"Exception":"Error","Message":"Call to a member function getPath() on null","Code":0,"Trace":
[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"getThumb","class":"OCA\\FaceRecognition\\Controller\\FaceController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/apps/facerecognition/lib/Controller/FaceController.php","Line":105},"message":"Call to a member function getPath() on null in file '/var/www/html/nextcloud/apps/facerecognition/lib/Controller/FaceController.php' line 105","exception":{},"CustomMessage":"Call to a member function getPath() on null in file '/var/www/html/nextcloud/apps/facerecognition/lib/Controller/FaceController.php' line 105"}}

![Capture d'écran 2024-05-22 063622](https://github.com/matiasdelellis/facerecognition/assets/95849263/7462b040-a655-49d3-8ebe-562647668cef)

**Comment by matiasdelellis** [comment]
Hi @dtony974 
This is normal because we didn't want to make another photo gallery application.. This interface is maintained because it offers some interesting operations for error correction..  But my current recommendation is that you install Memories, and in any case, you can use the side panel in the official Photos application.

**Comment by dtony974** [comment]
Hi Matias thank you very much, yes that make sense because memories can detect the listing of facerecogition.

Thank you again to maintain facerecogition !
Good day
Tony,

**Comment by dtony974** [comment]
Hi Matias thank you very much, yes that make sense because memories can detect the listing of facerecogition.

Thank you again to maintain facerecogition !
Good day
Tony,
