### ISSUE TITLE
Facerecognition version confusion from NextCloud app store

### ISSUE THREAD

**Issue by jw1720** [matiasdelellis/facerecognition#756]
I have the latest facerecognition installed through NextCloud. 

From the app directory, it shows verion 0.9.50 is installed and running
$ head /var/www/nextcloud/apps/facerecognition/CHANGELOG.md 
     # Changelog
     All notable changes to this project will be documented in this file.

     ## [0.9.50] - 2024-05-22
     - Enable Nextcloud 29 and drop 27.

$php occ app:enable facerecognition
facerecognition already enabled

This seems all right. However, from the Nextcloud web interface (see attached screenshot), it shows facerecognition version is 0.9.31 and is disabled. What's wrong here? How to fix that? Thanks.

<img width="1630" alt="Screenshot 2024-06-04 at 10 50 15 AM" src="https://github.com/matiasdelellis/facerecognition/assets/101196094/329be9de-167b-42ef-84b0-2f17f6f9d627">
 
Jim

**Comment by matiasdelellis** [comment]
Hi @jw1720 
On our part there is nothing that affects the store.. Unless you installed it by hand first, and you have two apps installed, it's probably just an app store cache issue.

**Comment by jw1720** [comment]
Thanks. Indeed I had a backup copy of the old version (when I was playing with the code) in the /var/www/nextcloud/apps directory. This is the cause of the problem.

**Comment by jw1720** [comment]
closed
