### ISSUE TITLE
Still the same error since month now. "Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174"}}. Is the app abandoned now?

### ISSUE THREAD

**Issue by axeljerabek** [matiasdelellis/facerecognition#777]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour
I can open the Face recognition admin page

Tell us what should happen
The admin page should open when I click it.

### Actual behaviour
"Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 192.168.178.21
Anfragekennung: hssPgNxMciUPD8JehTqJ"

Means "internal server error"

Tell us what happens instead
Internal server error

### Steps to reproduce
1. Install dlib, pdlib
2. Install facerecognition
3. setup facerecognition

Error in full from nextcloud.log:
less /var/www/nextcloud/data/nextcloud.log | grep hssPgNxMciUPD8JehTqJ
{"reqId":"hssPgNxMciUPD8JehTqJ","level":3,"time":"2024-09-26T08:19:11+00:00","remoteAddr":"192.168.178.21","user":"axel","app":"index","method":"GET","url":"/settings/admin/facerecognition","message":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","version":"30.0.0.14","exception":{"Exception":"Exception","Message":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":146,"Previous":{"Exception":"Error","Message":"Class \"CnnFaceDetection\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnHogModel/DlibCnnHogModel.php","line":104,"function":"open","class":"OCA\\FaceRecognition\\Model\\DlibCnnModel\\DlibCnnModel","type":"->"},{"file":"/var/www/nextcloud/apps/facerecognition/lib/Settings/Admin.php","line":84,"function":"open","class":"OCA\\FaceRecognition\\Model\\DlibCnnHogModel\\DlibCnnHogModel","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":117,"function":"getForm","class":"OCA\\FaceRecognition\\Settings\\Admin","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":74,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":142,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":58,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php","Line":174},"message":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174","exception":{},"CustomMessage":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174"}}

### Server configuration

* **Operating system:**
Ubuntu 24.04

* **Pdlib version:**
newest

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
newest with cuda support

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
phpize and newest

* **PHP version:**
8.3.6

* **Web server:**
Server version: Apache/2.4.62 (Ubuntu)
Server built:   2024-07-22T12:37:10

* **Database:**
mariadb  Ver 15.1 Distrib 10.11.8-MariaDB

* **Nextcloud version:**
27.28.29 and now 30. The error was with all versions

### Client configuration

* **Browser:**
any

* **Operating system:**
any

### Logs
see above

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
too long to insert
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
less /var/www/nextcloud/data/nextcloud.log | grep hssPgNxMciUPD8JehTqJ
{"reqId":"hssPgNxMciUPD8JehTqJ","level":3,"time":"2024-09-26T08:19:11+00:00","remoteAddr":"192.168.178.21","user":"axel","app":"index","method":"GET","url":"/settings/admin/facerecognition","message":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","version":"30.0.0.14","exception":{"Exception":"Exception","Message":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":146,"Previous":{"Exception":"Error","Message":"Class \"CnnFaceDetection\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnHogModel/DlibCnnHogModel.php","line":104,"function":"open","class":"OCA\\FaceRecognition\\Model\\DlibCnnModel\\DlibCnnModel","type":"->"},{"file":"/var/www/nextcloud/apps/facerecognition/lib/Settings/Admin.php","line":84,"function":"open","class":"OCA\\FaceRecognition\\Model\\DlibCnnHogModel\\DlibCnnHogModel","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":117,"function":"getForm","class":"OCA\\FaceRecognition\\Settings\\Admin","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":74,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":142,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":58,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php","Line":174},"message":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174","exception":{},"CustomMessage":"Class \"CnnFaceDetection\" not found in file '/var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php' line 174"}}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by axeljerabek** [comment]
Ne, hat geholfen. die pdlib.so war als extension verschwunden. Das ging jahrelang und seit einem update wohl weg gewesen. Danke!

**Comment by Oski19831** [comment]
Ok the Issue can be closed...

**Comment by matiasdelellis** [comment]
> Is the app abandoned no?

No.. I just had bilateral pneumonia that almost killed me... 😅 I'm fine now.. 😉 

Thanks for the support @Oski19831.. I see you're commenting on several issues. That's very important! 😄
