### ISSUE TITLE
PDlib debian packages

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#86]
Maybe I should add this issue in PDLib repository, but I find it much better to add it here, ha ha. Assigned to you @matiasdelellis (feel free to remove assignee label:D). I think this is blocker for beta version, as this can help with installations. This can also help to be written in FAQ and it will unblock bunch of integration tests.

BTW, where will those debian packages be hosted? LMK if you need some VMs or any other help for this task!

**Comment by matiasdelellis** [comment]
I take the job ..  :wink: 
But I'll have to wait a bit since I'm about to take vacations, and I have to leave many jobs ready ..

> debian packages be hosted?

Being only two packages, dlib and pdlib, we can use any host we have rented ..  It will be easy..

**Comment by matiasdelellis** [comment]
Hi @stalker314314 
I still can not test it, but I have faith ..  :pray: :sweat_smile: 

```
echo "deb [ allow-insecure=yes ] https://services.delellis.com.ar/data/pdlib-repo/ ./" > /etc/apt/sources.list.d/pdlib.list
apt update
apt install php7.0-pdlib
```

First package, just debian stretch amd64.

**Comment by SlavikCA** [comment]
@matiasdelellis Does the "`debian stretch amd64`" means, that it will not work on Ubuntu 18.04?

**Comment by matiasdelellis** [comment]
Hi @SlavikCA 
In principle, it is not compiled for ubuntu.. But it can work if the dependencies are met.. 
I would recommend that you download the debs and install them one by one to try. :wink:

**Comment by matiasdelellis** [comment]
Well.. 
The package has something wrong .. and two steps are missing: :sweat_smile: 

```
echo "extension=pdlib" > /etc/php/7.0/mods-available/20-pdlib.ini
echo "extension=pdlib" > /etc/php/7.0/cli/conf.d/20-pdlib.ini
systemctl restart php7.0-fpm
```

But it works!. :smile: 
On Monday with your comments I fix it .. :wink: 
Thanks!!!

**Comment by matiasdelellis** [comment]
Well, Fix the package. You can update directly..
Now I want to improve the repo.-

**Comment by matiasdelellis** [comment]
Fixed:

```
echo "deb [allow-insecure=yes] http://repo.delellis.com.ar/debian ./" > /etc/apt/sources.list.d/pdlib.list
apt update
apt install php7.0-pdlib
```

**Comment by matiasdelellis** [comment]
Hello everyone,
I am making progress in the packages for ubuntu Xenial..
After many laps, I was able to compile dlib, but I must compile again due to name conflicts... so I did not even test it .. :sweat_smile: 
The idea is to have Xenial repositories, and then bionic.. With this would be enough?

**Comment by stalker314314** [comment]
As spokeperson of travis tests (not as what user would need), xenial will not be enough, as travis is on 14.04 (based on [logs](https://api.travis-ci.org/v3/job/496424570/log.txt)). However, should be [trivial to bump it to xenial](https://docs.travis-ci.com/user/reference/xenial/). Expect me to do it these days.

**Comment by stalker314314** [comment]
@matiasdelellis Just ping here when you have some initial Xenial packages (they don't have to be perfect), so I can start adding Travis support and more testing (not sure what will be possible on Travis VMs) on *actual* calls to pdlib!

**Comment by matiasdelellis** [comment]
Hi @stalker314314 ,
https://github.com/matiasdelellis/facerecognition/wiki/Installation#ubuntu-xenial

I could not test it, but it should work ..

**Comment by stalker314314** [comment]
Heya @matiasdelellis, tried it and it doesn't seem to be working:
https://travis-ci.org/matiasdelellis/facerecognition/builds/509640735
If it helps, I am getting same error locally (in fresh xenial VM). Furthermore, if I try that, I get:
```sh
branko@ubuntu:~$ sudo apt-get install libdlib19
[sudo] password for branko:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdlib19 : Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

And there is no libpng12-0 package, at least as I am aware

**Comment by matiasdelellis** [comment]
The package exists.. :confused: 

https://packages.ubuntu.com/xenial/libpng12-0

Please check this... to know what you have installed.

> matias@services:~$ sudo apt-cache search libpng
```
fp-units-gfx - Free Pascal - graphics-library units dependency package
fp-units-gfx-3.0.0 - Free Pascal - graphics-library units
libpng-dev - PNG library - development (version 1.6)
libpng-tools - PNG library - tools (version 1.6)
***********libpng16-16 - PNG library - runtime (version 1.6)**********
libpng++-dev - C++ interface to the PNG (Portable Network Graphics) library
libpng-sixlegs-java - Sixlegs Java PNG Decoder
libpng-sixlegs-java-doc - Documentation for Sixlegs Java PNG Decoder
libpnglite-dev - lightweight C library for loading and writing PNG images
libpnglite0 - lightweight C library for loading and writing PNG images
pngquant - PNG (Portable Network Graphics) image optimising utility
ruby-oily-png - native mixin to speed up ChunkyPNG
tkpng - PNG photo image support to Tcl/Tk
fp-units-gfx-3.0.4 - Free Pascal - graphics-library units
```

> sudo apt-cache policy libpng16-16
```
libpng16-16:
  Installed: 1.6.28-1
  Candidate: 1.6.28-1
  Version table:
 *** 1.6.28-1 500
        500 http://ftp.us.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

...and finaly:
> matias@services:~$ sudo apt install libpng16-16
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpng16-16 is already the newest version (1.6.28-1).
libpng16-16 set to manually installed.
```

But in this case is Debian Stretch....

**Comment by matiasdelellis** [comment]
But I see more problems:

https://travis-ci.org/matiasdelellis/facerecognition/jobs/509640736

The error is:
```
The following packages have unmet dependencies:
 php7.0-pdlib : Depends: libdlib19 but it is not going to be installed
                Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
E: Unable to correct problems, you have held broken packages.
The command "sudo apt install php7.0-pdlib" failed and exited with 100 during .
```

According to Ubuntu archive, the version of libstdc++6 in Xenial is 5.4.0.. No 4.8.4!.
 * https://packages.ubuntu.com/xenial-updates/libstdc++6

I think travis is still in trusty. See the libstdc version there:

 * https://packages.ubuntu.com/trusty-updates/libstdc++6

**Comment by matiasdelellis** [comment]
Definitely is trusty.. :disappointed: 

https://travis-ci.org/matiasdelellis/facerecognition/jobs/509699328#L500

**Comment by stalker314314** [comment]
OK, OK, I am idiot:) I created this branch *before* I added support for xenial:) This is why it is not working:)

Now (after merging) it is working, although, now we need packages for php7.1 and php7.2 to be able to use it:
https://travis-ci.org/matiasdelellis/facerecognition/builds/510526990

But this means Travis will install it! Let me know if you plan to create 7.1/7.2 packages?

**Comment by matiasdelellis** [comment]
> OK, OK, I am idiot:) I created this branch before I added support for xenial:)

haha..
From my part,.. It would have been easier to see the whole file, that do another branch, edit it, push, and wait for the result of travis to confirm that it was not xenial.. No? :sweat_smile: :see_no_evil: 

> This is why it is not working:)

Great!

> now we need packages for php7.1 and php7.2 to be able to use it:

Can you differentiate the tests by versions? Do certain tests only with 7.0?
I would prefer not to make more packages for xenial, since officially, it only has 7.0.
I do not know from which repositories, travis installs the other versions, and is difficult compile something correctly, if you do not know where to build it..
These packages that I publish, are all compiled against a chroot only with the ubuntu official repositories.

**Comment by stalker314314** [comment]
If you remember, I removed PHP7.0 from test matrix with some reasoning (https://github.com/matiasdelellis/facerecognition/commit/9d5e672138132d082dea429b3a8924d642dc19ff#diff-354f30a63fb0907d4ad57269548329e3). So, we test only 7.1 and 7.2 now (and this is what most other active NC apps are doing, now that NC is only recommending PHP 7.1+).

Also, there is [no higher version of Ubuntu on Travis](https://docs.travis-ci.com/user/reference/overview/#linux).

You still plan to create 7.1/7.2 packages for Bionic?

I have no idea how to move forward now.
* Either we give up on Travis and set up our own Docker pipeline on, I don't know, Gitlab and move there?
* Or we have to create Xenial packages (ondrej/php PPA repo is where PHP lives, I think). Either you or me.
* Or we don't have testing:) In that case, I don't see why we cannot release beta version on app store even without packages.

I heard some horror stories about packaging Debian software, but I am not sure how hard it really is and can I help in any way (can we automate this stuff with some Vagrant, or whatsnot?) If you want to hand this off to me, sure, why not, just let me know. I would rather see packages on (xenial|bionic) (7.1|7.2) and some tests on top of it, then to be hostage of Travis.

**Comment by matiasdelellis** [comment]
> If you remember, I removed PHP7.0 from test matrix with some reasoning (9d5e672#diff-354f30a63fb0907d4ad57269548329e3)

D'OH!!!. I had forgotten this .. :disappointed: 

> Also, there is no higher version of Ubuntu on Travis.

I know ... and it's pretty disappointing..  They are simply old, and do not represent current needs, but I must admit that they are still in maintenance.

Version | Code name | End of Life date
-- | -- | --
Ubuntu 14.04.6 LTS | Trusty Tahr | April 2019

> You still plan to create 7.1/7.2 packages for Bionic?

7.2 for bionic:
 * https://packages.ubuntu.com/bionic/php/php7.2-dev

..since it is officially supported, and the idea is to reduce the gap entry to potential users. But we can not supply all the possibilities... This week continue with it..

> I have no idea how to move forward now.

I do not know either.. Frustrated .. :disappointed: 

> Or we have to create Xenial packages (ondrej/php PPA repo is where PHP lives, I think). Either you or me.

If we identify exactly where you get the updated packages, I can replicate the chroot, and generate a clean package.. But do not expect to cover all versions..

> Or we don't have testing:) In that case, I don't see why we cannot release beta version on app store even without packages.

Of course .. Even if it is not automated, we can move forward and run it ourselves..

> Either we give up on Travis and set up our own Docker pipeline on, I don't know,

I thought a lot, I have some experience in jenkins, but the difficulty is greater and will not offer better results ..

> Gitlab and move there?

In my experience, if we want to add users / developers to help, we better stay in github...

> I heard some horror stories about packaging Debian software

hahaha.. :see_no_evil: 
It's no worse than packaging for Fedora, Arch, or Windows ¿?. :wink:

> I would rather see packages on (xenial|bionic) (7.1|7.2) and some tests on top of it, then to be hostage of Travis.

If we identify Xenial repos, can try to make 7.1. and will package 7.2 for bionic.. :wink:

**Comment by matiasdelellis** [comment]
@stalker314314 
For travis we definitely do not need packages.
 * https://travis-ci.org/matiasdelellis/facerecognition/jobs/512518499#L181

They do not use packages, just a tar.gz that decompress in the root .. :disappointed: 

So, let's not be more papable than the Pope .. :sweat_smile: 
Let's compile them by hand, and copy them in the same way .. What you think?

**Comment by stalker314314** [comment]
Makes sense. So, what do you suggest? That we checkout DLib, pdlib and compile them from .travis.yml and install it from there? We got [50 mins for it](https://docs.travis-ci.com/user/customizing-the-build#sts=Build%20Timeouts%20#) :) We would probably need to `apt-get install build-essential and php-dev and whatsnot`.

Or to do what they do with PHP - just keep pdlib.so somewhere handy online and wget it in tests?:) We would need "only" PHP7.1 and PHP7.2 versions, and only for x64, only for xenial.

I am more for latter, what do you think?

**Comment by matiasdelellis** [comment]
At least compile.. :grimacing: 
https://travis-ci.org/matiasdelellis/facerecognition/builds/512629419

**Comment by stalker314314** [comment]
80 seconds? I could live with it:) should we continue like that? I can take over if you want (or after you push your change)?

**Comment by matiasdelellis** [comment]
--and the extension is loaded.. :smile: 
https://travis-ci.org/matiasdelellis/facerecognition/jobs/512692813#L936

> 80 seconds? I could live with it:)

Great!. Only compile pdlib, against dlib of my repos. :wink: 

> should we continue like that?

I guess it's acceptable.. 

> I can take over if you want (or after you push your change)?

Please take the ideas from there, and make a new branch cleaner. :wink:

**Comment by axeljerabek** [comment]
Can I request a pdlib for php8.1, debian bullseye on a raspberry arm64? :)
Cannot get it to compile at all. Seems the misery starts with gcc-14 already :/

**Comment by matiasdelellis** [comment]
Hi @axeljerabek 
> Can I request a pdlib for php8.1, debian bullseye on a raspberry arm64? :)

I can't make any packages with third party repositories, because it would have to be done for each repository and it's impossible to maintain for one person. 😞 

> Cannot get it to compile at all. Seems the misery starts with gcc-14 already :/

Show me what you're doing and I'll help you.. 😉

**Comment by matiasdelellis** [comment]
Look at this... maybe you may apply that simple patch... 😉

**Comment by axeljerabek** [comment]
Hi and thanks for your quick answer! :)

Well, I use your facerecognition on a Rapsberry Pi Bullseye arm64, since the Nextcloud 25 dirched 32 bit support. And since Recognize does not give any good results, I want to stick with your implementation for pictures sorting and face recognition, it is way better.

I tried the manual compile with dlib and the phpize the pdlib. The first part works and the dlib is installed. But the pdlib part gives tons of errors and does not get compiled after all.
You talked about a patch? Where is it? :)

And thanks for your great work! Works like a charm :)

**Comment by matiasdelellis** [comment]
D'Oh! 😅
Ser that https://github.com/goodspb/pdlib/pull/53/files

**Comment by axeljerabek** [comment]
Build complete.
Don't forget to run 'make test'.

:D

Perfect! Thanks!

**Comment by axeljerabek** [comment]
Quick correction:
After numerous tries, I was able to enable the facerecognition app, but it tells me that I cannot install a model:

You do not meet the dependencies to install the model 1 (Default)
Summary: The PDlib PHP extension is not loaded

Any further hints in this? :)
