### ISSUE TITLE
Support for HOG detector

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#93]
Current (CNN) detector is super precise and super slow:) HOG is very fast, but it can also find face in every lamp-post:) Still, it is...usable. Friend was telling me recently that he used HOG for fast and dirty face clustering (and he says all lamp posts were clustered together:D). Anyway, that got me thinking - we now require 2GB and 60 seconds per image. We should be able to offer low-quality, poor-result, bu available-for-everyone option. I think HOG is the detector that you @matiasdelellis used when you had Python (you used get_frontal_face_detector)?
I guess that can increase amount of people that can use this app. And I guess it shouldn't be that hard to include it - just add new `face_model` (id=2), and add additional model files and put `if (model==2)` to couple of places:) So, @matiasdelellis - back to the origins, what do you say?:) (I think this might not be a blocker for some initial beta release)

**Comment by matiasdelellis** [comment]
Finally we have HOG :smile: :hugs: :beers: 

In my analyzes it actually seems slower, but memory usage drops dramatically, and therefore will be a good improvement for users. :grimacing: 

Leave 2Gb as the minimum memory of the system, since the clustering is still inefficient.
