### ISSUE TITLE
Add PHP memory recommendation to README

### ISSUE THREAD

**Issue by SlavikCA** [matiasdelellis/facerecognition#94]
Please add minimum required PHP memory and recommended PHP memory setting to README

**Comment by stalker314314** [comment]
You are right, we definitevely should:) and we probably need more explanation (wiki pages?) around requirements, FAQ, security, install, usage... (before publishing). We can use this as umrella issue to track all of this:)

**Comment by stalker314314** [comment]
I think both @matiasdelellis  and me are on vacations, so expect some delay:)

**Comment by SlavikCA** [comment]
sure,
whenever you have time for it...

it appears to me, that memory usage is not controlled by PHP memory setting, but by dlib / pdlib...

Because I have PHP memory limit set to 192MB, but see scanning using few Gigs of RAM.
Interesting...

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
50604 www-data  20   0 4845816 3.731g  51056 R 130.6 64.1  38:35.12 php
```

**Comment by matiasdelellis** [comment]
> it appears to me, that memory usage is not controlled by PHP memory setting, but by dlib / pdlib...

Ohh.. It is to investigate..

About the documentation, for me it is fundamental, but obviously we have other priorities. :disappointed:
Do you dare to make some contributions documenting a bit?

**Comment by stalker314314** [comment]
@matiasdelellis, @SlavikCA I am going and writing documentation, it's not done, but I am doing it slowly:) I am dumping everything in wiki, but not sure where final place will be (suggestions? I don't really have opinion). Anyway, just a heads up and maybe you want to see if I am going in good direction:
https://github.com/matiasdelellis/facerecognition/wiki

I wrote (copy/pasted from various sources:smile:):
* https://github.com/matiasdelellis/facerecognition/wiki/Introduction
* https://github.com/matiasdelellis/facerecognition/wiki/Requirements-and-Limitations
* https://github.com/matiasdelellis/facerecognition/wiki/Installation

I am now planning to write "Usage" and "FAQ". This should be it for now, I think.

**Comment by matiasdelellis** [comment]
Great!.
This is fundamental. :smile: 
About the debian installation, it's still only for debian stretch. :disappointed: 

But at least improve the repository in preparation to maintain other distributions.

Now the apt/sources.list.d/20-pdlib.list must be: 
> deb  [ allow-insecure=yes ] http://repo.delellis.com.ar stretch main

I'm in doubt about signing the packages or not.. For now they remain unsigned. :confused: 

p.s:
There are also packages for fedora from f28 onwards. :wink: 
> dnf copr enable matias/dlib
> dnf install pdlib

**Comment by stalker314314** [comment]
After biggest pause ever (but still under 1 year:D), I did it! Small step for mankind, but big for me:)

https://github.com/matiasdelellis/facerecognition/wiki/FAQ contains some questions and points to requirements and hardware limitations. Hopefully, that will help people.

@matiasdelellis As far as I am concerned, there is no blocking issues on me to release to app store!:)
