### ISSUE TITLE
I installed PDLib, but getting error, that "PDLib is not loaded"

### ISSUE THREAD

**Issue by SlavikCA** [matiasdelellis/facerecognition#96]
System:
- Ubuntu 16.04
- NextCloud 15

I installed dlib and pdlib.
Add to php.ini
I see it in phpinfo page:

![pdlib_info](https://user-images.githubusercontent.com/6293679/50734162-a16eea00-114f-11e9-9dee-dfcd8a13c49b.png)

However, when trying to scan, I'm getting error:
```
root@ubhome:/var/www/nextcloud# sudo -u www-data php occ face:background_job -u slavik
1/8 - Executing task CheckRequirementsTask (Check all requirements)
        PDLib is not loaded. Cannot continue
Task CheckRequirementsTask signalled we should not continue, bailing out
```

What am I missing?

**Comment by SlavikCA** [comment]
ok, learned today, that modules managed separately for Apache and CLI.
One `php.ini` for Apache and one `php.ini` for CLI.

Adding this to right file fixed the issue:
```
[pdlib]
extension="pdlib.so"
```

In CLI you can inspect them via `php -m`.

**Comment by stalker314314** [comment]
Thanks for reporting this, this is kind of stuff that we will need in documentation/FAQ. Keep them coming:D

**Comment by pureexe** [comment]
Thank you. I face with the same problem and you post help.
