### ISSUE TITLE
Thumbnail shows wrong detail of image instead of the face

### ISSUE THREAD

**Issue by nervnet65** [matiasdelellis/facerecognition#98]
Some thumbnails do not show the recognized face, but another part of the photo. But the position information in the database about the recognized face in such a photo is correct when it is normally upright. It is noticeable that these thumbnails are always rotated by 90°. The EXIF orientations of the tested photos were "left bottom". The photo has to be rotated according to the EXIF orientation.

Inserting the following line in FaceController.php after line "$img->loadFromFile($fileName);" fixes this issue:
$img->fixOrientation();

@stalker314314 and @matiasdelellis: Thank you for your great work.

**Comment by stalker314314** [comment]
I want to consult with @matiasdelellis about this issue before proceeding, as here we need to decide between 2 things:
1. Either we keep face coordinates in DB _normalized_ (e.g. after call to `fixOrientation`) as today, and then we call `fixOrientation` in FaceController.php (as you proposed) and retrieve proper position of face in image, or
2. We keep original face coordinates in DB, before re-orientation (so: 1) do face detection on oriented image, 2) revert coordinates back to original orientation once face is found) and later, in FaceController.php, we crop those coordinates from original image and then reorient cropped (small) face.

Seems that 2. is more "correct" and it might be faster (as we are not rotating whole image, but only cropped face). Interestingly, we are already doing something similar to 2 when resizing and reverting size back to match face coordinates in [here](https://github.com/matiasdelellis/facerecognition/blob/master/lib/BackgroundJob/Tasks/ImageProcessingTask.php#L204).

P.S. Thanks for kind words, but we are not done yet - wait for first release;)
